### ISSUE TITLE
Accessibility issue - can't tell which channels are unread 

### ISSUE THREAD

**Issue by staabm** [mattermost/mattermost#10577]
similar to https://github.com/mattermost/mattermost-server/issues/8443 I want to report a usability problem regarding unread-state of private/public-channels 
messages.

#### Summary
the default (and also dark theme) provide only very slight visual indication when messages are unread.
we use mattermost for a few weeks in our company and some users already reported, that they didn't realized that they had unread messages (these were users which are _not_ visually impaired - so even for those this seem to be an issue).

#### Steps to reproduce
make sure you have a unread message

#### Expected behavior
the visual indication should be "more agressive"... its too easy to miss it.

#### Observed behavior (that appears unintentional) 
visual indication is very slight and can be missed easily

unread channel (same team) / Dark Theme
![grafik](https://user-images.githubusercontent.com/120441/55793569-818af180-5ac3-11e9-89d5-afc8a4ceaeb5.png)

unread channel (other team) / Dark Theme
![grafik](https://user-images.githubusercontent.com/120441/55793578-864fa580-5ac3-11e9-9eee-3ef6325b3876.png)

unread channel (same team) / Default Theme
![grafik](https://user-images.githubusercontent.com/120441/55794074-a03db800-5ac4-11e9-9a53-00b37681bc41.png)

unread channel (other team) / Default Theme
![grafik](https://user-images.githubusercontent.com/120441/55794068-9c119a80-5ac4-11e9-8b17-785316dab386.png)

**Comment by staabm** [comment]
in contrast, on slack the "unread-state" looks better to me:

![grafik](https://user-images.githubusercontent.com/120441/55797502-eac33280-5acc-11e9-9d5a-f57f0f6e0cbe.png)

I guess the text in slack is bolder then in mattermost and also has a bigger font-size

**Comment by amyblais** [comment]
Hi @staabm,

Thank you for the feedback,

As a workaround, have you had a chance to try sidebar sorting settings? They can be found under Account Settings > Sidebar. (I believe they have to be first enabled by a System Admin).

If you choose "Unreads grouped separately", then you will easily see which channels are unread as all unread channels will get grouped at the top of the screen.

Please let me know your thoughts on these options,

**Comment by amyblais** [comment]
Letting you know that I've forwarded your feedback to our UX team. I haven't received a response from them yet but I'll let you know when I do.

**Comment by amyblais** [comment]
Opened a ticket for UX team here: https://mattermost.atlassian.net/browse/MM-15031.
