### ISSUE TITLE
Review and refine in-product text for Channel Menu Settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost#10879]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15684)

Review in-product text for all Channel Menu Settings to determine improvements to make labels and descriptive text more helpful and clear to the end-user:  

* Include channel notification, channel header and channel purpose

Please reference: [https://github.com/mattermost/mattermost-webapp/tree/master/i18n](https://github.com/mattermost/mattermost-webapp/tree/master/i18n) and our [design guidelines](https://docs.mattermost.com/developer/fx-guidelines.html#design-guidelines) when working on these improvements.

**Comment by escofresco** [comment]
Can I take? (I'm getting some redux help for my other assigned issue and would like to fix something else in the meantime)

**Comment by esethna** [comment]
@escofresco we actually have some work underway to improve these modals, I'm going to close this ticket for now

**Comment by escofresco** [comment]
@esethna Wondering…should the other issues starting with **"Review and refine in-product text"** or can I claim one?

**Comment by esethna** [comment]
@escofresco good question, I'll defer to @cwarnermm (our technical writer). Carrie can you help review these open issues and close them + associated jira tickets for any that are no longer valid? https://github.com/mattermost/mattermost/issues?q=is%3Aissue+is%3Aopen+Review+and+refine+in-product+text

**Comment by cwarnermm** [comment]
Thanks for the ping, @esethna! I'll review the tickets and close as needed.
