### ISSUE TITLE
Review and refine in-product text on search hint box and no results found

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost#10889]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15686)

Review in-product text for search hint box and no search results found text to determine improvements to make text more helpful and clear to the end-user:  

Please reference: [https://github.com/mattermost/mattermost-webapp/tree/master/i18n](https://github.com/mattermost/mattermost-webapp/tree/master/i18n) and our [design guidelines](https://docs.mattermost.com/developer/fx-guidelines.html#design-guidelines) when working on these improvements.

**Comment by cwarnermm** [comment]
Closing
