### ISSUE TITLE
Allow Display of More Than 60 Flagged Posts

### ISSUE THREAD

**Issue by wtollett-usgs** [mattermost/mattermost#11064]
Currently, the app (this behavior is the same on the web, desktop, and phone) will only display 60 flagged posts. If the user flags a 61st post, one of the posts will be non-viewable until the user unflags another post and then closes and reopens the flagged post list. It would make sense to have a 'load more posts' link like there is when browsing channels.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @wtollett-usgs.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Actually, I'm not sure if this is a bug or feature request. Can you help confirm what Mattermost server version you're on?

**Comment by amyblais** [comment]
I opened a bug ticket for this earlier and it was changed into an improvement: https://mattermost.atlassian.net/browse/MM-17005.

**Comment by wtollett-usgs** [comment]
Sorry about the delayed response -- was out on vacation. We're running v5.8

**Comment by amyblais** [comment]
Closing as a feature request. Please share this as a feature request on Uservoice as described here https://github.com/mattermost/mattermost/issues/11064#issuecomment-499468242.
