### ISSUE TITLE
Reinstalling at the same URL requires users to manually delete all cookies

### ISSUE THREAD

**Issue by jernst** [mattermost/mattermost#11645]
In [UBOS](https://ubos.net/) testing, we often install, uninstall and re-install the same app at the same URL. When doing that, the new install uses the old cookies, and that confuses the app. Manual deleting of the cookies fixes it.

I don't know how important this issue is to others, but it would be nice if -- to the unspecting user -- the app wasn't left in a very confusing state saying "No sign-in methods are enabled. Please contact your System Administrator." Not sure the system administrator could tell easily either.

Original issue: https://github.com/uboslinux/ubos-mattermost/issues/11.

**Comment by amyblais** [comment]
Hi @jernst, what Mattermost server version are you on?

**Comment by jernst** [comment]
This has been the same behavior for a long time. Most recently observed in 5.12.4.

**Comment by amyblais** [comment]
Opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-17283.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
