### ISSUE TITLE
Can not upload image from mobile version when network speed is low

### ISSUE THREAD

**Issue by vania-github** [mattermost/mattermost#13575]
#### Summary
Can not upload image from mobile version when network speed is low.

#### Steps to reproduce
When I'm using the mobile app ( as much as Android as iOS ) and the network speed is low because I'm far from an antenna or because I'm connected to an old wifi without the optical fiber, I can not upload an image. The transfer does not end and I obtain the icon to replay the transfer. I did speed test, this issue occurs when I have less than 200 ko/s ( pure rate ).

#### Environment
App Version: 1.26.1 (Build 256)
Server Version: 5.13.0 (Build 5.13.2)
Database: MariaDB

#### Expected behavior
Even if the network speed is low, the transfer should take time but finish with success.

#### Observed behavior (that appears unintentional) 
This issue seems to come from the mobile app only because when my speed rate is low ( because I just have one 3G bar for instance ), I can not send my image with the app, but if I use a mobile webclient ( tried with Chrome, Opera, Firefox ), my transfer take time but it succeeds.

#### Observed logs 
In my logs, I can observ this strange line when the error occurs :
{"level":"error","ts":1578344026.2426882,"caller":"mlog/log.go:172","msg":"Unable  to upload file(s). Error reading or parsing request  data.","path":"/api/v4/files","request_id":"3zrr5iz5ekekiz7rtem918w","ip_addr":"X.X.X.X","user_id":"mbfedugpmdpnziifp9q8nco","method":"POST","err_where":"uploadFileMultipartLegacy","http_code":500,"err_details":"unexpected  EOF"}
It means that the server didn't receive the end of the post request.

#### Possible fixes
I didn't check the source code of the React Native mobile app, maybe there is a timeout set and when the network speed is low, this timeout is reached and the client stops the transfer.

**Comment by amyblais** [comment]
Hi @vania-github, I'm wondering if you notice any difference in one of our recent server versions such as 5.18. Would you be open to do some testing on https://community.mattermost.com/core (which is on 5.18) to see if you see any changes?

**Comment by vania-github** [comment]
Hi @amyblais ! Thank you for your answer.
So I created an account on your server and tried to send an image of 4,63 Mo from the mobile app ( Android and iOS ) using an an old wifi ( with a low connection ). And I got the same issue that I have on my server. The image upload did reach 100% and I got the replay icon.
I just did it two minutes ago, if you look at your logs, you should find the line that I have.

**Comment by amyblais** [comment]
@vania-github What iOS and Android versions are you on?

**Comment by vania-github** [comment]
@amyblais I tested on Android 9 and iOS 13.3.

**Comment by amyblais** [comment]
@vania-github We did some improvements around image uploads for v1.27.1 release, would you be open to updating to the latest when it is available in the app store?

**Comment by vania-github** [comment]
Hi @amyblais ! 
I updated my Mattermost mobile clients ( to v1.27.1 ), on my iOS and my Android, and the issue remains. When network speed is low, I can not upload files.

**Comment by amyblais** [comment]
Opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-22154.

**Comment by vania-github** [comment]
Thank you @amyblais for your consideration !

**Comment by sosek108** [comment]
Hello,

I have similar problem but it occurs always - no matter if you have good or bad connection.

**Comment by laimison** [comment]
Client: Latest Mattermost beta client on Android v2.0.0, 25 Jun 2022
Server: 6.1.4-rc1

I've got same `unexpected EOF` for `uploadFileMultipartLegacy`

I was resizing video resolution to reduce file size of same video to see how uploader behaves.
Few tests showed that upload that is taking longer than 60 seconds fails.

Can it be the case, that some timeout value just aborts upload after 60 seconds? `unexpected EOF` looks not graceful, as far as I know. So it aborts upload progress.

Can you advice if we are able to tune some timeout values?

Thanks
