### ISSUE TITLE
Team description bubble cut off in /select_team

### ISSUE THREAD

**Issue by Centzilius** [mattermost/mattermost#14112]
#### Summary
Description bubble of team in `/select_team` is cut off if it is at the top (or at least if the list only contains one team)

#### Steps to reproduce
Create a team (that you are not part of) with a semi long description and visit <mmurl>/select_team

#### Expected behavior
Bubble is not cut off at the border of the team list.

#### Observed behavior (that appears unintentional) 
Bubble is cut off
![Screenshot from 2020-03-19 13-46-42](https://user-images.githubusercontent.com/1499392/77069097-17bfdb00-69e8-11ea-9a57-638e9c4a87f1.png)
(For reference: The text that is in this bubble is "Für Fragen zu dieser Mattermost Instanz")

**Comment by amyblais** [comment]
@Centzilius What Mattermost server version are you on? What device and OS are you on?

**Comment by Centzilius** [comment]
@amyblais 
Mattermost Enterprise Edition w/o License version 5.21.0
Chromium 80 (private mode) on Arch Linux (desktop)

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-23457.

**Comment by Centzilius** [comment]
The issue is still present in Mattermost Community Edition version 7.5.2.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
