### ISSUE TITLE
promote guest to user: account joined as guest into off-topic channel

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost#14821]
If you have a guest user joined only to read-only ``town-square`` ("Announcements") and not to ``off-topic`` they will get joined into ``off-topic``, once you promote the account from guest to user.

The Problem is: The newly converted account is joined into ``off-topic`` as guest (in the db: ``scheme_guest = True, scheme_user = False``). The promoted user is able to do everything a user is able to, but it leads to the ``off-topic`` channel permanently having the label `This channel has guests` which is not really true.

#### Steps to reproduce
+ create a guest account
+ join to team
+ join to team's town-square
+ promote guest to user
+ watch the guest being "added to channel as guest"
+ watch the team's off-topic channel to get the ``This channel has guests``-label.

#### Expected behavior
+ promoting a guest to user should add them to ``off-topic`` as normal user, not as guest.
+ or add them as guest, but then convert them to user-memberships like it happens with other channels.

#### Observed behavior (that appears unintentional) 
+ promoting a guest to user adds the now-user as guest to ``off-topic`` (scheme_guest = True, scheme_user = False) instead of as user (scheme_guest = False, scheme_user = True)

**Comment by amyblais** [comment]
@someone-somenet-org What Mattermost server version are you currently on?

**Comment by someone-somenet-org** [comment]
@amyblais 5.23.0

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-26202.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
