### ISSUE TITLE
Incompatible with incoming webhook payloads in slack block kit format

### ISSUE THREAD

**Issue by Dalabad** [mattermost/mattermost#14973]
#### Summary
Incoming webhook messages in the "new" slack block kit format are ignoring the block content

- https://api.slack.com/block-kit
- https://app.slack.com/block-kit-builder/

#### Steps to reproduce
- Create an incoming webhook link
- Send the following Webhook content to the webhook url

`curl -X POST \
     -H 'Content-type: application/json; charset=utf-8' \
    --data '{"attachments":[{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Some content for the first block"}},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"Another block"}},{"type":"actions","elements":[{"type":"button","text":{"type":"plain_text","text":"Button 1","emoji":true},"value":"click_me_123"}]}]}]}' \
https://mattermost-webhook-link.com/hooks/............`

- This works with all the examples/templates from the "block kit builder" page

#### Expected behavior
Here is a screenshot of what the webhook should look like on slack.

![block-kit-slack](https://user-images.githubusercontent.com/2007311/86570297-fde2dd80-bf6f-11ea-8bd4-0e97126a5be6.png)

#### Observed behavior (that appears unintentional) 
This screenshot shows, how the webhook is displayed by mattermost. The attachment part is displayed (visible by the box with the blue line on the left) but the content of the attachment block is completely missing. Blocks can also appear outside of the attachments block as it can be seen in the official block kit documentation.

![block-kit-mattermost](https://user-images.githubusercontent.com/2007311/86570295-fd4a4700-bf6f-11ea-9183-7f9cf9ec99d5.png)

**Comment by amyblais** [comment]
@Dalabad Would you be open to confirming your Mattermost server version?

**Comment by Dalabad** [comment]
@amyblais Sure thing. My testing instance has the following version:

Mattermost Version: 5.21.0
Database Schema Version: 5.21.0
Database: postgres

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-26729.
