### ISSUE TITLE
align entrypoint.sh with one in mattermost-docker

### ISSUE THREAD

**Issue by laur89** [mattermost/mattermost#15554]
#### Summary
This image's `entrypoint.sh` should be brought in-line with the one in [mattermost-docker/app](https://github.com/mattermost/mattermost-docker/blob/master/app/entrypoint.sh) - we'd still likely want the initial configuration, and it overall makes sense to keep uniform behavior.

#### Expected
`entrypoint.sh` in this repository should contain the bootstrap code as its counterpart in mattermost-docker repository.

#### Actual
`entrypoint.sh` in this repository contains no initial bootstrap code.

**Comment by laur89** [comment]
Maybe provide base-image for both of them to avoid code duplication? Or maybe docker mods, however [LSIO guys](https://github.com/linuxserver/docker-mods) implement it (basically enables pulling in a single layer).

**Comment by amyblais** [comment]
I created a ticket https://mattermost.atlassian.net/browse/DOPS-861.

**Comment by amyblais** [comment]
The ticket was closed as won't fix for now,
