### ISSUE TITLE
Information Loss: Messages Missing From Message Stream After Connection Issue On Receiver Side

### ISSUE THREAD

**Issue by gohrner** [mattermost/mattermost#16505]
#### Summary
Sent message seems to have been permanently lost for a user due to connection issues.
I.e. the message was
1. sent successfully by the sender
1. and appears in her/his message stream,
1. but does not appear in the receiver's stream
1. also not after switching channels.

#### Steps to reproduce
Sender A used Mattermost desktop app and had a stable connection.
While sending the message, receiver B, using the Mattermost web frontend, had a disconnect due to changing the workplace and thus temporarily unplugging the wired Ethernet connection.

Sender A sent a message during this time.

#### Expected behavior
The message from Sender A should appear in receiver B's message stream / channel after the connection was re-established.

#### Observed behavior (that appears unintentional) 
The message is missing on the receiver side and also does not appear after switching channels and back.

The sender does not have any indication that not all of his/her messages actually reached the receiver!

See screenshot at sender and receiver side, notice the timestamps and the missing message with timestamp 12:52:
![image](https://user-images.githubusercontent.com/26199042/101355786-645d8600-3897-11eb-98ff-1852b3774f01.png)
![image](https://user-images.githubusercontent.com/26199042/101355799-69223a00-3897-11eb-8537-2c6154ba11d2.png)

#### Possible fixes
Unknown.

**Comment by amyblais** [comment]
@gohrner 
1. What OS and version is the Mattermost server installed?
2. What is your Mattermost server version?
3. Are you experiencing the issues with the browser webapp, if so which one?
4. Can you send a snippet of the Mattermost server logs around the time of the incident?

**Comment by gohrner** [comment]
Oh, sorry, beginner's mistakes... :-/

> * What OS and version is the Mattermost server installed?

Debian Buster 10.7 x64

> * What is your Mattermost server version?

Mattermost Version: 5.25.5
Database Schema Version: 5.25.0
Database: mysql

> * Are you experiencing the issues with the browser webapp, if so which one?

Not sure if I understand the question? What do you mean by "which webapp"?

I was the user who cannot see the message. I'm just using a browser (Chromium Version 87.0.4280.88 (Offizieller Build) snap (64-Bit)) to access the Mattermost server.

> * Can you send a snippet of the Mattermost server logs around the time of the incident?

The last log message seems to be from this night, so apparently there are no relevant logs of the incident. File log level is "INFO".

**Comment by amyblais** [comment]
@gohrner Do you experience this issue on the latest ESR version (v5.25.7)? Would you be open to changing the log level to DEBUG to gather any errors when the issue happens again?

**Comment by agnivade** [comment]
This is a known issue, and should be fixed once we have reliability implemented as part of the message send architecture.
