### ISSUE TITLE
Recommend a more privacy friendly app than GAuthenticator for MFA

### ISSUE THREAD

**Issue by madonius** [mattermost/mattermost#16904]
#### Summary
Mattermost suggests that the users use Google Authenticator which no longer is available under a free license.
I would propose making a different recommendation.
(I could not verify if there already is a ticket Jira throws 500s)

#### Steps to reproduce
Enable MFA for your account, the dialogue recommends Google Authenticator

#### Expected behavior
A more privacy conform or ideally opensource app is beeing recommended

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @madonius,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by NicolasCARPi** [comment]
The idea is awaiting moderator approval, but here it is:

https://mattermost.uservoice.com/forums/306457-general/suggestions/48669407-recommend-a-more-privacy-friendly-app-than-google

@madonius @kantorkel @martin-v @MFTabriz please upvote :)

**Comment by amyblais** [comment]
Closing for tracking on UserVoice,
