### ISSUE TITLE
Autolinking doesn't work for TLDs longer than 4 characters

### ISSUE THREAD

**Issue by Gittenburg** [mattermost/mattermost#17025]
#### Summary

The Markdown autolinking only works for TLDs up to 4 characters.
Even though there are [many new TLDs with more than 4 characters](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains), e.g. `.africa`, `.computer`, etc.
In fact TLDs can be as long as 63 characters.

#### Steps to reproduce

With Mattermost v5.32.1, send a message with:

```md
* example.com/page
* example.computer/page
```

#### Expected behavior
Both links are autolinked.

#### Observed behavior (that appears unintentional) 
Only the first link is autolinked since the TLD of the second link has more than 4 characters.

#### Possible fixes
Increase the autolink TLD limit to 63 characters or alternatively check the TLD against a list of all TLDs.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-33321

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
