### ISSUE TITLE
Authorize screen for OAuth 2.0 apps always shown when user had to login to Mattermost

### ISSUE THREAD

**Issue by bauerj** [mattermost/mattermost#17370]
#### Summary
When users have to login for an OAuth request, the "Authorize" screen is always shown, even if it shouldn't be.

#### Steps to reproduce
1. Set up an OAuth 2.0 application (e.g. https://github.com/mattermost/mattermost-oauth2-client-sample)
2. Add it as an integration to Mattermost and set it to "trusted". 
![image](https://user-images.githubusercontent.com/598790/114192746-21e3ad00-994e-11eb-8b68-5b580f9fe269.png)

3. Logout from Mattermost
4. Start Authorization from the OAuth 2.0 application
5. Login to Mattermost when asked to

#### Expected behavior
Since the application has been added as trusted, according to the docs it "does not require the user to accept authorization."

#### Observed behavior (that appears unintentional) 
This screen appears:
![image](https://user-images.githubusercontent.com/598790/114192373-b00b6380-994d-11eb-9d91-1e43143c4467.png)

If I refresh the tab, I get properly redirected to the OAuth 2.0 application and am authorized correctly. It also works as intended when I'm logged in to Mattermost before starting the authorization.

#### Other information
This is on a freshly installed Mattermost 5.33.3.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-34737

**Comment by haivala** [comment]
I'm experiencing almost the same thing. (MM 6.6)
Our instance asks the confirmation always no matter what you do.
