### ISSUE TITLE
Changing a channel on iPad opens the onscreen keyboard

### ISSUE THREAD

**Issue by staabm** [mattermost/mattermost#17539]
#### Summary

jumping between channels on ipad, when using the default webinterface opens up the onscreen keyboard, which is annoying.

#### Steps to reproduce
- login with ipad on the webinterface
- Select a channel from the sidebar -> keyboard opens
- Jump to another channel -> keyboard opens

the same happens when changing teams via the navigation, but I guess its the same cause. Changing the team means also changes the channel.

#### Expected behavior
Keyboard should not open per default, because with a onscreen keyboard it makes the whole ui shifiting/flowing arround on every channel switch

#### Observed behavior (that appears unintentional) 
I guess the cause is that the message input field is focused. 

#### Possible fixes
Dont focus the input field on iOS/touch devices

Mattermost-Version: 5.33.2
Datenbankschema-Version: 5.33.2
Datenbank: mysql

**Comment by amyblais** [comment]
QA was able to reproduce, ticket here: https://mattermost.atlassian.net/browse/MM-35328

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
