### ISSUE TITLE
🎯 Focalboard: Help wanted tickets

### ISSUE THREAD

**Issue by chenilim** [mattermost/mattermost#17625]
![Focalboard screenshot](https://user-images.githubusercontent.com/46905241/118319025-09b40000-b4af-11eb-9054-e9fe794d6c57.jpg)

Focalboard is an open source, self-hostable alternative to Trello, Notion, and Asana. It will [soon ship](https://github.com/mattermost/focalboard/discussions/349) as part of Mattermost, and we need your help to make it awesome!

Check out the [Focalboard repo](https://github.com/mattermost/focalboard) and [contributors guide](https://www.focalboard.com/contribute/getting-started/) to get started.

### Popular searches for Help Wanted issues:
* [Help wanted tickets currently up for grab](https://github.com/mattermost/focalboard/issues?q=is%3Aissue+is%3Aopen+label%3A%22Up+for+grabs%22)
* [Good first issue tickets](https://github.com/mattermost/focalboard/issues?q=is%3Aopen+label%3A%22good+first+issue%22+label%3A%22up+for+grabs%22)

For more information, also check out our [Road to v1.0](https://github.com/mattermost/focalboard/discussions/413) and come chat with us on the very friendly [Focalboard channel](https://community.mattermost.com/core/channels/focalboard).

Thank you! ❤️

**Comment by wintercodeNKJJ** [comment]
Hi, I am new to open source contrib. could I take on this issue if no one is working on it already?

**Comment by amyblais** [comment]
@wintercodeNKJJ Feel free to grab any of the Help Wanted issues from these links:
* [Help wanted tickets currently up for grab](https://github.com/mattermost/focalboard/issues?q=is%3Aissue+is%3Aopen+label%3A%22Up+for+grabs%22)
* [Good first issue tickets](https://github.com/mattermost/focalboard/issues?q=is%3Aopen+label%3A%22good+first+issue%22+label%3A%22up+for+grabs%22)

**Comment by wintercodeNKJJ** [comment]
@amyblais Thank you very much 🙏

**Comment by Mishrasubha** [comment]
Hey @amyblais, can I take up this issue?
