### ISSUE TITLE
Console's apply button get hidden on iPad OS Safari

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/mattermost#17639]
#### Summary
On iPad OS (iPad Pro 12.9) 'apply' button jump almost below reachability, when some of the settings get changed - please, see screenshot.
It's also quite hardly reachable, if Safari's URL bar is not hidden.

#### Steps to reproduce
Open settings, change any setting, node the apply button jumps down.

#### Expected behavior
Apply button to stay where it is =)

#### Observed behavior (that appears unintentional) 
That's where the button happened to be, after the setting has been changed.
<img width="1366" alt="System Console - Mattermost" src="https://user-images.githubusercontent.com/2323840/118664788-6d656280-b7fa-11eb-96f6-dbace485933d.png">

**Comment by amyblais** [comment]
@alexander-akhmetov What Mattermost server version and Mattermost mobile app version are you on?

**Comment by amyblais** [comment]
Meant to ping @alexander-potemkin ^

**Comment by alexander-potemkin** [comment]
@amyblais , 1.42.1 (build 354) for the app; 5.34.0 (5.34.2 build) for the server; team edition.

**Comment by josephbaylon** [comment]
@alexander-akhmetov @amyblais This looks like mobile-web and NOT mobile-native scenario. I'm not able to reproduce the issue on v5.35 server. Please try v5.35

**Comment by amyblais** [comment]
@alexander-potemkin Please try v5.35 (server version) ^

**Comment by alexander-potemkin** [comment]
Ok, but my server is managed by Cloudron, so the update will take some time

**Comment by alexander-potemkin** [comment]
<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/2323840/121226408-329f9900-c893-11eb-85a7-0a1898fea257.png">
Thanks for waiting. It doesn't jump, but I just can't reach it now.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-36292

**Comment by alexander-potemkin** [comment]
@amyblais , any ETA on this?

**Comment by amyblais** [comment]
I don't have a specific update at this moment, the ticket is in one of our dev teams' queue.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
