### ISSUE TITLE
Healthcheck fails for mattermost-team-edition docker image when HTTPS is used

### ISSUE THREAD

**Issue by Petaris** [mattermost/mattermost#17833]
#### Summary
Healthcheck fails for mattermost-team-edition docker image when HTTPS is used

#### Steps to reproduce
- Run mattermost-team-edition docker image with required configuration for using HTTPS
- - Make sure this is done properly and that you have a correctly working HTTPS connection to mattermost
- Check the docker container with "docker ps", you will see that it has a status of "unhealthy"
- - This is because the dockerfile has this:
`#Healthcheck to make sure container is ready
HEALTHCHECK --interval=30s --timeout=10s \
  CMD curl -f http://localhost:8065/api/v4/system/ping || exit 1`

#### Expected behavior
As this is not the "preview" container it should be expected that HTTPS will be used, not HTTP.  I would expect the health check to use HTTPS for its check

#### Observed behavior (that appears unintentional) 
Mattermost works properly however the docker instance sees it as "unhealthy".

#### Possible fixes
Update this line to be `CMD curl --insecure -f https://localhost:8065/api/v4/system/ping || exit 1`
Line in dockerfile:  https://github.com/mattermost/mattermost-server/blob/a9b3e423e6a181c49db96048c0c6fc12d275c330/build/Dockerfile#L38

The reason for the "insecure" option is that any self singed CA issued cert would throw errors as there is no way to provide the CA cert to the command once it is deployed"

**Comment by amyblais** [comment]
@cpanato @metanerd Would you like me to open a ticket for this?

**Comment by cpanato** [comment]
I'm not sure if we want to change that

**Comment by cpanato** [comment]
@Petaris thanks for this issue

can you describe the steps you mention above

> Run mattermost-team-edition docker image with required configuration for using HTTPS
Make sure this is done properly and that you have a correctly working HTTPS connection to mattermost

**Comment by Petaris** [comment]
@cpanato Its just the steps to setup HTTPS, provide the cert/key, and verify that you can connect to the Mattermost service with HTTPS without errors.

In my case I have:
- A certificate signed by our internal CA and the private key in a docker volume that gets mounted in the container: "-v /mnt/dockervol/mattermost/certs:/certs"
- The configuration in the Mattermost System Console > Web Server
- - Setting the "Site URL" to https
- - Setting "Connection Security" to TLS
- - Setting "TLS Certificate File" to the path to the cert
- - Setting "TLS Key File" to the path to the private key (for the cert)
- - Hitting "Save"
- - Restarting the docker container
- Connect to Mattermost using a web browser that has out Internal CA cert and verify that I can connect using HTTPS without errors or warnings

I continued to use the port 8065, others might change this which would also break this health check.  Is there a way the health check could be done in an alternate fashion that would not depend on what the protocol and port are for the Mattermost service?  That would solve both issues if there is a way.

**Comment by amyblais** [comment]
Opened a ticket for Devops https://mattermost.atlassian.net/browse/DOPS-862.

**Comment by NicolasCARPi** [comment]
Hello,

I believe one way of solving this issue would be to add this to the docker-compose config of the MM service:

~~~yml
healthcheck:
      test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8065/api/v4/system/ping"]
      interval: 5m
      timeout: 10s
      retries: 3
~~~

This will override the HEALTHCHECK of the Dockerfile.

**Comment by kchiem** [comment]
Wasted some time scratching my head on this one.

How about?

```
CMD curl -f http://localhost:8065/api/v4/system/ping || curl -kf https://localhost:8065/api/v4/system/ping || exit 1
```

**Comment by Petaris** [comment]
Does anyone know where the Dockerfile went?  Its not in the same path as it was previously in this repo.

**Comment by NicolasCARPi** [comment]
@Petaris https://github.com/mattermost/mattermost-server/blob/master/server/build/Dockerfile
