### ISSUE TITLE
Sidebar channel group headers visible through sidebar menu during opening animation

### ISSUE THREAD

**Issue by LauSam09** [mattermost/mattermost#18049]
#### Summary
Sidebar channel group headers visible through sidebar menu whilst it is animating.

#### Steps to reproduce
Tested on version 5.36.0 in Chrome 92.0.4515.107 (Linux) and Firefox 90.0.2 (Linux):
1. Open the menu with sidebar channel group headers positioned behind it.
2. Observe that they are visible with full opacity throughout the duration of the menu opening animation.

#### Expected behavior
Expect the headers to be no more opaque than the other elements behind the menu.

#### Observed behavior (that appears unintentional) 
The sidebar channel group headers appear more visible than surrounding elements.

#### Possible fixes
As shown in the GIF, removing the `background-color` style from the .SidebarChannelGroupHeader class fixes the problem, however I don't really understand why or what other consequences this may have.

![blinking-menu](https://user-images.githubusercontent.com/24778857/128052095-9edb7856-21ba-4443-b48d-088286b6f538.gif)

**Comment by amyblais** [comment]
Thanks, opened a ticket https://mattermost.atlassian.net/browse/MM-37615.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
