### ISSUE TITLE
Setting users authentication method to email via API fails

### ISSUE THREAD

**Issue by BaaaZen** [mattermost/mattermost#18115]
#### Summary
Almost all our users use the LDAP service to log in. Now we have a single user that should be switched back to email authentication. I was using the API call https://api.mattermost.com/#operation/UpdateUserAuth to switch the authentication method. From the documentation and the attributes of other users having email authentication active I was sure to set the parameters `auth_service` and `auth_data` to an empty string. But setting one of them to an empty string caused an error response.

#### Steps to reproduce
For settings an empty `auth_service`:
```
curl -XPUT -H "Content-type: application/json" -H "Authorization: Bearer ${TOKEN}" -d '{"auth_data":"", "auth_service":""}' 'https://${SERVER}/api/v4/users/${USER_ID}/auth'
```

For setting `auth_service == 'email'`:
```
curl -XPUT -H "Content-type: application/json" -H "Authorization: Bearer ${TOKEN}" -d '{"auth_data":"", "auth_service":"email"}' 'https://${SERVER}/api/v4/users/${USER_ID}/auth'
```

#### Expected behavior
HTTP Status 200
```json
{
  "auth_data":"",
  "auth_service":""
}
```

#### Observed behavior (that appears unintentional)
HTTP Status 400 
```json
{
  "id":"api.user.update_user_auth.invalid_request",
  "message":"Anfrage fehlt entweder der AuthData oder AuthService parameter.",
  "detailed_error":"",
  "request_id":"xxty1pyd3jydxq4rogsdscia9r",
  "status_code":400
}
```

#### Possible fixes
I think the problem is here:
https://github.com/mattermost/mattermost-server/blob/master/api4/user.go#L1460
This prevents setting empty strings - is this intended to do so? 

What would be the correct way to switch the user back to email authentication?

**Comment by amyblais** [comment]
@isacikgoz @mkraft Let me know if you'd have thoughts on this issue.

**Comment by isacikgoz** [comment]
It seems like this issue introduced in `v5.33`. Created the [ticket](https://mattermost.atlassian.net/browse/MM-37830).

**Comment by amyblais** [comment]
Closing as we haven't been able to prioritize fixing this. Please let us know if this reproduces on the latest Mattermost version,
