### ISSUE TITLE
Improve the new channel switcher sort by listing channels with unread messages with a mention

### ISSUE THREAD

**Issue by glunardi** [mattermost/mattermost#18294]
The contributing Feature Proposal was created back in January 2017:
https://mattermost.uservoice.com/forums/306457-general/suggestions/17828368-sort-channel-when-switching-with-ctrl-cmd-k-by-unr

This is related to:
https://github.com/mattermost/mattermost-server/issues/14633

#### Summary

The old sort with unread channels with mention listed first, then unread channels, then the rest of the channels worked really well I thought.

#### Steps to reproduce

- Have a few dozen channels with unread messages
- Have 10 or more channels (or direct messages) with unread messages with mentions
- And try to get through them efficiently. It feels really difficult now that the Channel Switcher sort

Before you could just Ctrl+K and Arrow-down to the right channel/direct message

#### Expected behavior

The desire here is to make it easy for heavy users to navigate and jump to unread messages with a mention

Please see the comment posted here:
https://github.com/mattermost/mattermost-server/issues/14633#issuecomment-907289324

#### Observed behavior (that appears unintentional) 

The new sort is very non-intuitive for users who jump between channels constantly. I can never find what I am looking for in the new Channel Switcher.

#### Possible fixes

- Revert to the old sort solution
- Add to the new sort that the unread channel with mentions are listed first
- Make it user configurable 
- Create a separate dialog for quickly go to unread mentions (the Recent mentions Ctrl+Shift+M is not that and too slow)

**Comment by raoulbhatia** [comment]
I also enjoyed the old functionality where I was able use the "quick channel switcher dialog" to clearly identify all unread conversations and was able to specifically pick the ones I care about most first.

**Comment by neszt** [comment]
In the new mattermost version, I was surprised to find that the previous function (ctrl + k) has changed and there is no shortcut to quickly find my unread messages. It was a great feature and I say this as a non power user. The new recent list has negligible benefits for me, so +1 point for the old functionality.

**Comment by esethna** [comment]
Thanks for the feedback all, we have some improvement tickets open to bring back some unread functionality to the switcher and still offer recent channels
