### ISSUE TITLE
Long threads (> 119 messages) crash the Mattermost websocket

### ISSUE THREAD

**Issue by ReagentX** [mattermost/mattermost#18319]
#### Summary
Replying to a thread longer than 119 messages crashes Mattermost.

#### Steps to reproduce
Reply to any thread with 119 messages already in it.

#### Expected behavior
Message replies work.

#### Observed behavior (that appears unintentional) 
Mattermost crashes to a blank screen.

#### Possible fixes

```log
react_devtools_backend.js:2850 TypeError: Cannot read property 'id' of undefined
    at ct.componentDidUpdate (thread_viewer.tsx:218)
    at ii (react-dom.production.min.js:212)
    at gu (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at _u (react-dom.production.min.js:248)
    at nu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
```

This happens because the websocket dies, and `id` becomes undefined [here](https://github.com/mattermost/mattermost-webapp/blob/dbeb28b6150c0093d7fcd6cf9265429e7c6825c8/components/threading/thread_viewer/thread_viewer.tsx#L70-L84):

```js
public componentDidUpdate(prevProps: Props) {
        const prevPostsArray = prevProps.posts || [];
        const curPostsArray = this.props.posts || [];

        const reconnected = this.props.socketConnectionStatus && !prevProps.socketConnectionStatus;
        const selectedChanged = this.props.selected.id !== prevProps.selected.id;

        if (reconnected || selectedChanged) {
            this.props.actions.getPostThread(this.props.selected.id);

            if (
                this.props.isCollapsedThreadsEnabled &&
                this.props.userThread == null
            ) {
                this.fetchThread();
            }
        }
```

This might be related to the retention policy, as the first message in the thread may have been removed and thus cannot be found.

**Comment by amyblais** [comment]
@ReagentX 
1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see any errors in Mattermost logs?

**Comment by ReagentX** [comment]
1. Server 5.38.2
2. MacOS 10.14.6 (18G9323) , Mattermost Desktop Version Version 4.7.1 (4.7.1.11707) (replicates in Chrome as well)
3. No

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-38278

**Comment by vineelyalamarthy** [comment]
@amyblais  any dev help needed?

**Comment by amyblais** [comment]
Closing as we haven't been able to reproduce this internally,
