### ISSUE TITLE
Plugin API for Custom Statuses

### ISSUE THREAD

**Issue by vblz** [mattermost/mattermost#18389]
There is a feature called "Custom status". There is API to set, get and delete user's custom status: `/api/v4/users/me/status/custom`.  In web client, desktop client, mobile client users can set a custom status. But in plugin API there are no methods to manage users' statuses: https://github.com/mattermost/mattermost-server/blob/f9bd7cce8e31f5baa2809a6a752f7d5b2d74c035/plugin/api.go

**Comment by amyblais** [comment]
Opened a ticket https://mattermost.atlassian.net/browse/MM-38576
