### ISSUE TITLE
Doing bulk export/import drops saved post data

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost#18641]
#### Summary
Since `Post.FlaggedBy` is not the target of bulk export, saved posts will be dropped while migration process via bulk export/import. [This condition](https://github.com/mattermost/mattermost-server/blob/561bc968c8737bd44ee0c6e0f08314f7ea0f5897/app/import_functions.go#L1329-L1330) never been true.

#### Steps to reproduce
1. Doing bulk export by `bin/mattermost export bulk data.json`
2. Doing import exported data to new mm instance by `bin/mattermost import bulk data.json`

#### Expected behavior
Saved posts is imported to new instance.

#### Observed behavior (that appears unintentional) 
Saved posts is empty for all users.

#### Possible fixes
Make [PreferenceCategoryFlaggedPost](https://github.com/mattermost/mattermost-server/blob/561bc968c8737bd44ee0c6e0f08314f7ea0f5897/model/preference.go#L19) the target of export

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-39271

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
