### ISSUE TITLE
Failed upgrade to 6.0

### ISSUE THREAD

**Issue by olivierlambert** [mattermost/mattermost#18663]
#### Summary
Upgrading from Matermost 5.38 to 6.0 leads to mattermost failing to start

#### Steps to reproduce
Upgrading from 5.38 to 6.0 on Debian

#### Expected behavior
Upgrade and database migration should work

#### Observed behavior (that appears unintentional) 
Process output is relevant:
```
oct. 13 08:09:56 shelter mattermost[23950]: {"timestamp":"2021-10-13 08:09:56.533 +02:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:252","database":"master"}
oct. 13 08:09:56 shelter mattermost[23950]: {"timestamp":"2021-10-13 08:09:56.537 +02:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:252","database":"migrations"}
oct. 13 08:09:56 shelter mattermost[23950]: {"timestamp":"2021-10-13 08:09:56.622 +02:00","level":"warn","msg":"Attempting to upgrade the database schema version","caller":"sqlstore/upgrade.go:245","stored_version":"5.38.0","current_version":"5.38.0","new_version":"5.39.0"}
oct. 13 08:09:56 shelter mattermost[23950]: {"timestamp":"2021-10-13 08:09:56.623 +02:00","level":"warn","msg":"The database schema version has been upgraded","caller":"sqlstore/upgrade.go:226","version":"5.39.0"}
oct. 13 08:10:26 shelter mattermost[23950]: {"timestamp":"2021-10-13 08:10:26.683 +02:00","level":"fatal","msg":"Failed to alter column type. It is likely you have invalid JSON values in the column. Please fix the values manually and run the migration again.","caller":"sqlstore/store.go:854","error":"pq: la valeur par défaut de la colonne « timezone » ne peut pas être convertie vers le\ntype jsonb automatiquement"}
oct. 13 08:10:26 shelter systemd[1]: mattermost.service: Main process exited, code=exited, status=1/FAILURE
oct. 13 08:10:26 shelter systemd[1]: mattermost.service: Failed with result 'exit-code'.
```

The interesting thing is this sentence I translated (from French to English):
```
Failed to alter column type. It is likely you have invalid JSON values in the column. Please fix the values manually and run the migration again.","caller":"sqlstore/store.go:854","error":"pq: default value for the row « timezone » can't be converted automatically toward jsonb type"]
```

#### Possible fixes
I have no idea

**Comment by agnivade** [comment]
It seems that the "timezone" column in your "users" table has invalid JSON values. You would need to manually inspect that column and fix the incorrect values.

cc @streamer45

**Comment by olivierlambert** [comment]
That's weird, I never tinkered the database manually :thinking: The current version seems to be working without any issue. But yes, it seems to be related to a malformed JSON

**Comment by masterbender** [comment]
i got the same error: 
```
Oct 13 08:29:01 mattermost mattermost[43642]: {"timestamp":"2021-10-13 08:29:01.439 +02:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:252","database":"master"}
Oct 13 08:29:01 mattermost mattermost[43642]: {"timestamp":"2021-10-13 08:29:01.460 +02:00","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:252","database":"migrations"}
Oct 13 08:29:01 mattermost mattermost[43642]: {"timestamp":"2021-10-13 08:29:01.620 +02:00","level":"fatal","msg":"Failed to alter column type. It is likely you have invalid JSON values in the column. Please fix the values manually and run the migration again.","caller":"sqlstore/store.go:854","error":"pq: Vorgabewert der Spalte »timezone« kann nicht automatisch in Typ jsonb umgewandelt werden"}
```

**Comment by masterbender** [comment]
@availchet , @streamer45  postgres version is 13 , upgrading from 5.3X

**Comment by streamer45** [comment]
Okay the problem seems to be that you have a default value for the column which is causing this. I suggest to drop it and try again:

```
ALTER TABLE users ALTER COLUMN timezone DROP DEFAULT;
```

**Comment by masterbender** [comment]
> @masterbender can you tell me the exact steps you did?


1.) stop mattermost service / container 
2.) using psql ( or a tool of choise) log into the postgres db 
3.) ALTER TABLE users ALTER COLUMN timezone DROP DEFAULT; 
4.) restart the service 
5.) db migrations passed , mm is running again
6.) fill the timezone colums ( now jsonb format ) with json string :  ``` {"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"} ```

u can use ``` UPDATE users SET timezone =  {"manualTimezone": "", "automaticTimezone": "", "useAutomaticTimezone": "true"} ```

**Comment by streamer45** [comment]
@olivierlambert We just need to make sure to update the timezone only where empty otherwise we risk resetting non-default data.

**Comment by streamer45** [comment]
> after doing that:
> 
> ```
> Oct 13 09:27:29 mattermost mattermost[44295]: {"timestamp":"2021-10-13 09:27:29.149 +02:00","level":"error","msg":"Unable to find an existing account matching your username for this team. This team may require an invite from the team owner to join.","caller":"web/context.go:105","path":"/api/v4/users/34w1z1yrqir8fdob9zmfx3pe5w/image","request_id":"pncyo1ehijgoiqkzc1fhyokokr","ip_addr":"178.157.244.219","user_id":"34w1z1yrqir8fdob9zmfx3pe5w","method":"GET","err_where":"GetUser","http_code":500,"err_details":"failed to unmarshal user timezone: unexpected end of JSON input"}
> ```
> 
> i inserted the json from befor and now it works
> 
> but its a little bit risky to perform in production scream

@masterbender
That's very unusual, was the timezone field empty? If so the upgrade would have failed anyway. Dropping the default doesn't change the data in the existing users so I am not sure how you could get that error unless something was manually modified.

**Comment by masterbender** [comment]
it was not empty , it contains a correct json string before: ```{"automaticTimezone":"","manualTimezone":"","useAutomaticTimezone":"true"} ```

after performing ALTER TABLE users ALTER COLUMN timezone DROP DEFAULT the field was null ( i used datagrip, maybe the reason )

**Comment by streamer45** [comment]
Okay that makes sense. Any idea how it got to be `NULL` though? It seems very strange that dropping the default could be causing for previously inserted data. Also I assume the server was not running when doing all this.

**Comment by MikeN123** [comment]
FYI, just running `ALTER TABLE users ALTER COLUMN timezone DROP DEFAULT;` worked for me.

**Comment by khanhibus** [comment]
Hello,

I am getting a different error but similar to the OP's:

`{"timestamp":"2021-10-13 03:07:19.894 -07:00","level":"fatal","msg":"Failed to alter column type. It is likely you have invalid JSON values in the column. Please fix the values manually and run the migration again.","caller":"sqlstore/store.go:854","error":"pq: unsupported Unicode escape sequence"}`

Any ideas on how to fix this?

**Comment by streamer45** [comment]
@khanhibus 

That is a separate (although related) issue. Some DB column has an invalid character that is causing the conversion to fail. To better identify the issue, could you share the output of the following query:

```sql
SELECT table_name, column_name, data_type FROM information_schema.columns WHERE table_name IN ('posts', 'users', 'channelmembers', 'jobs', 'linkmetadata', 'threads', 'sessions');
```

**Comment by khanhibus** [comment]
@streamer45 

Please see the output below:

`
table_name   |    column_name     |     data_type     
----------------+--------------------+-------------------
 threads        | postid             | character varying
 threads        | channelid          | character varying
 threads        | replycount         | bigint
 threads        | lastreplyat        | bigint
 threads        | participants       | text
 posts          | id                 | character varying
 posts          | createat           | bigint
 posts          | updateat           | bigint
 posts          | editat             | bigint
 posts          | deleteat           | bigint
 posts          | ispinned           | boolean
 posts          | userid             | character varying
 posts          | channelid          | character varying
 posts          | rootid             | character varying
 posts          | parentid           | character varying
 posts          | originalid         | character varying
 posts          | message            | character varying
 posts          | type               | character varying
 posts          | props              | character varying
 posts          | hashtags           | character varying
 posts          | filenames          | character varying
 posts          | fileids            | character varying
 posts          | hasreactions       | boolean
 posts          | remoteid           | character varying
 channelmembers | channelid          | character varying
 channelmembers | userid             | character varying
 channelmembers | roles              | character varying
 channelmembers | lastviewedat       | bigint
 channelmembers | msgcount           | bigint
 channelmembers | mentioncount       | bigint
 channelmembers | notifyprops        | character varying
 channelmembers | lastupdateat       | bigint
 channelmembers | schemeuser         | boolean
 channelmembers | schemeadmin        | boolean
 channelmembers | schemeguest        | boolean
 channelmembers | mentioncountroot   | bigint
 channelmembers | msgcountroot       | bigint
 jobs           | id                 | character varying
 jobs           | type               | character varying
 jobs           | priority           | bigint
 jobs           | createat           | bigint
 jobs           | startat            | bigint
 jobs           | lastactivityat     | bigint
 jobs           | status             | character varying
 jobs           | progress           | bigint
 jobs           | data               | character varying
 linkmetadata   | hash               | bigint
 linkmetadata   | url                | character varying
 linkmetadata   | timestamp          | bigint
 linkmetadata   | type               | character varying
 linkmetadata   | data               | character varying
 sessions       | id                 | character varying
 sessions       | token              | character varying
 sessions       | createat           | bigint
 sessions       | expiresat          | bigint
 sessions       | lastactivityat     | bigint
 sessions       | userid             | character varying
 sessions       | deviceid           | character varying
 sessions       | roles              | character varying
 sessions       | isoauth            | boolean
 sessions       | props              | character varying
 sessions       | expirednotify      | boolean
 users          | id                 | character varying
 users          | createat           | bigint
 users          | updateat           | bigint
 users          | deleteat           | bigint
 users          | username           | character varying
 users          | password           | character varying
 users          | authdata           | character varying
 users          | authservice        | character varying
 users          | email              | character varying
 users          | emailverified      | boolean
 users          | nickname           | character varying
 users          | firstname          | character varying
 users          | lastname           | character varying
 users          | position           | character varying
 users          | roles              | character varying
 users          | allowmarketing     | boolean
 users          | props              | character varying
 users          | notifyprops        | character varying
 users          | lastpasswordupdate | bigint
 users          | lastpictureupdate  | bigint
 users          | failedattempts     | integer
 users          | locale             | character varying
 users          | timezone           | character varying
 users          | mfaactive          | boolean
 users          | mfasecret          | character varying
 users          | remoteid           | character varying
(88 rows)
`

**Comment by jondale** [comment]
Mine seems a little different.

```
{"timestamp":"2021-10-14 00:59:15.974 Z","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:252","database":"migrations"}
{"timestamp":"2021-10-14 00:59:15.978 Z","level":"fatal","msg":"Error creating database tables.","caller":"sqlstore/store.go:199","error":"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json, `LastUpdateAt` bigint, `SchemeUser` tinyint, `SchemeAdmin` tinyint, `Schem' at line 1"}

```

**Comment by streamer45** [comment]
@khanhibus Thanks, looks like nothing has been converted which suggests there may be a problem with the `Posts.Props` column, unless you somehow downgraded (or restored the db).

To find out what's going could you run (and share the output for) the following set of queries?

```sql
SELECT COUNT(*) FROM Posts WHERE Props LIKE '%\u0000%';
SELECT COUNT(*) FROM Jobs WHERE Data LIKE '%\u0000%';
```

@jondale  That looks like a different problem. Would you mind opening a separate issue so we track it better?

@rhettlunn That sounds about right. There's no actual need to create the default back as we are making sure of it from the application. In fact, the default was introduced a long time ago (version 4.9) but it was never used on new installations.

**Comment by summer-espresso** [comment]
So I revert back to 5.39.0 and now the log is spammed with:
```
{"level":"error","ts":1634218695.3618913,"caller":"mlog/log.go:251","msg":"Unable to get user threads","path":"/api/v4/users/[REDACTED]/threads","request_id":"[REDACTED]","ip_addr":"127.0.0.1","user_id":"[REDACTED]","method":"GET","err_where":"GetThreadsForUser","http_code":500,"err_details":"pq: column posts.parentid does not exist"}
```

**Comment by streamer45** [comment]
> So I revert back to 5.39.0 and now the log is spammed with:
> 
> ```
> {"level":"error","ts":1634218695.3618913,"caller":"mlog/log.go:251","msg":"Unable to get user threads","path":"/api/v4/users/[REDACTED]/threads","request_id":"[REDACTED]","ip_addr":"127.0.0.1","user_id":"[REDACTED]","method":"GET","err_where":"GetThreadsForUser","http_code":500,"err_details":"pq: column posts.parentid does not exist"}
> ```

Reverting needs a db schema downgrade as well to make things work. Please refer to [this document](https://gist.github.com/streamer45/59b3582118913d4fc5e8ff81ea78b055#downgrading-600----538x539x).

**Comment by slavonicsniper** [comment]
There is another column name that requires the same fix. 

```
{
  "timestamp": "2021-11-17 09:11:58.211 Z",
  "level": "fatal",
  "msg": "Failed to alter column type. It is likely you have invalid JSON values in the column. Please fix the values manually and run the migration again.",
  "caller": "sqlstore/store.go:860",
  "error": "pq: default for column \"notifyprops\" cannot be cast automatically to type jsonb",
  "tableName": "ChannelMembers",
  "columnName": "NotifyProps"
}
```

`\d channelmembers` 

```
    Column    |          Type           | Collation | Nullable |         Default         
--------------+-------------------------+-----------+----------+-------------------------
 notifyprops  | character varying(2000) |           |          | '{}'::character varying
 ```
 
 `ALTER TABLE channelmembers ALTER COLUMN notifyprops DROP DEFAULT;` fixed the migration but it would be nice if it was included in `store/sqlstore/upgrade.go`

**Comment by streamer45** [comment]
@slavonicsniper Thanks for letting us know. Unlike `Users.Timezone` I don't recall defaults getting set for that column. Do you know what was the first MM version you installed?

**Comment by slavonicsniper** [comment]
@streamer45 I don't know exactly but probably 5.6.4.

**Comment by jpptinsley** [comment]
This caught me, upgrading from 5.35 to 6.1. https://github.com/mattermost/mattermost-server/issues/18663#issuecomment-942854495 worked for me.  Don't know what our first version was, but we first installed mattermost 2016-10-03
