### ISSUE TITLE
Scrollbar is not visible Clearly in the Denim & Sapphire Theme As Compare to Quartz, Indigo & Onyx Theme

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost#18678]
#### Summary
issue :- Scrollbar is not visible Clearly in the denim & Sapphire Theme as Compare to the Other Theme

Browser :- Chrome Version 94.0.4606.71 (Official Build) (64-bit) 
OS         :- Ubuntu 18.04.6 LTS
Mattermost Version :- cloud-2021-10-12-1
                                   Database Schema Version: 6.0.0 

#### Steps to reproduce
1) you have to join multiple Channels so you can scroll in the Page.
2) mouse hover on the first channel and scroll the page by click on the Scrollbar.  

#### Expected behavior
  :- Scrollbar should be visible clearly in the Denim & Sapphire Theme.

#### Observed behavior (that appears unintentional) 
 :- Scrollbar is not visible Clearly in the Denim & Sapphire Theme As Compare to Quartz, Indigo & Onyx Theme

![Scrollbar is not visible clearly](https://user-images.githubusercontent.com/89907719/137261454-b5e88f88-3b65-4036-8ddf-84dd7dda566d.jpg)

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-39346.
