### ISSUE TITLE
From The Invite Screen by Click on The Back Button From The browser, Then User is Not Redirecting On The Back Page.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost#18682]
#### Summary
From The Invite Screen by Click on The Back Button From The browser, Then User is Not Redirecting On The Back Page.

Mattermost Version: cloud-2021-10-12-1
Database Schema Version: 6.0.0
OS :- Ubuntu 18.04.6 LTS
Browser :- Chrome Version 94.0.4606.71 (Official Build) (64-bit)

#### Steps to reproduce
1) Go to the invite page and Click on the back button from the browser.

#### Expected behavior
The user should redirect Back On the page where he come on the Invite page.

#### Observed behavior (that appears unintentional) 
When user Press back button then User is not redirecting back, some times i get the 404, 403 and some other error, some times by click on the back button, it disable so because of that user is not able to click again on that button. 
![error SS](https://user-images.githubusercontent.com/89907719/137282187-4264e328-3a98-40bc-bf29-3151f088227e.png)

https://user-images.githubusercontent.com/89907719/137282866-a2ab8f71-4664-4eb8-8188-79a8c786bfbd.mp4

**Comment by amyblais** [comment]
Closing as we haven't been able to prioritize fixing this. Please let us know if this reproduces on the latest Mattermost version,
