### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T1257 CTRL/CMD+UP or DOWN in RHS"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost#18711]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T1257 CTRL/CMD+UP or DOWN in RHS</h1>
<div>
<div>
<h3>Steps  #1</h3><ol><li>Refresh the page</li><li>Open the right hand sidebar</li><li>Post five messages in the right hand sidebar, with the last message being '/shrug'</li><li>Press CTRL+UP (Windows) or CMD+UP (Mac) repeatedly in the right hand sidebar, then press CTRL/CMD+DOWN</li></ol><h3>Expected</h3>Each time you press CTRL/CMD+UP, a previous message you have posted will appear in the text box on the right hand sidebar. Once you have repeated it five times (and reached the end of message history), CTRL/CMD+UP does no action. CTRL/CMD+DOWN shows next message in succession<hr><h3>Steps  #2</h3>In the center channel message box, press CTRL+UP (Windows) or CMD+UP (Mac) once<h3>Expected</h3>'/shrug' displays in the center channel text box<hr><h3>Steps  #3</h3>In the center channel message box, press CTRL+DOWN (Windows) or CMD+DOWN (Mac) once<h3>Expected</h3>'/shrug' displays in the center channel text box (repeatedly pressing doesn't clear message box)<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/keyboard_shortcuts``
**Test code arrangement:**
```
describe('Keyboard Shortcuts', () => {
    it('MM-T1257 CTRL/CMD+UP or DOWN in RHS', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by saturninoabril** [comment]
@ZeeshanAmjad0495 Sure and thanks!

**Comment by ZeeshanAmjad0495** [comment]
@saturninoabril I cannot find the rhs sidebar can you please guide, thanks.

**Comment by saturninoabril** [comment]
If you click Reply to one of the posts, then it will open the RHS sidebar.
<img width="234" alt="Screen Shot 2021-10-21 at 2 48 10 PM" src="https://user-images.githubusercontent.com/5334504/138225923-8215b8a5-030f-441a-a958-d1cd425272fb.png">
