### ISSUE TITLE
Playbooks missing in MM6.0

### ISSUE THREAD

**Issue by nt7** [mattermost/mattermost#18723]
A second report about this here: https://forum.mattermost.org/t/playbooks-plugin-not-visible-after-upgrade-to-6-0/12319.

_Originally posted by @amyblais in https://github.com/mattermost/mattermost-server/issues/18681#issuecomment-944508171_

Hi, this is in reference to the above post, I opened a new thread to keep these 2 issues separated, even though they seem to be related.

I initially posted on the MM forum, but can't uplaod log files there.

I'm using mattermost release-6.0 (docker container from Thursday, 14.10) with MariaDB as the db (https://hub.docker.com/layers/linuxserver/mariadb/110.4.11mariabionic-ls46/images/sha256-18dbf539728227e960f94f1d3ebbb4d9f978d8aedcbd9fb309e6494ccb888d02?context=explore)

Here's my log file
[mm.log](https://github.com/mattermost/mattermost-server/files/7357592/mm.log)

And here's the list of my current plugins:
![grafik](https://user-images.githubusercontent.com/6541486/137588430-35fb4fd4-6bdc-4768-a005-d5ca1a8f73cc.png)

**Comment by wget** [comment]
For those witnessing this issue and finding this error via a search engine:
```
{"timestamp":"2021-11-14 15:16:45.309 +01:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:146","plugin_id":"playbooks","error":"failed to run migrations: failed to complete migrations: error executing migration from version 0.29.0 to version 0.30.0: unable to add a primary key: Error 1280: Incorrect index name 'posts_unique'"}
```

If you do not want to wait for Mattermost 6.1 or be urged to migrate to a more recent version because you're following the ESR branch for instance, just remove the faulty index with:
```
MariaDB [(none)]> use mattermostdb;
MariaDB [mattermostdb]> drop index posts_unique on IR_StatusPosts;
```

Go in the `System Console` > `Plugin Management`, disable the plugin  `Playbooks` and reenable it. You should be all right after that.

**Comment by lieut-data** [comment]
Thank you, @wget! To anyone else arriving here, I'd love to more about your reliance on MariaDB so we can surface usage to the right channels. We still don't officially support MariaDB, and it seems the gap with MySQL is only growing wider. Getting ahead of these issues would be great :)
