### ISSUE TITLE
Is there any special setup needed to make playbooks working?

### ISSUE THREAD

**Issue by sokoow** [mattermost/mattermost#18748]
Hi All,

I've clicked through couple of useful patterns in playbooks sections, but can't save them. Every time I click on a Save button, I get this:

```
/plugins/com.mattermost.plugin-incident-management/api/v0/playbooks:1 Failed to load resource: the server responded with a status of 500 ()
client4.js:2155 Uncaught (in promise) Error: {"error":"An internal error has occurred. Check app server logs for details."}
    at new t (client4.js:2155)
    at dt (client.ts:475)
    at async ct (client.ts:431)
    at async client.ts:178
    at async onClick (playbook_edit.tsx:283)
```
is there anything to be done on mattermost server first before using playbooks? I'm on 5.39.0.

**Comment by lieut-data** [comment]
Hi @sokoow! Sorry about the trouble you're experiencing -- that error comes from the client-side, while the really interesting stuff will be in the server logs. Do you have access to those logs that we might be able to use to debug further?
