### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2079 Can remove profile pic then choose different pic without saving in between"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost#18815]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2079 Can remove profile pic then choose different pic without saving in between</h1>
<div>
<div>
<h3>Steps </h3>Can remove profile pic then choose different pic without saving in between<br />&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;<br />1) Add a profile picture (aka &quot;old profile picture&quot;) and close the account settings.<br />2) Open Profile &gt; Profile Settings &gt; Profile Picture &gt; Edit<br />3) Click the X to remove the old profile picture but do not click save.<br />4) Select a new profile picture and click Save.<h3>Expected</h3>Account setting modal closes and newly selected profile picture is persisted and displayed in profile.<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/account_settings``
**Test code arrangement:**
```
describe('Account Settings', () => {
    it('MM-T2079 Can remove profile pic then choose different pic without saving in between', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by poflankov** [comment]
Hi, can I try it?

**Comment by saturninoabril** [comment]
Sure and thanks @poflankov!
