### ISSUE TITLE
Write Webapp E2E with Cypress: "MM-T2078 Profile picture: file types accepted"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost#18812]
See our [documentation for Webapp end-to-end testing with Cypress](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) for reference.

<article>
<h1>MM-T2078 Profile picture: file types accepted</h1>
<div>
<div>
<h3>Steps </h3>Profile picture: file types accepted<br />&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;<br />1. Go through the file types that are accepted: PNG, JPG, JPEG, BMP<h3>Expected</h3>All listed file types successfully used as profile picture<hr>
</div>
</div>
</article>

**Test Folder:** ``/cypress/integration/profile_settings``
**Test code arrangement:**
```
describe('Profile Settings', () => {
    it('MM-T2078 Profile picture: file types accepted', () => {
        // code
    });
});
```

Notes:
1. Do not add ``@prod`` label in a spec file
  - If you're writing script into a newly created test file, ``@prod`` label should not be included.
  - If you're adding script into an existing test file, ``@prod`` label should removed.
2. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by ZeeshanAmjad0495** [comment]
Hi @saturninoabril , I would like to write the e2e test for this issue.

**Comment by saturninoabril** [comment]
Sure and thanks @ZeeshanAmjad0495!

**Comment by ZeeshanAmjad0495** [comment]
Thanks @saturninoabril.

**Comment by adj2908** [comment]
Hi @saturninoabril , 

I would like to work on this if @ZeeshanAmjad0495 is not working on it. Please let me know. 

Thanks.

**Comment by saturninoabril** [comment]
Thanks for your interest @adj2908!

**Comment by adj2908** [comment]
Hey @saturninoabril, Based on the conversation on https://github.com/mattermost/mattermost-server/issues/18819. Please update the ticket. Thanks.

**Comment by mr-orlik** [comment]
Hi @saturninoabril,
Can I work on this?
Do I get it right, that for every file type in [PNG, JPG, JPEG, BMG] separate test should be done?
And every file type should be uploaded as profile picture using UI, and we verify that it became a profile picture OK?

**Comment by saturninoabril** [comment]
@mr-orlik Sure and thanks for your interest! Yes, that's correct. I made minor correction and updated the description as it should be BMG -> BMP and Account Settings -> Profile Settings. Also, there are images available at [fixtures](https://github.com/mattermost/mattermost-webapp/tree/master/e2e/cypress/tests/fixtures) that you may use for this case. Feel free to let me know if you have question, clarification or anything.

**Comment by hmhealey** [comment]
@mr-orlik Let us know if you'd like to continue working on this. If not, I'm going to open it back up for others

**Comment by eunicode** [comment]
I'd like to pick up on this task!

**Comment by saturninoabril** [comment]
@eunicode Sure and thank you for your interest!

**Comment by nokedajunky** [comment]
Can I have a chance to automate that? Looks like I have the code already :)

**Comment by saturninoabril** [comment]
@nokedajunky Thanks for your interest and sure, feel free to send PR and ping me if you need anything.

**Comment by nokedajunky** [comment]
@saturninoabril i've created a PR
