### ISSUE TITLE
MM 6.0.2: Import from slack crashes due to invalid memory access or nil pointer dereference

### ISSUE THREAD

**Issue by geverl** [mattermost/mattermost#19093]
Mattermost Version: 6.0.2
Database Schema Version: 6.0.2
Database: mysql

Following https://docs.mattermost.com/onboard/bulk-loading-data.html with 5 MB file size:
Running mattermost import bulk <filename> --validate works and confirms validity.
Running mattermaost import bulk <filename> --apply fails with the following error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fe7e29]

goroutine 4949 [running]:
github.com/mattermost/mattermost-server/v6/app.(*App).importUserTeams(0xc001941160, 0xc0017be900, 0xc002371e90, 0x5)
        github.com/mattermost/mattermost-server/v6/app/import_functions.go:751 +0xb89
github.com/mattermost/mattermost-server/v6/app.(*App).importUser(0xc001941160, 0xc00191add0, 0x44d100, 0x0)
        github.com/mattermost/mattermost-server/v6/app/import_functions.go:703 +0x107e
github.com/mattermost/mattermost-server/v6/app.(*App).importLine(0xc001941160, 0xc00146aa00, 0xc0017d4cd0, 0x4, 0x0, 0x0, 0x0, 0xc00191add0, 0x0, 0x0, ...)
        github.com/mattermost/mattermost-server/v6/app/import.go:305 +0x2e5
github.com/mattermost/mattermost-server/v6/app.(*App).bulkImportWorker(0xc001941160, 0xc00146aa00, 0x0, 0xc000f98d20, 0xc0017d6900, 0xc0014e9620)
        github.com/mattermost/mattermost-server/v6/app/import.go:139 +0x705
created by github.com/mattermost/mattermost-server/v6/app.(*App).bulkImport
        github.com/mattermost/mattermost-server/v6/app/import.go:240 +0x3aa

**Comment by streamer45** [comment]
Thansk @geverl , this looks like an issue triggered by unexpected data, created [MM-40377](https://mattermost.atlassian.net/browse/MM-40377).
@isacikgoz Maybe something your team could look into?

**Comment by mkraft** [comment]
@geverl Did you happen to have minimal (redacted if necessary) example json file that causes the issue for us to replicate this bug?

**Comment by tomash** [comment]
It seems I have stumbled upon the same thing.
mmctl versio 6.4.0, installed today with `go install github.com/mattermost/mmctl@latest`.

Doing the docker preview locally. Entire container goes down when trying to process an import from uploaded file. `docker logs` show:

```
{"timestamp":"2022-06-01 12:06:47.512 Z","level":"debug","msg":"Worker received a new candidate job.","caller":"jobs/base_workers.go:50","worker":"ImportProcess"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b25451]

goroutine 6068 [running]:
panic({0x2170d00, 0x3cb9ec0})
	runtime/panic.go:941 +0x397 fp=0xc004362958 sp=0xc004362898 pc=0x439d97
runtime.panicmem(...)
	runtime/panic.go:220
runtime.sigpanic()
	runtime/signal_unix.go:818 +0x336 fp=0xc0043629a8 sp=0xc004362958 pc=0x4506d6
github.com/mattermost/mattermost-server/v6/app.(*App).importUserTeams(0xc00209b350, 0xc00461a780, 0xc0043f78a8)
	github.com/mattermost/mattermost-server/v6/app/import_functions.go:761 +0x1091 fp=0xc0043635f8 sp=0xc0043629a8 pc=0x1b25451
github.com/mattermost/mattermost-server/v6/app.(*App).importUser(0xc00209b350, 0xc002768dd0, 0x0)
	github.com/mattermost/mattermost-server/v6/app/import_functions.go:713 +0x469c fp=0xc004363d90 sp=0xc0043635f8 pc=0x1b241dc
github.com/mattermost/mattermost-server/v6/app.(*App).importLine(0x7f997851ea68?, 0x10?, {{0xc002ba8980, 0x4}, 0x0, 0x0, 0x0, 0xc002768dd0, 0x0, 0x0, ...}, ...)
	github.com/mattermost/mattermost-server/v6/app/import.go:305 +0x198 fp=0xc004363df0 sp=0xc004363d90 pc=0x1b1e538
github.com/mattermost/mattermost-server/v6/app.(*App).bulkImportWorker(0x443ba5?, 0xc00457f480?, 0x88?, 0xc00468ce40?, 0x0?, 0x0?)
	github.com/mattermost/mattermost-server/v6/app/import.go:139 +0x5cd fp=0xc004363fa0 sp=0xc004363df0 pc=0x1b1d14d
github.com/mattermost/mattermost-server/v6/app.(*App).bulkImport.func2()
	github.com/mattermost/mattermost-server/v6/app/import.go:240 +0x3a fp=0xc004363fe0 sp=0xc004363fa0 pc=0x1b1e25a
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc004363fe8 sp=0xc004363fe0 pc=0x46d741
created by github.com/mattermost/mattermost-server/v6/app.(*App).bulkImport
	github.com/mattermost/mattermost-server/v6/app/import.go:240 +0x9ba
```

I can provide the zip file with `mattermost.jsonl` that caused it but since it's a complete import of my company's Slack history I'd rather not upload it publictly, please contact me via email - `t.stachewicz@gmail.com`. The zip file is 36MB (jsonl is 157MB) without assets and 25GB with assets.

**Comment by amyblais** [comment]
Comment from a dev in the Jira ticket: "Closing for now, it’s been a year without people complaining. Feel free to reopen if it resurfaces."
