### ISSUE TITLE
Bot message previews break original messages on chromium-based applications. 

### ISSUE THREAD

**Issue by setpill** [mattermost/mattermost#19198]
#### Summary

Bot message previews break original messages on chromium-based applications. NB: this includes the electron desktop app.

#### Steps to reproduce

Mattermost Version: 6.1.0

1. Copy a link to a bot message
2. Send the link in a different channel
3. See the (empty) preview
4. Open the channel with the original message
5. The message is broken
6. Full refresh (ctrl-shift-r in the desktop app)
7. The message is fixed
8. Open the channel with the message link
9. Open the channel with the original message
10. The message is broken again

NB: If the link is sent in the same channel, it will always break the message, no matter how hard you refresh.

#### Expected behavior

Bot messages don't break. This is how it works in firefox.

![image](https://user-images.githubusercontent.com/37372069/146545808-74167a47-664d-41bf-a164-5cd9c98508e6.png)

#### Observed behavior (that appears unintentional) 

The message appears empty (other messages from the same bot look normal)

![image](https://user-images.githubusercontent.com/37372069/146545853-823da5f1-a848-49dc-bf3d-70dd1e380472.png)

**Comment by amyblais** [comment]
We have a ticket for this here: https://mattermost.atlassian.net/browse/MM-39404.

**Comment by setpill** [comment]
Ah, thanks :) I tried searching in Atlassian but didn't use the same terms. Interesting additional information for your ticket is that (at least in the case I ran into) the issue is browser-specific.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
