### ISSUE TITLE
/code command prefixes code with whitespace

### ISSUE THREAD

**Issue by mreymann** [mattermost/mattermost#19463]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 Pro Build 19044.1503
- Mattermost Desktop App version: 5.0.2 
- Mattermost Server version: 6.2.1 

**Steps to reproduce**
Type "/code foo"
**Expected behavior**
Renders "foo"
**Observed behavior**
Renders " foo" <- notice the prefixed space character!

**Possible fixes**
Not currently known

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-41507

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
