### ISSUE TITLE
The heading structure lacks hierarchy

### ISSUE THREAD

**Issue by rpkoller** [mattermost/mattermost#19528]
#### Summary
if you open the screen reader rotor for example in apple voiceover you have several h1 and several h2 which might lead into confusion for screen reader users

#### Steps to reproduce
- access a server and team in a browser or desktop app
- start voice over (i've only voice over available)
- start the rotor
- navigate to the rotors headline section

#### Expected behavior
a clearer structure would be helpful in case the screen reader user is relying onto headline instead of regions or other ways. 

#### Observed behavior (that appears unintentional) 
you have an h1 for channels then another h1 right after for the team name then an h2 for the channel title and then another h2 for the headline within the channel. 

#### Possible fixes
based on that plain heading structure i would be unable to make sense out of things. there is a lack of hierarchy for those headings. and also talking of hierarchy the case if you have searched something and get the results in the sidebar or if you take a look into thread replies those two dont have a heading at all those are only span elements

**Comment by amyblais** [comment]
Created a ticket: https://mattermost.atlassian.net/browse/MM-41720.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
