### ISSUE TITLE
Default  FeedbackName and FeedbackEmail and empty and prevent SMTP sending, should have sane defaults.

### ISSUE THREAD

**Issue by gdevenyi** [mattermost/mattermost#19687]
Mattermost Version: 6.4.0 Open Source Edition
Bare metal install, using postgres, on Ubuntu 20.04

#### Summary
The SMTP configuration page does not allow specification of FeedbackName and FeedbackEmail (found in config.json), and defaults to empty for both when sending email. This results in gmail (and probably more) servers rejecting delivery.

#### Steps to reproduce
1. Install Mattermost 6.4.0
2. configure SMTP
3. attempt to verify email.

#### Expected behavior
1. Configuration of from parameters should be provided
2. Default empty parameters should use sensible defaults.

#### Observed behavior (that appears unintentional) 
From mail logs:

```
		"headers": {
			"to": "gdevenyi@gmail.com",
			"message-id": "20220303191920.9B1C01F9591@cloud1.douglasneuroinformatics.ca",
			"from": "<\"\">",
			"subject": "[Douglas Research Center Chat] Verify new email address"
```

```
		"message": "5.7.1 [209.61.151.230      14] Messages missing a valid address in From:\n5.7.1 header, or having no From: header, are not accepted. a23-20020a0568301dd700b005acf3831ca5si1746511otj.143 - gsmtp",
```

I was above to resolve this by stopping the server, manually editing the config.json to sensible values, and starting the server again, at which point the settings were used for email

**Comment by furqanmlk** [comment]
> @saturninoabril @furqanmlk Is this something QA would be able to help test?

@amyblais let me try

**Comment by furqanmlk** [comment]
@gdevenyi 
Did you set `FeedbackName` and `FeedbackEmail` from `/environment/notifications` page ?

<img width="880" alt="image" src="https://user-images.githubusercontent.com/6909890/156658411-d5b3491c-22ef-477a-aebc-f05a25cbe958.png">

**Comment by gdevenyi** [comment]
I had not, because I didn't expect the SMTP From setting to come from a page other than the SMTP configuration.

In addition, if I didn't even want email notifications, this would still be broken for confirming a user's email address.

**Comment by gdevenyi** [comment]
Bug report title changed to reflect underlying issue.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-42317.

**Comment by c-lombardi** [comment]
I was having this issue on Mattermost version 6.4.2 and I found out that I had to have Email Notifications enabled and the Notification From Address set.

![image](https://user-images.githubusercontent.com/4417133/156929477-554feebd-e84e-414e-a8c7-267e1b27d97b.png)

**Comment by agnivade** [comment]
The `FeedbackEmail` defaults to `test@example.com`. Is this only about `FeedbackName`? Is it still invalid to have an empty name?
