### ISSUE TITLE
Incoming webhooks change their creator's status

### ISSUE THREAD

**Issue by Jay2k1** [mattermost/mattermost#19836]
#### Summary
When Alice creates a webhook and is offline, and that webhook is being used, Bob sees Alice switch to online (and shortly after back to offline). 

#### Steps to reproduce
This has been an issue for a while and is still present in 6.5.0.

* create two users
* have one of them create an incoming webhook
* have that user quit Mattermost
* send a message using the webhook
* have the second user observe that the first user's status changes from offline to online even though that user is not online (and then after 30-40 seconds back to offline)

#### Expected behavior
Using the webhook should not count as user activity and thus not potentially change their creator's status

#### Observed behavior (that appears unintentional) 
The user status of the account that created the webhook is influenced by the webhook in a way that it changes from offline to online when the webhook is being used.

In case it's necessary, use case:

I'm one of several sysadmins and I've set up an incoming webhook for our monitoring, so our admin team gets notified about incidents via Mattermost. Coworkers from a different shift wondered why I was randomly going online and offline while i was asleep. Turns out it's the webhook I created.

My hack fix: I noticed that there's a `UserId` column in the `IncomingWebhooks` DB table which (unsurprisingly) had my user ID for the hook I had created. I went to the `Users` table and copied the ID of a non-human account (there's `boards`, `todo`, `surveybot` etc.) and used this for the user ID of the webhook, followed by a restart of Mattermost.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-42782.
