### ISSUE TITLE
Building webapp from source fails since >6.1.0

### ISSUE THREAD

**Issue by edannenberg** [mattermost/mattermost#19854]
#### Summary
I maintain a install package for Gentoo that builds Mattermost server and webapp from source. After 6.1 this appears to fail because of node dependencies with a ssh git url.

#### Steps to reproduce
Building the webapp from source without having ssh keys for Mattermost organisation.

#### Expected behavior
I can build the webapp from source.

#### Observed behavior (that appears unintentional) 
The webapp build hangs after a while. I build in a Docker container and relevant `ps aux` looks like this:

```
portage    468  0.0  0.0   8032  3048 pts/0    S+   08:12   0:00 make build package
portage    476 20.2  0.9 1127076 312960 pts/0  Sl+  08:12   1:21 npm
portage    488  0.0  0.0  11860  4436 pts/0    S+   08:12   0:00 git ls-remote -h -t ssh://git@github.com/mattermost/marked.git
portage    489  0.0  0.0  11536  5788 pts/0    S+   08:12   0:00 /usr/bin/ssh -o SendEnv=GIT_PROTOCOL git@github.com git-upload-pack '/mattermost/marked.git'
portage    672  3.6  0.5 991384 170332 pts/0   Sl+  08:12   0:14 npm
portage    682  0.0  0.0  11860  4356 pts/0    S+   08:12   0:00 git ls-remote -h -t ssh://git@github.com/mattermost/eslint-config-mattermost.git
portage    683  0.0  0.0  11536  6048 pts/0    S+   08:12   0:00 /usr/bin/ssh -o SendEnv=GIT_PROTOCOL git@github.com git-upload-pack '/mattermost/eslint-config-mattermost.git'
```

Running the `git ls-remote` commands manually fails with:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

I guess it hangs in the build due to waiting for manual input for the host fingerprint verification, as I also see 

`The authenticity of host 'github.com (140.82.121.4)' can't be established`

during the build process. (The build uses a non-root sandbox user)

The problematic dependencies appear to be:

ssh://git@github.com/mattermost/marked.git
ssh://git@github.com/mattermost/eslint-config-mattermost.git

#### Possible fixes
Using https urls instead of ssh?

**Comment by amyblais** [comment]
I'll close this for now as there is a discussion in the webapp channel.
Using node 16.4.1 fixed the issue.
