### ISSUE TITLE
Duplicate default profile photos created if S3 has intermittent failure

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost#20067]
#### Summary
Duplicate default profile photos created if S3 has intermittent failure

#### Steps to reproduce
1. Enable S3 integration
2. Turn on S3 versioning
3. Remove profile picture
4. Force S3 issue with `GET`
5. Refresh Mattermost
6. Notice that a new default profile picture has been uploaded for user

#### Expected behavior
New versions of default profile picture should not be created

#### Observed behavior (that appears unintentional) 
Redundant default profile picture images are uploaded

#### Possible fixes
https://github.com/mattermost/mattermost-server/blob/v6.2.1/app/server.go#L2221-L2238 assumes that failure to load a profile picture means one should be created and uploaded. This logic could be improved. Additionally some logging should be added as part of this process.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-43814.

**Comment by agnivade** [comment]
This is more of a PM decision, I'll route it to Suite Users to be handled properly.

**Comment by amyblais** [comment]
Closing older issues as our team hasn't been able to prioritize this,
