### ISSUE TITLE
Unable to get/access CSRF Token in login api response headers

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost#20265]
#### Summary
We are using matter most APIs in our frontend application. For login, we are hitting our own server, which is again hitting the matter most server. 
In general, when I check the matter most deployed applications, they are sending a few headers in the login API response, which are used to set for subsequent requests.
<img width="1044" alt="Screenshot 2022-05-23 at 7 29 15 PM" src="https://user-images.githubusercontent.com/9896335/169836318-e61d280d-82c7-45a3-afb6-e0fb210415ec.png">
But when we hit the login API from our server, we are not getting the CSRF token in the response headers. It's the same when I hit the API from the postman
<img width="1301" alt="Screenshot 2022-05-23 at 7 29 56 PM" src="https://user-images.githubusercontent.com/9896335/169836479-4566599a-b636-4af1-830f-8f05f986113b.png">

<img width="1306" alt="Screenshot 2022-05-23 at 7 30 03 PM" src="https://user-images.githubusercontent.com/9896335/169836515-463eac71-f23f-47b0-8109-a6f02af22bd8.png">
Is there a way to get the CSRF cookie in the login API response header?

#### Steps to reproduce
As mentioned above

#### Expected behavior
We should be able to access the CSRF token in the login API response, even when we hit it from our server.

#### Observed behavior (that appears unintentional) 
NA

#### Possible fixes
NA

**Comment by amyblais** [comment]
@rajeshwarpatlolla Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or other community members will likely be able to help with this.

**Comment by rajeshwarpatlolla** [comment]
Ok, I posted on GitHub in here, in the forum and also in the peer to peer channel in community

**Comment by hmhealey** [comment]
Here's a link to the existing thread: https://community.mattermost.com/core/pl/ps8k6ibb9tnbige5sm6qgq5x4a

**Comment by rajeshwarpatlolla** [comment]
@hmhealey There is no update in the community about it. Is there any update on this issue?

**Comment by hmhealey** [comment]
Do personal access tokens not work for your use case? That's the last thing I remember discussing on this.

Looking back at your issue above though since I think I only responded in the thread before, it looks like we only attach those headers if the request was made with the `X-Requested-With` header set to `XMLHttpRequest` like in the browser. That logic is located [here](https://github.com/mattermost/mattermost-server/blob/master/api4/user.go#L1865) on the server if you're at all curious

**Comment by amyblais** [comment]
I believe this was resolved in the Peer-to-peer Help channel, but let me know if I'm wrong.
