### ISSUE TITLE
mmctl bulk export returns direct_post entries with empty channel_members list

### ISSUE THREAD

**Issue by Debilski** [mattermost/mattermost#20448]
#### Summary

Inspecting the `import.jsonl` file that the `mmctl` bulk export produced, shows lots of direct posts with an empty channel_members list. As per the spec (https://docs.mattermost.com/onboard/bulk-loading-data.html#example-directpost-object) these must have a minumum of two members.

#### Steps to reproduce

    mmctl --local export create

... then download and unzip the created file.

Mattermost version: 6.7.0

#### Expected behavior

`{"type":"direct_post" ....` should follow the spec and have a channel_members entry of size >= 2.

#### Observed behavior (that appears unintentional) 

Filtering for posts with an empty members list yields 104000 entries.

    $ jq -c 'select (.direct_post.channel_members == [])' import.jsonl | wc -l
    104000

Example json:

    {"type":"direct_post","direct_post":{"channel_members":[],"user":"%REDACTED%","type":"","message":"xxx","props":{"disable_group_highlight":true},"create_at":1627996182015,"edit_at":0,"flagged_by":null,"reactions":null,"replies":null,"attachments":null}}

When using the mattermost UI, this message can be searched and traced to its original private chat.

**Comment by isacikgoz** [comment]
Hey @Debilski I couldn't reproduce this issue, is there any integrity errors on your database? Or are there any log errors while trying to create an export file?

**Comment by Debilski** [comment]
Hmm, so apparently this could have been related to our old mariadb instance. (Which got the job done, so it was only until recently that we learned that it is not supported.)
We have done a db export to mysql in the meantime (now still in test mode) and here everything seems to be working fine with the bulk export, indeed.

**Comment by agnivade** [comment]
Thanks for the confirmation @Debilski !
