### ISSUE TITLE
Deactivated User Gets Notification Mail If User Name or Mail Address is Changed Through CLI

### ISSUE THREAD

**Issue by gohrner** [mattermost/mattermost#20665]
#### Summary
For EU GDPR reasons, I need to anonymize accounts of former users.

I don't want to fully delete the users and their messages, as the information contained therein may still be relevant in the future.

So I tried to use a script with `mmctl` which changes the user's name and mail address to some pseudonymized values.

Mattermost 5.37.x (I think) / 6.3.x

#### Steps to reproduce
```bash
mmctl user deactivate testuser
mmctl user email mails.anonymized123@examle.com
mmctl user username anonymized123
```

#### Expected behavior
The user is deactivated and its mail address and user name are silently changed to pseudonyms.

#### Observed behavior (that appears unintentional) 
The deactivated user receives notification mails about the username and mail address change.

https://forum.mattermost.com/t/renaming-inactive-users-without-sending-notification-mails/13671

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-45793.

**Comment by hanzei** [comment]
Closing as https://mattermost.atlassian.net/browse/MM-45793 was closed
