### ISSUE TITLE
Overflowing images on large screens

### ISSUE THREAD

**Issue by dmke** [mattermost/mattermost#20739]
#### Summary

On large screens (the breakpoint seems to be at 1550px window width), the "Show more" button is not shown, and embedded images flow out of the post message container.

These messages are created through the Gitlab integration, so I believe these are not "normal" messages, but message "attachments" (?).

https://user-images.githubusercontent.com/327411/181731249-c2586923-5308-48c5-b48e-155323e53e46.mp4

#### Steps to reproduce

- setup Gitlab (any supported version, ignore the bundled Mattermost version)
- setup Mattermost (I'm currently running 7.1.2)
  - add an incoming webhook
  - in your display settings, set the message display to "compact"
- in Gitlab, create a project, and setup the "Mattermost notification" for issues
- create a new issue in Gitlab with the following text:
  ```markdown
  Hello there!
  
  ![placeholder](https://dummyimage.com/1000x600/ccc/000.jpg)
  
  Some additional text.
  ```
- open the Mattermost web UI, make sure the window width is > 1550px
- observe the "glitchy" behaviour when hovering over the image (see video above)

Additionally:

- resize the window to below 1550px
- observe the "Show more" button appearing (shown in the video)
- resize the window to > 1550px again
- observe the "Show more" button to *not* disappear (not shown in the video)

#### Expected behavior

The "Show more" button should be visible on large screens as well.

#### Observed behavior (that appears unintentional) 

The "Show more" button is hidden, and hovering over the image causes the layout to break.

The "Show more" button only appears when resizing the window below a breakpoint, and stays on the page even after maximising the window. The presence of the "Show more" button stops the hover-glitch.

#### Possible fixes

Unknown. I guess, always show the "Show more" button, when the content contains an image?

**Comment by dmke** [comment]
FYI, v7.2 still show the same issue:

https://user-images.githubusercontent.com/327411/185349066-01309d64-1543-4f46-a61f-8f50b0ee2f92.mp4

I've also noticed that the standard message display (i.e. not "compact") seems to not be affected:

https://user-images.githubusercontent.com/327411/185349808-c017560f-d31e-4d2c-b938-130859437898.mp4

**Comment by jwilander** [comment]
I can't reproduce on latest, please re-open if you're still able to reproduce.

**Comment by dmke** [comment]
> I can't reproduce on latest

In v9.10.1, I'm now observing the following behaviour:

https://github.com/user-attachments/assets/29d1ef99-e3b4-4a43-a312-9119cf7c6458

- The recording starts after a fresh reload of the page (just <kbd>F5<kbd>, not clearing caches).
- Initially, the problem occurs as described in the issue description.
- At 00:08, I'm un-maximizing the browser window. The "show more" button appears and the image behaves as expected.
- At 00:12, I'm maximizing the browser window again. The "show more" button stays.

I usually don't resize my browser at all, as it starts maximized on a dedicated monitor, so I guess this issue is only half solved? I'm guessing some `resize` handler needs to also fire once on `DOMContentLoaded`.

**Comment by dmke** [comment]
> please re-open if you're still able to reproduce

I don't have the ability to do so here.
