### ISSUE TITLE
Emoji selector is going below other components when replying to thread which make it hard to see 

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost#20741]
#### Summary
Emoji selector is not completely visible when you are replying to thread with few replies

#### Steps to reproduce
1. Click threads
2. Find a thread with only 1-2 replies
3. Type `:as` to see suggestions 

#### Expected behavior
Emoji selector should be completely visible
<img width="1440" alt="Screen Shot 2022-07-30 at 00 47 48" src="https://user-images.githubusercontent.com/37421564/181855012-15d81f3a-a110-45d9-bc30-6dc5b4683eed.png">

#### Observed behavior (that appears unintentional) 
Emoji selector is going below other components
<img width="1440" alt="Screen Shot 2022-07-30 at 00 46 52" src="https://user-images.githubusercontent.com/37421564/181854958-be22b237-177a-4468-865f-566cdd41d84b.png">

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-46137

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
