### ISSUE TITLE
Channel admin can't post messages if "Create Posts" option disabled

### ISSUE THREAD

**Issue by ilusharulkov** [mattermost/mattermost#20847]
#### Summary
Channel admin can't post messages if "Create Posts" option disabled

#### Steps to reproduce
1) Create channel1
2) Make user1 channel admin
3) Disable permission "Create Posts" for members (Admin console -> Channels -> Channel Moderation)
4) Leave admin zone
5) Enter channel1
6) It is impossible to make a post

#### Expected behavior
User1 can post in channel1 because he is a channel admin. According to https://docs.mattermost.com/manage/team-channel-members.html#channel-moderation

#### Possible fixes
none

**Comment by amyblais** [comment]
@ilusharulkov What Mattermost server version are you on?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-46477.

**Comment by ilusharulkov** [comment]
Hi @amyblais
Sorry, I missed your question. Mattermost version is **7.1**

**Comment by ilusharulkov** [comment]
Hello! @amyblais any news about his issue?
It enforces to give system admin grants for users, who need post in "announcements" channel instead of give channel admin.

**Comment by amyblais** [comment]
The ticket is assigned to one of our dev teams but they haven't had a chance to fix the bug yet. If you are interested in submitting a fix, let me know!

**Comment by amyblais** [comment]
Our team can no longer reproduce this on the latest version. Please let us know if you're still able to reproduce this,
