### ISSUE TITLE
Improve channel intro message and illustration

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost#21205]
## The Problem

When a channel is empty or has very few messages, we don’t have a very good empty state. We should look to improve visual impact and the usefulness of the channel’s empty state. This will help orient the user and make it more obvious that the channel is empty and it will hopefully encourage users to engage.

#### Current Empty State of a Channel

![image](https://user-images.githubusercontent.com/14333569/153960467-fc45e120-03a8-4968-9a3e-181009a4fb55.png)

#### 

~~--~~

## Proposed Solution

  * Utilize illustrations for channel intros
  * Include buttons for key interactions for new channels
  * For servers with <10 members, the actions change to 1 single action (invite others to the workspace)

#### Public Channels

![image](https://user-images.githubusercontent.com/14333569/153960490-363705ef-65e8-4432-bcdf-c238fa941ee9.png)

#### Private Channels

![image](https://user-images.githubusercontent.com/14333569/153960597-9a06188f-2bb1-4575-8421-51fa4ecece00.png)

#### Direct Messages

![image](https://user-images.githubusercontent.com/14333569/153960531-21a6e11a-32be-4020-85b1-f8a53cb97759.png)

#### Group Messages

![image](https://user-images.githubusercontent.com/14333569/153960562-53a2057e-f859-4b58-8b7f-f93312cf847e.png)

#### Bots

![image](https://user-images.githubusercontent.com/14333569/153960582-99386fb6-9d2e-49ae-b0e6-1332dabf10c5.png)

### Design Files

[Figma design files](https://www.figma.com/file/LHSb4bMcvGles9ASdpA4sN/?node-id=0%3A1)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-28014

**Comment by esethna** [comment]
Work started here for anyone how wants to take this on! https://github.com/mattermost/mattermost-webapp/pull/9892#issuecomment-1266023058

**Comment by VishakhaPoonia** [comment]
Will take this

**Comment by esethna** [comment]
@VishakhaPoonia how's this going?

**Comment by amyblais** [comment]
I believe that's a Product decision - I'll defer to PMs.

**Comment by matthewbirtch** [comment]
I've got a PR going for this now due to inactivity on the issue. Changed assignees
