### ISSUE TITLE
Text Is Hidden Backside Of Video 

### ISSUE THREAD

**Issue by mustafaazad03** [mattermost/mattermost#21226]
There Is Issue In Your Website 
![image](https://user-images.githubusercontent.com/97380192/194127133-3f50bb0a-db12-4cd1-bbf6-d444cea30d30.png)

**Comment by Mustafa-Azad025** [comment]
Will You Assign This Task To Me ??

**Comment by Mustafa-Azad025** [comment]
Please Give A Path To That Particular Folder

**Comment by amyblais** [comment]
@Mustafa-Azad025 This will likely need to be fixed by our Marketing team.

1. Are you on webapp or mobile app?
2. What screen size are you on?
3. What OS and version are you on?

**Comment by Mustafa-Azad025** [comment]
Large Screen Size 1440px width device on windows

**Comment by Mustafa-Azad025** [comment]
But this is work of developer

**Comment by amyblais** [comment]
@Mustafa-Azad025 The https://mattermost.com/ website is currently hosted in WordPress and is not open source as far as I know. I'll forward this bug to our Marketing team to fix this. Thank you for reporting this!
