### ISSUE TITLE
Plugin Button on Channel Header

### ISSUE THREAD

**Issue by nokhaiz-iz** [mattermost/mattermost#21252]
I have added an App built in Node Server and it is added successfully. Now its button is not showing on app's channel header.

**Comment by amyblais** [comment]
Hi @nokhaiz-iz, 
1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see any errors in Mattermost logs?
4. Can you help add more specific reproduction steps?

**Comment by hanzei** [comment]
@nokhaiz-iz Can you confirm your apps is installed? Does it show up in `/apps list`?

**Comment by amyblais** [comment]
Closing some older issues. Feel free to re-open this issue if the problem persists on the latest version,
