### ISSUE TITLE
Bot didn't recieve mentions from channels where it is not a member

### ISSUE THREAD

**Issue by sobuctb** [mattermost/mattermost#21573]
Should a bot recieve the mention in the channel where the bot is not a member?

Mattermost Version: 7.1.2
Database Schema Version: 89
Database: postgres

We created a bot and a handler based on https://github.com/attzonko/mmpy_bot. 
The bot added in the System Admins group, but notifications in a channel where the bot is not added do not come to the handler.
From the ticket https://mattermost.atlassian.net/browse/MM-16744, I understood that there should be a different behavior: "bot accounts can interact with a channel without being a member in it".

So, can I get the expected behavior - bot mention works without adding the bot to the channel?

**Comment by amyblais** [comment]
@DHaussermann @mickmister Do you know what the expected behaviour here is?

**Comment by amyblais** [comment]
cc @hanzei

**Comment by hanzei** [comment]
> bot accounts can interact with a channel without being a member in it

As far as I know, this is not true. Bot accounts are tied to the same permission system as regular users. Only bot accounts managed by a plugin can get around the permission system.

Do you know how exactly `[mmpy_bot](https://github.com/attzonko/mmpy_bot)` works? If the bot is a system admin, it could add itself to all channels and then receive mentions.

**Comment by sobuctb** [comment]
> Do you know how exactly [mmpy_bot](https://github.com/attzonko/mmpy_bot) works? 

Hi! Yep, it use connection to the web socket to listen for events from the server.
1) So, adding the bot to each channel is the only one solution now?
2) Why are someone asked to remove the ephemeral message? The users use mention to the bot and think that every is fine, but our team is not notified.

**Comment by anx-ag** [comment]
If the bot has the `system_admin` role, it can post to all channels without being member of it. You might need to set these permissions directly in the database, but it works. I'm using a combination of the following bot permissions on my system:

```
mattermost=# select username,roles from users where username like '%bot';
    username     |               roles
-----------------+------------------------------------
 bot01           | system_user
 bot02           | system_user system_post_all
 bot03           | system_user system_admin
```

bot01 and bot02 can be clicked through the GUI and/or created using `mmctl`or the API, bot03 is the bot with super powers and does not need to be a member in the channels it posts to.

**Comment by sobuctb** [comment]
There is no problem with sending messages to the channels. There is a problem with receiving mention from the channel where the bot is not a member. No events from the web socket with bot's token

**Comment by sobuctb** [comment]
@hanzei So, should I try with plugin code to achieve expected result?

**Comment by sobuctb** [comment]
Any help?

**Comment by mickmister** [comment]
@sobuctb It's currently not possible for a user (including a bot) to receive notifications for a mention in a channel they are not a member of. However, what you're looking for could be implemented as a Go plugin using the [MessageWillBePosted](https://developers.mattermost.com/integrate/plugins/components/server/reference/#Hooks.MessageWillBePosted) or [MessageHasBeenPosted](https://developers.mattermost.com/integrate/plugins/components/server/reference/#Hooks.MessageHasBeenPosted) hooks.

Alternatively, this functionality may be able to be supported in the product. Would you be interested in looking into this?

**Comment by amyblais** [comment]
Feel free to open a feature request on Uservoice here for tracking https://mattermost.uservoice.com/forums/306457-general.
