### ISSUE TITLE
Bug in file upload 

### ISSUE THREAD

**Issue by MikaelStrom** [mattermost/mattermost#21604]
#### Summary
I think I've found a bug in the file upload using the free version at <name>.cloud.mattermost.com. Uploading files with certain filenames fails. 

I have only access to MacOS so the test case below applies to MacOS 10.15.7, Safari 15.6.1 and Mattermost desktop app Version 5.1.1.

#### Steps to reproduce
Using this zip file 
[files.zip](https://github.com/mattermost/mattermost-server/files/9951313/files.zip)
please follow these steps to reproduce:

1. Unpack the attached zip file. It contains two identical images but with different names. 
2. Upload the file named "x.jpg" by dragging and dropping to a channel window (desktop app or web). The image will upload properly and be displayed in the channel. 
3. Upload the file named "MB STUDIO PRE + 2C+.jpg" by dragging and dropping to a channel window (desktop app or web). This time the upload never complete and the image will be shown as "Processing" indefinitely as shown in the image below.

#### Expected behavior
That the file would be uploaded.

#### Observed behavior (that appears unintentional) 
The upload never complete and the image will be shown as "Processing" indefinitely.
 
![Screen Shot 2022-11-07 at 8 21 21 PM](https://user-images.githubusercontent.com/1664844/200309672-e0d5018b-5c02-4d51-bf8a-17696b8e95b4.png)

#### Possible fixes
It appears the file name itself is causing the issue.

**Comment by MikaelStrom** [comment]
I just tried to reproduce on a non-cloud installation (Mattermost Version: 6.6.1), and the problem does not exists there, so it seem to be specific to the current cloud version.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48218.

**Comment by amyblais** [comment]
@MikaelStrom Someone on community mentioned that deactivating the Antivirus Plugin fixed the issue https://forum.mattermost.com/t/uploading-files-hangs-in-processing/14669/7. Do you have this plugin enabled? I'm not sure if this is the same but I'm just checking.

**Comment by MikaelStrom** [comment]
Hi Amy,

I don't use antivirus, Running on MacOS.

Regards,
Mike

**Comment by amyblais** [comment]
@MikaelStrom Is this still reproducing for you on the latest version?

**Comment by MikaelStrom** [comment]
Hi Amy,

just tested on your open web service and the files i provided for you reference behaves identical to my bug report, i.e. "x.jpg" succeeds while "MB STUDIO PRE + 2C+.jpg" fails to upload.

In the following image you can see the version as well as the failed upload (status is "Processing" indefinitely).


I noticed that Nevyana Angelova could not reproduce, but did he/she try with the files i uploaded and that is provided in the bug report?

Perhaps i can help in testing, just let me know what to do.

Regards,
Mike

**Comment by nevyangelova** [comment]
Hey @MikaelStrom I did try with the files you provided. It is possible that you are encountering a corrupt file name?Personally testing with a few files that I renamed, as well as the provided ones, did not yield any issues. Are you open to trying renaming another file and upload? Then we will know if the file itself is the issue. Many thanks!

**Comment by MikaelStrom** [comment]
Of course, Let me know how I can help! 

Regards,
Mike

**Comment by nevyangelova** [comment]
@MikaelStrom thanks, the idea is to try renaming a few random files with a similar or the same pattern and see how it behaves.
