### ISSUE TITLE
Deleted bot using mmctl delete user still shows under bot list

### ISSUE THREAD

**Issue by supergeoff** [mattermost/mattermost#21677]
#### Summary
Try to permanently delete a bot using mmctl delete it from user but still shows under bot list in integration page

#### Steps to reproduce
1 - Create a bot
2 - Use mmctl to delete user using bot name
3 - Bot still shows under integration but cannot be interacted with

#### Expected behavior
Delete a user/bot should delete it everywhere

**Comment by amyblais** [comment]
@supergeoff What Mattermost server version are you on?

**Comment by supergeoff** [comment]
7.4.0

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48458.

**Comment by amyblais** [comment]
Closing for now as this is an older bug and our team won't have a chance to prioritize this,

**Comment by smileBeda** [comment]
You can actually delete the bot by doing this:
- first, transform them into a user
- then, delete the user
- this, deletes the bot as well

You may do so with the API:
```
curl --request POST \
  --url domain.com/api/v4/bots/BOT-ID/convert_to_user \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
  "email": "string@domain.com",
  "username": "string",
  "password": "blablablabla",
  "first_name": "string",
  "last_name": "string",
  "nickname": "string",
  "position": "string",
  "props": {},
  "notify_props": {
    "email": "string",
    "push": "string",
    "desktop": "string",
    "desktop_sound": "string",
    "mention_keys": "string",
    "channel": "string",
    "first_name": "string",
    "auto_responder_message": "string",
    "push_threads": "string",
    "comments": "string",
    "desktop_threads": "string",
    "email_threads": "string"
  }
}'
...
curl --request DELETE \
  --url 'domain.com/api/v4/users/USER-ID?permanent=true' \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer XXX'
```

This _permanently_ and forever and actually DELETEs the user + the bot.

I am not sure why MM dev's think it is such a good idea to not allow deletion of bots and use a `DELETE` command to actually only disable a user... but hey, with this workaround it actually works.

@hozza btw please see https://github.com/mattermost/mattermost/issues/34559 (that is the reason I came here, an unbelievable situation if you ask me - close to a security problem)
