### ISSUE TITLE
Message draft is not saved in webapp, if it ends with :emoji:

### ISSUE THREAD

**Issue by ITCDEK** [mattermost/mattermost#21687]
#### Summary
Emoji\reaction is a common way to end message, but drafts of such messages are not being saved

#### Steps to reproduce
Type messages with keypresses, then end with reaction insertion via UI. Switch to another channel and back... reaction is gone!

#### Expected behavior
Reaction should be saved in draft

#### Observed behavior (that appears unintentional) 
See above

#### Possible fixes
Attach draft saver not only to keypresses, but to insertions via UI all so

**Comment by amyblais** [comment]
@ITCDEK What Mattermost server version are you on? What OS and version are you on?

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-48519.

**Comment by abhinav700** [comment]
@ITCDEK Is it working fine on mobile app?

**Comment by abhinav700** [comment]
It is working fine on my end. Is it fixed? @ITCDEK  @amyblais 

![image](https://github.com/mattermost/mattermost/assets/78839973/606d574b-ee27-4caf-a305-bb742d21172a)

![image](https://github.com/mattermost/mattermost/assets/78839973/16c66d85-3783-43cb-a117-4efbd4e6da59)

**Comment by Emil-Carlsson** [comment]
Hello! I can't seem to replicate this bug. Adding an emoji via UI at the end of a message and then switching channel does not seem to remove the emoji from the draft. 

Let me know if I am missing something.

**Comment by amyblais** [comment]
Thank you, I'll close this for now then. @ITCDEK let us know if you still reproduce this on the latest version and we can re-open this if needed.
