### ISSUE TITLE
Switching from Team Edition to Enterprise edition should ask for a confirmation

### ISSUE THREAD

**Issue by prudloff-insite** [mattermost/mattermost#21710]
#### Summary
Free trial button does not ask for confirmation.

#### Steps to reproduce
1. Install the Team Edition.
1. Browse to `/admin_console/about/license`.
1. Click on the free trial button.
1. It immediately starts downloading the Enterprise Edition.

#### Expected behavior
The best would be to have an option to hide this banner entirely. But at least the button should ask for a confirmation.
It should also display a clear way to cancel the download after it started.

#### Observed behavior (that appears unintentional) 
The button does not ask for any confirmation before it starts to download a binary replace the running version of Mattermost Server.
We discovered this after a misclick and it kind of looks like a dark pattern.
The fact that this page is the homepage for the admin console makes it especially easy to click the button by mistake.
We are self-hosting the Team Edition and have no intention to switch to the Enterprise Edition.

**Comment by amyblais** [comment]
@prudloff-insite What Mattermost server version are you on? What OS and version are you on?

**Comment by prudloff-insite** [comment]
We are using Mattermost 7.5.1 on Debian 10.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48576.

**Comment by johndavidlugtu** [comment]
Hi @prudloff-insite thanks for bringing this to our attention.

Just to make sure I understand correctly, the issue at hand is that the switch from Team Edition to Enterprise edition doesn't ask for confirmation nor does it allow for cancelling the switch.

Is that correct?

The free trial (Enterprise plan trial) is only available in Enterprise edition.

**Comment by prudloff-insite** [comment]
> Just to make sure I understand correctly, the issue at hand is that the switch from Team Edition to Enterprise edition doesn't ask for confirmation nor does it allow for cancelling the switch.

Yes, that is exactly the problem.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
