### ISSUE TITLE
Cannot send messages using ENTER, again? 

### ISSUE THREAD

**Issue by niemeyer** [mattermost/mattermost#21729]
Hello all,

#### Summary
The problem looks like a DUP from previously filed issues (#8522, #4393, etc), but since it's happening on a recent setup, perhaps it's a regression?

#### Steps to reproduce
Issue is exactly the same as the previous ones: type a message on Android, press ENTER, and it creates a new line instead of sending it, same as if SHIFT was pressed. I've tested this on a number of combinations, so it seems real:

 * Multiple on-screen keyboards
 * Bluetooth hardware keyboard
 * Mulitple browsers (Chrome, Firefox)
 * Mobile app
 * All three values of the "Send Messages on CTRL+ENTER" setting

Behavior is the same in all cases: ENTER adds a line instead of sending the message.

Update: some more info:

 * Using CTRL-ENTER to try to force it also doesn't work
 * Using the "Desktop site" option from the browser makes ENTER work correctly, so this indeed seems related to some conditional logic being done by the site itself

This is running on Android 13, and this is the Mattermost build information:
```
Mattermost Version: 6.6.0
Database Schema Version: 78
Database: postgres
Licensed to: Canonical
Build Hash: e05e0f9379e1324618601e3ba6111d78710e6319
EE Build Hash: 6185d9ea2cb7954b153c280f91cedb11ae92930f
Webapp Build Hash: d1a2c598e67cc926d116e3530a3198fcc11ec76d
Build Date: Mon Apr 11 17:05:36 UTC 2022
```

Thanks for looking into this.

#### Expected behavior
Message gets sent on ENTER.

#### Observed behavior (that appears unintentional) 
Newline gets added on ENTER.

**Comment by amyblais** [comment]
@niemeyer We currently support server versions v7.1.0 and later. Would you be open to upgrading to a supported version?

**Comment by niemeyer** [comment]
My understanding is that there's some kind of upstream support for this installation, and it will certainly be updated in time, but I cannot request the out-of-time update for this one issue, without even having an idea if it's fixed or not.

**Comment by amyblais** [comment]
@niemeyer You can connect to our community server here to test it out: https://community.mattermost.com/. This server is on the latest version.

**Comment by niemeyer** [comment]
Done, and confirmed: bug is still there.

* Using CTRL-ENTER to try to force it also doesn't work

* Some more information: using the "Desktop site" option makes ENTER work correctly, so this indeed seems related to some conditional logic being done by the site itself.

I've updated the first post with this info.

**Comment by amyblais** [comment]
@niemeyer What Mattermost mobile app version are you on?

**Comment by niemeyer** [comment]
1.55.1, so the latest one as of today, but not sure about how that information will help, given that as I mentioned the exact same problem exists both in mobile Firefox and mobile Chrome as well.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-48634.

**Comment by niemeyer** [comment]
Thanks, and good luck there. :)

**Comment by agnivade** [comment]
Hello @niemeyer - one follow up question:
- Could you try in mobile app v2 beta and confirm that you see the issue present there?

Our mobile browser support is limited, so if you see the issue in v2 app, this would be much higher in priority. We are transitioning off from our v1 app to v2. So it would be helpful to see if the behavior is present in v2.

Thanks!

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
