### ISSUE TITLE
Mattermost interactive button do not call URL

### ISSUE THREAD

**Issue by Rodrigo-Vieira-Chaves** [mattermost/mattermost#21765]
Hi, I am new to Mattermost and I am making a feedback bot for my company to automate feedback process, I need to send an interactive button and when clicked, it must call my bot endpoint: …/message-event/mattermost/interactivity.

I am running mattermost enterprise docker container in my machine (http://localhost:8065/) and my bot is running at http://localhost:4000/ (accessible via ngrok).

The issue is, when I click the button, it does not call my url, it calls /api/v4/posts/{{post_id}}/action/{{action_id}}, and gives 404 error, see printscreen.

I am trying to solve this issue for almost a day with no success, in documentation I thought I just need to specify the url and that’s it, the button would just call it, but this is not happening, what am I doing wrong here?

Printscreen:
![image](https://user-images.githubusercontent.com/91415563/204615407-fcbbfbd0-b4a1-4ac9-80b7-214c2b0561b4.png)

This is the object I am sending to api/v4/posts:
`[
   {
      "text":"Hello @userName\nPlaceholder",
      "actions":[
         {
            "id":"message-event",
            "type":"button",
            "name":"Select",
            "integration":{
               "url":"https://0a8a-200-101-26-87.sa.ngrok.io/message-event/mattermost/interactivity",
               "context":{
                  "action":"selectUserModal"
               }
            }
         }
      ]
   }
]`

**Comment by amyblais** [comment]
@Rodrigo-Vieira-Chaves What Mattermost server version are you on? Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by Rodrigo-Vieira-Chaves** [comment]
Hi, I got the docker from here https://github.com/mattermost/docker

In my docker 'ps' it shows 'mattermost enterprise 7.1', also I already posted at mattermost forum, but no response so far:

https://forum.mattermost.com/t/mattermost-interactive-button-do-not-call-url/14534

**Comment by amyblais** [comment]
I'm sorry that this fell through the cracks. If you're still having this issue, please either at-mention me here or open a new issue, and I will make sure to create a ticket or find someone to help with this issue.

**Comment by MedionSF** [comment]
I have exactly the same issue with version 9.0

Did anyone really tried to reproduce before closing?

**Comment by MedionSF** [comment]
Ok it was simple but still hard to find. You can't use hyphen or underscore un the "id" field... Some clear documentation would have spared me many hours of test :)
