### ISSUE TITLE
Make text selectable in images

### ISSUE THREAD

**Issue by reftel** [mattermost/mattermost#21871]
In macOS Monterey, you can select text in screenshots and other images in e.g. Preview.app. When people paste screenshots of user interfaces etc. on Mattermost, and I want to copy some text from it, then I have to first right-click the image and select "Copy Image", then switch to Preview.app, paste the image there, and then select and copy, and switch back to Mattermost to paste the text. This requires more steps then necessary, and is not very discoverable, leading many to simply not know they _can_ copy text from screenshots.
It would be a lot easier if Mattermost could integrate with whatever OCR magic that macOS is doing directly.

**Comment by devinbinnie** [comment]
Transferred to server repo as this is a system-wide feature request.

**Comment by reftel** [comment]
Well, it should in principle be possible to do it that way, but it sounds like it´d be much, much more work to do it cross-platform. For the Desktop app on macOS, it´d be a few lines of code, and it´s done. See https://developer.apple.com/documentation/visionkit/enabling_live_text_interactions_with_images/#3971774

**Comment by amyblais** [comment]
Feel free to open a feature request on Uservoice here for tracking https://mattermost.uservoice.com/forums/306457-general.

**Comment by reftel** [comment]
Thanks! I´ve opened a request for it: https://mattermost.uservoice.com/forums/306457-general/suggestions/47647619-make-text-selectable-in-images
