### ISSUE TITLE
Auto change channel status to 'read' on 'unread' one, after certain amount of time after switch to that channel

### ISSUE THREAD

**Issue by kdurasie** [mattermost/mattermost#21884]
Now, 'unread' channel remains 'unread' even after a long time after switching to a given channel. Sometimes it is enough to switch to unread channel or even via Alt-TAB to MM Desktop Application, then take a look and leave it active without any response. In this case, after certain amount of time, channel could be marked as 'read'. This period could be available to set in user settings.

Unread channel and messages remains marked by dot on channel icon and blue separation horizontal bar in messages thread.
Now user has to swich to another channel just for clear 'unread' status from previous one. 
It's a little annoying, or.. I don't know how to set channel as 'read' easily. 

Client:
OS: Windows 11
Desktop Application version: 5.2.2

Server:
Wersja Mattermost: 7.5.1
Wersja Schematu Bazy Danych: 95
Baza danych: postgres

**Comment by devinbinnie** [comment]
Transferring to server repo as I'm pretty sure this happens on the webapp as well.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-49081.

**Comment by Willyfrog** [comment]
@kdurasie can you provide a video showing what you mean, I'm a bit confused about the blue dot and it can mean several things and I'd like to see if there is anything going on when the channel doesn't get marked as read on selection as that's something I haven't seen in a while.

**Comment by kdurasie** [comment]
"bluedot" - it's my mistake, I meant reddot badge on app icon in taskbar and on the left - sometimes channel/person name style remains **bold**, but not always, unfortunately :( However case with horizontal bar  is easily replicable. I hope screenshot will be enough... even after my response it didn't dissappear  (but channel/person bold style has gone).
<img width="749" alt="image" src="https://user-images.githubusercontent.com/32538774/208476451-efbc1f0e-500c-4de3-aff1-505e5a2f3d73.png">

**Comment by amyblais** [comment]
I've updated the ticket with the new details.

**Comment by Willyfrog** [comment]
Thanks for clarifying!! Do you know if there are any errors in the console log?

**Comment by kdurasie** [comment]
Application wrapper ConsoleLog remains empty. MM Server ConsoleLog log gives entries like below: 
![image](https://user-images.githubusercontent.com/32538774/208528545-e5fb7c1f-2907-4d21-b1dd-2f9974c9705d.png)

**Comment by kdurasie** [comment]
I know where I saw this "blue dot" mentioned earlier... It indicate new items if you are using more than one MM serwer :)
Please look at screenshot - three elements indicating new items... 
![image](https://user-images.githubusercontent.com/32538774/208695136-40bcd9b7-22e4-4f55-b601-f6da72a39ef7.png)

**Comment by kdurasie** [comment]
And here - if this dot doesn't really mean new items - it takes time to click there and check everythig manually..
<img width="260" alt="image" src="https://user-images.githubusercontent.com/32538774/208696347-726480c8-dd7d-466e-89a0-9282d18fe2af.png">
