### ISSUE TITLE
ExperimentalDefaultChannels shows empty channels in the sidebar if the channels don't exist

### ISSUE THREAD

**Issue by kchiem** [mattermost/mattermost#21902]
#### Summary

If ExperimentalDefaultChannels is used, and a new team is created without those channels, a user joining the team will be presented with a list of empty channels in the sidebar.  Similar to issue #17970, except there, OP was complaining about Town Square being created as well, which I'm not complaining about.

#### Steps to reproduce

Affects current latest v7.5.1.
1. populate ExperimentalDefaultChannels 
2. create new team without those channels
3. join team or add user to team

#### Expected behavior

Non-existent channels shouldn't result in empty channels in the sidebar of the desktop web UI.

#### Observed behavior (that appears unintentional) 

See screenshot in issue #17970.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49182.

**Comment by kchiem** [comment]
Thank you Amy.  I left out a step:

1.5 restart the server, as ExperimentalDefaultChannels doesn't seem to take effect while the server is running.

**Comment by amyblais** [comment]
Thank you, I've added it to the ticket.

**Comment by hossain-sazzad** [comment]
I think it is the same issue as #24644
