### ISSUE TITLE
Developing plugins on Windows seems to be unsupported

### ISSUE THREAD

**Issue by scriptdealer** [mattermost/mattermost#21962]
#### Summary
Plug-in compiled on Windows fails to start

#### Steps to reproduce
Mirror sample Makefile as Makefile.go, to make it truly cross-platform (maybe, using mage and MM client for deploy part)
Deploy it using MM client

#### Expected behavior
Deploying to https://mattermost.test: 
Uploading plugin via API: Ok
Enabling plugin: Ok
(this is what I get on Ubuntu over Win WSL2)

#### Observed behavior (that appears unintentional) 
Deploying to https://mattermost.test: 
Uploading plugin via API: fail!
Error: failed to upload plugin bundle: : Internal Server Error, unable to start plugin: my-plugin: fork/exec plugins/my-plugin/server/plugin-linux-amd64: permission denied
(this is Win11)

#### Possible fixes
Since you can't set executive bit for plug-in on windows and can't add `--mode='a+rwX` to the tar command, only option I can see  is to check that bit on deploy and fix it server-side

**Comment by scriptdealer** [comment]
Go is 1.19 and server is 7.4.0, if that matters

**Comment by amyblais** [comment]
@scriptdealer Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by scriptdealer** [comment]
No luck with p2p help, guess forum is much less populated ?

**Comment by amyblais** [comment]
I'm sorry that this fell through the cracks. If you're still having this issue, please either at-mention me here or open a new issue, and I will make sure to create a ticket or find someone to help with this issue.
