### ISSUE TITLE
Browse Channels option missing - mobile web version

### ISSUE THREAD

**Issue by NedXR** [mattermost/mattermost#22031]
Mattermost mobile web version - Chrome Version 108.0.5359.128

When selecting the 3 dots right of Channels the option to Browse Channels is missing.  If you use Find Channel then you need to know the name of the channel to be able to find it and join.
![MM - no Browse Channels option mobile web version - Screenshot 2023-01-09 161055](https://user-images.githubusercontent.com/86116678/211368133-8b93d122-cd3b-4989-a7aa-8533960d461c.jpg)

Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49571.

**Comment by gitstart** [comment]
@NedXR did you mean this component ?
<img width="330" alt="Screen Shot 2023-02-16 at 12 24 58" src="https://user-images.githubusercontent.com/1501599/219287910-abbba6f9-890d-43a6-b7f7-ab5e01c55d1c.png">

**Comment by hchorfispiria** [comment]
@amyblais Would you mind assigning this issue to me?
