### ISSUE TITLE
Better authUrl for OAuth service handling

### ISSUE THREAD

**Issue by vpecinka** [mattermost/mattermost#22132]
Hi,

the current code for building authUrl as stated here:
https://github.com/mattermost/mattermost-server/blob/68382c5fb71abc36a962a8bd4b86d3430fd4b268/app/oauth.go#L758

expects that authorization url `endpoint` has no parameters. In my case I can pass custom parameter (`prompt=login`) forcing OAuth2 server to always ask for username/password regardless its own session existence.

Thus my setup `https://my.oauth2/authorize?prompt=login` leads to `https://my.oauth2/authorize?prompt=login?response_type=code&client_id...` and that double `?` makes invalid url.

Would it be possible to parse entry `endpoint` and respect optional custom parameters?

Thanks
VP

**Comment by amyblais** [comment]
@vpecinka What Mattermost server version are you on?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49920.
