### ISSUE TITLE
PostgresSQL full-text search fails to use indexes with non-`english` `default_text_search_config`

### ISSUE THREAD

**Issue by jre-lsft** [mattermost/mattermost#22249]
Since #20472, Mattermost no longer uses a hardcoded text search config for full-text search in PostgresSQL databases, but relies on `default_text_search_config`.
Unfortunately, indexes are still created with a hardcoded text search config (`english`).
As a result, full-text search may never use the indexes.

Since I'm not familiar with the Mattermost source base and also not a PostgresSQL expert, I'm not sure what the best way to handle this problem is.
That said, I guess it would be possible to use `default_text_search_config` on index creation as well, e.g.:
```PLpgSQL
DO $$
BEGIN
	EXECUTE format(
		'CREATE INDEX idx_posts_message_txt ON public.posts USING gin (to_tsvector(%L::regconfig, (message)::text))',
		current_setting('default_text_search_config'));
END $$;
```
Although this may be just a little too much magic, especially when it comes to migrating existing setups.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50318.

**Comment by agnivade** [comment]
@agarciamontoro - I remember us doing something about this. Can you jog my memory as to the decision we made?

**Comment by agnivade** [comment]
Gentle ping @agarciamontoro

**Comment by agarciamontoro** [comment]
Thanks for the ping, @agnivade, I had read this and forgot to answer!

If I remember correctly, what we discussed last year were two issues that were closely related to this, but not specifically this: there was a regression in https://github.com/mattermost/mattermost-server/pull/20367 that we reverted because it was not making use of the indexes, and then we realized that the cloud installations were not setting `default_text_search_config` to `english`, so we changed it to make sure they made use of the GIN indexes.

So this is still unsolved as far as I know, and any installation that has a `default_text_search_config` different than `english` is not making use of the GIN indexes (and never has, this is not a regression). It would be a great improvement to let the admins specify the main language of the installation and use that for the indexes, but it's something we'd have to investigate.

**Comment by agnivade** [comment]
The main language should be specified by `DefaultServerLocale`. In the mean while, maybe this is something that can be documented? Admins can easily drop the existing index and create a new one in the new language right?

**Comment by agarciamontoro** [comment]
Sure, that'd be the main workaround as of today. @cwarnermm, do you think we could improve the documentation on this point?

**Comment by cwarnermm** [comment]
Absolutely, @agarciamontoro. Are you open to drafting the updates needed in bullet form? I can then identify the docs pages to update and create the PR. Your draft would be a big help here!

**Comment by agarciamontoro** [comment]
Without the context this would be in is a bit more difficult, but this goes something like this:
- Some of the tables, like Posts or Users, contain GIN indexes to improve the database full-text search feature in PostgreSQL.
- These indexes  built against a specific language, and at the moment of creation, they are hard-coded to english.
- Full-text search is performed using the `default_text_search_config` database setting, which can be changed

All of this is Postgres-specific.

**Comment by agarciamontoro** [comment]
It's a bit more difficult without the context where this would be in, but it would go something like this:

- Some of the tables in Mattermost, like `Posts` or `Users`, contain GIN indexes to improve the database full-text search feature in PostgreSQL.
- These indexes need to be built against a specific language, and at the moment of creation, they are hard-coded to English.
- For the full-text search feature to leverage the indexes, the language specified in the query needs to match the language specified in the index.
- Full-text search queries are always performed using the `default_text_search_config` database setting.
- If the `default_text_search_config` is not set to `english`, the GIN indexes will not be used.
- Database administrators can work around this by dropping the specific GIN index they're interested in and rebuilding it with the value of `default_text_search_config`.
- For example, if the default language of your server is Spanish:
```sql
# Create the new index with a new name before dropping the old one
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_posts_message_txt_spanish ON posts USING gin(to_tsvector('spanish', message));
# Check that the new index does work. If it does, drop the old one and rename the new one:
DROP INDEX CONCURRENTLY IF EXISTS idx_posts_message_txt;
ALTER INDEX idx_posts_message_txt_spanish RENAME TO idx_posts_message_txt;
```

All of this is Postgres-specific. I haven't really tested the example, so we should not add it to the docs until it's tested.

**Comment by cwarnermm** [comment]
This is incredible context, @agarciamontoro, thank you! I'll include you on a docs PR and we can refine together as needed.

**Comment by agarciamontoro** [comment]
Thanks, @cwarnermm :)

@jre-lsft, would the workaround work for your case? Is that something you'd be willing to do in your system? Again, the specific example I posted is not properly tested, but the general idea is that: drop and rebuild.

**Comment by jre-lsft** [comment]
> @jre-lsft, would the workaround work for your case? Is that something you'd be willing to do in your system? Again, the specific example I posted is not properly tested, but the general idea is that: drop and rebuild.

Well, for now we've settled on `default_text_search_config = 'english'`.
I actually considered just manually rebuilding the indexes with a custom text search config before reporting this issue, but decided against it because I thought it would only work as a short-term fix, as we would need to monitor the schema for relevant changes in the future.
Since we have a mix of two languages, often within the same channels, no single language setting will give perfect results anyway.
But thank you very much for your suggestion, I'll keep it in mind in case we later realize we have to change the `default_text_search_config` after all.

**Comment by agarciamontoro** [comment]
Thanks, @jre-lsft, let us know if we can help in any other way. As per this issue, we can keep it open until the docs are up.
