### ISSUE TITLE
EnsureBot function does not ensure a bot exists

### ISSUE THREAD

**Issue by leipert** [mattermost/mattermost#22254]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary

EnsureBot function does not ensure a bot exists if bot user has been deleted manually

#### Steps to reproduce

```
Mattermost-Version: 7.7.2-rc1
DB-Schema version: 100
```

1. Install Boards plugin
2. Disable Boards plugin
3. Find boards bot user and delete it e.g. via mmctl
4. Try to Enable Boards plugin, it cannot be enabled

Even a full uninstall and reinstall of a plugin doesn't fix it.

#### Expected behavior

If the bot user doesn't exist, the value from the Plugin Key-Value Store should be ignored.

#### Observed behavior (that appears unintentional) 

```
cannot activate plugin: error creating mention notifications backend: failed to ensure Boards bot: failed to patch bot: SqlBotStore.Get: Bot does not exist., resource: Bot id: gek5qfto1ib3pmf7iy59xxfwhw
```

#### Possible fixes

Looking at the code, if the Plugin Key-Value Store has a Bot-ID saved, it tries to patch it without checking before whether the user still exists. This probably can be fixed by: Checking whether the user exists before trying to patch it, or capturing the "Bot does not exist error".

[If you can, link to the line of code that might be responsible for the problem](https://github.com/mattermost/mattermost-server/blob/5e69c6b02f604ce1aecb4c22cc58f9412cc685a2/app/bot.go#L50-L71)

**Comment by leipert** [comment]
Created a PR: https://github.com/mattermost/mattermost-server/pull/22255

**Comment by annaos** [comment]
I would like to pick this.
