### ISSUE TITLE
redirect to landing page (“Where would you like to view this?”) is an annoyance, please remove or add option to disable

### ISSUE THREAD

**Issue by sebalis** [mattermost/mattermost#22253]
#### Summary
It used to be possible for browser users to bookmark a link to the login page, but now when they open that link they must read a different page (called “landing”) that promotes the desktop app and click once more before they can enter their credentials.

#### Steps to reproduce
On an instance running 7.7.1, open the /login URL in a desktop browser

#### Expected behavior
The browser shows the familiar login form

#### Observed behavior (that appears unintentional) 
A page appears asking users if they want to view this page in a desktop app or in their web browser. These are users who have opened “this” in their browser. That should tell you what they want. I don’t want Mattermost to go down the route of some of the worst proponents of the digital economy. Please do not try to nudge people to use the software you think they should use. Respect their choices.

I am the administrator of an instance that is currently running version 7.1.5. I wanted to upgrade it to 7.7.1, but after my local test instance shows this feature on 7.7.1 (and I had already noticed it on another instance where I am a user), I am not going to upgrade for the time being.

Please do not respond by referring to the checkbox that is included on the landing page. This depends on a cookie. I work for a digital rights NGO, part of our tips for digital self-defence is to configure browsers to forget all cookies as the browser is closed. This renders the checkbox ineffective. You should not require people to click checkboxes, or click away from a landing page, at all when they have made their choice already and are requesting the login form.

#### Possible fixes
There is [a thread on the forum](https://forum.mattermost.com/t/disabling-the-landing-page/14293) discussing this issue, it contains a link to a suggested patch that was posted on the community server. This patch uses UserAgent.isMobile() as an extra condition. I don’t think this is a good solution because it will not remove this disrespectful feature for mobile users. Mobile users can have reasons for using their browsers too, and they will be aware that there are apps for most chat systems. So this page should not be shown to mobile browser users either. It should be removed, or at least there should be a switch to disable this feature site-wide.

Thanks for your consideration from an otherwise quite happy Mattermost admin and user.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50347.

**Comment by sebalis** [comment]
Thank you for opening the report on your Jira instance, @amyblais. I see that nothing has happened on either side. Is there anything I can or should do? This is stopping me from updating the Mattermost instance I administrate beyond 7.1.x.

**Comment by amyblais** [comment]
cc @m1lt0n @hmhealey Let me know if there are any new updates.

**Comment by hmhealey** [comment]
Sorry, this slipped through the cracks for us.

We can't remove that page completely since we want people to use the apps, but I think it would be fairly easy to add a server-wide setting to turn off the landing page for desktop. We can't do it for mobile because the mobile web app has been soft-deprecated for quite a while now because our native mobile app is a lot better, but hopefully that setting would the main issue for you

**Comment by sebalis** [comment]
Thanks for the response, @hmhealey. I think it would be the right thing to add such a setting. Also, I think if people surf to the /login path directly they are basically telling the server they know what they’re doing and they should not be required to click once more to get what they originally ask for, i.e. the login form. That doesn’t mean you shouldn’t display any kind of hint. You could still invite people o the mobile app via some link or button. That way, the mobile app would be the same number of clicks away as it is now, but the login form would be accessible without an extra click, as it should be.

**Comment by sebalis** [comment]
Hi, I see that 7.1 ESR is no longer updated so I will have to look at the 7.8–7.10 versions.  Nothing seems to have happened either here or in the Jira issue. Could you tell me where things stand? I sincerely hope I will not have to manually patch the compiled JavaScript to remove this functionality from all the downloads I am going to use.

**Comment by M-ZubairAhmed** [comment]
@sebalis thank you for your continued patience regarding this feature. However, we have opened it for triage and respective teams will pick it up and work as per their team's schedule.

**Comment by sebalis** [comment]
Thank you for responding, @M-ZubairAhmed but could you be a bit clearer what this means? I know that the traige tag has been on the Jira issue for a long time now and I have no way of assessing whether, or when, I might see the issue resolved.

Grudgingly preparing a patched version of 7.8 now as I am not going to expose my users to this annoyance …

**Comment by vincentpricex** [comment]
any update ?

**Comment by M-ZubairAhmed** [comment]
There is a help wanted ticket for this, feel free to pick it up

**Comment by amyblais** [comment]
Closing as there is a help wanted issue for this https://github.com/mattermost/mattermost/issues/23484.
