### ISSUE TITLE
7.7.1 -> 7.8.0 = jscript error

### ISSUE THREAD

**Issue by shurrman** [mattermost/mattermost#22344]
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/15817293/219267564-596e36ab-8ad5-4e02-97b1-175619b68e0b.png">

Using Docker, changing 7.7.1 to 7.8.0 in .env results in error

**Comment by shurrman** [comment]
No, there were no errors (I did check the log).
Currently I just set 7.7.1 back in .env and started with docker-compose again... no issues

**Comment by amyblais** [comment]
Are you open to sharing upgrade steps and any other relevant information that may help us troubleshoot this?

**Comment by shurrman** [comment]
Ye, I will try to reproduce and provide more information in 1-2 days

**Comment by shurrman** [comment]
If I try to open it in the browser - I can see this in the console:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/15817293/219948757-7a4366b1-17c1-4b97-b550-fa3405a75a96.png">
In the Mattermost logs I see this:
`{"timestamp":"2023-02-19 15:39:00.861 +03:00","level":"warn","msg":"Query for non existent field","caller":"app/plugin_api.go:979","plugin_id":"playbooks","error":"graphql: Cannot query field \"metadata\" on type \"Run\". (line 16, column 9)","request_id":"uqdp4qg6hbdbiyuzpw1aqyxdar","operation":"PlaybookLHS","plugin_caller":"github.com/mattermost/mattermost-plugin-playbooks/server/api/graphql.go:151"}
{"timestamp":"2023-02-19 15:40:01.859 +03:00","level":"warn","msg":"Query for non existent field","caller":"app/plugin_api.go:979","plugin_id":"playbooks","request_id":"8eagrowzdtg8zd4qe4be4d4rwh","error":"graphql: Cannot query field \"metadata\" on type \"Run\". (line 16, column 9)","operation":"PlaybookLHS","plugin_caller":"github.com/mattermost/mattermost-plugin-playbooks/server/api/graphql.go:151"}
{"timestamp":"2023-02-19 15:41:02.848 +03:00","level":"warn","msg":"Query for non existent field","caller":"app/plugin_api.go:979","plugin_id":"playbooks","request_id":"utaz7n9zubfe8jmumtqqyi7kpo","operation":"PlaybookLHS","error":"graphql: Cannot query field \"metadata\" on type \"Run\". (line 16, column 9)","plugin_caller":"github.com/mattermost/mattermost-plugin-playbooks/server/api/graphql.go:151"}`

**Comment by shurrman** [comment]
All I change is MATTERMOST_IMAGE_TAG=7.7.1 to MATTERMOST_IMAGE_TAG=7.8.0
Changing it back to 7.7.1 resolve issues.

In fact, I see similar errors in the console when running 7.7.1 - however it does not show that red line about JavaScript errors and allows to work without issues

**Comment by mmospanenko** [comment]
Boards app doesn't work on 7.8. Menu item was removed.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50716.

**Comment by shurrman** [comment]
Just upgraded from 7.7.1 to 7.9.0
No issues so far....

**Comment by shurrman** [comment]
However some users do report this error!
