### ISSUE TITLE
Sent messages often stuck and needs to be resend

### ISSUE THREAD

**Issue by david-strejc** [mattermost/mattermost#22354]
Mattermost Version: 7.8.0
Database Schema Version: 101
Database: mysql

Client: Both - web and mobile app
Web server: Apache 2.4 proxy to Mattermost server

Don't know how to debug this and further investigate, but our team is experiencing issue when sending messages. This happens really randomly. 

It happens in web interface as same as in Mobile App client v2.

It is really annoying. 

Is there any specific settings which can cause this issue like "keepalive" (which I've modified with no success), any other keepalive between Apache and Mattermost server? Or any other place we shoudl look into?

There is 40ms latency between our clients and MM server.

Many thanks for pointing into right direction.

**Comment by amyblais** [comment]
@david-strejc Do you see any errors in Mattermost server logs?

**Comment by david-strejc** [comment]
@amyblais 

Only such kind of errors: 

`{"timestamp":"2023-02-22 09:52:11.159 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/groups","request_id":"rbh1u61cni8pxrcdtw69arttor","ip_addr":"37.48.18.45","user_id":"crxjmj5jpjywfmmp6spne36ghe","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 09:52:12.716 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/groups","request_id":"1z5mjffyc38b7kqyqjmtfiwjcw","ip_addr":"37.48.18.45","user_id":"crxjmj5jpjywfmmp6spne36ghe","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:00:54.255 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/users/db7acg7xhbng9fbqf31ic4isho/groups","request_id":"cwj17jdq3bnxiqtn9tyujy63na","ip_addr":"78.80.17.247","user_id":"db7acg7xhbng9fbqf31ic4isho","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:00:55.593 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/groups","request_id":"3jfzzu7xmpye7gbdjrkfqyqm8w","ip_addr":"78.80.17.247","user_id":"db7acg7xhbng9fbqf31ic4isho","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:01:21.050 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/users/db7acg7xhbng9fbqf31ic4isho/groups","request_id":"mjujgcdf6prw8eumxochkzh18r","ip_addr":"78.80.17.247","user_id":"db7acg7xhbng9fbqf31ic4isho","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:02:16.355 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/users/db7acg7xhbng9fbqf31ic4isho/groups","request_id":"uzxs7iqfcjr47dgkm1p9i7iadc","ip_addr":"78.80.17.247","user_id":"db7acg7xhbng9fbqf31ic4isho","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:03:42.852 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/users/crxjmj5jpjywfmmp6spne36ghe/groups","request_id":"76c4don893rcpfr1ppsmiu1yso","ip_addr":"37.48.18.45","user_id":"crxjmj5jpjywfmmp6spne36ghe","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:11:44.735 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/users/crxjmj5jpjywfmmp6spne36ghe/groups","request_id":"pjmcg8sw1j8e8y3w7pks5brn1r","ip_addr":"37.48.18.45","user_id":"crxjmj5jpjywfmmp6spne36ghe","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
{"timestamp":"2023-02-22 10:19:01.191 +01:00","level":"info","msg":"api endpoint requires a license","caller":"web/context.go:115","path":"/api/v4/users/crxjmj5jpjywfmmp6spne36ghe/groups","request_id":"7x6aeosa3idfpbx5e6wuq5keac","ip_addr":"37.48.18.45","user_id":"crxjmj5jpjywfmmp6spne36ghe","method":"GET","err_where":"","http_code":501,"error":": api endpoint requires a license"}
..[root@8] - [/home/chat.apertia.cz/public_html/logs] - [Wed Feb 22, 10:19]
..[$] <()> cat mattermost.log| grep -i error | less
..[root@8] - [/home/chat.apertia.cz/public_html/logs] - [Wed Feb 22, 10:20]
..[$] <()> cat mattermost.log| grep -i error | less| grep -v 501
{"timestamp":"2023-02-21 18:36:01.466 +01:00","level":"error","msg":"License key from https://mattermost.com required to unlock enterprise features.","caller":"platform/license.go:106","error":"resource: License id: "}
{"timestamp":"2023-02-21 18:36:01.528 +01:00","level":"error","msg":"License key from https://mattermost.com required to unlock enterprise features.","caller":"platform/license.go:106","error":"resource: License id: "}
{"timestamp":"2023-02-21 18:36:01.804 +01:00","level":"info","msg":"[ERROR] call to OnConfigurationChange failed, error: GIF commands: internal error: rootURL must be set, ","caller":"io/io.go:428","plugin_id":"com.github.moussetc.mattermost.plugin.giphy","source":"plugin_stderr"}
{"timestamp":"2023-02-21 21:34:25.056 +01:00","level":"error","msg":"app.draft.save.app_error","caller":"web/context.go:117","path":"/api/v4/drafts","request_id":"mw64cunojbdkjmuc4gzmkqzu1w","ip_addr":"217.138.220.195","user_id":"i99hewprkb8ozcqz7tmtsucidc","method":"POST","err_where":"CreateDraft","http_code":500,"error":"CreateDraft: app.draft.save.app_error, failed to save Draft: Error 1062 (23000): Duplicate entry 'i99hewprkb8ozcqz7tmtsucidc-e5eh3w4fatnx7rx5kuqy9kfowa-4sc8sj1...' for key 'PRIMARY'"}
..[root@8] - [/home/chat.apertia.cz/public_html/logs] - [Wed Feb 22, 10:20]
..[$] <()> cat mattermost.log| grep -i error | less| grep -v licen
{"timestamp":"2023-02-21 18:36:01.804 +01:00","level":"info","msg":"[ERROR] call to OnConfigurationChange failed, error: GIF commands: internal error: rootURL must be set, ","caller":"io/io.go:428","plugin_id":"com.github.moussetc.mattermost.plugin.giphy","source":"plugin_stderr"}
{"timestamp":"2023-02-21 21:34:25.056 +01:00","level":"error","msg":"app.draft.save.app_error","caller":"web/context.go:117","path":"/api/v4/drafts","request_id":"mw64cunojbdkjmuc4gzmkqzu1w","ip_addr":"217.138.220.195","user_id":"i99hewprkb8ozcqz7tmtsucidc","method":"POST","err_where":"CreateDraft","http_code":500,"error":"CreateDraft: app.draft.save.app_error, failed to save Draft: Error 1062 (23000): Duplicate entry 'i99hewprkb8ozcqz7tmtsucidc-e5eh3w4fatnx7rx5kuqy9kfowa-4sc8sj1...' for key 'PRIMARY'"}
..[root@8] - [/home/chat.apertia.cz/public_html/logs] - [Wed Feb 22, 10:20]
..[$] <()> 
`

**Comment by amyblais** [comment]
@david-strejc Thanks, would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to help troubleshoot this issue.
