### ISSUE TITLE
Work of group mentions depends on application (webapp/mobile) state

### ISSUE THREAD

**Issue by TiPo4u4eK** [mattermost/mattermost#22435]
#### Summary
Work of group mentions depends on application (webapp/mobile) state

#### Steps to reproduce
1. Give all users permission for Group Mentions
2. Create more then 60 groups (default pagination: page=0&per_page=60)
3. Log in via default user

#### Expected behavior
4. Try to use group mention for group[0] - it's working
5. Try to use group mention for group[60+] - it's found group[60+]

#### Observed behavior (that appears unintentional) 
4. Try to use group mention for group[0] - it's working
5. Try to use group mention for group[60+] - it's won't found any group because of 403 /api/v4/groups?q=

#### State influence
6. Open User Groups modal
7. Search for group[60+] - it will found group
8. Try to use group mention for group[60+] - it's working

#### Possible fixes
[Change permission check](https://github.com/mattermost/mattermost-server/blob/master/api4/group.go#L1017)
PermissionManagePrivateChannelMembers, PermissionManagePublicChannelMembers -> PermissionUseGroupMentions

**Comment by TiPo4u4eK** [comment]
Server - 7.7.0
Mobile - 2.1.0
OS - All OS confirmed (Windows, Ubuntu, macOS, iOS, Android)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51211.
