### ISSUE TITLE
Problem with animated emoji rendering

### ISSUE THREAD

**Issue by Trey-Fore** [mattermost/mattermost#22432]
When uploading an animated .gif file as an emoji it renders correctly on the preview but will smear all the frames together once it is submitted.
![2023-03-02_16-21-02](https://user-images.githubusercontent.com/60977635/222573086-d0dc0037-af8a-4c3d-87e6-e7d1a11799e9.png)
![2023-03-02_16-21-36](https://user-images.githubusercontent.com/60977635/222573090-495010da-e47f-4c6c-9f3c-10ff8d3117e0.png)
![DanCoin](https://user-images.githubusercontent.com/60977635/222573123-010767ef-7b68-46b8-88e1-91ae34676ab5.gif)

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-51057.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
