### ISSUE TITLE
Minio Connection Problems

### ISSUE THREAD

**Issue by dianshane** [mattermost/mattermost#22507]
Hello,
i have been trying for the best part of two days to connect my mattermost server with my minio cluster.

i have tried pretty much everything and cannot make it work. You dont have any docs on you site for this so i would greatly appreciaty any help.

keys used are simple keys. I also tried using IAM keys but same thing.

Whatever i try i get either 400 or 404 with various messages like cannot check if bucket exists, cannot list buckets, cannot access buckets, bucket doesn't exist etc.

I need to understand what each variable does and how it is used internally to apply correctly to my environment .
There is no documentation on that whatsoever and there obviously is some internal tweak/variable handling that i don't know of making the connection impossible.

minio is not at fault other apps using the same cluster are working fine.

other things i have tried:
- using or not using the port on minio_nginx
- with and without path_style
- different versions of s3 sigs

i have tried multiple combinations of the above.

heres the config (using docker compose since im deploying to docker swarm - connectivity and dns are fine i checked):
minio_nging is a load balancing nginx proxy with 4 minio servers behind it - it proxies port 9000 to them - i dont mind changing it if i have to ( havent actually  tried it i just now thought of it will try and tell you if it fixes it - but i dont see how it would change anything unless port 80 is hardcoded).

i can also dump logs if you need me to i just wanted to avoid clutter and first ask if there is some obvious error in the config.

services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    depends_on:
      - mariadb
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmpassword
      - MM_EMAIL=mmuser@example.com
      - MM_SITEURL=http://example.com
      - MM_CONFIG=mysql://mmuser:mmpassword@tcp(mariadb:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - MM_ENABLEBOTACCOUNTS=true
      - MM_BOTACCOUNTENABLED=true
      - MM_BOTACCOUNTUSERNAME=bot
      - MM_BOTACCOUNTPASSWORD=botpassword
      - MM_BOTACCOUNTDISPLAYNAME="Mattermost Bot"
      - MM_FILESETTINGS_DRIVERNAME=amazons3
      - MM_FILESETTINGS_AMAZONS3ACCESSKEYID=somekeyid
      - MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY=somekey
      - MM_FILESETTINGS_AMAZONS3ENDPOINT=minio_nginx:9000
      - MM_FILESETTINGS_AMAZONS3SSL=false
      - MM_FILESETTINGS_AMAZONS3S3SIGNATUREVERSION=S3v4
      - MM_FILESETTINGS_AMAZONS3BUCKET=mattermost-media
      - MM_FILESETTINGS_AMAZONS3FORCEPATHSTYLE=true

Thanx again for any help!

**Comment by amyblais** [comment]
@dianshane Thanks, would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to help troubleshoot this issue.
