### ISSUE TITLE
GET /v4/posts/{post_id}/thread with perPage returns different number of posts

### ISSUE THREAD

**Issue by Tripletri** [mattermost/mattermost#22528]
#### Summary
GET `/api/v4/posts/{post_id}/thread?perPage=200`  sometimes return 200 items and sometimes 201

#### Steps to reproduce
1. Create post. Suppose it has `id=qwer`
2. Create 200 posts with `rootId=qwer`
3. Get `/api/v4/posts/qwer/therad?perPage=200`

#### Expected behavior
Get should return 200 items in `order` and `posts` fields

#### Observed behavior (that appears unintentional) 
Sometimes it return 200 items and sometimes 201

I tested it on `mattermost/mattermost-preview:7.2.0` conteiner and `v7.8.1` release

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51464.

**Comment by DevilsAutumn** [comment]
Hi, i would like to give it a try, may i?

**Comment by amyblais** [comment]
Hi @DevilsAutumn, for technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

**Comment by DevilsAutumn** [comment]
got into some imp work, will pick up some other time.👍

**Comment by LuizArnoldChavezBurgos** [comment]
@DevilsAutumn can we collaborate to solve this problem?

**Comment by Delaney** [comment]
Hey @amyblais the JIRA ticket has been marked as resolved, and the endpoint consistently returns 201 items. Can we assume this is intended and that this issue can be closed?
