### ISSUE TITLE
"@" mentioning modal going out of screen on small window

### ISSUE THREAD

**Issue by MioAtSwivel** [mattermost/mattermost#22526]
#### Summary
When the client window size is sufficiently small in height, the mentioning modal will go downwards and makes it more difficult to use than just going up anyways.

#### Steps to reproduce
Version 7.9.0-rc2

1. Log in to your mattermost server through webapp / desktop app
2. Access any chatroom channels
3. Reduce window height to around 400px (at the point when the mention modal go pass the top channel header)
![image](https://user-images.githubusercontent.com/102662641/225510781-3f9a16b4-c6dc-4052-bf4f-e4203b27c44b.png)
4. The modal goes to the bottom and can't be used properly
![image](https://user-images.githubusercontent.com/102662641/225510888-ae76e896-46f0-4d3f-a2dc-c88cf4084e0e.png)

#### Expected behavior
The affected modal should continue to be displayed upwards regardless of window height

#### Observed behavior (that appears unintentional) 
It goes down instead as to avoid colliding with the top channel header.

#### Possible fixes
- Let the modal shoot through and cover up the channel header regardless of screen height, as in the context of mentioning users, able to mention someone is much higher priority than able to see the channel header all the time.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51463.

**Comment by thinkGeist** [comment]
I've tracked this down locally, if you could assign it to me I'll track down a solution and put it up in a PR.
