### ISSUE TITLE
"Mark as Read/Unread" from sidebar navigates to channel

### ISSUE THREAD

**Issue by mleyen** [mattermost/mattermost#22686]
#### Summary
Selecting "Mark as Read/Unread", or any other option, from a channel's sidebar dropdown menu (the three dots) navigates to that channel

#### Steps to reproduce
Server version 7.9.1, using the web app.
Hover a channel's name on the sidebar, click the three dots, then click an option, such as "Mark as Read" (or really, click anywhere inside the `SidebarChannelMenu-MenuList-{id}` element).

#### Expected behavior
User stays on the currently active channel

#### Observed behavior (that appears unintentional) 
The targeted channel is opened, navigating the user away from the currently active channel.

Note that selecting an option with the keyboard does not trigger the issue.

#### Possible fixes
n.a.

**Comment by jaysoni-ash42** [comment]
@amyblais  can i work on this issue ?
