### ISSUE TITLE
Caching the edited message

### ISSUE THREAD

**Issue by kropotin** [mattermost/mattermost#22755]
#### Summary
We use some topics for the knowledge base, for these topics editing posts is allowed for all users. But...

#### Steps to reproduce
1. User1 created a post.
2. User2 edited the post.
3. User1 tries to edit a post, but gets the post he created in the editing window (changes made by user2 are not applied).

#### Expected behavior
Post edit window should have updated text

#### Observed behavior (that appears unintentional) 
In the editing window, we observe the saved (cached) text from the moment of the previous editing.

#### Possible fixes
To avoid this behavior, you can only log out and log in again.

**Comment by amyblais** [comment]
What Mattermost server version are you on? Are you on webapp or desktop app?

**Comment by kropotin** [comment]
> What Mattermost server version are you on? Are you on webapp or desktop app?

Mattermost v7.7.1.
We've seen this behavior since at least version 7.5 in webapp and desktop.

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-51882.

**Comment by larkox** [comment]
@kropotin I ran into this ticket, and I wasn't able to reproduce with the latest version. Can you confirm this is no longer an issue with later Mattermost versions?
