### ISSUE TITLE
Non-latin mentions are not highlighted

### ISSUE THREAD

**Issue by ilia3546** [mattermost/mattermost#22758]
#### Summary
If you add non-latin words into "Words That Trigger Mentions" in field "Other non case-sensitive words, separated by commas" then this words will be not highlighted.

#### Steps to reproduce
Add non-latin words into "Words That Trigger Mentions" in field "Other non case-sensitive words, separated by commas".
Desktop version 5.2.2 (26066)
Server version 7.8.1

#### Expected behavior
Non-latin words must be correctly highlighted

#### Observed behavior (that appears unintentional) 
<img width="568" alt="Screenshot 2023-03-31 at 12 56 24" src="https://user-images.githubusercontent.com/4445510/229089311-f1cdebff-98ab-4960-8ff1-49e02bae0076.png">
<img width="509" alt="Screenshot 2023-03-31 at 12 56 39" src="https://user-images.githubusercontent.com/4445510/229089336-e294cb5c-8e67-4248-8f98-3b80f5d07f60.png">

Possible related issue - #22450

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51849.
