### ISSUE TITLE
Mattermost Server 7.9.1 linux x64 tarball ships with mmctl 7.9.0

### ISSUE THREAD

**Issue by tgmux** [mattermost/mattermost#22777]
#### Summary
Mattermost Server 7.9.1 linux x64 tarball ships with mmctl 7.9.0

#### Steps to reproduce

1. Download latest mattermost server release tarball https://releases.mattermost.com/7.9.1/mattermost-7.9.1-linux-amd64.tar.gz
2. Extract tarball
3. `mattermost/bin/mmctl version`

#### Expected behavior
Linux tarball of mattermost server 7.9.1 should provide mmctl 7.9.1

#### Observed behavior (that appears unintentional) 
From extracted tarball root:
```
% cd mattermost/bin/
% ls -l
total 175328
-rwxr-xr-x. 1 foo bar 113460771 Mar 16 14:11 mattermost
-rwxr-xr-x. 1 foo bar  66071495 Mar  1 03:40 mmctl

% ./mmctl version
mmctl:
Version:	v7.9.0
GitCommit:	56199911e811bb8d96f719049fecc3c64fce9782
GitTreeState:	"clean"
BuildDate:	2023-03-01T08:32:15Z
GoVersion:	go1.18.1
Compiler:	gc
Platform:	linux/amd64

% ./mattermost version
Version: 7.9.1
Build Number: 7.9.1
Build Date: Thu Mar 16 17:32:51 UTC 2023
Build Hash: 6bcbd64dca8fec945c7abb83ba58c7b68abffa86
Build Enterprise Ready: true
```

#### Possible fixes
I was not able to find a specific line of code for the build process and suspect the configuration may not be on github. Apologies if this issue should be filed somewhere else, but did not see a more appropriate repo.

**Comment by amyblais** [comment]
Thanks, I've opened a ticket for our team to take a look.

**Comment by abishekkishore** [comment]
ENV PATH="/mattermost/bin:${PATH}"
ENV MM_INSTALL_TYPE=docker

# Build argument to set Mattermost edition
ARG edition="team"
ARG PUID=2000
ARG PGID=2000
ARG MM_BINARY=
ARG MM_VERSION="7.9.1"


# Install some needed packages
RUN apk add --no-cache \
        ca-certificates \
        curl \
        jq \
        libc6-compat \
        libffi-dev \
        libcap \
        linux-headers \
        mailcap \
        netcat-openbsd \
        xmlsec-dev \
        tzdata \
        && rm -rf /tmp/*

# Get Mattermost
RUN mkdir -p /mattermost/data /mattermost/plugins /mattermost/client/plugins \
        && if [ ! -z "$MM_BINARY" ]; then curl $MM_BINARY | tar -xvz ; \
                elif [ "$edition" = "team" ] ; then curl https://releases.mattermost.com/$MM_VERSION/mattermost-team-$MM_VERSION-linux-amd64.tar.gz?src=docker-app | tar -xvz ; \
                else curl https://releases.mattermost.com/$MM_VERSION/mattermost-$MM_VERSION-linux-amd64.tar.gz?src=docker-app | tar -xvz ; fi \
        && cp /mattermost/config/config.json /config.json.save \
        && rm -rf /mattermost/config/config.json \
        && addgroup -g ${PGID} mattermost \
        && adduser -D -u ${PUID} -G mattermost -h /mattermost -D mattermost \
        && chown -R mattermost:mattermost /mattermost /config.json.save /mattermost/plugins /mattermost/client/plugins \
        && setcap cap_net_bind_service=+ep /mattermost/bin/mattermost \

USER mattermost


Even after giving the version 7.9.1 I'm still getting the old version of my mattermost and yet I couldn't find a proper solution in the mattermost documentation or GitHub.
