### ISSUE TITLE
[Bug, WebUI] mattermost-redux: cannot read properties of undefined (reading 'forEach') 

### ISSUE THREAD

**Issue by dafanasiev** [mattermost/mattermost#22863]
in mattermost-server v7.9.1
[here](
https://github.com/mattermost/mattermost-server/blob/master/webapp/channels/src/packages/mattermost-redux/src/utils/apps.ts#L109-L111) - parameter `bindings` can be `null` in runtime:

![image](https://user-images.githubusercontent.com/5094703/230289627-1131897f-4968-47d3-b213-9ddb0db03e9b.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-51982.

**Comment by Safouene1** [comment]
Sorry If I got it wrong but the bindings parameter in the validateBindings function has a default value of an empty array [], which means that if the function is called without passing any arguments, the bindings parameter will default to an empty array.

**Comment by dafanasiev** [comment]
@Safouene1 is true, but here fn called with `null` argument value.
