### ISSUE TITLE
Emoji Picker doesn't appear when clicking on Add Reaction from post menu in mobile view

### ISSUE THREAD

**Issue by no-1ne** [mattermost/mattermost#22889]
Bug in mobile view, modal that appears when three dot menu is clicked, it isn't dismissed on click belowthe modal, where on click above the modal dismisses it, also add reaction on click doesn't do anything  

![Screenshot_20230407-161317453 (1)_1](https://user-images.githubusercontent.com/11027129/230598371-c089c195-be23-4bc6-b2d0-7149539c5d4e.jpg)

https://community.mattermost.com/core/pl/x5fifkaazf8kzdttc81mtjp3zr

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52082.

**Comment by hchorfispiria** [comment]
@amyblais Would you mind assigning this issue to me?
