### ISSUE TITLE
Threads stay in unread page

### ISSUE THREAD

**Issue by majidys** [mattermost/mattermost#22899]
Hi

By opening the topics in the unread section and reading them, but still the unread sign remains on them and will not be removed from the unread page.

![image](https://user-images.githubusercontent.com/99164978/230843363-8e163b7b-8c7e-4eae-9827-2418da55fb24.png)

@amyblais

**Comment by majidys** [comment]
Mattermost Enterprise Edition
Modern communication from behind your firewall.

Mattermost Version: 7.8.0
Database Schema Version: 101
Database: postgres

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52080.

**Comment by majidys** [comment]
@amyblais 
This problem is very annoying

**Comment by amyblais** [comment]
Does the workaround mentioned here help in your case: https://github.com/mattermost/mattermost-server/issues/22060#issuecomment-1520127079?

**Comment by majidys** [comment]
This is a temporary solution.
This problem is very annoying.
@amyblais

**Comment by majidys** [comment]
PLZ PLZ PLZ ...
@amyblais

**Comment by amyblais** [comment]
I have re-assigned the ticket to another team, and they will triage the ticket in the near-term.

**Comment by devinbinnie** [comment]
@majidys Can you provide us with a video of what you're seeing? Unfortunately the logs posted aren't enough to go on. It would be really helpful to understand exactly what you're seeing, thanks :)

**Comment by majidys** [comment]
@devinbinnie I apologize for late answering...
I will definitely make that movie and send to you
