### ISSUE TITLE
webapp a11y: sso login button not keyboard activatable

### ISSUE THREAD

**Issue by swalladge** [mattermost/mattermost#22957]
#### Summary

The SSO login process is not accessible with the keyboard.  Using the keyboard to navigate to the SSO button, then pressing enter to activate it, results in the email/password form being submitted instead.

#### Steps to reproduce

- Visit the login page of a mattermost webapp: https://community-daily.mattermost.com/login
- Use the keyboard tabbing to navigate to the SSO button (Okta in the mattermost instance above)
- Press enter

#### Expected behavior

The button/url is activitated and I'm redirected to the SSO provider login.

#### Observed behavior (that appears unintentional) 

I see an error ("Please enter your email or username"), and I'm not redirected to the SSO provider login.  See screenshot:

![1681421829](https://user-images.githubusercontent.com/9714796/231889748-4f2467a7-6dfa-4f18-9e8a-620d2a36823b.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52170.

**Comment by saideepesh000** [comment]
hey @amyblais, can u please assign this to me?
