### ISSUE TITLE
Updating post.props.card doesn't trigger refreshing post card component

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost#22961]
#### Summary
In previous versions of Mattermost, updating `post.props.card` trigger refreshing post card component in RHS, but, this refreshing doesn't occur since v7.4.

Example: 
Mattermost v7.1 can refresh post card components automatically, but this doesn't occur since v7.4.

https://user-images.githubusercontent.com/1453749/231914104-62a7b1e5-dc6d-4134-addf-08deb6e8b7be.mov

#### Steps to reproduce
1. Create a post with props.card
2. Open RHS to show post card component, and it remains opening
3. Update text in props.card

#### Expected behavior
Refreshing the post card component with updated text

#### Observed behavior (that appears unintentional) 
The post card component isn't refreshed.
Once reopening (close and open) post card component, updated text is shown.

#### Possible fixes
https://github.com/mattermost/mattermost-webapp/pull/10861#discussion_r933884918
This issue seems to be cause by this deletion. As commented here, `nextState.selected` is always undefined, but `nextProps.selected` is always set during opening post card component. So I think the following can fix this issue.

```
    shouldComponentUpdate(nextProps: Props, nextState: State) {
        if (!deepEqual(nextState.selected, this.props?.selected)) {
        // or checking more specified field.
        // if (!deepEqual(nextState.selected?.props?.card, this.props?.selected?.props?.card)) {
                return true;
        }
        if (nextState.isScrolling !== this.state.isScrolling) {
            return true;
        }
        return false;
    }
```

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52171.
