### ISSUE TITLE
Insufficiently high contrast generated for some usernames

### ISSUE THREAD

**Issue by jasom** [mattermost/mattermost#23018]
https://github.com/mattermost/mattermost-server/blob/84a304224966b28416aafeef8e81206b3826bf03/webapp/channels/src/components/user_profile/utils.ts#L21-L26

This code tries to pick high contrast but has two deficiencies:

1. It only tries 3 values
2. When it fails to get a  value above the threshold, it uses the last value, not the best value.

I'm curious how 3 was selected for the number of tries, but regardless of whether that's the right number of trials, it should return the best found value, not the last found value.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52280.

**Comment by KuSh** [comment]
I'm willing to work on this
