### ISSUE TITLE
Unnecessary blank space in sidebar display in compact view mode

### ISSUE THREAD

**Issue by yoikeda** [mattermost/mattermost#23039]
#### Summary
In compact view mode, when "Recent mentions" or "Saved posts" are displayed in the sidebar, there is a blank space on the left side.

#### Steps to reproduce
1. Login to Mattermost 7.10.0
2. Set "Settings-Display-Message Display" to "Compact".
3. Display "Recent mentions" or "Saved posts".

#### Expected behavior
As with threads, no unnecessary blank space.

#### Observed behavior (that appears unintentional) 
- Recent mentions  
  :x: Blank space exists on the left side.  
  ![image](https://user-images.githubusercontent.com/56328076/233249957-5b6b7605-ec6e-4311-baaa-442bf10bde5d.png)
- Saved posts  
  :x: Blank space exists on the left side.  
  ![image](https://user-images.githubusercontent.com/56328076/233250020-faa6af07-c238-4730-831f-9e8fb946c70f.png)
- Thread  
  :o: Blank space no exists on the left side.  
  ![image](https://user-images.githubusercontent.com/56328076/233246483-d5652de2-67da-4d37-8c88-61c0db19b130.png)

**Comment by Manishpandey11** [comment]
Hi @yoikeda , I would like to work on this issue. Can you assign the issue to me?

**Comment by yoikeda** [comment]
I would very much appreciate a correction.  
However, I do not have the authority to assign.  
If you have the authority, please respond.

**Comment by ShlokJswl** [comment]
Hi @amyblais @yoikeda  If no one is working in this issue currently can this be assigned to me I have already started working on it will try to raise a PR asap. thanks
