### ISSUE TITLE
Attachment link to message makes client application to reload the window

### ISSUE THREAD

**Issue by sobuctb** [mattermost/mattermost#23241]
#### Summary
[Attachment](https://developers.mattermost.com/integrate/reference/message-attachments/) link to a message in the other thread makes client application to reload the window

#### Steps to reproduce
Windows client version - 5.2.2
- copy a link to any mattermost message
- create a post using API, using [message attachments](https://developers.mattermost.com/integrate/reference/message-attachments/) with copied link as title_link
- click the header of created post in the mattermost client

#### Expected behavior
The link should be opened without page reloading in the desktop client 

#### Observed behavior (that appears unintentional) 
When I click the header in the browser, the link opens in a new window
When I click the header in the desktop client, the client reloads a window

#### Possible fixes
I'v seen code in the browser, links in the header doesn't contais data-link attribute, but contains target="_blank". 
Can the application check links in attachments to make them work same way as plain message links?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52621.

**Comment by devinbinnie** [comment]
@amyblais There's one open already: https://mattermost.atlassian.net/browse/MM-51998

**Comment by amyblais** [comment]
Closing for now as we haven't been able to reproduce this. Let us know if the bug still reproduces on the latest Mattermost version,
