### ISSUE TITLE
"Mark as unread" not working in direct chat

### ISSUE THREAD

**Issue by ghost** [mattermost/mattermost#23291]
#### Summary
The "mark as unread" feature is not working in direct one-to-one channels/chat. The "New Messages" divider is missing, and the message doesn't get moved to the "Unreads" section in the left sidebar.

#### Steps to reproduce
- open up a direct chat with a single person
- on a past message, click the three dots on the right side and select "Mark as unread"

#### Expected behaviour
As in channels with multiple participants, the "New Messages" divider should appear above the message which has been marked as unread and the channel should be moved to in the "Unreads" section in the sidebar

#### Observed behavior (that appears unintentional) 
nothing of the expected happens.

**Comment by amyblais** [comment]
Hi @ulierhard-hp, what Mattermost server version are you on?

**Comment by ulierhard-hp** [comment]
> Hi @ulierhard-hp, what Mattermost server version are you on?
@amyblais 
We are on Mattermost Version 7.8.0 (Database Schema Version: 101)

**Comment by AbhinavVihan** [comment]
I would like to work on this.

**Comment by AbhinavVihan** [comment]
Hello @amyblais, The functionality is working as it is supposed to.
[Screencast from 21-06-23 04:51:00 PM IST.webm](https://github.com/mattermost/mattermost/assets/89139362/5659a864-4187-41d0-9951-a15e73f27140)
