### ISSUE TITLE
Link opened by clicking notification is truncated

### ISSUE THREAD

**Issue by tanmayrajani** [mattermost/mattermost#23314]
I confirm:

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Link opened by clicking notification is truncated. It opens only the part of the link which is visible in the notification

**Environment**
- Operating System: Ubuntu 16.04.6 LTS 64-bit
- Mattermost Desktop App version: 4.2.3 
- Mattermost Server version: 5.13.2 

**Steps to reproduce**
1. Send a link as part of the message (somewhat longer link so that half the link is visible)
2. Click on the link in the notification

**Expected behavior**
- Whole link should be opened in browser

**Observed behavior**
- Only the visible part of the link opened in browser

**Example**
- Actual Message: `Please create an issue for that here: https://github.com/mattermost/desktop/issues`
- Visible Message in notification: `Please create an issue for that here: https://github.com/mattermost/desk` (here it opens `https://github.com/mattermost/desk` in the browser when clicked)

**Comment by BarbUk** [comment]
From the [linked JIRA ticket](https://mattermost.atlassian.net/browse/MM-40568):

> Harrison Healey 
May 16, 2023 at 10:52 PM

> We’ve truncated this notification text as far back as the initial commit. My gut reaction to this would be to close it as those links aren’t clickable on other OSes to the best of my knowledge, but it might be an easy fix by just removing the truncation of those since I assume OSes handle truncation themselves nowadays

I've made a draft PR to see how to fix that for linux (and/or other system?):
https://github.com/mattermost/mattermost/pull/26536
