### ISSUE TITLE
When selecting a date on the calendar when searching, the date one day before is selected.

### ISSUE THREAD

**Issue by k-kurematsu** [mattermost/mattermost#23370]
#### Summary
When searching for posts, if the calendar is displayed with on, before, after, etc. and a date is selected, the date one day before the selected date will be selected.

#### Steps to reproduce

1. Select the post search window
2. Enter "on:" to display the calendar
3. Select any date (e.g. 5/11/2023)
4. The date one day before the selected date is displayed in the input field ("on: 2023/5/10")

Mattermost Server : v7.10.0
Mattemost Desktop : Version 5.3.1 commit: 2c3d80f

#### Expected behavior
The selected date is reflected in the input field

#### Observed behavior (that appears unintentional) 
Select date with red cursor
![image](https://github.com/mattermost/mattermost-server/assets/106578775/77342db7-32cd-447d-b6c2-f322a69dd214)

The entered date is one day ago
![image](https://github.com/mattermost/mattermost-server/assets/106578775/cbf41ebe-6ccf-411c-965c-8c6acdab399b)

As of 2023/05/11, mattermost community(https://community.mattermost.com/core/channels/town-square) accessed with a web browser had the same symptoms.

**Comment by amyblais** [comment]
@k-kurematsu I wasn't able to reproduce this, are you on Mac or Windows and what version?

**Comment by k-kurematsu** [comment]
@amyblais Thanks for your comment. Windows versions are as follows.

Edition: Windows 10 Pro
Version: 21H2
OSBuild: 19044.1826

It is also reproduced in the Windows version below.

Edition: Windows 11 Pro
Version: 22H2
OSBuild: 22621.1702

The version of the browser when reproduced in the web browser is as follows.

Web Browser: Google Chrome
Version: 113.0.5672.93（Official Build） （64bit）
MattermostServer: https://community.mattermost.com/core/channels/town-square

**Comment by k-kurematsu** [comment]
@amyblais Additional information.
The time zone was reproduced after UTC + 1H, and it was not reproduced before UTC ± 0.
My country's time zone is JST (UTC+9h), so it seems to have been reproduced.

![image](https://github.com/mattermost/mattermost-server/assets/106578775/20f9bf76-d8a9-4c97-ba90-4dda8ae346af)

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-52793.

**Comment by k-kurematsu** [comment]
@amyblais Hi, is there anything I can do?

I tried accessing the server URL (https://mattermost-server-pr-23391.test.mattermost.cloud) described in https://github.com/mattermost/mattermost-server/pull/23391 , but it didn't seem to improve the problem.

**Comment by amyblais** [comment]
Is the note from Julien helpful https://github.com/mattermost/mattermost-server/pull/23391#pullrequestreview-1433566912?

**Comment by k-kurematsu** [comment]
No, Julien's comment looks like a separate issue from the one I detected.

**Comment by k-kurematsu** [comment]
Hmmm...
I checked the PR (#23391) again and it doesn't seem to be related to the issue I found.

I will try to post it in the community.
thank you!

**Comment by k-kurematsu** [comment]
I think the following code is the date selection process for post search.
If the `day` argument passed to handleDayClick is 00:00:00, wouldn't it be one day earlier depending on the timezone?

`webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx`
```
    handleDayClick = (day: Date) => {
        const dayString = day.toISOString().split('T')[0];
        this.props.onClick(dayString, this.props.matchedPretext);
    };
```

**Comment by amyblais** [comment]
Got it 👍 I thought that the linked PR was fixing the bug. We can continue to follow this issue via the Jira ticket that I created earlier https://mattermost.atlassian.net/browse/MM-52793.

**Comment by hchorfispiria** [comment]
@amyblais Would you mind assigning this issue to me?
