### ISSUE TITLE
The scrollbar color of the pdf preview is too dark and thin.

### ISSUE THREAD

**Issue by skotlex** [mattermost/mattermost#23380]
#### Summary
The scrollbar color of the pdf preview is too dark and thin.
![주석 2023-05-12 164101](https://github.com/mattermost/mattermost-server/assets/31692408/a336439a-f27c-457a-b8b1-cfc5762c6987)

The color may vary depending on the monitor, but it's so hard to find a scrollbar, at least on the screen I see.
And because the thickness of the scroll is thin, if you press a little wrong, the pdf preview turns off.

I think we need to increase the thickness of the scroll bar and make the scroll bar a little brighter for this. And while it's okay to end the preview by clicking on the empty space, I think it's also good to provide the option to turn off the preview only by pressing the x button to prevent misinput.

Finally, this is a simple question, and I was wondering if the ability to find data inside the pdf preview is not provided separately.

**Comment by amyblais** [comment]
Hi @skotlex,
1. What Mattermost server version are you on?
2. What OS and version are you on?

**Comment by amyblais** [comment]
I was able to reproduce it, opened https://mattermost.atlassian.net/browse/MM-52794.

**Comment by skotlex** [comment]
@amyblais There is an additional bug, and there is no response when I press the clip icon (public link copied) on that screenshot.

**Comment by skotlex** [comment]
@amyblais I have one more thing to add. If you keep pressing the zoom (+) button, the pdf content covers the scroll bar, so you cannot check the following unless it is a mouse wheel.

**Comment by amyblais** [comment]
> I have one more thing to add. If you keep pressing the zoom (+) button, the pdf content covers the scroll bar, so you cannot check the following unless it is a mouse wheel.

I've added a note about this to the ticket.

**Comment by amyblais** [comment]
> There is an additional bug, and there is no response when I press the clip icon (public link copied) on that screenshot.

What is the bug in this case?

**Comment by skotlex** [comment]
> > There is an additional bug, and there is no response when I press the clip icon (public link copied) on that screenshot.
> 
> What is the bug in this case?

![image](https://github.com/mattermost/mattermost-server/assets/31692408/05118a23-d99b-4f20-a386-ed1145f2e76c)
I didn't get any response when I pressed this icon. No messages were printed, no links were copied.

**Comment by amyblais** [comment]
> I didn't get any response when I pressed this icon. No messages were printed, no links were copied.

I wasn't able to reproduce this on ``master``, perhaps this bug is already fixed for the next release.
