### ISSUE TITLE
Not able to edit encrypted messages in Mattermost v7.10.0

### ISSUE THREAD

**Issue by MarcVJ** [mattermost/mattermost#23404]
Hello,

We noticed that it is not possible to edit our own encrypted messages with Mattermost v7.10.0 : it is possible to "Modify" then "Save", but the modification doesn't appear in the chat, although there is the "edited" tag and it is visible if you click a second time on Modify. 
If the message is not encrypted, we can edit our own messages properly. 

With encrypted messages : 
![image](https://github.com/mattermost/mattermost-server/assets/38230768/880d4803-2447-4e04-91c3-c2cd00301afc)
![image](https://github.com/mattermost/mattermost-server/assets/38230768/d2c95a28-cdb3-41e6-a7c4-567a889a1661)

With normal messages : 
![image](https://github.com/mattermost/mattermost-server/assets/38230768/732f0bd2-4b0d-4085-aabd-54ccc4a51a17)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52855.

**Comment by marianunez** [comment]
Hi @MarcVJ, some questions:

- Can you expand on the encrypted messages functionality? Is this something added through a plugin?
- Was this working as expected with a previous Mattermost version and stopped working after upgrading to v7.10?
