### ISSUE TITLE
don't show (message deleted) placeholder to any user . just make it disappear.

### ISSUE THREAD

**Issue by arthur19q3** [mattermost/mattermost#23480]
Repro steps:

Post a message
Delete that message

**Observed**: All users see (message deleted) placeholder and can remove it by clicking the X button or refreshing the page.

**Expected**: The message immediately disappears for all users.

any idea how i could do this?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52917.

**Comment by arthur19q3** [comment]
well my applogies amy. first it seems that user who deletes the message whot see the placaholder. secondly this might not be a bug, i am merely wondering how i can turn off that placeholder, which is inconvenient in our work setting. :)

**Comment by marianunez** [comment]
Hi @arthur19q3! 

> . first it seems that user who deletes the message can see the placaholder.

The `message deleted` placeholder will show for active users that originally got the message and then it was deleted. Any user that never got the originally message or after a refresh won't see this any longer.  

>  i am merely wondering how i can turn off that placeholder, which is inconvenient in our work setting. :)

We currently don't have a way to disable this functionality. Can you elaborate on why this is inconvenient in your work setting?

**Comment by arthur19q3** [comment]
> We currently don't have a way to disable this functionality. Can you elaborate on why this is inconvenient in your work setting?

hi there

we've built a bot to monitor & report price changes in finacial market working in one of our channels, the traders who visit this channel would like to see only  one set of messages at the same time, so i kinda made the bot to delete all history messages every 5minutes with the help of Mattermost API. hence the deletion placeholders. 

i also tried ephemeral messaging, but then again these ephemeral ones would linger until a refresh, which is not desired.

**Comment by amyblais** [comment]
Since we currently don't support this functionality, would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general)? Please include a link back to this GitHub issue. If you're interested to open a pull request to implement this functionality, please let us know.

**Comment by wiidz** [comment]
I think adding a configuration option to enable or disable this feature would be more user-friendly
