### ISSUE TITLE
The profile popover is not visible when clicking on a user in the channel members search results.

### ISSUE THREAD

**Issue by Nick-Su** [mattermost/mattermost#23521]
#### Summary
When I open the channel members sidebar and search for a member, clicking on their avatar does not display the profile popover.

#### Steps to reproduce
1. Find a channel with 20 or more members.
2. Click the "View Members" button.
3. In the right members sidebar, enter the name of a user in the search bar.
4. From the search results, click on any avatar.
5. The profile popover briefly appears and then disappears immediately.

Note: This issue does not occur when viewing the normal users list. The search functionality is necessary to reproduce it

#### Expected behavior
I expect to be able to search for a user, click their avatar, and see the profile popover.

#### Observed behavior (that appears unintentional) 
The profile popover briefly appears and then disappears immediately.

#### Possible fixes
I'm not certain about the cause of the issue, but I believe the entry point for the bug could be in the `profile_popover.tsx` file, specifically in the componentDidMount hook on line 227.
```
if (currentTeamId && userId) {
    this.props.actions.getMembershipForEntities(
        currentTeamId,
        userId,
        channelId,
    );
}
```

**Comment by saideepesh000** [comment]
hey @amyblais , I can pick this up

**Comment by M-ZubairAhmed** [comment]
@saideepesh000 thank you for showing interest in this. However I would suggest to please wait until we triage this issue internally and come up with clear direction for this.
