### ISSUE TITLE
How to Change name Defualt mattermost chanel

### ISSUE THREAD

**Issue by ramindoroozeh** [mattermost/mattermost#23529]
hi evreyboady 
how to change defualt chanel name in server?

**Comment by amyblais** [comment]
Hi @ramindoroozeh, the default channels are currently hardcoded. This post may give more information https://forum.mattermost.com/t/modify-default-channel-for-new-users/11544/6.

**Comment by amyblais** [comment]
@ramindoroozeh I may have misunderstood your original question. As a system admin, I'm able to rename the default channels by clicking the channel name and then clicking the option "Rename Channel". Do you see this option as well? What Mattermost server version are you on?
