### ISSUE TITLE
Environment variable ignored

### ISSUE THREAD

**Issue by gpierre67** [mattermost/mattermost#23551]
Mattermost selfhosted container 7.10.2

Sending environment variable to manage password policy is useless. https://docs.mattermost.com/configure/authentication-configuration-settings.html#password-requirements 

Those variables are ignored :
  MM_PASSWORDSETTINGS_LOWERCASE
  MM_PASSWORDSETTINGS_UPPERCASE
  MM_PASSWORDSETTINGS_NUMBER
  MM_PASSWORDSETTINGS_SYMBOL
  
Even if these variables are set, it is still possible to modify their state in the app.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52982.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
