### ISSUE TITLE
Backspace is forbidden globally

### ISSUE THREAD

**Issue by akaravashkin** [mattermost/mattermost#23555]
#### Summary
I have a `div` `contenteditable="true"`  in my plugin, but MM forbids using `Backspace` globally.

I found a ticket from 2015 https://github.com/mattermost/mattermost-server/issues/533 that asks to prevent default browser behavior follows Backspace button. But modern browsers don't go back on `Backspace`.

#### Possible fixes
This fix could be deleted. If you decide to create a ticket, I would like to prepare a PR.

Blocking code is here:
`webapp/channels/src/components/logged_in/logged_in.tsx:`  `handleBackSpace`

**Comment by M-ZubairAhmed** [comment]
Let me discuss with the team if we are leaning towards removing that and its consequences.

**Comment by akaravashkin** [comment]
PR https://github.com/mattermost/mattermost/pull/23626
