### ISSUE TITLE
BOT tag being applied twice

### ISSUE THREAD

**Issue by elixx** [mattermost/mattermost#23615]
#### Summary
An incoming webhook created in the past by a converted Bot account causes the `BOT` tag to be applied twice

#### Steps to reproduce
Create a regular user, create an incoming webhook integration with that user, then convert that user to a Bot account with `mmctl`

#### Expected behavior
The bot tag to be applied once to the messages

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/2325870/3cbdd9cf-a04b-46e6-92c7-1a2dcf333078)
The tag is applied twice

#### Possible fixes
Don't append tag to integrations when a bot account is involved, since it is already getting tagged?

**Comment by amyblais** [comment]
This was fixed via https://mattermost.atlassian.net/browse/MM-52119 and the fix is queued for the next release.
