### ISSUE TITLE
Non Board members appearing in private board Assignee list

### ISSUE THREAD

**Issue by RoudyHanna** [mattermost/mattermost#23611]
#### Summary
Non Board members appearing in private board Assignee list

#### Steps to reproduce
Create a private board and invite one or two person.
Create a task for an assignee from the board members

#### Expected behavior
ONLY board members list should appear

#### Observed behavior
All server members are appearing (in their correct category after searching: i.e. board members or not)

Possible fixes
Have only board members appear in the drop down list before searching for names

**Comment by M-ZubairAhmed** [comment]
@RoudyHanna can you please use the issue template above with `Summary`, `Steps to reproduce
` , Expected behavior and Observed behavior (that appears unintentional)

**Comment by RoudyHanna** [comment]
Summary

Non Board members appearing in private board Assignee list

Steps to reproduce

Create a private board and invite one or two person. 
Create a task for an assignee from the board members

Expected behavior

ONLY board members list should appear

Observed behavior (that appears unintentional)

All server members are appearing (in their correct category after searching: i.e. board members or not) 

<img width="1247" alt="image" src="https://github.com/mattermost/mattermost/assets/94135081/9b901a36-e0e7-4cf4-bdac-b62bb6429b28">

<img width="1247" alt="image" src="https://github.com/mattermost/mattermost/assets/94135081/5e30bda6-da84-4c36-95f1-d9b4f1a3fdda">

Possible fixes

Have only board members appear in the drop down list before searching for names


Thanks

**Comment by amyblais** [comment]
Hi @RoudyHanna, what Mattermost server version are you on? What Mattermost Boards version are you using?

**Comment by RoudyHanna** [comment]
Hello @amyblais, I am on the application Version 5.3.1 (46002745061) and Mattermost version: 7.10.1 (Server of Forschungszentrum Jülich, Germany (IFFChat))

<img width="1203" alt="image" src="https://github.com/mattermost/mattermost/assets/94135081/e959c213-44b5-4d20-a3df-910aaf8517b1">

I am using Boards from the templates (i.e. Project Tasks) and created some of my own as well

**Comment by amyblais** [comment]
Thank you, I've added this as Up For Grabs so anyone can take this to submit a fix.

**Comment by RoudyHanna** [comment]
Thanks for your help !

**Comment by MattSilvaa** [comment]
It seems like this behavior is as expected because when you select a user that is not a board member you receive a prompt to add the user to the board (see screenshot). 
 
![Screenshot from 2023-06-05 19-59-54](https://github.com/mattermost/mattermost/assets/20505926/751d3766-d8b1-4ec3-a94a-da3287a9fa00)

**Comment by RoudyHanna** [comment]
But wouldn't it make more sense to assign task to existing board members more frequently than inviting new people? 

All I am saying, having the board members appear first is more practical and faster. One can always scroll/search for other people and invite them if needed.

**Comment by amyblais** [comment]
cc @sbishel maybe someone from your team can help clarify the expected behaviour here before I open this as Up For Grabs.

**Comment by sbishel** [comment]
I'm pretty sure, existing behavior is by-design. We went back and forth with the same argument and went with the more flexible implementation.

**Comment by amyblais** [comment]
Feel free to open a feature request on Uservoice here for tracking https://mattermost.uservoice.com/forums/306457-general.

**Comment by mmospanenko** [comment]
Will be great to have configuration for this dropdown with people. Show only Team Members, Board Members, etc. But now on private board we can see all server members from different teams including public.

Something like this, but for Boards:
<img width="927" alt="image" src="https://github.com/mattermost/mattermost/assets/2766211/7fabc4b9-ef4f-46a8-8de8-e3ad06f3b676">
