### ISSUE TITLE
Syntax highlighting not supported in Mattermost Boards

### ISSUE THREAD

**Issue by davide-prade** [mattermost/mattermost#23627]
#### Summary
In Mattermost Boards the cards don't support syntax highlighting in markdown code block.

#### Steps to reproduce
Create a card in Mattermost Boards and a text content. Fill the content with a code block with language specification, for example:

```` java
``` java
// Your First Program

class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!"); 
    }
}
```
````

#### Expected behavior
The syntax in the code block must be highlighted according to the language.

#### Observed behavior (that appears unintentional) 
The syntax in the code block is not highlighted according to the language.

#### Possible fixes
Use the same logic used for chat messages code block: https://docs.mattermost.com/channels/format-messages.html

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @davide-prade,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.
