### ISSUE TITLE
Notifications do not work in iOS Home Screen web app. 

### ISSUE THREAD

**Issue by MaxIsMyName** [mattermost/mattermost#23662]
#### Description
Notifications do not work in iOS Home Screen web app (PWA). 

Mattermost  7.7.1

#### Steps to reproduce
1. Go to Mattermost server in Safari
2. Add website to Home Screen (required for notifications to work per [Apple’s documentation](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/) )
3. Grant permission for notifications for the app when prompted. Might require browsing a bit or receiving a message. 
4. Receive message with app not in the foreground. 

#### Expected behavior
A notification should be received. 

#### Observed behavior (that appears unintentional) 
No notifications are received. 

#### Possible fixes
Unsure.

**Comment by MaxIsMyName** [comment]
Note that solving this issue would also provide a decent workaround for [this issue affecting Mobile](https://github.com/mattermost/mattermost-mobile/issues/1495) 

It is also a highly requested feature according to [Mattermost’s UserVoice](https://mattermost.uservoice.com/forums/306457-general/suggestions/14756865-mobile-client-ssl-authentication). While the request has been marked as implemented, this is incorrect as the mobile app on iOS does not support mTLS

**Comment by amyblais** [comment]
Since the Uservoice issue has been closed a while ago, feel free to create a new one. Thank you for sharing this!

**Comment by MaxIsMyName** [comment]
Thank you @amyblais. I have created a new Uservoice issue here: https://mattermost.uservoice.com/forums/306457-general/suggestions/46777495-extend-web-application-to-enable-ios-web-push-via (waiting to be approved currently).

**Comment by amyblais** [comment]
Thank you!

**Comment by MaxIsMyName** [comment]
Hi @amyblais , the user voice has been closed but I do not believe the idea was implemented. Do you know why?

**Comment by amyblais** [comment]
I don't seem to have access to UserVoice to re-open it. @azigler would you be able to re-open https://mattermost.uservoice.com/forums/306457-general/suggestions/46777495-extend-web-application-to-enable-ios-web-push-via?

**Comment by azigler** [comment]
Hi @amyblais, thanks for the ping! 👋 

I logged into the UserVoice admin account but I'm unable to view or retrieve the post because it's been deleted, no matter how I filter the views.

@MaxIsMyName If you'd like to try posting the suggestion again, I'll double-check approvals afterwards. Thank you for your patience in making a suggestion! 🙏
