### ISSUE TITLE
[Feature] Scroll to the bottom of channel chat

### ISSUE THREAD

**Issue by Pawel1894** [mattermost/mattermost#23683]
Hey, just a small idea. It would be cool to have some sort of button to show up with functionality to scroll to the latest message when scrolling chat to the top. I could implement it.

--- 
**Design notes:**

There should be a banner on the top of the channel to Jump to recents that will appear once the user has scrolled up. 

It should appear at the same time when the banner for “Tip: Try CMD+SHIFT+F to search this channel appears. The Jump to recents banner can follow the same logic for when it should appear or not appear as the tip banner.

The two banners should be independently dismissible. 

[Figma](https://www.figma.com/file/gbnx8ydTX0bTFIbJ8NWGfR/MM-XXXXX-Project-Template---Channels-(Copy)?type=design&node-id=1-7&mode=design)

![image-20230807-180511](https://github.com/mattermost/mattermost/assets/936315/f64dc5c2-327f-4786-a069-815259f6cf1a)

**Comment by amyblais** [comment]
cc @johndavidlugtu I can open this as Help Wanted if this is something we'd want to add.

**Comment by johndavidlugtu** [comment]
Sure, thanks @amyblais -- can we add `Help Wanted Candidate` label on the ticket? Need to evaluate merits of adding it to product considering other implications (e.g. performance)

**Comment by amyblais** [comment]
Opened a ticket https://mattermost.atlassian.net/browse/MM-53360.

**Comment by edwardnguyen225** [comment]
May I take over this ticket?

**Comment by amyblais** [comment]
@edwardnguyen225 Thank you for your interest in working on this. We need to evaluate merits of adding it to product considering other implications (e.g. performance) before we're ready to open this as Help Wanted.

**Comment by edwardnguyen225** [comment]
Just curious, how do you guys evaluate merits? Because I thought that it could be done after the implementation.

**Comment by abhijit-singh** [comment]
Hey @edwardnguyen225! We just wanted to make sure that we have a proposal that matches with our product and design guidelines and any dev effort doesn't go to waste. 

We've put together a quick mockup that we feel works well. Here's the [**Figma file**](https://www.figma.com/file/gbnx8ydTX0bTFIbJ8NWGfR/MM-XXXXX-Project-Template---Channels-(Copy)?type=design&node-id=1-7&mode=design) with a proposal on how it should work and also the hover states. 

Open to any feedback, thoughts or suggestions on this. Excited to have this in the product! 😄

![image](https://github.com/mattermost/mattermost/assets/14369607/1d7b9019-2dd0-4b81-9b69-6be1c09c2d2a)

**Comment by marianunez** [comment]
@Pawel1894 @edwardnguyen225 I've updated the ticket description with the design details provided by @abhijit-singh. Let me know if you would be interested in picking this up

**Comment by edwardnguyen225** [comment]
@marianunez May I pick this one? Besides, is there any due date for this?

**Comment by marianunez** [comment]
> @marianunez May I pick this one? Besides, is there any due date for this?

@edwardnguyen225 Great, I'll assign it to you. We don't expect it for any specific date. Let us know if you have any questios. Thanks !
