### ISSUE TITLE
Mattermost Client handles HTTP headers regardless of case.

### ISSUE THREAD

**Issue by a1vanov** [mattermost/mattermost#23704]
#### Summary
MM client handles HTTP headers regardless of case.

`export const HEADER_X_VERSION_ID = 'X-Version-Id';`
[/packages/client/src/client4.ts:L154](https://github.com/mattermost/mattermost-webapp/blame/149cb00b8282fbf3c31a82ed31b1be4d0b660883/packages/client/src/client4.ts#L154
)

'if' bellow is a lottery.
`
if (headers.has(HEADER_X_VERSION_ID) && !headers.get('Cache-Control'))
` 
[/packages/client/src/client4.ts:L4155](https://github.com/mattermost/mattermost-webapp/blame/149cb00b8282fbf3c31a82ed31b1be4d0b660883/packages/client/src/client4.ts#L4155)

I have got following headers:
`{"map" => {....., "x-request-id": "j4gquei1ht8b7nuub7fyofugzc", "x-version-id": "5.24.0.5.24.1.984ed9017de6bbb31691d3c2647f.false"}}`
Headers "x-request-id" and "x-version-id" have been ignored by the client.

According to [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) "Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive."

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53273.

**Comment by harshilsharma63** [comment]
@a1vanov can you please share what Mattermost version are you on? Also, in your installation, do you have any cache or reverse-proxy server or anything in between the client and MM server (load balancer, Apache server, etc.)?

Thanks!

**Comment by amyblais** [comment]
Closing as we haven't received a response for a while,
