### ISSUE TITLE
Web/Desktop App: Submit/Cancel button in interactive dialog sometimes does not populate channel_id

### ISSUE THREAD

**Issue by vitevskii** [mattermost/mattermost#23754]
#### Summary
Mattermost Web/Desktop client sometimes does not populate **channel_id** field in /dialog/submit a request when clicking on Submit/Cancel button in the interactive dialog.
#### Steps to reproduce
Open an interactive dialog.
Open the browser console (in Chrome:  Press F12, Network)
Click on the Submit/Cancel button.
Check in the console if the channel_id is correctly populated in the request body of /dialog/submit.

#### Expected behavior
When clicking on the Submit/Cancel button in an interactive dialog, the Mattermost web client sometimes does not populate the channel_id in the /dialog/submit request body. As a result, the Mattermost server responds with a 403 error. 
Occasionally, opening the post/thread link from which the dialog is invoked in a separate window resolves the issue.
This bug has been observed on both Windows/Chrome and Mac/Safari platforms. No such errors have been noticed in the Mattermost mobile app.

Mattermost Version: 7.10.2
Mattermost Desktop Version: 5.3.1 2c3d80f
Chrome Version: 114.0.5735.133
Safari Version: 16.5 (18615.2.9.11.4)

#### Observed behavior (that appears unintentional) 
Request from Mattermost Web Client (Chrome - F12 - Network): `POST https://mattermost-test.skyeng.tech/api/v4/actions/dialogs/submit`
Request body:
`{ "url":"http://sel-tezis-test.skyeng.link:8888/mattermost/webhook/assignment/confirm", "callback_id":"", "state":"...", "submission":{ "comment":null }, "channel_id":"", "team_id":"qy68iknxw7bopqqn1bbkswr4yy" }`
Response:
`{ "id":"api.context.permissions.app_error", "message":"You do not have the appropriate permissions.", "detailed_error":"", "request_id":"bdndggffnfdc9ggngs7xoej7xc", "status_code":403 }`

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53200.

**Comment by amyblais** [comment]
Closing as there is a Help Wanted issue open for this.
