### ISSUE TITLE
FocalBoards errors and drop down a service

### ISSUE THREAD

**Issue by Beast-Breacher** [mattermost/mattermost#23769]
Good day! Today we catch a some list of errors in Focalboard, which drops our MM down and fixed only by reboot of all service. 
Can you help us with this problem/ Or, maybe, i didn't find the same issue in Jira, which does goes earlier.

#### Summary
Errors in Mattermost and focalboards, which drop down the service and caused a forced reboot to return it back on. 
<details><summary>Code of some Errors</summary>
<p>

error [2023-06-16 09:49:18.615 +05:00] GetPreferencesForUser: We encountered an error while finding preferences. 
  github.com/mattermost/focalboard/server/api.(*API).errorResponse
      github.com/mattermost/focalboard/server/api/api.go:183
  github.com/mattermost/focalboard/server/api.(*API).handleGetUserPreferences
      github.com/mattermost/focalboard/server/api/users.go:392
  github.com/mattermost/focalboard/server/api.(*API).attachSession.func1
      github.com/mattermost/focalboard/server/api/auth.go:369
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1
      github.com/mattermost/focalboard/server/api/api.go:147
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).panicHandler.func1
      github.com/mattermost/focalboard/server/api/api.go:135
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/gorilla/mux.(*Router).ServeHTTP
      github.com/gorilla/mux@v1.8.0/mux.go:210
  github.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226
  main.(*Plugin).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110
  github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP
      github.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453
  reflect.Value.call
      reflect/value.go:584
  reflect.Value.Call
      reflect/value.go:368
  net/rpc.(*service).call
      net/rpc/server.go:382
  runtime.goexit
      runtime/asm_amd64.s:1594
      
      
      error [2023-06-16 09:49:18.148 +05:00] access denied to team 
  github.com/mattermost/focalboard/server/api.(*API).errorResponse
      github.com/mattermost/focalboard/server/api/api.go:183
  github.com/mattermost/focalboard/server/api.(*API).handleGetTeam
      github.com/mattermost/focalboard/server/api/teams.go:97
  github.com/mattermost/focalboard/server/api.(*API).attachSession.func1
      github.com/mattermost/focalboard/server/api/auth.go:369
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1
      github.com/mattermost/focalboard/server/api/api.go:147
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).panicHandler.func1
      github.com/mattermost/focalboard/server/api/api.go:135
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/gorilla/mux.(*Router).ServeHTTP
      github.com/gorilla/mux@v1.8.0/mux.go:210
  github.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226
  main.(*Plugin).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110
  github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP
      github.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453
  reflect.Value.call
      reflect/value.go:584
  reflect.Value.Call
      reflect/value.go:368
  net/rpc.(*service).call
      net/rpc/server.go:382
  runtime.goexit
      runtime/asm_amd64.s:1594
      
      
      error [2023-06-16 09:49:18.155 +05:00] EOF 
  github.com/mattermost/focalboard/server/api.(*API).errorResponse
      github.com/mattermost/focalboard/server/api/api.go:183
  github.com/mattermost/focalboard/server/api.(*API).handleGetTeams
      github.com/mattermost/focalboard/server/api/teams.go:49
  github.com/mattermost/focalboard/server/api.(*API).attachSession.func1
      github.com/mattermost/focalboard/server/api/auth.go:369
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1
      github.com/mattermost/focalboard/server/api/api.go:147
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).panicHandler.func1
      github.com/mattermost/focalboard/server/api/api.go:135
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/gorilla/mux.(*Router).ServeHTTP
      github.com/gorilla/mux@v1.8.0/mux.go:210
  github.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226
  main.(*Plugin).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110
  github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP
      github.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453
  reflect.Value.call
      reflect/value.go:584
  reflect.Value.Call
      reflect/value.go:368
  net/rpc.(*service).call
      net/rpc/server.go:382
  runtime.goexit
      runtime/asm_amd64.s:1594

error [2023-06-16 09:49:18.155 +05:00] API ERROR code=500 error=EOF api=/api/v2/teams
  github.com/mattermost/focalboard/server/api.(*API).errorResponse
      github.com/mattermost/focalboard/server/api/api.go:200
  github.com/mattermost/focalboard/server/api.(*API).handleGetTeams
      github.com/mattermost/focalboard/server/api/teams.go:49
  github.com/mattermost/focalboard/server/api.(*API).attachSession.func1
      github.com/mattermost/focalboard/server/api/auth.go:369
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1
      github.com/mattermost/focalboard/server/api/api.go:147
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).panicHandler.func1
      github.com/mattermost/focalboard/server/api/api.go:135
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/gorilla/mux.(*Router).ServeHTTP
      github.com/gorilla/mux@v1.8.0/mux.go:210
  github.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226
  main.(*Plugin).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110
  github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP
      github.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453
  reflect.Value.call
      reflect/value.go:584
  reflect.Value.Call
      reflect/value.go:368
  net/rpc.(*service).call
      net/rpc/server.go:382
  runtime.goexit
      runtime/asm_amd64.s:1594

error [2023-06-16 09:49:18.568 +05:00] read tcp 10.32.94.139:51130->10.1.66.1:6432: read: connection reset by peer 
  github.com/mattermost/focalboard/server/api.(*API).errorResponse
      github.com/mattermost/focalboard/server/api/api.go:183
  github.com/mattermost/focalboard/server/api.(*API).handleGetTeams
      github.com/mattermost/focalboard/server/api/teams.go:49
  github.com/mattermost/focalboard/server/api.(*API).attachSession.func1
      github.com/mattermost/focalboard/server/api/auth.go:369
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1
      github.com/mattermost/focalboard/server/api/api.go:147
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).panicHandler.func1
      github.com/mattermost/focalboard/server/api/api.go:135
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/gorilla/mux.(*Router).ServeHTTP
      github.com/gorilla/mux@v1.8.0/mux.go:210
  github.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226
  main.(*Plugin).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110
  github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP
      github.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453
  reflect.Value.call
      reflect/value.go:584
  reflect.Value.Call
      reflect/value.go:368
  net/rpc.(*service).call
      net/rpc/server.go:382
  runtime.goexit
      runtime/asm_amd64.s:1594

error [2023-06-16 09:49:18.568 +05:00] API ERROR code=500 error="read tcp 10.32.94.139:51130->10.1.66.1:6432: read: connection reset by peer" api=/api/v2/teams
  github.com/mattermost/focalboard/server/api.(*API).errorResponse
      github.com/mattermost/focalboard/server/api/api.go:200
  github.com/mattermost/focalboard/server/api.(*API).handleGetTeams
      github.com/mattermost/focalboard/server/api/teams.go:49
  github.com/mattermost/focalboard/server/api.(*API).attachSession.func1
      github.com/mattermost/focalboard/server/api/auth.go:369
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1
      github.com/mattermost/focalboard/server/api/api.go:147
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/mattermost/focalboard/server/api.(*API).panicHandler.func1
      github.com/mattermost/focalboard/server/api/api.go:135
  net/http.HandlerFunc.ServeHTTP
      net/http/server.go:2109
  github.com/gorilla/mux.(*Router).ServeHTTP
      github.com/gorilla/mux@v1.8.0/mux.go:210
  github.com/mattermost/focalboard/mattermost-plugin/server/boards.(*BoardsApp).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/boards/boardsapp.go:226
  main.(*Plugin).ServeHTTP
      github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:110
  github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP
      github.com/mattermost/mattermost-server/v6/plugin/client_rpc.go:453
  reflect.Value.call
      reflect/value.go:584
  reflect.Value.Call
      reflect/value.go:368
  net/rpc.(*service).call
      net/rpc/server.go:382
  runtime.goexit
      runtime/asm_amd64.s:1594

</p>
</details>

**Comment by amyblais** [comment]
Thanks, would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to help troubleshoot this issue.

**Comment by amyblais** [comment]
Ongoing discussion at https://forum.mattermost.com/t/focalboards-errors-and-drop-down-a-service/16235.
