### ISSUE TITLE
The channel input field does not receive focus when navigating from the thread sidebar to the channel

### ISSUE THREAD

**Issue by Nick-Su** [mattermost/mattermost#23772]
#### Summary
The channel input field does not receive focus when navigating from the thread sidebar to the channel.

#### Steps to reproduce
1. Enable collapsed reply threads.
2. Open a channel and open any message thread.
3. Click on "Threads" in the left sidebar.
4. Open a channel or direct message.
5. The input field in the right thread sidebar (from step 2) intercepts the focus.

Note: Subsequent clicks on channels or direct messages behave as expected

#### Expected behavior
I expect the channel and direct message input fields to receive focus when navigating from the thread sidebar.

#### Observed behavior (that appears unintentional) 
The input field in the right thread sidebar takes focus away from the main input field.

**Comment by amyblais** [comment]
Hi @Nick-Su, what Mattermost server version are you on?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53215.

**Comment by Nick-Su** [comment]
Hi @amyblais, it's v7.8.6
