### ISSUE TITLE
403 forbidden when channel member request channel info

### ISSUE THREAD

**Issue by luozhouyang** [mattermost/mattermost#23781]
#### Summary
version: mattermost-team-edition: 7.10.0
3 mattermost pods in a k8s cluster.

I noticed occasional 403 response when requesting channel info as a channel member. This 403 response is not guaranteed to happen.

#### Steps to reproduce

0. A logined user connect mattermost server using websocket
1. Create a team
2. Create a new user
3. Add the new user to the team, and add the logined user to this team as well
4. Create a  new channel
5. Add these two users to the channel
6. The new user send a post to this channel
7. The logined user received a `posted` event, and trying to request channel info with `channel_id`, which is parsed from the `posted` event
8. Then a 403 response is received when request channel info `GET /api/v4/channels/{channel_id}`

What makes me confused is that, the same request to get channel info will success after a few minutes.

#### Expected behavior
Response success instead of 403

#### Observed behavior (that appears unintentional) 
Response 403 accidentally, and sometimes response 200 OK with correct channel information

#### Possible fixes

Is there some async logic when add users to a channel and assign them the neccessary permissions?

**Comment by luozhouyang** [comment]
Update:
* 403 forbidden requests will increment msgcount in table channelmembers

I send 4 posts to channel `jhdtq5kyatdd9rte8m1a5fjx7a`, 3 posts fails(403), the last post posted successfully.

![01](https://github.com/mattermost/mattermost/assets/34032031/c7541bdf-4032-4677-ba7c-cfc6f30c5031)
![02](https://github.com/mattermost/mattermost/assets/34032031/56554793-44bd-454b-aa27-1e6a5d1beac4)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53235.

**Comment by amyblais** [comment]
Closing as there is a Help Wanted issue open for this,
