### ISSUE TITLE
How to log websockets

### ISSUE THREAD

**Issue by luozhouyang** [mattermost/mattermost#23801]
I meet issue when using mattermost websockets. My question is how to log websockets for debugging in mattermost?

**Comment by amyblais** [comment]
Hi @luozhouyang, would you be open to posting this question on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our devs or community members will likely be able to answer this question.

This document might also be helpful https://docs.mattermost.com/install/troubleshooting.html.
