### ISSUE TITLE
[Bug]: Setting a status puts cursor in channel (not the modal)

### ISSUE THREAD

**Issue by brynwhyman** [mattermost/mattermost#23842]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Version

Mattermost Version: 7.8.9
Database Schema Version: 107
Database: postgres

### Operating System

macOS 12.1

### Steps to reproduce

1. Click the profile button, at the top right of app
2. Click 'Set a Custom status'
3. Attempt to write a new status

### Expected behavior

Typing enters text into the 'set a status' textbox

### Observed behavior

The cursor is still set in the channel (not the modal). You are required to re-click the textbox in the modal before typing the status.

### Log Output

```shell
Not relevant, I believe.
```

**Comment by amyblais** [comment]
@brynwhyman What Mattermost server version are you on?

(You can find the server version from Main Menu > About)
![image](https://github.com/mattermost/mattermost/assets/29708087/0bd119af-0b1e-4ce6-adc9-d07241c1ec6f)

**Comment by amyblais** [comment]
> What Mattermost server version are you on? (You can find the server version from Main Menu > About)

@brynwhyman Just following up on this question.

**Comment by brynwhyman** [comment]
Hi sorry for the late reply:

Mattermost Version: 7.8.9
Database Schema Version: 107
Database: postgres

(added to description too)

**Comment by brynwhyman** [comment]
Also, this relates to the MacOS app. 

I can raise another issue for the problem noted in this comment (for the webapp) if you like? https://github.com/mattermost/mattermost/issues/23842#issuecomment-1604319244

> I'll add that I tried to recreate this on the browser version (Chrome, macOS) but I couldn't even click any of the top level buttons on the right-hand side, so not sure what is going on there.

**Comment by amyblais** [comment]
Thank you, looks like this has been fixed in the latest ESR (v8.1.0). Are you open to upgrading in the near-term?

**Comment by brynwhyman** [comment]
If this is fixed in a later version I'm happy for the issue to be closed - just wanted to flag it in the first place :)
