### ISSUE TITLE
Dragging an email from Outlook to MM results in an error

### ISSUE THREAD

**Issue by zpersichetti12** [mattermost/mattermost#23843]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Dragging an email from Outlook to MM results in an error "Folders cannot be uploaded. Please drag all files separately."

#### Steps to reproduce
Drag a single email from Outlook to MM like you want to attach it

#### Expected behavior
Attaches the msg file.

#### Observed behavior (that appears unintentional) 
Outputs "Folders cannot be uploaded. Please drag all files separately."
Dragging to desktop (or wherever) then to MM functions properly. 

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Hi @zpersichetti12, what Mattermost server version are you on? What OS and version are you on?

**Comment by zpersichetti12** [comment]
> Hi @zpersichetti12, what Mattermost server version are you on? What OS and version are you on?

Server:  7.8.1

Win11, desktop app 5.3.1. Also happens in browser.

**Comment by amyblais** [comment]
I realized we have an existing ticket here https://mattermost.atlassian.net/browse/MM-36351.

**Comment by zpersichetti12** [comment]
> I realized we have an existing ticket here https://mattermost.atlassian.net/browse/MM-36351.

Oh that's quite an an old ticket :/
