### ISSUE TITLE
`override_icon_url` prop not respected for reply summary

### ISSUE THREAD

**Issue by svenssonaxel** [mattermost/mattermost#23916]
#### Summary
When the `override_icon_url` prop is set for replies in a thread, this affects the profile icon of the reply itself, but not the miniature icons in the channel under the thread parent.

#### Steps to reproduce
Use any method of your choice to create messages that has the `override_icon_url` prop set, but that leaves the user intact. Create replies to a message using that method.

#### Expected behavior
The chosen icon URL is used as profile icon for the replies in the thread. In the channel, under the parent message, a short summary of the replies is shown, with miniature profile pictures and the number of replies. The chosen icon URL is used to select what miniature profile pictures to show there, so that they match the messages in the thread.

#### Observed behavior (that appears unintentional) 
The default profile picture for the user is shown as miniature in the channel.

**Comment by svenssonaxel** [comment]
This affects at least
* The web app in Mattermost Enterprise Edition version 7.1.5
* Android app version 2.5.1 (Build 6000476)

**Comment by amyblais** [comment]
Closing for now - this can be re-opened if this still reproduces on a supported server version,
