### ISSUE TITLE
Double command response

### ISSUE THREAD

**Issue by svenssonaxel** [mattermost/mattermost#23955]
#### Summary
Command responses and other ephemeral messages sent as response to a command in a thread, appear both in the thread and the channel.

#### Steps to reproduce
* Open a thread
* Type `/online` and hit Enter

#### Expected behavior
The ephemeral response message appears in the thread

#### Observed behavior (that appears unintentional) 
The ephemeral response message also appears in the channel

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53506.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this,
