### ISSUE TITLE
Unexpectedly fire the handleEnterKeyPress in NewChannelModal with Japanese IME input mode

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost#23967]
#### Summary

In NewChannelModal, while typing channel name with Japanese character, unexpectedly fire "Create channel".

https://github.com/mattermost/mattermost/assets/1453749/30ab11a1-d9fd-46a7-b795-ee4a515a3513

In the above movie, I pressed Enter with intend to determine the input, but creating channel is fired. If I press Enter twice, the behavior in the above movie is correct (the first is to determine, and the second is to create a channel).

#### Steps to reproduce
1. Open NewChannelModal
2. Type some alphanumeric in "Channel name" (to avoid the following problem)
    * if "Channel name" is filled by only Japanese character, channel url is automatically filled with invalid url (I don't know why this happens, but this behavior is out of scope for this issue)
    * <img width="590" alt="image" src="https://github.com/mattermost/mattermost/assets/1453749/c7ac0bde-5f1a-4f8e-b2d7-c3bfc37f5554">
4. Switch input mode to Japanese IME
5. Type some word (e.g.: channel name = "aaaあいう")
6. Type Enter (to determine the input)

#### Expected behavior
Determined the input, but don't fire "Create channel"

#### Observed behavior (that appears unintentional) 
"Create channel" is done unexpectedly.

#### Possible fixes
In channel purpose area, avoid firing the handleEnterKeyPress, but does not in channel name are.
https://github.com/mattermost/mattermost/blob/master/webapp/channels/src/components/new_channel_modal/new_channel_modal.tsx#L273

Similar issue is #20838

**Comment by amyblais** [comment]
Hi @kaakaa What Mattermost server version are you on? Or did you see this on master?

**Comment by kaakaa** [comment]
Ah, sorry. I'm using v8.0.0-rc1.

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-53521.

**Comment by johndavidlugtu** [comment]
Hi @kaakaa , thanks for opening this Github issue.

> In the above movie, I pressed Enter with intend to determine the input, but creating channel is fired. If I press Enter twice, the behavior in the above movie is correct (the first is to determine, and the second is to create a channel).

Pressing `Enter` while in the Channel Name field is designed to create a channel. 

To determine / validate whether the set channel name is valid, one should switch focus away from the field by using the `Tab` key or by mousing over and clicking away from the Channel Name field.

Hope this clarifies things!

**Comment by kaakaa** [comment]
Thanks @johndavidlugtu .

> Pressing Enter while in the Channel Name field is designed to create a channel.

This design would make most Japanese (and maybe CJK) users confusing, because Japanese users press the Enter key not to confirm the content of a dialog, but to confirm the word they are typing. The problem is due to the peculiarities of Japanese input method, but I do not think many Japanese users will tolerate this behavior. (I am not familiar with other languages, but I think at least Chinese users would feel the same)

> To determine / validate whether the set channel name is valid, one should switch focus away from the field by using the Tab key or by mousing over and clicking away from the Channel Name field.

Switching focus away from the field is one of the workarounds, but It continues to be a major problem that just pressing `Enter` key confirms the contents of the dialog. `Tab` key, like the `Enter` key, is a special key in Japanese input situations, so it is difficult to workaround.

[Japanese input method \- Wikipedia](https://en.wikipedia.org/wiki/Japanese_input_method)
`Kana to kanji conversion` section in the above page may be helpful in explaining the Japanese input method. I think Japanese people press the `Enter` key more than people imagine.

**Comment by kaakaa** [comment]
This issue seems to be fixed in v8.1.0. I expect that the fix was introduced by #23839 that address the issue related to `Enter` key of Korean's IME. #23839 added some changes to `GenericModal`, and it might have good effect to `NewChannelModal` because `GenericModal` is also used for `NewChannelModal`.

I'll close this issue, and thank you for your continuous effort @johndavidlugtu.
