### ISSUE TITLE
Websocket failed after upgrading from 7.9 to 8.0

### ISSUE THREAD

**Issue by fengwang** [mattermost/mattermost#23976]
#### Summary
Masttermost pops up such error `Error: Please check connection, Mattermost unreachable. If issue persists, ask administrator to check WebSocket port` after upgrade

#### Steps to reproduce
1. Clone docker/docker-compose files from https://github.com/mattermost/docker
2. Create `.env` file based on `env.example`, updating `MATTERMOST_IMAGE_TAG=release-7.9 ` option. Other options get updated accordingly to custom environment.
3. Bring up docker containers with command `docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d`. Everything works well since April.
4. Update image tag to `MATTERMOST_IMAGE_TAG=release-8.0` in the `.env` file, and then execute `docker-compose down && docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d`.
5. Login to Mattermost in the web UI, and found error message popped up.

#### Expected behavior
Expect consistent behavior from 7.9 to 8.0.

#### Observed behavior (that appears unintentional) 

I encountered this problem also in 7.10. Seems this problem starting from 7.10.

#### Possible fixes
No Idea.

#### Attached file

This log file is exported from developer option from my Chromium browser (13.0.5672.126) with 8.0 server.

[mattermost.local-1688895490105.log](https://github.com/mattermost/mattermost/files/11994912/mattermost.local-1688895490105.log)

**Comment by amyblais** [comment]
Hi @fengwang , did you also read the important upgrade notes while upgrading https://docs.mattermost.com/upgrade/important-upgrade-notes.html? One of the notes mentions about setting the ``AllowCorsFrom`` to "*" in mattermost/config/config.json.

**Comment by fengwang** [comment]
Hi @amyblais, this problem has gone after updating `AllowCorsFrom` option from `` to `"*"` in the configuration file `app/mattermost/config/config.json`. Many thanks.
