### ISSUE TITLE
Gyfcat service being discontinued September 1st 2023

### ISSUE THREAD

**Issue by papodaca** [mattermost/mattermost#23984]
#### Summary
Per [gyfcat.com](https://gfycat.com/) the Gyfcat service will be discontinued September 1, an alternate integration should be implemented.

> The Gfycat service is being discontinued. Please save or delete your Gfycat content by visiting https://www.gfycat.com and logging in to your account. After September 1, 2023, all Gfycat content and data will be deleted from gfycat.com

#### Steps to reproduce
N/A

#### Expected behavior
N/A

#### Observed behavior (that appears unintentional) 
N/A

#### Possible fixes
1. An alternate integration is implemented to replace the gyfcat integration.
    * [tenor.com](https://tenor.com/gifapi)
    * [GIPHY](https://developers.giphy.com/docs/api/)
2. The Gyfcat integration is deprecated and removed.

**Comment by amyblais** [comment]
New ticket: https://mattermost.atlassian.net/browse/MM-53842.

**Comment by amyblais** [comment]
v7.8.10, v8.0.2, and v8.1.1 releases include a fix for this (and the upcoming v9.0.0 release).
