### ISSUE TITLE
Multi-line channel header preview is narrow on web

### ISSUE THREAD

**Issue by chenilim** [mattermost/mattermost#23990]
#### Summary
The hover preview of a multi-line channel header is narrow.

#### Steps to reproduce
1. Edit a channel's header (using Chrome on macOS)
2. Enter multiline markdown, e.g.:

```
# Channel header
* First thing
* Second thing
* Third thing
```
3. Save it
4. Hover over to preview

#### Expected behavior
The text is shown at full width

#### Observed behavior (that appears unintentional) 
The text is wrapped to a narrow view
<img width="158" alt="Screenshot 2023-07-10 at 1 51 53 PM" src="https://github.com/mattermost/mattermost/assets/46905241/7a9a1767-7626-4513-965f-7be7abf55b05">

**Comment by amyblais** [comment]
@chenilim Can you help open a Jira ticket for this? Instructions here if needed: https://handbook.mattermost.com/operations/research-and-development/product/development-process/new-bug-tickets.

**Comment by chenilim** [comment]
Created a Jira ticket here: https://mattermost.atlassian.net/browse/MM-53564, thanks Amy.
