### ISSUE TITLE
MM_EXPERIMENTALSETTINGS_USERSTATUSAWAYTIMEOUT does not seem to work

### ISSUE THREAD

**Issue by vraisa-coinmotion** [mattermost/mattermost#24000]
#### Summary
We have setup experimental option to mattermost-value.yaml 
```
    - name: MM_EXPERIMENTALSETTINGS_USERSTATUSAWAYTIMEOUT
      value: "900"
```
But the  user status away timeout is still default 300 seconds.

#### Steps to reproduce
Deploy to Kubernetes with Helm chart and edit config.

Mattermost Version: 7.10.3

#### Expected behavior
Value should change to 300 seconds in the system console.

#### Observed behavior (that appears unintentional) 
Value keeps at 300 seconds in the system console.

#### Possible fixes
No idea. Is this implemented?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53621.

**Comment by amyblais** [comment]
A comment was added to the ticket by a dev:

UserStatusAwayTimeout is part of [TeamSettings](https://github.com/mattermost/mattermost/blob/master/server/public/model/config.go#L2041).
You can use ``MM_TEAMSETTINGS_USERSTATUSAWAYTIMEOUT`` instead.

**Comment by vraisa-coinmotion** [comment]
no effect. 

![Screenshot 2023-07-13 at 10 45 15](https://github.com/mattermost/mattermost/assets/1743396/52eb69a8-db57-4dee-9bae-a2a847aca9cc)
![Screenshot 2023-07-13 at 10 45 27](https://github.com/mattermost/mattermost/assets/1743396/968c684b-1c6c-4e59-b11a-f96130c76aa0)

**Comment by agnivade** [comment]
@gabrieljackson - Do you have any thoughts on this helm chart issue?

**Comment by gabrieljackson** [comment]
@vraisa-coinmotion just checking in if this is still an issue for you?

The helm chart doesn't have any special logic that would alter environment variables and how they are applied as configuration overrides in Mattermost. Let me know if you are still troubleshooting this.

**Comment by vraisa-coinmotion** [comment]
This seems to be working now. We have upgraded from Mattermost server 7.x to 9.x so I think that solved this issue.
