### ISSUE TITLE
[Bug]: Unable to browse/add reactions on macOS 

### ISSUE THREAD

**Issue by rymagee** [mattermost/mattermost#24013]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0

### Operating System

macOS Venture 13.2.1  Apple Silicon

### Mattermost Server Version

5.4.0

### Steps to reproduce

If I click the drop-down menu inside the app, clicking "add a reaction" results in a pop-up menu that instantly disappears as soon as I release the mouse. The offending option:

![image](https://github.com/mattermost/desktop/assets/24324897/70f925f6-16b8-4922-8f1b-2982574d88ec)

This makes it impossible to add any reactions unless I double click very quickly (and am ok with a random emote). I have reinstalled the application and cleared the cache, but to no avail. I can add reactions if someone else has already reacted by clicking this button:

![image](https://github.com/mattermost/desktop/assets/24324897/3f8555f8-1988-4481-a7e7-9599a1c010bc)

### Expected behavior

I expect to be able to click "add a reaction" and browse the existing reactions.

### Observed behavior

The ability to browse reactions disappears when I release the mouse.

### Log Output

```shell
This is the log output from today:

[2023-07-12 11:25:24.373] [debug] [DownloadsManager] init { 'this.json': {}, validatedJSON: {} }
[2023-07-12 11:25:24.378] [debug] [DownloadsManager] saveAll
[2023-07-12 11:25:24.378] [debug] [MainWindow] Can't send update-downloads-dropdown, will retry
[2023-07-12 11:25:24.379] [debug] [DownloadsManager] checkForDeletedFiles
[2023-07-12 11:25:24.398] [error] Logger Log level set to: info
[2023-07-12 11:25:24.406] [warn]  [App.Initialize] Current working directory is /Users/ryan/Library/Containers/Mattermost.Desktop/Data, changing into /Applications/Mattermost.app/Contents/MacOS
[2023-07-12 11:25:24.466] [info]  [App.Initialize] Autoupgrade disabled: false
[2023-07-12 11:25:24.495] [info]  [ServerDropdownView] init
[2023-07-12 11:25:24.498] [warn]  [i18nManager] Failed to set new language en-US
[2023-07-12 11:25:24.498] [warn]  [i18nManager] Failed to set new language JP
```
```


### Additional Information

_No response_

**Comment by amyblais** [comment]
@rymagee Does this only happen on desktop app or does it also happen on webapp? Are the logs that you shared from the developer console?

**Comment by rymagee** [comment]
@amyblais this only happens on the desktop app. The webapp and mobile app both work correctly for me. I think I sent the wrong logs over before. This is the end of the output for the console associated with `Developer Tools for Current Server`. If there's some other snippet that's useful, please let me know.


```
calboard_e39c6fc379c85ab9_bundle.js:2 [1689270383.55] Polling websockets connection for state: undefined
logWarn @ focalboard_e39c6fc379c85ab9_bundle.js:2
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270384.06] Polling websockets connection for state: undefined
logWarn @ focalboard_e39c6fc379c85ab9_bundle.js:2
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270384.55] Polling websockets connection for state: undefined
logWarn @ focalboard_e39c6fc379c85ab9_bundle.js:2
websocket.js:75 websocket re-established connection
websocket_actions.jsx:209 Reconnecting WebSocket
com.mattermost.calls_f6c4e25cc808765f_bundle.js:2 com.mattermost.calls: websocket reconnect handler
com.mattermost.calls_f6c4e25cc808765f_bundle.js:2 com.mattermost.calls: resetting state
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.14] WSClient reconnected
logWarn @ focalboard_e39c6fc379c85ab9_bundle.js:2
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.14] WSClient in plugin mode, reusing Mattermost WS connection
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.14] Sending commands for the registered subscriptions
websocket.js:136 got connection id  bc1418ktm7fpfdcyjjfncpp6so
websocket.js:141 long timeout, or server restart, or sequence number is not found.
websocket_actions.jsx:209 Reconnecting WebSocket
com.mattermost.calls_f6c4e25cc808765f_bundle.js:2 com.mattermost.calls: websocket reconnect handler
com.mattermost.calls_f6c4e25cc808765f_bundle.js:2 com.mattermost.calls: resetting state
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.21] Polling websockets connection for state: 1
logWarn @ focalboard_e39c6fc379c85ab9_bundle.js:2
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.21] WSClient reconnected
logWarn @ focalboard_e39c6fc379c85ab9_bundle.js:2
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.21] WSClient in plugin mode, reusing Mattermost WS connection
focalboard_e39c6fc379c85ab9_bundle.js:2 [1689270385.21] Sending commands for the registered subscriptions
```

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-53682.

**Comment by devinbinnie** [comment]
I'm still unable to reproduce this on community, nor on ESR v7.8.9. This might be an issue with your Desktop App. Have you tried doing a "Clear Cache and Hard Reload? (`Cmd/Ctrl+Shift+R`). If that doesn't work, can you try reinstalling your Desktop App?

**Comment by rymagee** [comment]
Thank, @devinbinnie . I've just done a hard reload/cache clear as well as a reinstall of the app. Unfortunately, the problem persists. I have one new observation; this appears to happen only when the app is snapped to half of the screen. When full screen, there is no issue. This may suggest the problem is elsewhere.

**Comment by devinbinnie** [comment]
@rymagee Can you try running against the community server? https://community.mattermost.com

**Comment by rymagee** [comment]
Thanks @devinbinnie . I can verify that this issue does not appear for me on the community server.

**Comment by devinbinnie** [comment]
Okay this is likely an issue specific to your server then, or your server version. Which version of the server are you on?

**Comment by skymoo** [comment]
The version thats provided with GitLab Omnibus 16.2.x, looks like 7.10.4.
