### ISSUE TITLE
Unexpected system-bot management transitions following admin user deletion

### ISSUE THREAD

**Issue by ShiroDN** [mattermost/mattermost#24026]
#### Summary
After installing a new Mattermost server and creating the first admin user, let's call this user "tomas", the system-bot is automatically created after a few minutes. However, it's stated as being "Managed by tomas". Could this possibly be a bug? Upon the creation of another admin user "tomas2" and the deletion of the previous admin user "tomas" via mmctl, the system-bot is now in a disabled state. Upon reenabling it, the system-bot is now "Managed by plugin". You can observe all three states in the attached screenshots.

Just to confirm, the "appsbot" should have options like "Create New Token", "Edit", and "Disable", correct?

#### Steps to reproduce
1. Perform a new installation of Mattermost. I have tested versions 7.8.8 and 7.10.4.
2. Create the first admin user.
3. Wait for the system-bot to appear; it will be "Managed by the admin user".
4. Create another admin user.
5. Delete the first admin user.
6. Reenable the system-bot.
7. The system-bot is now "Managed by plugin".

#### Expected behavior
I am uncertain about the correct state.

<img src="https://github.com/mattermost/mattermost/assets/36225991/e2dca4c7-f508-40dc-8035-9f01a208e46e" width="200">

<img src="https://github.com/mattermost/mattermost/assets/36225991/1c6f8e03-b519-4a9b-807c-3c7d9cf900a5" width="200">

<img src="https://github.com/mattermost/mattermost/assets/36225991/216076f9-2fb2-48ba-b390-242af739f9d8" width="200">

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53663.

**Comment by ShiroDN** [comment]
This behavior seems to be implemented by the commit https://github.com/mattermost/mattermost/commit/72c86448b94f29aa17dd4a3ea56b18d38a45cb42, and there is explicit code that sets the owner on line https://github.com/mattermost/mattermost/blob/master/server/channels/app/bot.go#L204 which specifically selects admin user: `OwnerId: sysAdminList[0].Id`.

So, I think this needs to be fixed for situations like these when the first admin is deleted.

**Comment by amyblais** [comment]
Thanks for the report, the ticket was closed by the product managers as "won't fix" given this has low impact and seems that it doesn't have any negative functional consequences. Please let us know if this is not the case.
