### ISSUE TITLE
[Bug] Update channel info brokes channel list

### ISSUE THREAD

**Issue by BigMakCode** [mattermost/mattermost#24023]
#### Summary
When [API request]({{baseUrl}}/api/v4/channels/:channel_id) updates channel info for private conversation, channel is showing as empty row and not selectable

#### Steps to reproduce
Create private conversation
Update any info by endpoint PUT {{baseUrl}}/api/v4/channels/:channel_id
Conversation is broken

#### Expected behavior
1. Server says '400 Bad Request'
or 
2. Channel (Private conversation) info was updated

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/81349914/6ffd8c23-1a06-4b71-aa3e-4619d0df1837)

#### Possible fixes
Reload application, reload server

Current version is 8.0.0 (master/Tue Jul 11 13:17:40 UTC 2023) (Docker mattermost/mattermost-enterprise-edition:master)

**Comment by amyblais** [comment]
@lindy65 @yasserfaraazkhan Is this something you'd be able to help test to see if you can reproduce it?

**Comment by yasserfaraazkhan** [comment]
Hi @BigMakCode ,
I tried using api to update the info, I couldn't replicate it.
can you also share browser you used?

https://github.com/mattermost/mattermost/assets/15979783/62cb0676-b13d-423a-b820-ab318a6e2e21

cc: @amyblais

**Comment by BigMakCode** [comment]
@amyblais 

OS Windows 11 Pro 22H2 22621.1992
Browser Version Chrome 111.0.5563.64 (Official Build) (64-bit)
Server version 8.0.0 (master/Tue Jul 11 13:17:40 UTC 2023) (Docker mattermost/mattermost-enterprise-edition:master)

1. Write direct message to bot account, the conversation added on the left panel
![image](https://github.com/mattermost/mattermost/assets/81349914/03f2c85b-4b12-45de-8fa9-27d96055925f)

2. Receive new message event on websocket which contains channel id
3. Send PUT request via Postman to update channel info by channel id
![image](https://github.com/mattermost/mattermost/assets/81349914/e55a1567-ed6c-4731-b92d-ffa3da8c5de1)

4. Chat will be unavailable and empty row in list
![image](https://github.com/mattermost/mattermost/assets/81349914/fa38e99b-f01c-408a-801c-24bd431d4a9d)

![image](https://github.com/mattermost/mattermost/assets/81349914/d046870c-5785-4fc8-ac52-27d1e10134ef)

**Comment by amyblais** [comment]
cc @yasserfaraazkhan on the above additional info ^

**Comment by yasserfaraazkhan** [comment]
got it , I'll try it on windows

**Comment by yasserfaraazkhan** [comment]
@BigMakCode ,
can you try the same on latest chrome  v114? 
I tried it on windows chrome, didn't see it occurring, only difference is chrome version. Please let me know if this is occurring on latest chrome version. 

<img width="741" alt="Screenshot 2023-07-14 at 2 39 25 AM" src="https://github.com/mattermost/mattermost/assets/15979783/4fabe33e-ceb4-48db-b259-d86d7a81eb46">

**Comment by BigMakCode** [comment]
Okay but I just want to say that Web UI is cross platform, and my server
hosted with Docker image on Ubuntu server, I wrote about Windows because my
client OS is Windows but mattermost server hosted on Linux (official Docker
image)
Thank you

**Comment by lindy65** [comment]
Thanks for looking into this @yasserfaraazkhan 👍

**Comment by BigMakCode** [comment]
I updated my Chrome to Version 114.0.5735.199 (Official Build) (64-bit)
Now the behavior is unpredictable

https://github.com/mattermost/mattermost/assets/81349914/1e678020-8021-49d4-9faa-d18d9fcdd7e1


https://github.com/mattermost/mattermost/assets/81349914/37880c20-e539-4d9a-9956-235c80660a66


cc @lindy65 @yasserfaraazkhan @amyblais

**Comment by BigMakCode** [comment]
I also found that the server doesn't allow the channel name to be updated if the text length of the new name doesn't match something. But when I increase the length of the name, the server quietly resolves the request, and the channel becomes invisible and inaccessible. A new direct message channel is being created and old conversation is broken.
I'm assuming that updating the channel information should not be available at all, since it's technically a channel, but in fact it's a direct message.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53687 to investigate further.
