### ISSUE TITLE
[Bug] Empty draft error

### ISSUE THREAD

**Issue by BigMakCode** [mattermost/mattermost#24022]
#### Summary
Draft was created and not removing when message is removed

#### Steps to reproduce

1. Create post
2. Start writing message in thread by this post
3. Draft created
4. Delete this post
5. Draft exists - showing empty drafts but draft icon show (1)

#### Expected behavior
Draft removed with post

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/81349914/8fa30f4d-9c0a-44f0-857a-2e6b36c07738)

#### Possible fixes
Restart server, restart application, clear cache

Current version is 8.0.0 (master/Tue Jul 11 13:17:40 UTC 2023) (Docker mattermost/mattermost-enterprise-edition:master)

**Comment by amyblais** [comment]
@BigMakCode In Step 4 (Delete this post), are you referring to the parent post or the reply post?

**Comment by amyblais** [comment]
We did fix this bug in v8.0: https://mattermost.atlassian.net/browse/MM-52797. What OS and version are you on?

**Comment by amyblais** [comment]
We have an existing ticket here https://mattermost.atlassian.net/browse/MM-53520.

**Comment by BigMakCode** [comment]
@amyblais Okay, thank you very much, I will close as duplicate.

**Comment by BigMakCode** [comment]
Re-login fixes this error

**Comment by mhvelplund** [comment]
> Re-login fixes this error

Not for me.

**Comment by mhvelplund** [comment]
> We did fix this bug in v8.0: https://mattermost.atlassian.net/browse/MM-52797. What OS and version are you on?

@amyblais The bug is still present in Mattermost Version: 9.3.0, Build Number: 7014621505 :(

**Comment by amyblais** [comment]
> The bug is again/still present in Mattermost Version: 9.3.0, Build Number: 7014621505 :(

Feel free to open a new issue with reproduction steps and your environment details.

**Comment by mhvelplund** [comment]
Unfortunately, I didn't notice immediately, so I don't know how to reproduce it. The problem persists though on PC, across browsers on different machines. The problem doesn't appear on the mobile Android version.
