### ISSUE TITLE
Open redirect via state parameter at [signup/gitlab/complete] endpoint

### ISSUE THREAD

**Issue by hecvs17** [mattermost/mattermost#24048]
#### Summary
I found that state parameter at `https://<url>/signup/gitlab/complete` is vulnerable to open redirect, which may lead to redirect users to unsafe websites.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
1. Modify the `redirect_to` field in the state parameter {"action":"mobile","isMobile":"true","redirect_to":"https://google.com","token":"abcxyz"}
2. Base64 encode the state parameter
3. Visit the following url: `https://<url>/signup/gitlab/complete?code=1e9784fd44xxxxxx&state=eyJhY3Rpb24iOiJtb2JpbGUiLCJpc01vYmlsZSI6InRydWUiLCJyZWRpcmVjdF90byI6Imh0dHA6Ly9nb29nbGUuY29tIiwidG9rZW4iOiJhYXppMTZ6dzR4NHl5In0%3d`
4. Click on `Back to Mattermost` and you will be redirected to google.com

#### Expected behavior
`redirect_to` field should be validated so it cant redirect to malicious sites.

#### Possible fixes
Validate `redirect_to` that you will redirect to valid site/deeplinks in case of mobile apps

**Comment by amyblais** [comment]
@hecvs17 Would you be open to reporting this via responsibledisclosure@mattermost.com? Please see for more details: https://mattermost.com/security-vulnerability-report/.

**Comment by hecvs17** [comment]
@amyblais OK

**Comment by amyblais** [comment]
@DSchalla Does this issue need to be deleted or made internal?
