### ISSUE TITLE
"Team not found" error occurs on attempt to follow the link to the message in chat

### ISSUE THREAD

**Issue by AlexandraChistyakova** [mattermost/mattermost#24066]
#### Summary
"Team not found" error occurs on attempt to follow the link to the message in chat

#### Steps to reproduce
Mattermost Version: 7.10.0-16765
Database Schema Version: 105
Database: postgres

- Create a chat with a person NameOfThePerson
- Send a message to the chat
- Choose the team NameOfThePerson has no access to
- Copy link to the message in the chat via "Copy Link" menu
- Send the copied link to the same chat

#### Expected behavior
Clicking on the link to the message works correctly for the person NameOfThePerson - they are redirected to the message

#### Observed behavior (that appears unintentional) 
Clicking on the link to the message works _incorrectly_ for the person NameOfThePerson: error occurs
"Team Not Found. The team you're requesting is private or does not exist. Please contact your Administrator for an invitation."

![image](https://github.com/mattermost/mattermost/assets/139977901/d6c5ac86-c8c6-4515-a3df-eaa5a4550290)

**Comment by amyblais** [comment]
@devinbinnie @M-ZubairAhmed Would you know if this a bug or expected behaviour?

**Comment by amyblais** [comment]
Opened a ticket here for review https://mattermost.atlassian.net/browse/MM-53755.

**Comment by amyblais** [comment]
Closing for now as we haven't been able to reproduce/prioritize this.
