### ISSUE TITLE
prepackaged_plugins directory empty in ARM releases (no playbooks, boards etc)

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/mattermost#24100]
When downloading for x86, eg https://releases.mattermost.com/8.0.0/mattermost-8.0.0-linux-amd64.tar.gz , the prepackaged plugins are available.

However, when I download an ARM build from https://releases.mattermost.com/8.0.0/mattermost-8.0.0-linux-arm64.tar.gz , they are not present.

I can see the makefile downloads prepackaged plugins from URLs such as https://plugins-store.test.mattermost.com/release/mattermost-plugin-playbooks-v1.37.0-linux-amd64.tar.gz (however the equivalent arm64 URL returns a 404).

This results in a mattermost install which is generally functional, but lacks any playbook features.

I've tracked this as far as https://github.com/mattermost/mattermost/blob/master/server/build/release.mk#L169C1-L169C73 which indicates it's not implemented at present (which is unfortunate - linux ARM servers being so much cheaper to run).

https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/Makefile indicates that the playbooks plugin is being built for arm64 (and JIRA ticket MM-39928 indicates it has been built for nearly two years!).

It appears that virtually all of the work to support ARM linux has been done, but the final stretch of adjusting release scripts to include the compiled binaries has been neglected (apparently for over a year).

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53781.

**Comment by amyblais** [comment]
Closing for now as our team is not planning to work on this for now. Feel free to share this as a feature request at https://mattermost.uservoice.com/forums/306457-general.
