### ISSUE TITLE
Following links do not position correctly in threads

### ISSUE THREAD

**Issue by tbc** [mattermost/mattermost#24109]
#### Summary
This issue only affects web and desktop apps. The mobile app works as expected.

#### Steps to reproduce
1. Create a post that links to a message in a thread
1. Follow the link and notice how the message is highlighted briefly, then you are positioned to the newest message in the thread
1. Scroll up and notice how the message is highlighted only briefly.

##### Versions
Desktop app 5.4.0 commit: 420c63d
Browser app Mattermost Enterprise Edition Version: 7.9.1
Database Schema Version: 104
Database: postgres

#### Expected behavior
The mobile app works as expected. When I follow such a link there, I am shown the message I expect.

**Comment by amyblais** [comment]
Hi @tbc! You can find the server version from Main Menu > About. Let me know here once you've been able to find the version.

![image](https://github.com/mattermost/mattermost/assets/29708087/0bd119af-0b1e-4ce6-adc9-d07241c1ec6f)

**Comment by tbc** [comment]
Found it, I appreciate you @amyblais!
Browser app Version: 7.9.1
Database Schema Version: 104
Database: postgres

**Comment by amyblais** [comment]
Thank you, opened https://mattermost.atlassian.net/browse/MM-53785.

**Comment by tbc** [comment]
Kudos team! I cannot reproduce since we updated to
Mattermost Version: 9.0.0
Database Schema Version: 111
Database: postgres
Build Hash: 987e843629fe3f11861fda23ceb66884f5973ef1
EE Build Hash: d5fcba6ba62b19cd029e6c913b1b65d81d2c89f3

**Comment by kobzarvs** [comment]
The issue is reproducible in version 9.9.
Please do not close the issue without resolving it.
