### ISSUE TITLE
Disable direct messages

### ISSUE THREAD

**Issue by Soufiane1929** [mattermost/mattermost#24138]
Hello, our company is considering whether to start using Mattermost for our internal communications. But as we have very sensitive info to keep private, we would like to know how can we disable direct messages ? 
I know there was a plugin for it some years ago, but apparently it isn't working anymore.

Is there a way to have the same result or if there's another plugin to block all DMs ?

**Comment by amyblais** [comment]
Hi @Soufiane1929, there is one setting that can be used to determine whether a user can open a direct message channel with anyone on the Mattermost server or only to members of the same teamhttps://docs.mattermost.com/configure/site-configuration-settings.html#enable-users-to-open-direct-message-channels-with.

I'm not aware of other options other than the plugin that you mentioned, so feel free to open a feature request on Uservoice here https://mattermost.uservoice.com/forums/306457-general!

**Comment by amyblais** [comment]
Feel free to open a feature request at https://mattermost.uservoice.com/forums/306457-general for tracking,
