### ISSUE TITLE
DB migration fails with newer Docker image mattermost/mattermost-enterprise-edition

### ISSUE THREAD

**Issue by densen45** [mattermost/mattermost#24201]
#### Summary
Using the current master image (d557fb29ea65, referred to Diggest on  [Docker Hub](https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags)) Mattermost does not start anymore due to db error.

#### Steps to reproduce
* Setup Mattermost with the image dd29d550d5c9 and postgres 11.
* Update the image from dd29d550d5c9 to d557fb29ea65.

#### Expected behavior
Mattermost starts without any error.

#### Observed behavior (that appears unintentional) 
Mattermost does not start due to the below error and the container stops.
~~~
Error: failed to initialize platform: cannot create store: failed to apply database migrations: driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: duplicate key value violates unique constraint "db_migrations_pkey", query: 

INSERT INTO db_migrations (version, name) VALUES (110, 'update_vacuuming')

{"timestamp":"2023-08-07 07:39:16.703 +02:00","level":"error","msg":"failed to initialize platform: cannot create store: failed to apply database migrations: driver: postgres, message: failed to execute migration, command: executing_query, originalError: pq: duplicate key value violates unique constraint \"db_migrations_pkey\", query: \n\nINSERT INTO db_migrations (version, name) VALUES (110, 'update_vacuuming')\n","caller":"commands/server.go:76"}
~~~

#### Possible fixes
My DB contains in the table `db_migrations` already a `version` (pkey) `110`. It's `name` is `create_desktop_tokens`.

When I use the new d557fb29ea65 image with a clean DB, this DB does not contain the `create_desktop_tokens`. Everything else in the `db_migrations` table is identical.

Maybe just the ID for the new value that should be inserted `update_vacuuming` is wrong? 
Or is the `create_desktop_tokens` in my DB wrong? If so, where does it come from?

**Comment by agnivade** [comment]
Hey @densen45 - Sorry for the troubles! This is fixed now in master via https://github.com/mattermost/mattermost/commit/555009aa8271a7d1ff61fca84b51256aa3376adc.

**Comment by pippobimbo** [comment]
That works again. Thanks
