### ISSUE TITLE
Mattermost api is not working (React.js, Docker) but working on Postman

### ISSUE THREAD

**Issue by vivekanand999** [mattermost/mattermost#24219]
#### Summary
Hi I tried many different api's but they all are working on postman but not working via React.js application. I'm using docker container for my app. can someone please help me. 

Container Logs from Postman 
`{"timestamp":"2023-08-08 17:13:32.809 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:163","method":"GET","url":"/api/v4/users/6nypg5u1u3r538fx8jepj6ixga","request_id":"dfcb33uhdjb1mjakp9ane154aa","status_code":"200"}`

Container Logs from Axios
{"timestamp":"2023-08-08 17:10:54.778 Z","level":"debug","msg":"not found handler triggered","caller":"web/web.go:63","path":"/6nypg5u1u3r538fx8jepj6ixga","code":404,"ip":"172.17.0.1"}

I'm sending Authorization header also on both cases.

**Comment by vivekanand999** [comment]
![image](https://github.com/mattermost/mattermost/assets/141058060/06a6f6b0-5036-40a8-a684-ece1c781fee8)


Working fine from postman but not from React.js application using axios and fetch.

**Comment by vivekanand999** [comment]
With Axios

`let response = () => {
      return new Promise(function (resolve, reject) {
        axios.get('http://localhost:8065/api/v4/users/6nypg5u1u3r538fx8jepj6ixga',
          {
            headers: {
              Authorization: `Bearer token`,
              "Access-Control-Allow-Origin": "*",
              'Access-Control-Allow-Headers': "*"
            },
          }).then((response: any) => {
            resolve(response);
          }).catch((error: any) => {
            reject(error);
          });
      });
    };
    let responseData: any = await response();
    console.log(responseData.data);`

**Comment by amyblais** [comment]
Hi @vivekanand999, do any of these troubleshooting threads help?
 - https://forum.mattermost.com/t/cannot-connect-to-mattermost-api-v4/9051
 - https://stackoverflow.com/questions/60924212/api-works-in-postman-but-not-in-react-front-end
 - https://stackoverflow.com/questions/67528105/why-i-can-request-to-a-api-with-postman-but-not-working-in-react-js

**Comment by vivekanand999** [comment]
@amyblais I tried this solution but not working..

**Comment by vivekanand999** [comment]
Thanks issue is solved. 

By setting close and passing 

 'Access-Control-Allow-Origin': '*',
 'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,PATCH,OPTIONS',
 
 in header solved my issue.

![image](https://github.com/mattermost/mattermost/assets/141058060/226a3f7f-2b02-441f-a2d7-b0eecce828c4)
