### ISSUE TITLE
Duplicate categories are created if new members are assigned to channels via Welcome Bot plugin and channels are assigned to categories via Channel Actions Trigger

### ISSUE THREAD

**Issue by christianhueserhzdr** [mattermost/mattermost#24240]
#### Summary
The automatic assignment of new team members to channels via the Welcome Bot plugin and the triggered automatic assignment of this channels to the new member's categories via the Channel Actions triggers creates duplicate categories.

#### Steps to reproduce
1. Create Welcome Bot config for a team with automatic assignment to channels.
2. Enter channel actions trigger "Add the channel to a sidebar category for the user" for a couple of channels that assign them to the same new category.
3. New members will be added automatically to channels, while adding those channels to the category results in same categories being created multiple times.

#### Expected behavior
All channels will be assigned to the same category.

#### Observed behavior (that appears unintentional) 
Some channels get there own, separate category with the same name.

#### Possible fixes
I would suggest to resolve this issue of concurrency adequately in Mattermost, since it appears to happen, because of the following assumption:
If this member to channel assignments are not finished when the channel to category assignments start, there will be duplicate categories, because when the check occurs if the category is already present or needs to be created there are several triggered channel to category assignments which all think that no category has yet been created, thus they all create duplicate categories. 

Thank you very much for looking into this issue and for your valuable feedback! :slightly_smiling_face:

**Comment by amyblais** [comment]
Hi @christianhueserhzdr, what Mattermost server version are you currently on?

**Comment by christianhueserhzdr** [comment]
Hi Amy @amyblais, thank you very much for your quick response. It is Mattermost Version 7.10.4.

**Comment by amyblais** [comment]
Thank you! Opened a ticket https://mattermost.atlassian.net/browse/MM-54003.

**Comment by christianhueserhzdr** [comment]
Dear Amy @amyblais, I am wondering, if the Welcome Bot plugin maintainers are not responding so far, is it feasible to look into this issue from the Mattermost Server perspective. Personally I think the solution has to be found here anyway and that might be the reason for the Welcome Bot plugin maintainers not to react to messages, if they are of the same opinion, but that's just an assumption of course. What do you think? Could we re-open this issue here? Daniel wrote in the Jira ticket that this could also be solved on the Channel Actions. I would agree.

**Comment by amyblais** [comment]
Sounds good, I'll re-open the ticket for re-triage.
