### ISSUE TITLE
Add more than one member to a channel

### ISSUE THREAD

**Issue by salbuquerque97** [mattermost/mattermost#24241]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
It is not possible to add more than 1 member for each call of the Mattermost API. It should be possible to send a list of user ids.

**Comment by amyblais** [comment]
Hi @salbuquerque97, what Mattermost server version are you currently on? What are the reproduction steps?

**Comment by salbuquerque97** [comment]
Hello @amyblais 
Currently using the version v4 for Mattermos API calls. When trying to add members to channel by calling:
http://your-mattermost-url.com/api/v4/channels/{channel_id}/members

It only supports 1 member per API call. The userID needs to be a string, a list is not supported. 

Is there any other api endpoint that we can call to optimize this? Thanks

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-54025.

**Comment by salbuquerque97** [comment]
Hello @amyblais 
Thanks for opening the ticket. 

Another topic/issue: 
When using the Mattermost API to run a playbook it creates a **new channel**. Through the UI is possible to attach a run to a already created channel.
