### ISSUE TITLE
mattermost has no connection to MariaDB

### ISSUE THREAD

**Issue by atakan72** [mattermost/mattermost#24267]
I have searched for hours for a solution and have not found one I hope someone can help me.

I am trying to create Mattermost as a container in Portainer I followed the instructions on the official Github page and still I get the error.

![image](https://github.com/mattermost/mattermost/assets/74542485/2dc639ca-0729-4fd2-86ad-ea2c4f696280)
![image](https://github.com/mattermost/mattermost/assets/74542485/752b5e57-0c97-4545-a525-4cae9f2fce16)
![image](https://github.com/mattermost/mattermost/assets/74542485/76c274ac-c46f-487f-ae9e-6549e4f75137)

I have replaced my username and password with ***.

**Comment by amyblais** [comment]
@atakan72 Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or other community members will likely be able to help troubleshoot this issue.

**Comment by amyblais** [comment]
Thank you for opening the Forum issue!
