### ISSUE TITLE
Unable to archive channels after updating to v8.0.1

### ISSUE THREAD

**Issue by Asgaros** [mattermost/mattermost#24274]
#### Summary
After updating Mattermost from v7.10.5 to v8.0.1 we are not longer able to archive channels.

#### Steps to reproduce
- Create or open an existing channel
- Click on its name and click _"Archive Channel"_

#### Expected behavior
The channel should be archived

#### Observed behavior (that appears unintentional) 
The system message _"@user archived the channel."_ appears, but the channel remains open.
![image](https://github.com/mattermost/mattermost/assets/12525671/f1fbbd11-015b-4a20-acad-0b5c502a54e4)

Additionally, the archive channel action triggers the following error in the server logs:
```
{
  "caller": "web/context.go:117",
  "err_where": "DeleteChannel",
  "error": "DeleteChannel: Unable to delete the persistent notifications by channel., failed to delete notifications for channels [1dcpqstuibd4upwo78dt8ypjso]: Error 1267 (HY000): Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='",
  "http_code": 500,
  "ip_addr": "127.0.0.1",
  "level": "error",
  "method": "DELETE",
  "msg": "Unable to delete the persistent notifications by channel.",
  "path": "/api/v4/channels/1dcpqstuibd4upwo78dt8ypjso",
  "request_id": "e6dmyrafqpg7mne44u17kktemh",
  "timestamp": "2023-08-15 09:37:48.895 Z",
  "user_id": "uemz8fi7p3ynpyt919d9ahj6kc"
}
```

#### Installation Details
Mattermost Enterprise Edition (Self-Hosted)
Mattermost Version: 8.0.1
Database Schema Version: 109
Database: mysql

Feature Flags:
```
TestFeature	off
TestBoolFeature	false
EnableRemoteClusterService	false
AppsEnabled	true
PluginPlaybooks	
PluginApps	
PluginFocalboard	
PluginCalls	
PermalinkPreviews	true
CallsEnabled	true
BoardsFeatureFlags	
BoardsDataRetention	false
NormalizeLdapDNs	false
GraphQL	false
InsightsEnabled	false
CommandPalette	false
SendWelcomePost	true
PostPriority	true
WysiwygEditor	false
PeopleProduct	false
ReduceOnBoardingTaskList	false
OnboardingAutoShowLinkedBoard	false
ThreadsEverywhere	false
GlobalDrafts	true
OnboardingTourTips	true
DeprecateCloudFree	false
CloudReverseTrial	false
```

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54134.

**Comment by Fischmuetze** [comment]
Same here in 9.2.2
Got the message " Unable to delete the persistent notifications by channel."

**Comment by Asgaros** [comment]
Hello @Fischmuetze 

I fixed it by myself in the meantime by changing the collation of all tables manually from `utf8mb4_general_ci` to `utf8mb4_unicode_ci`. Best you check your error log regarding which collation it expects. No idea why it got mixed up at some point with different collations.

**Comment by Fischmuetze** [comment]
> changing the collation of all tables manually from `utf8mb4_general_ci` to `utf8mb4_unicode_ci`.
> ... No idea why it got mixed up at some point with different collations.

Thank you! Yes it's strange for me why a wrong collation is applied. I guess this is an effect of some wrong update scripts by Mattermost, since I run former in a similar issue with the collation (in conjunction with using emojis) and fixed that by update the collation for all tables. Obviously I have to do that again - very annoying :(

**Comment by agnivade** [comment]
Glad you were able to resolve it. In MySQL 8, the default collation was changed which might make it possible to have something like this: https://docs.mattermost.com/install/software-hardware-requirements.html#mysql-8-support.

We also have some upgrade notes here: https://docs.mattermost.com/deploy/legacy-self-hosted-changelog.html#id219

I'll go ahead and close this as the issue was resolved.

**Comment by karlquint** [comment]
Had the same problem in version 9.6.1. The easy fix looked like this:

1. create an SQL dump of the mattermost database (e.g. use: `mysqldump -u username -p your_database > your_dump.sql`)
2. use sed to change the collation parameters in the dump (e.g. in bash: `sed -i 's/utf8mb4_general_ci/utf8mb4_unicode_ci/g' your_dump.sql`)
3. delete the old database (e.g. in mysql: `DROP DATABASE your_database;`)
4. import the new database (e.g. use: `mysql -u your_username -p your_database_name < modified_your_dump.sql`)

This worked for me in two mattermost installations without problems.
