### ISSUE TITLE
Running a playbook creates a new channel

### ISSUE THREAD

**Issue by salbuquerque97** [mattermost/mattermost#24280]
#### Summary
When using the Mattermost API to run a playbook it creates a new channel. Through the UI is possible to attach a run to a already created channel.

#### Steps to reproduce
Run a playbook using the mattemost API.

#### Expected behavior
Run of a playbook in a already existing Mattermost Channel if we provide the channel ID. 

#### Observed behavior (that appears unintentional) 
When using the Mattermost API to run a playbook it creates a new channel. Through the UI is possible to attach a run to a already created channel.

Thanks.

**Comment by sbishel** [comment]
The `/run` endpoint accepts a `PlaybookRunCreateOptions` object which includes ChannelID.
https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/client/playbook_run.go#L127-L137

It then gets decoded and used here - 
https://github.com/mattermost/mattermost-plugin-playbooks/blob/master/server/api/playbook_runs.go#L165C4-L165C4

I hope this solves your issue.

**Comment by salbuquerque97** [comment]
Hello @sbishel 
I'm sending a POST request to /plugins/playbooks/api/v0/runs and sending this payload:
{
"name": "name",
"owner_user_id": "z1spi6mn4id3jn89u49f6u1nor",
"team_id": "rk4mc9murp8mixdziw7frdnsza",
"playbook_id": "dyk4d9rojpryjqs7typw4anmqo",
"channel_id": "{{webhookData.fields.customfield_10901}}"
}

It completely ignores the channel_id field and creates a new channel where it runs the playbook. 
Maybe I'm sending an incorrect payload? 
Thanks for your help.

**Comment by salbuquerque97** [comment]
same here https://github.com/mattermost/mattermost-plugin-playbooks/issues/1800

**Comment by honzamach** [comment]
I would like to kindly ask, whether this is merged into codebase. I am running Mattermost Version: 10.3.1 and this issue still persists.
