### ISSUE TITLE
Clients crash when an invalid Form is posted via an App Integration

### ISSUE THREAD

**Issue by darkecho731** [mattermost/mattermost#24318]
Hi,

We found a Bug with the interactive Posts that embed a form created via a Mattermost App.

If the Fields in Form contain a `null`, the Webapp as well as (at least) the Android App crash when opening the corresponding Channel (Webapp only shows a white screen and the Android App throws an exception and exits).

Example for some `app_bindings` that will create this behavior:

```json
"app_bindings": [
  {
    "location": "embedded",
    "app_id": "some_app_id",
    "bindings": [
      {
        "form": {
          "title": "Do Something",
          "fields": [
            {
              "value": "Value 1",
              "is_required": true,
              "label": "field_a",
              "name": "field_a",
              "type": "text"
            },
            null,
            {
              "is_required": true,
              "label": "field_b",
              "name": "field_b",
              "type": "text",
              "value": "Whatever"
            }
          ],
          "submit": {
            "path": "/api/call"
          }
        },
        "label": "Do something",
        "location": "some Location"
      }
    ],
    "description": "test app binding"
  }
]
```

If this is posted in a channel, it's not possible to view the channel with the clients anymore until the post gets deleted by the Integration or an Admin.

**Comment by amyblais** [comment]
Hi @darkecho731 
1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see any errors in the Mattermost server logs?

**Comment by darkecho731** [comment]
Sorry, could have added that information right away.

Mattermost Version: 7.10.0
OS: Linux Electron App, Webclient in Firefox and Android App all show this behavior (Webclients show whitescreen and Android App crashes).

Linux Client Version is 5.0.4-3 while the Android App Version is 2.7.0 (Build 6000482).

I don't have access to the Server Logs right now but that it's very likely that this is just a client display Bug, as the Server serves the data without any problems via the API.

**Comment by amyblais** [comment]
Thank you, opened https://mattermost.atlassian.net/browse/MM-54248.

**Comment by darkecho731** [comment]
Thanks

**Comment by amyblais** [comment]
Closing for now as we haven't been able to reproduce/prioritize this,
