### ISSUE TITLE
Upgrading leads to error in focalboard plugin: Error 1054: Unknown column 'dirty' in 'field list' in line 0

### ISSUE THREAD

**Issue by Iceforgedmvp** [mattermost/mattermost#24316]
#### Summary
After updating Mattermost (Team Edition) from 7.1.5 (ESR) to 7.8.2 (ESR) or 7.8.9 (ESR) the following error occurs on startup:

> Unable to restart plugin on upgrade., error initializing the DB: Error 1054: Unknown column 'dirty' in 'field list' in line 0: SELECT version, dirty FROM `focalboard_schema_migrations` LIMIT 1

#### Steps to reproduce
```
sudo su
systemctl stop mattermost

# Backup
cd /opt
rm -rf mattermost-back* mattermost-upgrade
cp -ra mattermost/ mattermost-back-$(date +'%F-%H-%M')/

# Upgrade
wget https://releases.mattermost.com/7.8.9/mattermost-team-7.8.9-linux-amd64.tar.gz
tar -xf mattermost*.gz --transform='s,^[^/]\+,\0-upgrade,'

find mattermost/ mattermost/client/ -mindepth 1 -maxdepth 1 \! \( -type d \( -path mattermost/client -o -path mattermost/client/plugins -o -path mattermost/config -o -path mattermost/logs -o -path mattermost/plugins -o -path mattermost/data \) -prune \) | sort | sudo xargs rm -r

cp -an mattermost-upgrade/. mattermost/
chown -R mattermost:mattermost mattermost
setcap cap_net_bind_service=+ep ./mattermost/bin/mattermost

# Restart service
systemctl start mattermost

# View log
journalctl -u mattermost -r
```

#### Expected behavior
Mattermost should start without errors.

#### Observed behavior (that appears unintentional) 
Running `journalctl -u mattermost -r` gives the following output:
> Aug 20 14:21:54 mattermost mattermost[1370]: {"timestamp":"2023-08-20 14:21:54.498 +02:00","level":"error","msg":"Failed to sync plugin from file store","caller":"app/plugin.go:366","bundle":"plugins/focalboard.tar.gz","error":"installExtractedPlugin: Unable to restart plugin on upgrade., error initializing the DB: Error 1054: Unknown column 'dirty' in 'field list' in line 0: SELECT version, dirty FROM `focalboard_schema_migrations` LIMIT 1"}
> 
> Aug 20 14:21:54 mattermost mattermost[1370]: {"timestamp":"2023-08-20 14:21:54.478 +02:00","level":"error","msg":"Table creation / migration failed","caller":"app/plugin_api.go:976","plugin_id":"focalboard","error":"\"Error 1054: Unknown column 'dirty' in 'field list' in line 0: SELECT version, dirty FROM `focalboard_schema_migrations` LIMIT 1\""}

#### Possible fixes
n/a

**Comment by amyblais** [comment]
Hi there, would you be open to re-opening this issue in the Focalboard repo https://github.com/mattermost/focalboard/issues? Thanks!

**Comment by Iceforgedmvp** [comment]
Hi, thanks for your reply.

Correct me if I'm wrong but according to the [official announcement](https://github.com/mattermost/focalboard/issues/4721) the Mattermost plug-in (which I use) is now part of the Mattermost server repository:

> The codebase for Focalboard Personal Editions was separated from the ongoing Mattermost Boards Plugin code on March 09, 2023. [...]
> The Mattermost Boards in-product/plugin code will be merged into the [Mattermost-server repository](https://github.com/mattermost/mattermost-server) where future enhancements will be added to moving forward.

Source: https://github.com/mattermost/focalboard/discussions/4645

So posting my bug to the Focalboard project would not help as a bugfix would not make it to the Mattermost server (which I use), would it?

**Comment by amyblais** [comment]
@Iceforgedmvp That announcement is outdated and no longer relevant as Focalboard will remain as a plugin. I'll ask our team to close out that announcement.

**Comment by Iceforgedmvp** [comment]
Ok, thanks :)

**Comment by Spone** [comment]
> @Iceforgedmvp That announcement is outdated and no longer relevant as Focalboard will remain as a plugin. I'll ask our team to close out that announcement.

In this case, I think you should edit the announcement to make it clear that the decision was reverted. I got really confused by it.
