### ISSUE TITLE
Wrong files (low-res previews) are downloaded from image posts.

### ISSUE THREAD

**Issue by Roy-Orbison** [mattermost/mattermost#24392]
#### Summary
Right-clicking an image in chat offers to save it, but it's the preview, not the sent file.

#### Steps to reproduce
Post any image, preferably 

#### Expected behaviour
Interacting with the image should deliver the original, not the preview.

#### Observed behaviour (that appears unintentional) 
Previews are sent instead which can be, resized, the wrong type, and lower quality.

Non-technical users don't understand they're getting the wrong file, and it's entirely because of your UI.

#### More info
This was discussed extensively in pull https://github.com/mattermost/mattermost-webapp/pull/11773, and it was agreed the the patch was not the best way to solve it, but the issue is still present in v8.1.

From [this comment](https://github.com/mattermost/mattermost-webapp/pull/11773#issuecomment-1414570730):
>I just tested a post of a large image in an old Slack account. The resized thumbnail present in the channel showed no image context menu options, they block them with an `::after` pseudo-element, which is actually a better solution than I wrote. All the link options were directly to the full sized image:
>
>![thread context](https://user-images.githubusercontent.com/28617290/216484153-e5577895-27da-4ef8-aeee-8a6413dcc926.png)
>
>In Slack, Expanding that preview shows the original image, unlike Mattermost which still shows the preview version in the expanded view. I hadn't tested this in Slack before now, and their choice validates what I was trying to accomplish here.

Slack is getting this right, a preview that links and expands to the original, Mattermost is not. This was in the last responses

>And will also keep an eye out for users reporting this particular issue to understand the severity of it.

I think Mm devs are being naive if they think the average user is going to know about GitHub, let alone create an account and report a UI issue, when they don't even realise they've downloaded the wrong image.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54267.

**Comment by Roy-Orbison** [comment]
*any image, preferably one greater than the max preview width (1920 pixels), and with some meta data like EXIF in a JPEG.

**Comment by Roy-Orbison** [comment]
Hit a new ESR and it's still broken.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
