### ISSUE TITLE
Importing a `boardarchive` breaks timestamps on imported tasks

### ISSUE THREAD

**Issue by loganmarchione** [mattermost/mattermost#24412]
#### Summary
Importing a `boardarchive` breaks timestamps on imported tasks

#### Steps to reproduce

- I'm running stand-alone Focalboard 7.10.4 in Docker (left screenshot)
- I spun up a Mattermost instance in Docker with Boards 7.11.2 (right screenshot)
- I exported my board from Focalboard to a `boardarchive` file
- When importing the `boardarchive` to Mattermost, all of the timestamps are wrong
- Also, the order of the items in the columns is lost (unsure if this is related to the timestamp changes)

Below you can see the left (Focalboard) has the correct time of 10 months ago, while the right (Mattermost import) has the incorrect time of 12 days ago
![Screenshot_20230829_115834](https://github.com/mattermost/mattermost/assets/4955337/52bb70e5-7724-4423-9202-bfc4ba26abc0)

Here is the JSON from the Focalboard export for that entry.
```
{"type":"block","data":{"id":"ayiaef857sjy1tb5psu3hkp9pka","parentId":"cukrxnfw8n3dmjnbgjc1n3uz3wa","createdBy":"u1b6q77ixji8mtg84agcfbfp6ew","modifiedBy":"u1b6q77ixji8mtg84agcfbfp6ew","schema":1,"type":"comment","title":"I think this is done, but Ansible playbooks will need to be redone to ensure it's done for the correct user","fields":{},"createAt":1667328548338,"updateAt":1667328548338,"deleteAt":0,"boardId":"bfy769tekmtgw9gcuzc8b5cqsne"}}
```

You can see the timestamp is `1667328548338`, which was 10 months ago (the correct time). I'm unsure how Mattermost is getting 12 days ago...
![Screenshot_20230829_120249](https://github.com/mattermost/mattermost/assets/4955337/be1cca08-4b67-4c92-a29d-758fa965777b)

Here is a different example where the time on the import was updated to the current time...

![Screenshot_20230829_120757](https://github.com/mattermost/mattermost/assets/4955337/ce94ab9a-defd-4ffc-8cb5-0f0fdf62fa6b)

...even though the timestamp is `1681324659924` (5 months ago) 

```
{"type":"block","data":{"id":"aent5ct6fjid678h7irtu74e7ry","parentId":"cu56gdg5dnbdumqa4ntkijn4fra","createdBy":"u1b6q77ixji8mtg84agcfbfp6ew","modifiedBy":"u1b6q77ixji8mtg84agcfbfp6ew","schema":1,"type":"comment","title":"https://docs.netgate.com/pfsense/en/latest/recipes/dns-over-tls.html#enable-dns-over-tls-server-optional","fields":{},"createAt":1681324659924,"updateAt":1681324659924,"deleteAt":0,"boardId":"bfy769tekmtgw9gcuzc8b5cqsne"}}
```

#### Expected behavior
I think I should be given the option to either preserve timestamps, or completely overwrite them with the current timestamps.

#### Observed behavior (that appears unintentional) 
See above...

#### Possible fixes
See above...

**Comment by amyblais** [comment]
Hi @loganmarchione! Would you be open to re-opening this issue at https://github.com/mattermost/focalboard/issues? Thank you!

**Comment by loganmarchione** [comment]
Yep, just opened https://github.com/mattermost/focalboard/issues/4864.
