### ISSUE TITLE
Migrate all users from email to GitLab authentication provider using CLI

### ISSUE THREAD

**Issue by asenyaev** [mattermost/mattermost#24425]
We have a Mattermost server running for a year, and a lot of users have created an account with their email, because it was the only option at the moment. Now we have the ability to use GitLab authentication, and we want to migrate all users to that authentication provider.

Currently, one command for this exists - `mmctl user migrate-auth` ([doc](https://docs.mattermost.com/manage/mmctl-command-line-tool.html#mmctl-user-migrate-auth)), but there are some limitations with authentication services to migrate users to, `ldap` and `saml` are only available.

I would like to have an opportunity to migrate users from email to GitLab authentication provider - `mmctl user migrate-auth email gitlab users.json`

I've seen the closed issue - https://mattermost.atlassian.net/browse/MM-2520. But the fix for the issue did not add a lot of choices.

There is also the ticket on mattermost forum about the same issue - https://forum.mattermost.com/t/migrate-all-users-from-email-to-gitlab-sso-as-sysadmin/10696

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @asenyaev,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by asenyaev** [comment]
@amyblais I've created an idea - https://mattermost.uservoice.com/forums/306457-general/suggestions/47192909-migrate-users-from-email-to-gitlab-authentication
