### ISSUE TITLE
Webapp: Thread reply textarea width incorrect size until typed into 

### ISSUE THREAD

**Issue by tejclark** [mattermost/mattermost#24442]
#### Summary
Thread reply textarea width size of placeholder until typed into. Clicking to the right of the placeholder text removes focus from field and occasionally moves 

#### Steps to reproduce
Tested on version 8.0.1, Macbook pro, latest MacOS. Tested on AppStore desktop client and webapp.

* Start a thread
* Click on the "Reply to this thread..." placeholder
* Click further to the right of the placeholder.

#### Expected behavior
When clicking inside the "Reply to this thread" textarea, I expected to see a cursor and be able to type my reply.

#### Observed behavior (that appears unintentional) 
Clicking to the right of the placeholder causes the textarea to unfocus; or not to gain focus.

Screenshot showing the width of the textarea in the webapp:

![Screenshot 2023-09-01 at 16 03 30](https://github.com/mattermost/mattermost/assets/6714962/61d046dc-dd8c-413f-bec7-c68459d4993f)

#### Possible fixes
The max-width on the textarea appears to be being incorrectly set by the webapp. Setting the max-width to 100% fixes the issue.

**Comment by amyblais** [comment]
Hi @tejclark! This issue has been fixed in v8.1.0 https://mattermost.atlassian.net/browse/MM-50460.

**Comment by tejclark** [comment]
Amazing - I was clearly searching for the wrong thing when seeing if it had been reported.

Thanks @amyblais !
