### ISSUE TITLE
LHS resize is overriding with Browse/ Create Channel Menu

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost#24455]
#### Summary
When browse Browse/ Create Channel Menu is opened the cursor is still able to select the line for LHS resizing

#### Steps to reproduce
1. Click plus icon on LHS
2. Hover over the line between LHS and main channel view (i.e. the part where you see the messages in the channel)

#### Expected behavior
The users should not be able to resize LHS when Browse/ Create Channel Menu is open

#### Observed behavior (that appears unintentional) 
<img width="1440" alt="Screenshot 2023-09-03 at 17 50 10" src="https://github.com/mattermost/mattermost/assets/37421564/d4a82c77-059c-4cae-9f33-aeca981725fd">

#### Possible fixes
Change the z-index of Browse/ Create Channel Menu

**Comment by sinansonmez** [comment]
cc: @amyblais

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54367

**Comment by kyeongsoosoo** [comment]
I currently worked on this feature. If this is a ticket for a contributor,I would like to take this issue.

**Comment by marianunez** [comment]
@kyeongsoosoo I've assigned this to you so feel free to submit a PR for this issue. Thanks!
