### ISSUE TITLE
cannot upgrade via apt/dpkg

### ISSUE THREAD

**Issue by AnID-Aux** [mattermost/mattermost#24450]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
upgrade via apt fails with error code 1

#### Steps to reproduce
apt update && apt dist-upgrade as root user. Installed Version 8.0.1

#### Expected behavior
Ubuntu 22.04. Systemctl stop Mattermost. Mattermost is trying to upgrade from 8.0.1 to 8.1.0 via apt. Apt fails with error code 1. After that, Mattermost can no longer be started. Mattermost runs without a reverse proxy. It has 80to443 enabled and Letsencrypt is also done by Mattermost. Package source is also from Mattermost. Restore backup and the old version runs fine. What could be the reason? Forcing or repairing did nothing.

#### Observed behavior (that appears unintentional) 
dpkg exit with error code 1

**Comment by amyblais** [comment]
@AnID-Aux Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this issue.
