### ISSUE TITLE
Favicon Change in Mattermost API reference site

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/mattermost#24504]
favicon on mattermost API reference site Is outdated 
![image-xkc8wkzmffns7m8mkuqxtf137o](https://github.com/mattermost/mattermost/assets/71702982/23031a43-ff1b-4c3f-8334-bb244626a0db)
`https://api.mattermost.com/`?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54449

**Comment by IronOnet** [comment]
@amyblais can you assign me this one?

**Comment by IronOnet** [comment]
Hi @amyblais  I've added a pull request  https://github.com/mattermost/mattermost/pull/24525

**Comment by amyblais** [comment]
Thank you, I added reviewers to the PR.
