### ISSUE TITLE
Question on emoji picker screen

### ISSUE THREAD

**Issue by skotlex** [mattermost/mattermost#24508]
I worked on replacing the emoji's *.png files, which is provided by default in basic Mattermost, with something else.
(in /mattermost/client/emoji folder)
As a result, the newly replaced emoji is displayed as I wish in the chat window

But apart from that, the emoji picker window still shows the emoji preview that Mattermost provides as a base, not the image I replaced.
Is there anything else I need to do to update the preview image of emoji picker?

**Comment by amyblais** [comment]
@skotlex Would you be open to posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or other community members will likely be able to help answer this question.
