### ISSUE TITLE
The code button can break the formatting if the code has valid markdown

### ISSUE THREAD

**Issue by LarsErikP** [mattermost/mattermost#24532]
#### Summary
Marking selected text as code will render markdown depsite being inside the code tags

#### Steps to reproduce
Write a message like this:
```
Test
====
hello
```
Mark all text and click the "code" button (Ctrl Alt C). That will give you something like this:
````
```Test
====
hello```
````
And send the message

#### Expected behavior
Clicking the code button should produce valid syntax.

#### Observed behavior (that appears unintentional) 
Doing what's described above will produce invalid syntax, as the backticks should have been on their own lines, not just inserted at the beginning of the first line, and on the end of the last line. If the selected text contains valid markdown, it will be rendered, instead of creating a code block.

EDIT: If you do the same steps, but without markdown, it will render inline code on separate lines, not a multiline code block..

I am aware that you could call this a user error, but I still think it's slightly a surprising behaviour.

#### Possible fixes
No suggestion, I'm just a regular user :-)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54474.

**Comment by Paul-vrn** [comment]
Hi, I would like to work on this issue 👋
