### ISSUE TITLE
Direct and group messages are sorted incorrectly by recent activity when you switch team

### ISSUE THREAD

**Issue by svetlanak-git** [mattermost/mattermost#24546]
#### Summary
Direct and group messages are sorted incorrectly by recent activity when you switch team

#### Steps to reproduce
Mattermost Version: 8.0.1-25503
Database Schema Version: 109
Database: postgres

- Set sorting order for direct messages to "Recent activity"
- Start direct message chat with any member of your team
- Switch the team and start chat with another team member
- Keep recieving messages in the chats and switching teams. At some point you see that chat with most recent message is not at the top.
- Switch to another team and see that sorting order is correct.
- Switch the team back and the order is incorrect again.
We couldn't find the exact sequence of steps that leads to this problem but many of our users sporadically experience it.

#### Expected behavior
Switching team doesn't affect the sorting order of direct and group messages. Most recent messages come first.

#### Observed behavior (that appears unintentional) 
When you switch team the sorting order becomes broken and the most recent chat may go down

#### Possible fixes
If you delete site cookies then sorting order becomes correct again for all teams.
Debugging showed that at some point the list of channels that comes from redux store has incorrect information in last_post_at and last_root_post_at fields that leads to incorrect sorting. So when you switch to one channel it has correct data and when you switch to another channel it has incorrect data.
<img width="682" alt="screenshot1" src="https://github.com/mattermost/mattermost/assets/107425580/a505058d-f205-42f7-a522-d0e2666119a3">
<img width="671" alt="screenshot2" src="https://github.com/mattermost/mattermost/assets/107425580/457ccee4-b726-4288-a08e-54e91c368f6e">

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54501.

**Comment by svetlanak-git** [comment]
Update: seems the problem is that http request gets status code 304 for a team and therefore we have outdated information in the store:
![image](https://github.com/mattermost/mattermost/assets/107425580/515df1ae-49e1-4751-848e-ec11b0df5d39)
We keep recieving this status even if there are new direct messages or new messages in the team channels. So the problem is much deeper and concerns not only direct messages but channel updates too. This becomes a showstopper for us.

**Comment by amyblais** [comment]
Closing older issues as our team hasn't been able to prioritize this,
