### ISSUE TITLE
Poor handling of expired session

### ISSUE THREAD

**Issue by juresaht2** [mattermost/mattermost#24564]
When the server is restarted, or the sessions expire for whatever reason (see: https://github.com/mattermost/mattermost-server/issues/1105 ), the desktop client behaves erratically instead of handling the situation gracefully.

Expected behavior: User is asked to log in again and a new working session is established.

Observed behavior: The desktop client behaves erratically, with the display occasionaly going blank when switching teams, or various error messages being displayed, which are confusing to users (such as "rate limited" or "channel does not exist"). CTRL + SHIFT + R does not always resolve issue and has to be pressed repeatedly on different teams.

I realise this is an issue caused by restarting the server, however I think the client should be able to handle errors from the server gracefully instead of causing additional issues and requiring users to restart the client several times, or know secret key combinations, etc.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54510.

**Comment by juresaht2** [comment]
Okay so, 1 year 

> > @juresaht2 Can you try reproducing by leaving a web browser open? This sounds like is could be more of a webapp issue so I'd like to figure out if that's true.
> 
> Currently we don't have a test setup to gather this information. I will make it a point to set one up but this may take a long time. Hopefully this ticket can remain open in the time being and perhaps someone else experiencing the issue can help with this stuff.

Okay so 1 year later the test environment is set up.

I currently cannot reproduce the issue on this test environment, but reading your answers especially @moospit , I think I know what's going on and why this issue does not occur on the test system:

Basically the issue is that when you restart the server on production, all the desktop clients have to revalidate their session and with hundreds of clients doing this at once, when the server is restarted, triggers the RateLimit mechanism, hence the "limit exceeded" error message.

There are just a handful of clients on the test system and therefore the issue does not occur there.

However on production this boots random requests from clients in an unpredictable pattern and the client does not handle this well, as the user does not always get the error message and instead functionality just quietly fails and clients may even function normally and simply not recieve messages.


The workaround for this issue, is to either disable RateLiming on the server or increase the limits to the point that this reboot situation can be handled.

The proper solution would probably be to make the server emmit a HTTP error code on exceeded rate limits and have the client handle such errors more gracefully.

An alternative solution that would also work, would be to not immediately enable RateLimitng when a server is restarted, but delay it a few minutes to allow the initial spike to pass.

**Comment by amyblais** [comment]
Closing for now as we haven't been able to reproduce/prioritize this,
