### ISSUE TITLE
Team edit invalidates invite code

### ISSUE THREAD

**Issue by baznikin** [mattermost/mattermost#24584]
#### Summary
Any team edit (change team description, list of allowed domains, setting team admins) change invite id as well.

#### Steps to reproduce
1. check invite code in Team settings interface
2. change team description
3. check invite code again. It is changed

#### Expected behavior
According to documentation it should not change unless manually re-generated:

> The team invite link is a unique URL that directs people to an account creation page for a team. A team invite link can be used by anyone and does not change unless it is re-generated by a System Admin or Team Admin via Team Settings > General > Invite Code. For example, the team invite link can be included in a company-wide email to invite all employees to join a Mattermost team.

#### Observed behavior (that appears unintentional) 
![Screenshot from 2023-09-18 12-41-47](https://github.com/mattermost/mattermost/assets/5183334/eae2372e-f15a-4568-8321-0a5214b8665d)
![Screenshot from 2023-09-18 12-42-04](https://github.com/mattermost/mattermost/assets/5183334/944320b0-809b-44cc-9966-204301d96dc3)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54514.

**Comment by baznikin** [comment]
@amyblais thanks! It is reproduced on 8.0.1 and 8.1.2 (didn't try other versions)
