### ISSUE TITLE
Mattermost should provide settings for data retention policy

### ISSUE THREAD

**Issue by phidahl** [mattermost/mattermost#24588]
#### Summary
In Mattermost CE it is not possible to set data retention to a finite duration

#### Steps to reproduce
Version 8.1.2 and prior versions

#### Expected behavior
I expect Mattermost Team Edition to be compliant to EU and national law. For a few years, there has to be mechanisms in software handling personal data to remove data if requested by affected persons. The fact that it is not possible to really delete data from database and file system by the software itself makes it not usable for most organizations.
It might even be illegal to distribute Mattermost Team Edition  in this form in the EU.
Additionally the database will grow depending on usage. The lack of a mechanism to limit this growth (retention policy) makes an installation of Team Edition  hard to maintain in the long term.

#### Observed behavior (that appears unintentional) 
I cannot set data retention policy in Mattermost Team Edition 
Deleting of message or attachments won't delete the underlying data from databases or the file system

#### Possible fixes
The implementation of these important functionality is there the paid edition of Mattermost

**Comment by amyblais** [comment]
Hi @phidahl, that's correct, this feature is currently only available in the paid edition. If you're planning to update to a paid version, please request a quote via https://mattermost.com/pricing/.
