### ISSUE TITLE
Missing builds of push proxy v5.25.0

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost#24589]
#### Summary
As of this writing, [push proxy v5.25.0](https://github.com/mattermost/mattermost-push-proxy/releases/tag/v5.25.0) was released 5 days ago, but the published assets on Github only include the source code.

#### Steps to reproduce
As [per documentation](https://developers.mattermost.com/contribute/more-info/mobile/push-notifications/service/#install-and-upgrade), 

`wget https://github.com/mattermost/mattermost-push-proxy/releases/download/v5.25.0/mattermost-push-proxy.tar.gz`

#### Expected behavior
Receive mattermost-push-proxy.tar.gz

#### Observed behavior (that appears unintentional) 
404 Not Found

**Comment by amyblais** [comment]
I've opened a ticket for our SRE team to take a look.

**Comment by amyblais** [comment]
This is now fixed,
