### ISSUE TITLE
React To Last Message shortcut in threads doesn't work

### ISSUE THREAD

**Issue by momja** [mattermost/mattermost#24581]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
If I am in the threads main window, nothing happens when pressing this shortcut. If I have a thread open in the side window, it steals focus from the side window into whatever was the last message in the channel.

#### Steps to reproduce
**Version** 7.10.0

**MacOS Version** 13.5.2

#### Expected behavior
I would expect (on Mac) the command `CMD-SHIFT-\` to let me react to last message in threads, the same way it does in other direct messages. 

#### Observed behavior (that appears unintentional) 
Nothing happens, or the it steals focus to the main pane.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54513.
