### ISSUE TITLE
unread message count value is negative

### ISSUE THREAD

**Issue by luozhouyang** [mattermost/mattermost#24587]
The unread message count of a user in a channel is negative value.

#### Observed behavior (that appears unintentional) 
```bash
curl -i -X GET https://mydomain.com/api/v4/users/ngsaa9fyn78gudeaiepenmy1my/channels/a6c1k4kri3ydinyfqtsxintn7o/unread \
 -H 'Content-Type:application/json' \
 -H 'Authorization: Bearer xxxxx'
HTTP/2 200
content-type: application/json
content-length: 184
expires: 0
permissions-policy:
referrer-policy: no-referrer
vary: Origin
vary: Accept-Encoding
x-content-type-options: nosniff
x-request-id: yyyfnnc44bdipkgh5gtbtq39iw
x-version-id: 7.10.0.7.10.0.a502c5cefebb29d8960c55f3add7825c.false
date: Tue, 19 Sep 2023 03:46:51 GMT


{"team_id":"fx9zz7pauiy3mep4bqhjdji43o","channel_id":"a6c1k4kri3ydinyfqtsxintn7o","msg_count":-4,"mention_count":0,"mention_count_root":0,"urgent_mention_count":0,"msg_count_root":-4}
```

#### Possible fixes
I have 3  mattermost pods deployed in a k8s cluster. Maybe it's a bug of mattermost?

**Comment by amyblais** [comment]
@luozhouyang What Mattermost server version are you currently on? Do you see any errors in the server logs?

**Comment by amyblais** [comment]
If you're on v7.10, would you be open to checking if the issue reproduces on the latest version? Our community instance https://community.mattermost.com/ is on the latest.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54530.
