### ISSUE TITLE
Wishlist: Link to posts/threads?

### ISSUE THREAD

**Issue by hloeung** [mattermost/mattermost#24598]
#### Summary
Wishlist: Add ability to link to specific posts / threads similar to _~channel_ and _@user_.

#### Steps to reproduce
Something like typing _@@msg/thread_ID_ via the web UI or seen in an API post would link to that post/thread.

Example:

"Please see this post here about focal board @@zf1hsu3ppf8rjxg4kepn5hoh7o"

Which would appear as and link to https://community.mattermost.com/core/pl/zf1hsu3ppf8rjxg4kepn5hoh7o

#### Expected behavior
"My message @@zf1hsu3ppf8rjxg4kepn5hoh7o" would show a hyperlink to the post https://community.mattermost.com/core/pl/zf1hsu3ppf8rjxg4kepn5hoh7o

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @hloeung,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
