### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/mattermost#24593]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.0

### Operating System

Windows 10 x64

### Mattermost Server Version

 8.1.0

### Steps to reproduce

Set the Desktop client window so narrow that the Channels part from the left disappears/collapses. When you do that, the responsive mode is activated. 

### Expected behavior

The call icon should be on the top of the backgroun circle

### Observed behavior

As a result the Start call -link moves to the top as a icon BUT now it is only a button without an icon (only the background circle no icon).

### Log Output

```shell
There is nothing in the logs or in diagnostics file regarding this issue.
```

### Additional Information

We have tested this in several client and client themes.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54527.

**Comment by amyblais** [comment]
@kaksikanaa Our team wasn't able to reproduce this. Are you able to reproduce this on our community server https://community.mattermost.com/?

Also, the button in your screenshot, can you confirm if this the Calls or the Apps button?

**Comment by amyblais** [comment]
I'll close this for now, but we can re-open this if it still reproduces,
