### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [mattermost/mattermost#24608]
#### Summary
⭐ Suggestion
The Twitter logo has been updated recently and hasn't been updated on the site.

#### Steps to reproduce
Step 1: Go to footer section and see twitter old lcon
<img width="306" alt="Screenshot 2023-09-26 at 1 31 48 AM" src="https://github.com/mattermost/mattermost/assets/69191344/07f294af-d336-4472-9093-b1d566c9d877">

#### Expected behavior
The Twitter logo should be changed to X.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Hi there, our Marketing team has a ticket open to update the logo in the coming days.

**Comment by amyblais** [comment]
This is now completed.
