### ISSUE TITLE
Text ghosting on i3wm

### ISSUE THREAD

**Issue by fmiqbal** [mattermost/mattermost#24601]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Text ghosting on i3wm

#### Steps to reproduce
local/mattermost-desktop-bin 5.5.0-1 (Archlinux package)
local/i3-wm 4.22-4
local/xorg-server 21.1.8-2

#### Expected behavior
Text not ghosting 

![image](https://github.com/mattermost/mattermost/assets/8409391/49faf33e-295f-42c8-bbc6-b20f8610c280)

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/8409391/01b924ff-7ec4-4f75-a383-a1db89908ac3)

**Comment by agnivade** [comment]
@fmiqbal - To clarify, this behavior does _not_ happen in other desktop environments?

**Comment by amyblais** [comment]
> @fmiqbal - To clarify, this behavior does _not_ happen in other desktop environments?

@fmiqbal Would you be open to sharing more details on this issue? What Mattermost server version are you on?

**Comment by amyblais** [comment]
Closing for now as we haven't received more details. Can be re-opened as needed,
