### ISSUE TITLE
Posible Ldap log in. 

### ISSUE THREAD

**Issue by RaditzCosplay** [mattermost/mattermost#24600]
Can anyone suggest a possible way to configure LDAP on the free version?

**Comment by amyblais** [comment]
Hi @RaditzCosplay, this feature is currently only available in the paid edition. If you're planning to update to a paid version, please request a quote via https://mattermost.com/pricing/.

**Comment by Febbe** [comment]
Can you consider adding this to the free version, it's a requirement for us to even consider Mattermost.
