### ISSUE TITLE
How/where would I add sounds for the notifications for Mattermost clients in the repos?

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost#24643]
I think many people are finding that the existing six sounds for Desktop Notifications to be difficult to use/hear. This has been one source of ongoing complaining I've heard for years based upon the default bing and now the other sounds are really no better in terms of quality and intrusiveness. A couple folks even have misophonia and simply have to live with all alerts off (since all six of the sounds trigger a mental/emotional response for them). 

I would like to add some sounds to Mattermost that have appropriate licenses that would not be considered as intrusive or difficult to hear. It might even be nice, but I don't know if I have the time to do this, if I can add the ability for users to upload/add their own custom sounds (or at least allow an admin to do so). 

Could someone please outline where/how these sounds are stored and handled by the clients so as to get started in such an effort?

I've personally thought about simply replacing the web clients directly at `client/files/` before, but that is, of course, highly brittle with updates and these are clearly managed by some asset manager due to their renaming form the original mp3 files from the source.

**Comment by amyblais** [comment]
Would you be open to asking about this on our community server either at https://community.mattermost.com/core/channels/developers or at https://community.mattermost.com/core/channels/tickets? One of our devs will likely be able to help with this question.

**Comment by ylluminate** [comment]
Thanks, sorry - I thought this implementation-specific question was more appropriate here. I'll try to seek out information from the other venues. Once I find out some info I'll also document it here since so much information seems to be fragmented across various services/forums.

**Comment by amyblais** [comment]
I've pinged the team to take a look at the question. In case I don't hear a response, here are some additional channels where it might help to post the question: https://community.mattermost.com/core/channels/tickets and https://community.mattermost.com/core/channels/community-team.

**Comment by larkox** [comment]
@ylluminate In `webapp/channels/src/sounds` you will find all the sounds we use right now in the app.

Regarding the selection of the sound, it is mainly handled in `webapp/channels/src/utils/notification_sounds.ts`.

If I am not mistaken, just adding any desired sound there should work.
