### ISSUE TITLE
Download URL in channel file search is missing the `Site URL` path

### ISSUE THREAD

**Issue by danialkeimasi** [mattermost/mattermost#24653]
#### Summary
The path in the value of [Site URL](https://docs.mattermost.com/configure/environment-configuration-settings.html#site-url) setting does not affect the download address in channel file searches.

#### Steps to Reproduce
1. In Mattermost settings configure the `Site URL` to a value that contains path. For example: `https://example.com/company/mattermost`.
2. Conduct a file search within a channel.
3. Attempt to download a file.

#### Expected Behavior
The download URL should include the path of `Site URL` setting, following this format: `${site_url_path}/api/v4/files/${fileID}?download=1`.

#### Observed Behavior
The download URL lacks the path of `Site URL` parameter, appearing as `/api/v4/files/ID?download=1`, which is not correct.

#### Possible Fix
Modify `webapp/channels/src/components/file_search_results/file_search_result_item.tsx:194` ([link](https://github.com/mattermost/mattermost/blob/460fa05eb9e87278def9ac9f493a587481bebb78/webapp/channels/src/components/file_search_results/file_search_result_item.tsx#L194C33-L194C33)) to utilize the `getFileDownloadUrl` function from `mattermost-redux/utils/file_utils`.

**Comment by Girishbari** [comment]
would Like to take a look, if it is needed to be assigned then please assign me
