### ISSUE TITLE
Need Some Alignment to the right of Need More Info Section

### ISSUE THREAD

**Issue by LynxSumit** [mattermost/mattermost#24671]
As we can see in the photo there is a need of margin from the left.

![Screenshot 2023-10-02 233128](https://github.com/mattermost/mattermost/assets/114245865/b94e41c6-b999-4e49-8865-c1894471a6b1)

Please Assign this issue to me.

**Comment by amyblais** [comment]
@LynxSumit Where did you see this issue happen?

**Comment by emdecr** [comment]
@amyblais Circling-back after talking to the team - the styling is intended as per the current designs. We have some tweaks that might help, and will put those in our queue. Thanks for the flag though @LynxSumit!
