### ISSUE TITLE
Desktop App: Release deb is marked as propietary on ubuntu

### ISSUE THREAD

**Issue by mattermod** [mattermost/mattermost#24688]
The .deb packages generated for the Desktop App don't have the license set correctly, so it's displayed as proprietary instead of Apache-2.0 like on the repository.
 ![](Screenshot 2019-12-11 at 17.30.25.png|thumbnail) 
The build process for those packages should be updated so that the package has the license set to match this repository.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-21185

**Comment by kurayami07734** [comment]
Please assign to me this issue

**Comment by kurayami07734** [comment]
I cannot for the life of me, get this to build

I use pnpm so it does not recognize `run-p`  or `npm-run-all`

I even tried using github codespaces 
[debug log from npm](https://github.com/mattermost/mattermost/files/12883235/log.txt)

**Comment by devinbinnie** [comment]
@kurayami07734 Did you follow the Developer Setup guide for Desktop App: https://developers.mattermost.com/contribute/more-info/desktop/developer-setup

We also use just regular `npm` if that might make a difference, but hopefully shouldn't.

**Comment by kurayami07734** [comment]
![screenshot-2023-10-15_11:11:21](https://github.com/mattermost/mattermost/assets/60501848/7e957d4a-abce-48fe-9dbb-2c6d701d2107)

I don't see where it is marked as proprietary @devinbinnie

**Comment by devinbinnie** [comment]
@kurayami07734 Hmm, this is a pretty old bug. I'm wondering if this was something Electron fixed a while ago. I'm not seeing the proprietary label either, so I think we can actually call this closed :)

**Comment by kurayami07734** [comment]
Please close this issue
