### ISSUE TITLE
Desktop App: HiDPI and fractionnal scaling support on Linux under Wayland

### ISSUE THREAD

**Issue by timotheencl** [mattermost/mattermost#24685]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost Desktop is blurry under Wayland do not handle HiDPI screens with scaling enabled.

**Environment**
- Operating System: Linux, Ubuntu 22.04 Jammy with Wayland
- Mattermost Desktop App version: 5.1.1

**Steps to reproduce**

Mattermost desktop installed via Snapstore.

**Expected behavior**
Fonts, images and all should be sharp on hiDPI screens with scaling enabled.

**Observed behavior**
Windows is blurry as well as fonts and images.

**Possible fixes**

I've tried with `--enable-features=UseOzonePlatform --ozone-platform=wayland` which fixes the blurriness. But there is no window borders and title, so it would be appreciable to be supported in your next releases.

Thanks

**Comment by tmke8** [comment]
I'm running on GNOME 45 with
```
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
```
to avoid the electron `WaylandFractionalScaleV1` problem, and that works well with
```
--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
```
but I do see that resizing overflow bug. (This might suggest the bug is related to `WaylandFractionalScaleV1` but I have no real knowledge about this.)

**Comment by pastelcyborg** [comment]
Just wanted to add a quick clarification here: this is an issue on all displays, not only high-DPI ones - very much related to Wayland rendering of all Electron apps at present. Confirm that the resizing overflow bug still exists regardless of which Wayland-related flags I use, also.

On 5.7.0, Ubuntu 22.04.4

Thank you!

**Comment by AndreasBackx** [comment]
When running on Wayland (using `mattermost-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`), Mattermost fails to render images on some of my devices. This is an example message including 2 :emoji:s. An emoji only renders if it was inputted as unicode.

![image](https://github.com/mattermost/mattermost/assets/1593486/28db396e-b37b-4027-a5d2-b9a601630b98)
![image](https://github.com/mattermost/mattermost/assets/1593486/4b7f0099-54b9-414f-a5dc-c30ab488a5e6)

Clicking the image I uploaded shows an empty black screen as well.

**Comment by milux** [comment]
Just wanted to state that this issue still exists here for the latest version (5.8.1) in both snap and deb distributions.
Upon start (not fullscreen) it sometimes works correctly, but as soon as the windows is resized, the overflow bug occurs.

**Comment by AndreasBackx** [comment]
Seems like running it in XWayland leads to the obvious fractional scaling blurriness, but also to mouse input seemingly not working. Might be due to some positioning weirdness caused by the fractional scaling and different scaling on other windows.

**Comment by milux** [comment]
> The entire window has also gone invisible for me in Wayland. Can be resolved with `rm -rf $HOME/.config/Mattermost/GPUCache`. It also resolves the other issue above with the hidden images.

Doesn't fix the scaling bug here. What exactly do you mean by "issue above with the hidden images"?

**Comment by lkraav** [comment]
5.9.0 is in pretty good shape on Wayland already, no more obvious layout glitches :100:

**Comment by milux** [comment]
Yes, works here as well. :rocket: :tada:

**Comment by devinbinnie** [comment]
I guess this is something Electron has dealt with then :)
Closing this for now, if anyone else is still seeing issue please let me know.

**Comment by enticedwanderer** [comment]
For me it won't even display a window, spamming in the logs "Unable to send the message to the main window for message type ..." whenever any window is supposed to show up. Usually this was the case when the flags were not applied. I used to run it at startup successfully with:

```
sleep 5 && /usr/bin/mattermost-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland "$@"
```

Version:        5.13.0
