### ISSUE TITLE
Gif picker error

### ISSUE THREAD

**Issue by dillfrescott** [mattermost/mattermost#24706]
#### Summary
Gif picker throws error

#### Steps to reproduce
Go to gif menu. It throws an error.

#### Expected behavior
Able to choose gifs and have them display in the menu.

#### Observed behavior (that appears unintentional) 
Error

#### Possible fixes
I have no clue! Sorry!

![Screenshot 2023-10-04 005955](https://github.com/mattermost/mattermost/assets/56714680/0b92dd03-18c4-4483-8c78-7f9784bd0878)

**Comment by amyblais** [comment]
@dillfrescott Another person faced this issue and they fixed it by getting a new giphy sdk key https://forum.mattermost.com/t/solved-giphy-integration-not-working-after-upgrade/16774/2. Does this solution work for you?

**Comment by dillfrescott** [comment]
Yes! Thank you!
