### ISSUE TITLE
[Bug]: Theme color sidebarHeaderTextColor is used with different backgrounds

### ISSUE THREAD

**Issue by nmatt** [mattermost/mattermost#24707]
### Mattermost Desktop Version

Version 5.5.1 commit: db8645b

### Operating System

Windows 10 x64

### Mattermost Server Version

8.1.3-rc1

### Steps to reproduce

Use the following custom theme:
```
{"awayIndicator":"#eab11d","buttonBg":"#0044aa","buttonColor":"#ffffff","centerChannelBg":"#ffffff","centerChannelColor":"#000000","codeTheme":"github","dndIndicator":"#fb3232","errorTextColor":"#ff4048","linkColor":"#005599","mentionBg":"#f7f7f7","mentionBj":"#f7f7f7","mentionColor":"#145dbf","mentionHighlightBg":"#ffffff","mentionHighlightLink":"#166de0","newMessageSeparator":"#2fb538","onlineIndicator":"#0ae24a","sidebarBg":"#f7f7f7","sidebarHeaderBg":"#0044aa","sidebarHeaderTextColor":"#ffffff","sidebarTeamBarBg":"#003688","sidebarText":"#222222","sidebarTextActiveBorder":"#579eff","sidebarTextActiveColor":"#001155","sidebarTextHoverBg":"#dddddd","sidebarUnreadText":"#000000"}
```

### Expected behavior

The expected behavior is for _sidebarHeaderTextColor_ to only be used in conjunction with the _sidebarHeaderBg_ background color.

### Observed behavior

In the desktop client, the teams dropdown above the "Find channel" search box uses _sidebarHeaderTextColor_ on top of _sidebarBg_, making the dropdown virtually invisible.

### Additional Information

See also https://github.com/mattermost/mattermost-mobile/issues/7583, where the issue is more pervasive.

### Possible fixes
Do one of the following:

- Use _sidebarHeaderBg_ as the background color instead of _sidebarBg_ wherever _sidebarHeaderTextColor_ is currently used as the foreground color.
- Change the current uses of _sidebarHeaderTextColor_ on _sidebarBg_ to _sidebarText_.
- Introduce new theme colors for the places where the incompatible foreground-background combinations are currently used.

**Comment by devinbinnie** [comment]
Webapp issue, transferred to main repo.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54750.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this https://github.com/mattermost/mattermost/issues/25702
