### ISSUE TITLE
Paste Clipboard Contents Failed

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost#24710]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence
Can't paste clipboard images, but paste text work well.

#### Steps to reproduce
1. Copy any images to clipboard.
2. Make sure the image that you copied is in the Finder (macOS) clipboard.
3. Try to paste it into the text input box.
This issue is common in all recent versions. I tested it on V9.0.0 and V8.x.x

#### Expected behavior
The clipboard image should be pasted.

#### Observed behavior (that appears unintentional) 
![mattermost](https://github.com/mattermost/mattermost/assets/20394843/41007c54-8b98-4831-a75f-b4772d199440)

#### Possible fixes
I have confirmed that it works in V7.

**Comment by thinkmms** [comment]
Yes, I am facing the issue. 300+ users in our org reported the same issue. 
![image](https://github.com/mattermost/mattermost/assets/1117753/b8885cf0-6dc1-4cc4-bb10-21b9f81081ee)

**Comment by Gloriashield** [comment]
> Yes, I am facing the issue. 300+ users in our org reported the same issue. ![image](https://user-images.githubusercontent.com/1117753/272803246-b8885cf0-6dc1-4cc4-bb10-21b9f81081ee.png)

Thank you, I will close this issue. :D

**Comment by NotSnowyy** [comment]
Why would you close this then? There's clearly something wrong in the newer version(s).
Same problem here on 9.0.0.
