### ISSUE TITLE
Convert ./components/channel_header_dropdown/menu_items/close_channel/close_channel.tsx from Class Component to Function Component

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost#24764]
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-54800

**Comment by bhavuk2002** [comment]
can you pls assign me to this issue?

**Comment by larkox** [comment]
@bhavuk2002 I assigned you the ticket :smile: In the ticket description you have a few example PRs, so feel free to use them as template.

**Comment by sjcode99** [comment]
Hey @larkox , is the issue still open? would like to work on it.

**Comment by larkox** [comment]
Since we haven't heard from @bhavuk2002 for a while, I reassigned it to you, @sjcode99 . Thanks!

**Comment by larkox** [comment]
@sjcode99 I saw that @ARJ2160 pushed a PR, but this is assigned to you. Are you OK with us following with @ARJ2160 's PR? If you have a PR already open for this, you have preference, but since @ARJ2160 has it already opened, I preferred to ask.

**Comment by sjcode99** [comment]
@larkox , yeah fine with it.Please go ahead with @ARJ2160.

**Comment by larkox** [comment]
@ARJ2160 If you could comment here so I can assign the issue to you, it would be great. :smile:

**Comment by ARJ2160** [comment]
Absolutely
Thanks @sjcode99! Much appreciated
