### ISSUE TITLE
Convert ./components/post_emoji/post_emoji.tsx from Class Component to Function Component

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost#24767]
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-54804

**Comment by parag477** [comment]
Can I work on this.

**Comment by larkox** [comment]
@parag477 Here you have! I am happy to see you are taking several issues, and that is great. Just make sure you don't take more than you can handle, so other people can also take issues :smile:

**Comment by AvaterClasher** [comment]
Can i get this if he doesnt want it anymore or anyone of the ones he is assigend to @larkox

**Comment by larkox** [comment]
@AvaterClasher :
@parag477 is already working on this. Feel free to look for any other ticket Up for Grabs.
If you are specially interested in the converting class components to functional components campaign, stay tuned. We still have more tickets in this campaign, and we are waiting to merge a few more before releasing the rest :smile:

**Comment by larkox** [comment]
It is still open. We should follow the order, so if neither @parag477 nor @AvaterClasher respond to this in the following 24 hours, feel free to take it and I will assign it to you.

**Comment by sjcode99** [comment]
Sure, that sounds perfect

**Comment by AvaterClasher** [comment]
i would like to work on it @larkox

**Comment by larkox** [comment]
@AvaterClasher All yours!
