### ISSUE TITLE
Can't set 0 to a dialog element with subtype=number in interactive dialog

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost#24817]
#### Summary
When setting 0 to a dialog element with subtype=number, 0 is disappeared and cannot be set.

#### Steps to reproduce
1. Open interactive dialog
2. Set 0 to a dialog element with subtype=number

#### Expected behavior
Complete to set 0.

#### Observed behavior (that appears unintentional) 
0 is disappear and submitting is failed.

![dialog-element-zero](https://github.com/mattermost/mattermost/assets/1453749/5c753782-ba9e-4359-9d8a-b31676337004)

#### Possible fixes
The value of an element with type=text and subtype=number is set as `value={textValue || ''}` in the following.
https://github.com/mattermost/mattermost/blob/master/webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx#L166-L174

When `value = 0`, 0 is considered as falsy and `textValue || ''` will return `''`, so 0 is disappeared. It's also needed to think about  behavior of [`checkDialogElementForError`](https://github.com/mattermost/mattermost/blob/master/webapp/channels/src/packages/mattermost-redux/src/utils/integration_utils.ts#L12) when 0 is set.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54858.

**Comment by marianunez** [comment]
@kaakaa would you be open to submitting a PR for this issue?

**Comment by kaakaa** [comment]
@marianunez Sure, I'll work for this.
