### ISSUE TITLE
[Bug]: Linux Client can not handle similar server URLs anymore.

### ISSUE THREAD

**Issue by drittelhacker** [mattermost/mattermost#24885]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.1 

### Operating System

Ubuntu (tested 20.04 and 22.04 both x64)

### Mattermost Server Version

8.0.1

### Steps to reproduce

Add 2 servers running on the same base URL, such as:
https://my.domain/server-one
https://my.domain/server-two

Have the same user name on both (can not say if the same happens with different user names)

### Expected behavior

Both servers work fine next to each other. (Which, in fact, two more servers at completely different locations do in the same client)

### Observed behavior

As soon as the second server authenticates, both sessions get logged out saying they expired. (The two additional sessions on the other servers keep running fine)

### Log Output

```shell
Nothing out off the ordinary.
```

### Additional Information

This seems to affect only fresh installations. I messed up my `.config/Mattermost` where I had inherited the setup from earlier client versions, which worked. When I started over with a clean folder, this started happening. I have seen this on 2 machines now. For both of them, I do not have backups of the working folders, though.

**Comment by amyblais** [comment]
Closing for now as we haven't been able to prioritize/reproduce this,
