### ISSUE TITLE
PDF preview: Fields in PDF form appear to be empty although they contain data.

### ISSUE THREAD

**Issue by christianhueserhzdr** [mattermost/mattermost#24895]
#### Summary
Filled-out Fields in PDF form are empty if displayed in PDF preview.

#### Steps to reproduce
Open a PDF in PDF preview with filled-out fields.

#### Expected behavior
All data contained in PDF form should be displayed.

#### Observed behavior (that appears unintentional) 
Fields containing data are empty.

**Comment by amyblais** [comment]
Hi @christianhueserhzdr, what Mattermost server version are you on?

Opened https://mattermost.atlassian.net/browse/MM-54924.

**Comment by christianhueserhzdr** [comment]
Dear Amy @amyblais, we are using Mattermost server version 7.10.5 at the moment. Thank you very much for opening this ticket.

**Comment by SimeonEhrig** [comment]
Dear @amyblais I'm the user who had the problem. First I contacted @christianhueserhzdr to solve the problem internally. Now, he opened this PR. Therefore I can give also some information. Here is a reproducer pdf. It was filled out with Firefox 118.0.2

[testantrag2.pdf](https://github.com/mattermost/mattermost/files/12882649/testantrag2.pdf)

**Comment by hmhealey** [comment]
I don't know much about PDFs and why this would happen, but it feels like a good first step for this would be to update pdfjs-dist to the latest version.

We're using 2.15.349 currently, and the latest version is 3.11.174 at the moment. Since this is a major version, extra care needs to be taken to make sure it doesn't break anything. I'm seeing some stuff about dropping support for older browsers in their docs, so hopefully that doesn't affect any that we still support.

**Comment by sinansonmez** [comment]
@hmhealey I tested locally. Upgrading the `pdfjs-dist` package to the latest version (3.11.174) fixed the issue. However, I checked their minimum supported browser versions, you can find a summary below. 

The only issue seems to be firefox. I was not also sure what is the minimum node version preferred for Mattermost?

| System  | Pdfjs         | Mattermost    |
|---------|---------------|---------------|
| Chrome  | 92+           | 116+          |
| Firefox | ESR (115+)     | 102+          |
| Safari  | 15.4+         | 16.2+         |
| node    | 18+           | 18+ (TBC)     |
| IE      | not supported | not supported |

Source for pdfjs-dist: https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs#L80-L89
Source for mattermost: https://docs.mattermost.com/install/software-hardware-requirements.html

**Comment by KuSh** [comment]
You can view a difference of supported features between Firefox 102 and 115 here :

https://caniuse.com/?compare=firefox+102,firefox+115&compareCats=all

The only thing that could cause problem at first glance is offscreen canvas which seems to be safeguarded in pdfjs : https://github.com/mozilla/pdf.js/blob/898cc2e399e47ae70e08624a72852954030370b0/src/core/operator_list.js#L603

As stated in the [patch](https://github.com/mozilla/pdf.js/commit/6e3179994869d5713b3adabdea37966c3767b79b) that switched to Firefox ESR, this mostly requires that the browser natively support async/await which is the case of Firefox 102, and the 4 remaining features required by the "modern" build (optional chaining, nullish coalescing and private `class` fields/methods) are also supported by it

**Comment by hmhealey** [comment]
Thanks for checking that out! In that case, I'll double check, but I think we're fine to update the minimum version of Firefox to that We update Chrome/Edge to basically the latest version every once in a while, so I don't see why we'd hold Firefox back.

As for Node, we currently use 18.17 (which can be found in the `.nvmrc`), but I don't think that's actually a concern here unless the library is used in unit tests

**Comment by KuSh** [comment]
I can work on this if you want
