### ISSUE TITLE
[Bug]: Copying and pasting images doesn't work

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost#24903]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.1

### Operating System

macOS Ventura 13.6

### Mattermost Server Version

8.1

### Steps to reproduce

Right-click the image
Copy an image
Press Control+V in the text input window

### Expected behavior

The image should appear in the text field

### Observed behavior

No response

### Log Output

```shell
Log files, but no special logs
```

**Comment by amyblais** [comment]
Existing ticket https://mattermost.atlassian.net/browse/MM-54486.

**Comment by bitdessert** [comment]
@devinbinnie Isn't pasting with hotkeys (CmdOrCtrl+V) an issue with electron? Paste as a shortcut still doesn't work in browser-based web apps. However, we have implemented pasting with shortcuts in our desktop apps. It's temporary, of course, but it works.

**Comment by devinbinnie** [comment]
@bitdessert Yes, but the keyboard shortcuts are working correctly as intended for text. They should also work for images but there's an issue with the Web App, which is the one you reported.
