### ISSUE TITLE
canarytokens.org webhook not works 

### ISSUE THREAD

**Issue by cepheiden** [mattermost/mattermost#24904]
#### Summary
when generating tokens with  canarytokens.org via Webhook , error : invalid webhook supplied. 
In Slack it works with no issues.  

#### Steps to reproduce
Create token like aws, use webhook as notification option

#### Expected behavior
notification in Channel

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
![Screenshot 2023-10-12 172937](https://github.com/mattermost/mattermost/assets/15054746/f7fee9db-b592-4de7-b755-22ccf14ecab3)

#### Possible fixes
no so far

**Comment by amyblais** [comment]
Hi @cepheiden, can you help with more details on this issue?

1. What Mattermost server version are you on?
2. What documentation or instructions did you follow to set up this webhook with Mattermost?

**Comment by cepheiden** [comment]
![image](https://github.com/mattermost/mattermost/assets/15054746/800cbbfc-7c27-4caf-a0be-9bdd80fe9b4b)

just creating a new webhook url for a channel , and copy paste it to canarytokens.org

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55007.

**Comment by amyblais** [comment]
@cepheiden Is this documentation page helpful https://help.canary.tools/hc/en-gb/articles/360012787197-How-do-I-configure-notifications-for-a-generic-webhook-on-a-flock-?

**Comment by sbishel** [comment]
What happens if you run that curl command...
<img width="910" alt="Screenshot 2023-10-24 at 3 21 46 PM" src="https://github.com/mattermost/mattermost/assets/12704875/0fa2944d-6990-4c09-9185-f4509d234aec">

**Comment by cepheiden** [comment]
@amyblais , i am using the "free tier", there for i have no account to test. 
but as i mentioned , the free  version works with slack.
