### ISSUE TITLE
Incoming webhook can @ notify specific users but not @ all, here, or channel

### ISSUE THREAD

**Issue by mxroo** [mattermost/mattermost#24930]
#### Summary
We have a incoming webhook that is showing the text `@channel` but is not notifying everyone in the channel.

#### Steps to reproduce
Mattermost Enterprise Edition
Mattermost Version: 7.8.12
Database Schema Version: 113
Database: postgres

#### Expected behavior
We have a ticketing system, and we have a PHP script that calls on that taking system, then sends the result to Mattermost via a Mattermost incoming webhook. That web hook works in terms of the text that is sent from the script is what shows up in Mattermost, but notifications are not working for any of the group notifications all, here, or channel.

#### Observed behavior (that appears unintentional) 
The text said the user names, and `@channel` but did not notify the whole channel, just the two usernames.

#### Possible fixes
Are there any additional incoming webhooks settings that will allow an incoming webhook to notify all users?

![Screenshot 2023-10-13 at 1 36 44 PM](https://github.com/mattermost/mattermost/assets/5217174/aaee39d1-53c3-4475-96bc-dd4e818d11d1)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54938.

**Comment by san70sh** [comment]
I would like to investigate this issue and resolve it. Can I be assigned to this issue? @amyblais

**Comment by lindy65** [comment]
@mxroo - can you tell me how many members there are in the channel the webhook posts to? 

Wondering whether [this](https://docs.mattermost.com/configure/environment-configuration-settings.html#maximum-notifications-per-channel) could be the issue?

**Comment by san70sh** [comment]
@mxroo can you comment on the find by @lindy65 as it would help diagnose the issue at hand? Thanks!

**Comment by mxroo** [comment]
Thank you, there are six human members and one Hubot instance.

**Comment by mxroo** [comment]
Other calls to all, channel, or here work and send notifications. Just not this one.

**Comment by san70sh** [comment]
Hello @mxroo, I was unable to reproduce the issue on my local. Can you provide any debug logs generated when the webhook is run? Incoming webhooks can be debugged by following the steps in the **Troubleshoot incoming webhooks** section on this page [Incoming Webhooks](https://developers.mattermost.com/integrate/webhooks/incoming/)

**Comment by mxroo** [comment]
Hi @san70sh, thank you, I will work on getting you logs.
Thank you for the heads up on the lifecycle, I will make a plan for that upgrade.

**Comment by mxroo** [comment]
Thank you for your patience, we are working on upgrading.
Here are logs from today at 10am my time when this happened.

> {"timestamp":"2023-11-02 10:00:01.985 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"ping"}
{"timestamp":"2023-11-02 10:00:06.653 -04:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:171","method":"POST","url":"/hooks/6c9yqyc4w7bzdj9urzjz9bpxoo","request_id":"mnmbuweffb8imbgzek9obnfn7h","status_code":"200"}
{"timestamp":"2023-11-02 10:00:07.755 -04:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:171","method":"GET","url":"/api/v4/image","request_id":"cpq68knthp8kxpbnybsnzaubpc","status_code":"200"}
{"timestamp":"2023-11-02 10:00:07.810 -04:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:171","method":"POST","url":"/api/v4/users/status/ids","request_id":"xisuipbq97raikfbiss3ezdqpr","status_code":"200"}
{"timestamp":"2023-11-02 10:00:24.576 -04:00","level":"debug","msg":"Email batching job ran. Some users still have notifications pending.","caller":"email/email_batching.go:126","number_of_users":0}
{"timestamp":"2023-11-02 10:00:24.671 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_update_active_status"}
{"timestamp":"2023-11-02 10:00:24.691 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_update_active_status"}
{"timestamp":"2023-11-02 10:00:24.695 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_update_active_status"}
{"timestamp":"2023-11-02 10:00:31.493 -04:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:171","method":"POST","url":"/api/v4/users/status/ids","request_id":"oj4awu65tbfx5j6xiz71cjic7c","status_code":"200"}
{"timestamp":"2023-11-02 10:00:31.840 -04:00","level":"debug","msg":"Cleaning up command webhook store.","caller":"sqlstore/command_webhook_store.go:93"}
{"timestamp":"2023-11-02 10:00:31.848 -04:00","level":"debug","msg":"Cleaning up token store.","caller":"app/server.go:1243"}
{"timestamp":"2023-11-02 10:00:31.988 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"ping"}
{"timestamp":"2023-11-02 10:00:37.385 -04:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:171","method":"POST","url":"/api/v4/users/status/ids","request_id":"mdwaqt5dmpbsbfabkyof3stcja","status_code":"200"}
{"timestamp":"2023-11-02 10:00:53.209 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_update_active_status"}
{"timestamp":"2023-11-02 10:00:53.210 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_update_active_status"}
{"timestamp":"2023-11-02 10:00:53.211 -04:00","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"user_update_active_status"}
{"timestamp":"2023-11-02 10:00:54.576 -04:00","level":"debug","msg":"Email batching job ran. Some users still have notifications pending.","caller":"email/email_batching.go:126","number_of_users":0}

**Comment by mxroo** [comment]
We have upgraded to 8.1.6 and unfortunately this issue is still happening. Is there additional information that I could help provide?

**Comment by lindy65** [comment]
Hi @san70sh - do the logs that @mxroo posted above help debugging this issue?

**Comment by mxroo** [comment]
If there are things I could try to try to isolate the cause of the issue please let me know. I've tried using `@channel` or `@here` or `@all` or using the slack style notifications and all has the same effect of showing the text but not pinging everyone.

**Comment by mxroo** [comment]
I haven't heard back on this, please do let me know if there's any other information I can help provide to figure out why my setup is not behaving as it should.

**Comment by mxroo** [comment]
I believe I have tracked down the issue.
The original web hook that my script was using was made in 2016.
I made a new web hook, and pointed my script at that one instead, and now this is working as it should.
So, for future reference, a troubleshooting step would be to try making a new web hook.
