### ISSUE TITLE
Infinite loop when trying to load default avatar without network.

### ISSUE THREAD

**Issue by oOoBenoitoOo** [mattermost/mattermost#24953]
#### Summary

While browsing, if the user loses network connectivity and selects a channel where the default avatar is present.
The application falls into an infinite loop which increases the machine's memory.

#### Issue recording
https://github.com/mattermost/mattermost/assets/39456891/1f22d5ce-cdba-4d40-b37e-ae614f5e8ca3

#### Steps to reproduce
1 - Choose a channel with the default avatar already loaded.
2 - Switch the network "offline" in the chrome devtools.
3 - Switch between channel and come back on the previous with the default avatar.

#### Expected behavior
Don't fell in an infinite loop and print an error message.

#### Observed behavior (that appears unintentional) 
Infinite loop increasing the laptop memory.

#### Possible fixes
Error handler fells the system in an infinite loop by re-attributing the `src` that is not accessible due to the network connectivity.
https://github.com/mattermost/mattermost/blob/b6fd1b7bcfa61720bca077e3cb4511a2e42af73a/webapp/channels/src/components/widgets/users/avatar/avatar.tsx#L76
Do a fetch call to check if the path of the default avatar is available.
Something like this:
```
 onError={(e) => {
      const fallbackSrc = (url && isURLForUser(url)) ? replaceURLWithDefaultImageURL(url) : BotDefaultIcon;

      // Test if the image URL is reachable and returns a successful response.
      fetch(fallbackSrc).
          then(({ok}) => {
              if (ok) {
                  if (e.currentTarget.src !== fallbackSrc) {
                      e.currentTarget.src = fallbackSrc;
                  }
              }
          }).
          catch((error) => {
              console.error('Error while trying to load default avatar image URL:', error);
          });
  }}
```

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54966.

**Comment by oOoBenoitoOo** [comment]
@sjcode99 do you plan to submit the PR soon?

**Comment by sjcode99** [comment]
Hey team, i am not able to reproduce the issue in my local . did my setup in gitpod.
can anyone help me with the same.

**Comment by oOoBenoitoOo** [comment]
Hi @sjcode99,
You're right, it looks like the behavior has been fixed, I'm not able to reproduce it again due to the default BOT logo already loaded.
@amyblais I think you can close this issue.
Thanks
