### ISSUE TITLE
Externally managed users (GitLab) do not have their names updated

### ISSUE THREAD

**Issue by gdevenyi** [mattermost/mattermost#24956]
#### Summary
Changing a user's name on Gitlab does not result in changing the name in Mattermost, and we cannot manually change the name in Mattermost.

#### Steps to reproduce
In Community Edition 9.0.0, have a new user login via Gitlab with a typo in their name, correct their name on Gitlab backend.

#### Expected behavior
Name updates.

#### Observed behavior (that appears unintentional) 
Name does not update.

#### Possible fixes
- Allow manual fix by user or admin on mattermost
- Re-query user information on login.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54967.

**Comment by gdevenyi** [comment]
Tested how? It doesn't work for me. Please clarify.

**Comment by amyblais** [comment]
I'll add @enahum here to clarify.
