### ISSUE TITLE
System Console -> About doesn't show Mattermost version

### ISSUE THREAD

**Issue by gdevenyi** [mattermost/mattermost#24957]
I am aware (after googling) that there is another about interface in the main mattermost, but as the admin, this is the obvious place I would look.

#### Summary
System Console -> About doesn't show Mattermost version

#### Steps to reproduce
In Mattermost Community 9.0.0 go to System Console -> About

No version information is found.

#### Expected behavior
I can find version information here

#### Observed behavior (that appears unintentional) 
No version

#### Possible fixes
Add version info here.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54968.

**Comment by amyblais** [comment]
There are a few places in the system console where this displays. Workplace optimization tells admins if an update is available, then there’s also the system console > hamburger > about mattermost. We closed the Jira ticket as this is an improvement/feature.

@gdevenyi Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)? Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. You get **10** votes in the feature idea forum, and each one influences the future of the project.
