### ISSUE TITLE
Number in group at 0 with two open instances

### ISSUE THREAD

**Issue by oOoBenoitoOo** [mattermost/mattermost#24960]
#### Summary
If I create a group with two open instances(desktop & browser) with the same account, one of them stay to 0(in the group count)

#### Screenshot
<img width="2996" alt="Screenshot 2023-10-16 at 17 36 16" src="https://github.com/mattermost/mattermost/assets/39456891/4a0daefa-d941-4743-9828-decad369f092">

#### Steps to reproduce
1 - Open 2 instances (desktop & browser) with the same account.
2 - In the browser, create a group with few people.

#### Expected behavior
Get the correct count members on both.

#### Observed behavior (that appears unintentional) 
Desktop count should be correct in the desktop app.

#### Possible fixes
Change this implementation: https://github.com/mattermost/mattermost/blob/1a12faaaaeca21162e85186dfb38d08fce16c6c0/webapp/channels/src/actions/websocket_actions.jsx#L1254
 to catch also `Constants.Preferences.CATEGORY_GROUP_CHANNEL_SHOW` like:
```
function addedNewDmUser(preference) {
    return [Constants.Preferences.CATEGORY_DIRECT_CHANNEL_SHOW, Constants.Preferences.CATEGORY_GROUP_CHANNEL_SHOW].includes(preference.category) && preference.value === 'true';
} 
```
(change the name of the method for consistency)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54976.

**Comment by oOoBenoitoOo** [comment]
Hi @amyblais , you can assign to me. Thanks

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this: https://github.com/mattermost/mattermost/issues/25067.
