### ISSUE TITLE
Changing channels during file upload breaks file upload behaviour

### ISSUE THREAD

**Issue by marcusburst** [mattermost/mattermost#25008]
#### Summary
If you upload a file attachment to channel A and switch to channel B before it uploads, the attachment will be part of your message in channel B and stay indefinitely pending in channel A.

#### Steps to reproduce
This is on Mattermost self-hosted version 8.1.3.

1. Upload a larger file into channel A
2. Whilst it's uploading, open channel B
3. The uploaded file is now able to be sent in channel B
4. Go back to channel A and the attachment is stuck in a pending state indefinitely

#### Expected behavior
File is uploaded in channel A's message and not available in any other channel.

#### Observed behavior (that appears unintentional) 
The file is accessible from other channels if you change channel whilst it's uploading and it also remains in a pending state indefinitely if you change channels whilst it's uploading.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55045.

**Comment by hmhealey** [comment]
New ticket link: https://mattermost.atlassian.net/browse/MM-54781
