### ISSUE TITLE
Mattermost is violating the SAML 2 core specs in regard to Entity Identifiers

### ISSUE THREAD

**Issue by SphericalBastards** [mattermost/mattermost#25041]
https://github.com/mattermost/mattermost/blob/2f5ca43158bb1838c032eba9ff51c45f16910a6b/server/public/model/config.go#L3782

Mattermost is incorrectly requiring a valid URL as an entityID (aka Issuer).  This violates the SAML2 core specs.  EntityID is defined in the specs as a URI, not a URL, and requiring this to be a valid URL breaks SAML integration with production IdPs that use a URI as an entityID.  Many of these IdPs have been in production for over a decade.

See the following reference:
https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

8.3.6 Entity Identifier

...The syntax of such an identifier is a URI of not more than 1024 characters in length..."

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55061.

**Comment by SphericalBastards** [comment]
Just noticed I incorrectly linked the line of code concerned here in the original report.  Should have been lines 3782-3784.

if *s.IdpDescriptorURL == "" || !IsValidHTTPURL(*s.IdpDescriptorURL) {
			return NewAppError("Config.IsValid", "model.config.is_valid.saml_idp_descriptor_url.app_error", nil, "", http.StatusBadRequest)
		}

**Comment by SphericalBastards** [comment]
Original report was edited to correct an incorrect link to the source.

**Comment by amyblais** [comment]
Thanks, updated the ticket.

**Comment by hanzei** [comment]
cc @JulienTant

**Comment by JulienTant** [comment]
Hi @SphericalBastards, we have a PR waiting for one last security review here: https://github.com/mattermost/mattermost/pull/24250

**Comment by mgmax** [comment]
Probably the issue can be closed now because the PR has been merged
https://github.com/mattermost/mattermost/pull/24250

**Comment by hanzei** [comment]
Good catch @mgmax. Closing
