### ISSUE TITLE
Never miss thread messages

### ISSUE THREAD

**Issue by marcungeschikts** [mattermost/mattermost#25149]
#### Summary
With setting "Collapsed Reply Threads", which offers a clear view when using threads, you can miss some messages inside a thread,  if you forget to click on the "follow" button for a thread. 

#### Context
It can happen when you have many channels and threads to follow.

#### Enhancement proposal
We missed an option by channel to follow all threads by default.
And then, if you  are not interested by the thread, you can decide to unfollow it.

**Comment by amyblais** [comment]
@marcungeschikts I believe this Help Wanted ticket covers what you're looking for https://github.com/mattermost/mattermost/issues/20519.

If it doesn't, would you like to [submit a new feature request](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

**Comment by marcungeschikts** [comment]
Hi @amyblais ,
indeed, this is the same feature request. 
So I close this one, thks
