### ISSUE TITLE
Cut off text in the Position field in the profile modal

### ISSUE THREAD

**Issue by abrawkin** [mattermost/mattermost#25182]
Hi!
In version ММ 8 we noticed that in the profile modal window when clicking on a username in the channel window the Position field is not displayed in full.

When editing a Profile, all the text is saved in full, but the text is cut off when shown in the channel window.
Example on the attached image.

Client MM version - 5.5.1  (mac & win)
Server MM version - 8.1.2

#### Summary
Unable to read the title of the Employee Position in its entirety

#### Steps to reproduce
- Open any channel
- Click on the employee's name in the channel
- Wait for the profile modal window to appear
- View the Position field
- The text in the Position field is cut off

#### Expected behavior
- Open any channel
- Click on the employee's name in the channel
- Wait for the profile modal window to appear
- View the Position field
- The text in the Position field is not cut off, but is transferred line by line.

#### Observed behavior (that appears unintentional) 
<img width="508" alt="scrn_2023-27-10" src="https://github.com/mattermost/mattermost/assets/43991227/adff36db-8c29-40b0-92f8-681b89e6805b">

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55180.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this https://github.com/mattermost/mattermost/issues/25243.
