### ISSUE TITLE
Webapp: does not dismiss posts when rejected by plugin with DismissPostError

### ISSUE THREAD

**Issue by osyu** [mattermost/mattermost#25198]
#### Summary
Webapp [should dismiss/remove posts](https://github.com/mattermost/mattermost/blob/v9.1.1/webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts#L273-L279) when a plugin rejects the post with [`plugin.DismissPostError`](https://github.com/mattermost/mattermost/blob/v9.1.1/server/public/plugin/hooks.go#L61) from a MessageWillBePosted hook, but instead it does nothing.

Client: 5.5.1, Server: 9.1.1

#### Steps to reproduce
- Install [the Mattermost demo plugin](https://github.com/mattermost/mattermost-plugin-demo).
- Mention the demo plugin user (by default `@demo_plugin`) in a post anywhere other than the auto-created demo channel. The plugin [will reject the post with DismissPostError](https://github.com/mattermost/mattermost-plugin-demo/blob/v0.9.0/server/message_hooks.go#L47-L56).

#### Expected behavior
- The webapp dismisses the attempted post.

#### Observed behavior (that appears unintentional)
- The post remains, as if it had been sent successfully. There's no indication that it failed.

https://github.com/mattermost/mattermost/assets/8067918/884ea60b-45bf-424b-abfa-8a70a07db0a4

#### Possible fixes
May be a regression, since [this same bug cropped up when DismissPostError was first being implemented](https://github.com/mattermost/mattermost/issues/10883#issuecomment-495218637). It was fixed in https://github.com/mattermost/mattermost-redux/pull/844 but appears to have been partially undone by https://github.com/mattermost/mattermost-redux/commit/a9a44d557582a5b048c72d4eb2600d7d9032b3fd.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55200.
