### ISSUE TITLE
tilde ~ and at @ cause searches to return fewer results than expected

### ISSUE THREAD

**Issue by setharnold** [mattermost/mattermost#25223]
#### Summary

The `~` tilde and `@` at are the sigils to indicate channel names and usernames respectively throughout most of the interface. However, in the Search field, adding `~` to a channel name in the `in:` field will cause nothing to match. Adding `@` to a username in the `from:` field will cause nothing to match.

#### Steps to reproduce

- create a new channel, `~brand-new-channel`
- write `hello` to the new channel
- in the search field, `in:~brand-new-channel from:seth-arnold hello` --> `No results for "in:~brand-new-channel from:seth-arnold hello"`
- in the search field, `in:~brand-new-channel from:@seth-arnold hello` --> `No results for "in:~brand-new-channel from:@seth-arnold hello"`
- in the search field, `in:brand-new-channel from:seth-arnold hello` --> The new message that was sent a few seconds ago shows up in the search results pane.

#### Expected behavior
I expect prepending a single `~` on channel names or `@` on user names to not modify the search results. To my mind, they are part of the object identifier and when they are forbidden in the Search field it is very confusing.

#### Observed behavior (that appears unintentional) 
- `No results for "in:~brand-new-channel from:seth-arnold hello"`
- `No results for "in:~brand-new-channel from:@seth-arnold hello"`

Thanks

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55208.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
