### ISSUE TITLE
Boards: Can not swap person columns

### ISSUE THREAD

**Issue by kvaps** [mattermost/mattermost#25238]
#### Summary

Can not swap columns when grouping by Person is enabled

#### Steps to reproduce

- Create a new board
- Create few cards and assign them to different persons
- Switch dashboard to `Group By: Assignee`
- Try swapping columns with persons

#### Expected behavior

- Columns are swapped

#### Observed behavior (that appears unintentional) 

- Columns are not swapped

**Comment by amyblais** [comment]
Hi @kvaps, would you be open to re-opening this issue in the Focalboard repository https://github.com/mattermost/focalboard/issues?

**Comment by kvaps** [comment]
Thanks, just opened it here
https://github.com/mattermost/focalboard/issues/4923
