### ISSUE TITLE
Boards: sub-groups feature

### ISSUE THREAD

**Issue by kvaps** [mattermost/mattermost#25237]
Hello, thank you for amazing project!
There is one feature missing that is blocking me to start using it:

Sub-groups, the same way as notion do:
https://www.notion.so/releases/2021-10-19

![изображение](https://github.com/mattermost/mattermost/assets/7556217/be0c1478-0ef8-4ce3-b83f-40884ab57cbb)

Thanks!

**Comment by amyblais** [comment]
Hi @kvaps, would you be open to re-opening this issue in the Focalboard repository https://github.com/mattermost/focalboard/issues?

**Comment by kvaps** [comment]
Thanks, I just described it here:
https://github.com/mattermost/focalboard/issues/4922
