### ISSUE TITLE
Boards: Can not sort options in select dropdown

### ISSUE THREAD

**Issue by kvaps** [mattermost/mattermost#25239]
#### Summary

Eg. I want to sort possible statuses for a task:
![Screenshot 2023-10-31 at 12 20 22](https://github.com/mattermost/mattermost/assets/7556217/6ab9d903-0f4a-460c-8815-4f960a3c1fc8)

I can't move newly created "PAUSED" state to be between "TO DO" and "NEXT UP" states

#### Steps to reproduce
- Create new status
- Try to put it before existing

#### Expected behavior

- Any option to reorder dropdown list

#### Observed behavior (that appears unintentional) 

- Drag and Drop not work
- Switching board to `Group By: Status` and reordering columns also makes no effect on dropdown list

**Comment by amyblais** [comment]
Hi @kvaps, would you be open to re-opening this issue in the Focalboard repository https://github.com/mattermost/focalboard/issues?

**Comment by kvaps** [comment]
Thanks, just opened it here
https://github.com/mattermost/mattermost/issues/25239
