### ISSUE TITLE
Mattermost 9.2.0 fails to launch on Ubuntu 20.04 due to glibc errors

### ISSUE THREAD

**Issue by parnic-sks** [mattermost/mattermost#25278]
#### Summary
Mattermost 9.2.0 fails to launch due to glibc errors

#### Steps to reproduce
Extract Mattermost 9.2.0 from the release tgz file on Ubuntu 20.04.6 LTS (Focal) x86_64 (https://releases.mattermost.com/9.2.0/mattermost-9.2.0-linux-amd64.tar.gz)
Attempt to start bin/mattermost
Observe failure to launch

#### Expected behavior
Mattermost starts up normally

#### Observed behavior (that appears unintentional) 
Mattermost does not start up. Errors from journalctl:

```
Nov 02 13:30:25 sks-mattermost-10-10-7-145 systemd[1]: Starting Mattermost...
Nov 02 13:30:25 sks-mattermost-10-10-7-145 mattermost[1471949]: /opt/mattermost/bin/mattermost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/mattermost/bin/mattermost)
Nov 02 13:30:25 sks-mattermost-10-10-7-145 mattermost[1471949]: /opt/mattermost/bin/mattermost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/mattermost/bin/mattermost)
Nov 02 13:30:25 sks-mattermost-10-10-7-145 systemd[1]: mattermost.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 13:30:25 sks-mattermost-10-10-7-145 systemd[1]: mattermost.service: Failed with result 'exit-code'.
Nov 02 13:30:25 sks-mattermost-10-10-7-145 systemd[1]: Failed to start Mattermost.
Nov 02 13:30:28 sks-mattermost-10-10-7-145 systemd[1]: Stopped Mattermost.
```

This is the installed version of libc6 on this version of Ubuntu:

```
$ dpkg -l libc6
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version          Architecture Description
+++-==============-================-============-=================================
ii  libc6:amd64    2.31-0ubuntu9.12 amd64        GNU C Library: Shared libraries
```

#### Possible fixes
Something about compiling without CGO_ENABLED maybe? 🤷

**Comment by phoinixgrr** [comment]
Hey @parnic-sks  
We appreciate your report.

We've always shipped dynamically linked binaries. 

We have successfully replicated the problem on Ubuntu 20.04.6 Focal, confirming its existence, and we've already pinpointed the culprit. 

Rest assured, we are actively working on a solution.

**Comment by toninis** [comment]
Hey @parnic-sks thanks a lot for raising this . We found the issue and we are working on a fix . 

Can you test from your side with https://mattermost-releases.s3.amazonaws.com/test-builds/master/enterprise/614a1f4a48765b7c45b42f93c399eb90abc0e833_d837b519d333fa0110b8e79cb313cb349294ea8e/mattermost-enterprise-linux-amd64.tar.gz that is is deployed properly ? 

The issue is specific to `Ubuntu 20.04` . We do not face this issue with `Ubuntu 22.04` and is tied against the version of glibc we compiled the application . 
In any case we are going to fix this 😄

**Comment by parnic-sks** [comment]
Yes, that launched successfully.

**Comment by gigawhitlocks** [comment]
Thank you @amyblais for y'all's attention to this issue, which I encountered as well. 

For posterity and anyone who finds this through Google, this issue affects Debian 11 (bullseye) as well, so if you encounter the above skip version 9.2.0 and upgrade directly to 9.2.1
