### ISSUE TITLE
Feature : Dark Mode toggle switch

### ISSUE THREAD

**Issue by VaibhavSharma24** [mattermost/mattermost#25330]
I want to add a toggle switch on right of navbar which can change the theme into dark mode it will enhance the UI

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @VaibhavSharma24,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
