### ISSUE TITLE
Convert ./components/widgets/popover/index.tsx from Class Component to Function Component

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost#25359]
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-55330

**Comment by 0xJamin** [comment]
Hi, there seems to be no PR yet for this issue. Can I take it up?

**Comment by larkox** [comment]
@aarushis18 are you still working on this?

**Comment by 0xJamin** [comment]
Hi @larkox  I'm currently running into error when trying to set up the project locally:

<img width="1512" alt="Screenshot 2023-11-23 at 6 13 09 PM" src="https://github.com/mattermost/mattermost/assets/34829458/f2a1277a-a0e9-4753-a9d5-d7aa47f9b978">

I'd highly appreciate any pointers on how to resolve this issue🙏🏽

**Comment by larkox** [comment]
@0xJamin Try what was proposed in this thread and let me know if it works for you: https://community.mattermost.com/core/pl/3jj68zc7bfypifwxofozouau8c

**Comment by 0xJamin** [comment]
@larkox  Thanks it helped
