### ISSUE TITLE
Duplicate operationId SaveAcknowledgementForPost in openapi description document

### ISSUE THREAD

**Issue by commonism** [mattermost/mattermost#25384]
#### Summary
The OpenAPI Description Document at https://api.mattermost.com/ is invalid as the operationId SaveAcknowledgementForPost is not unique.

#### Steps to reproduce
```python
from pathlib import Path

from aiopenapi3 import OpenAPI, FileSystemLoader
from aiopenapi3.plugin import Document

class FixDD(Document):
    def parsed(self, ctx: "Document.Context") -> "Document.Context":
        ctx.document["paths"]["/api/v4/users/{user_id}/posts/{post_id}/ack"]["delete"]["operationId"] = "DeleteAcknowledgementForPost"
        return ctx

def test_mm():
    api = OpenAPI.load_file(url="https://mymattermost.org", path=Path("tests/data/mattermost-openapi3.json"), loader=FileSystemLoader(Path(".")), plugins=[FixDD()])
```

#### Possible fixes
https://github.com/mattermost/mattermost/blob/5e62ba8cccecb8603bb4aa6d2d4763b9ae205b65/api/v4/source/posts.yaml#L976
https://github.com/mattermost/mattermost/blob/5e62ba8cccecb8603bb4aa6d2d4763b9ae205b65/api/v4/source/posts.yaml#L1020

Rename the delete operation to DeleteAcknowledgementForPost.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55402.

**Comment by hmhealey** [comment]
Hi @commonism, since you found the location of those, would you be interested in submitting a fix for that?

**Comment by Alpha-4** [comment]
Hi, can i have this?

**Comment by commonism** [comment]
I won't object.
