### ISSUE TITLE
Remote marketplace no longer working with 9.2.2

### ISSUE THREAD

**Issue by domibarton** [mattermost/mattermost#25385]
#### Summary

When using the Docker image `mattermost/mattermost-team-edition:9.2.2`, the remote marketplace no longer works.  
The remote marketplace wasn't even displayed. I followed the [plugin configuration settings](https://docs.mattermost.com/configure/plugins-configuration-settings.html), especially the [enable remote marketplace](https://docs.mattermost.com/configure/plugins-configuration-settings.html#enable-remote-marketplace).

Without setting anything plugin-specific related, the `Enable Remote Marketplace` isn't even displayed in the system console.  
After setting `MM_FEATUREFLAGS_STREAMLINEDMARKETPLACE=false` (as suggested for `9.0`, not clear that we need to set this for `9.2`?) and `MM_PLUGINSETTINGS_ENABLEUPLOADS=true`, the remote marketplace is displayed and enabled in the System Console again. However, no remote plugins are displayed and can be installed. 

Connectivity in the container itself is given:

```bash
mattermost@bf25fd27d0c9:~$ curl https://api.integrations.mattermost.com
{"message":"Missing Authentication Token"}
```

#### Steps to reproduce

- Use `mattermost/mattermost-team-edition:9.2.2`
- Set `MM_FEATUREFLAGS_STREAMLINEDMARKETPLACE=false`
- Set `MM_PLUGINSETTINGS_ENABLEUPLOADS=true`

#### Expected behavior

Remote marketplace / plugins can be installed again.

#### Observed behavior (that appears unintentional) 

Only a few plugins (shipped w/ Mattermost) are displayed:

![image](https://github.com/mattermost/mattermost/assets/4124099/63f1dd9d-4e21-4252-88c3-e99f75d81197)
![image](https://github.com/mattermost/mattermost/assets/4124099/9bf1ddac-cbcb-4aac-ad3a-ce3d8b4f3f4f)

#### Possible fixes

Downgrade?

**Comment by amyblais** [comment]
@domibarton What version did you upgrade from?

**Comment by amyblais** [comment]
@domibarton In v9.0, Mattermost Boards and various other plugins have transitioned to being fully community supported, but you can install those plugins via the System Console. You can find more details here https://forum.mattermost.com/t/upcoming-product-changes-to-boards-and-various-plugins/16669.

**Comment by domibarton** [comment]
> > @domibarton What version did you upgrade from?
> 
> From `mattermost/mattermost-team-edition:7.8`

Just tried a fresh install with `9.2.2`, same error :/

**Comment by calebroseland** [comment]
> Expected behavior
Remote marketplace / plugins can be installed again.

> Observed behavior (that appears unintentional)
Only a few plugins (shipped w/ Mattermost) are displayed:


Hi @domibarton, are you seeing any error messages in Mattermost? The screenshots show what I would expect given the version and configurations you referenced.

As Amy [mentioned](https://github.com/mattermost/mattermost/issues/25385#issuecomment-1803824274) above, a number of plugins were moved to being fully community supported and were hence removed from the remote marketplace hosted at https://api.integrations.mattermost.com/. The in-app marketplace uses the endpoint https://api.integrations.mattermost.com/api/v1/plugins to retrieve the plugin listings, and I believe this is returning the correct results.

https://mattermost.com/marketplace/ contains links to many additional plugins that can be downloaded and installed via the System Console (including those plugins that were removed from https://api.integrations.mattermost.com).
