### ISSUE TITLE
Incorrect alignment of horizontal divider in sidebar

### ISSUE THREAD

**Issue by rahulsuresh-git** [mattermost/mattermost#25396]
#### Summary
I noticed that the horizontal divider in the sidebar isn't uniformly aligned with the dividing section on the left hand side. Not sure if this is intentional or if it's a bug.
<img width="236" alt="image" src="https://github.com/mattermost/mattermost/assets/22114682/4e21c8e1-882b-4988-b1b3-ab0b57988c89">

#### Steps to reproduce
v9.2.2 (latest version)

#### Expected behavior
The divider on the right hand side (sidebar) should perfectly align with the dividing section on the left.

#### Possible fixes
Can be fixed via vertical padding/margin modifications.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55438.
