### ISSUE TITLE
Not Enough Length of the Field for Email Domains in "Only specific email domains can join this team" setting

### ISSUE THREAD

**Issue by menanggung** [mattermost/mattermost#25417]
#### Problem Description:
Currently, when attempting to configure the "Only specific email domains can join this team" setting through the Mattermost System Console, it is observed that the field for specifying email domains has a limitation of 500 characters. This poses difficulties in managing a large number of domains, requiring manual addition and removal.

#### Expected Behavior:
It is suggested to increase the maximum character limit in the "Only specific email domains can join this team" field to facilitate the management of a large number of domains. This improvement will allow users to more efficiently manage the list of allowed email domains without the need for manual intervention for each domain.

#### Steps to Reproduce:
Navigate to the Mattermost System Console.
Go to the "Teams" tab.
Select the option "Only specific email domains can join this team."
Observe the 500-character limitation when entering email domains.

#### Additional Information:

1) Mattermost Server: 8.1.2
2) When attempting to bypass the character limit by updating the database directly, an error is encountered, stating that the value is incorrectly set.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55477.

**Comment by Emil-Carlsson** [comment]
Hi! I would like to work on this issue :D

**Comment by hossain-sazzad** [comment]
I want to pick it up? @amyblais can you assign it to me please?

**Comment by hossain-sazzad** [comment]
@amyblais I did not find the options at teams tab as specified in the description
![Uploading Screenshot 2024-02-27 at 11.55.34 AM.png…]()

**Comment by amyblais** [comment]
Did you navigate to System Console > User Management > Teams > Edit (for any team) > Team Management?

**Comment by hossain-sazzad** [comment]
> Did you navigate to System Console > User Management > Teams > Edit (for any team) > Team Management?

@amyblais Thanks. Found it. So how many characters we want to allow now? Currently it is 500.

**Comment by amyblais** [comment]
I'm not sure, would you be open to posting this question at https://community.mattermost.com/core/channels/tickets or at https://community.mattermost.com/core/channels/developers on our community server?

**Comment by hossain-sazzad** [comment]
> I'm not sure, would you be open to posting this question at https://community.mattermost.com/core/channels/tickets or at https://community.mattermost.com/core/channels/developers on our community server?

https://community.mattermost.com/core/channels/tickets/rdzybuyx8fg158t5ibh4c74bgo

I have posted this the day before yesterday. Didn't get any response yet. @amyblais

**Comment by amyblais** [comment]
I noticed that another community member previously claimed this Issue before we had had triaged this internally, so our team may not yet know what the ideal character limit should be. I'm thinking of moving this back to internal triage, and maybe you'll find another Issue to work on in the meanwhile?

**Comment by amyblais** [comment]
Closing for now as our team hasn't been able to prioritize/reproduce this,
