### ISSUE TITLE
Recently joined channel on mobile app does not appear on the desktop client

### ISSUE THREAD

**Issue by unaimed** [mattermost/mattermost#25413]
#### Summary
A recently joined channel on mobile app does not appear on the desktop client sidebar list

#### Steps to reproduce
1. Join a channel on mobile android app
2. Look for channel in channel list (sidebar) on desktop client

#### Expected behaviour
Joined channel appears in channel list (left sidebar) on desktop client

#### Observed behaviour (that appears unintentional) 
Channel list is unchanged 

#### Possible fixes
Workaround: open and close the channel list in the desktop client

#### Version Information

**Mobile Client:**
App Version: 2.9.1 (Build 6000491)
Server Version: 9.2.2 (Build 6801073174
Datenbank: postgres
Version des Datenbankschemas: 113

on Pixel 6a, Android 14

**Desktop Client**
Mattermost-Version: 9.2.2
Datenbankschema-Version: 113
Build-Nummer: 6801073174
Datenbank: postgres

on Mac OS X 14.0 (23A344) M1

**Comment by amyblais** [comment]
Hi @unaimed, what Mattermost desktop app version are you on?

**Comment by unaimed** [comment]
Version 5.4.0 (5.4.0)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55485.

**Comment by hmhealey** [comment]
Hi @unaimed. To get a better idea of what you're seeing here, we could use some more details if possible.

1. Are you seeing this with a public/private channel or with a DM/GM channel?
2. You said that closing and opening the channel list fixed it. I'm not sure what you mean by that, so could you elaborate a bit on that? Do you mean that you open the Browse Channels modal or that you expand and collapse the Channels section in the sidebar?
3. If you could, is it possible to get a video of what this looks like on the desktop client?

**Comment by unaimed** [comment]
Hey @hmhealey,

1. I was seeing the problem with a public channel
2. I meant collapse and expand the channels section in the sidebar
3. I can't provide a video right now, but I am trying to provide on in the upcoming days.

Greetings

**Comment by hmhealey** [comment]
Thanks for those details! I might have an idea about why that channel didn't appear in the sidebar, but we haven't had a chance to look into this yet, so if you happen to catch it on video, that'll be helpful when we get to this

**Comment by unaimed** [comment]
Here is a video of a similar problem with a private channel, but this time I could not get the channel to show up on the mac desktop app, even if I wrote in the channel:

Video showing the channel on mobile:
https://github.com/mattermost/mattermost/assets/3675674/a503ae76-aae4-48ef-b0a8-5eff4687ecbe


Video not showing the channel on the mac desktop app
https://github.com/mattermost/mattermost/assets/3675674/829169f2-c3ad-44e9-8b65-5be19cdac33c
