### ISSUE TITLE
Threads with many replies causes slowdown and failed messages

### ISSUE THREAD

**Issue by LogFlames** [mattermost/mattermost#25414]
#### Summary
Long threads causes messages to fail to send, requiring many retries and abnormally high CPU usage.

#### Steps to reproduce
1. Create a thread with a lot of replies. 

On our server we have a thread with around 5000 replies, which is now almost impossible to use due to failing messages, but the issues started to appear (altough less severe) at around 3000 replies.

Version: 8.1.2
Database: Postgres

#### Expected behavior
That no slowdown would occur. Messages would send almost instantly as they do in newly created threads and the CPU usage would not be noticibly affected.

#### Observed behavior (that appears unintentional) 
Messages often fail to send, both on android, ios, and in the webbrowser. They appear as sent but only for the person who sent them (guessing they werent really sent). Messages ”jump down” and appear in the wrong order. The server has very high CPU usage (normally around 10%, when writing in the long thread it jump to 60-70%).

![IMG_0413](https://github.com/mattermost/mattermost/assets/36220731/8bcc4416-ebce-48d3-9a5b-1aa0bfe96f35)

When sending from an app (android/ios) the red exclamationmark appears saying that the message failed to send. In the browser this message appears, although it isnt true as the original post is still there.

![IMG_0415](https://github.com/mattermost/mattermost/assets/36220731/b852f6a5-4c32-41b4-aa86-0e1962cb4188)

#### Possible fixes
My guess would be some indexing problem in the database, although I know far too little to say for sure.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55476.

**Comment by agnivade** [comment]
@LogFlames - Could you please share a CPU profile when you see a CPU spike on your server next time? Since you already have a long thread, maybe you can try to reply and artificially trigger the condition. https://docs.mattermost.com/scale/performance-monitoring.html#standard-go-metrics - (curl -o cpu.prof http://localhost:8067/debug/pprof/profile?seconds=10)

**Comment by LogFlames** [comment]
I have gotten the profile, github didn't seem to support the format so I zipped it, is there some eaiser way to share it?
[cpu.prof.zip](https://github.com/mattermost/mattermost/files/13352099/cpu.prof.zip)

I asked a couple of people to write in the thread so this profile is of multiple users trying to write (and view the thread) simultaniously.

As soon as a message is attempted to send the CPU spikes to 100%, and a `postgres 15/main: mmuser mattermost ::1([some sort of id]) SELECT` process appears in htop using between 13% and 80%.

**Comment by agnivade** [comment]
Ahh so it's actually the DB CPU which is spiking to 100% and not the app CPU right? From the profile you sent, there isn't anything happening. To debug what's happening in postgres, we'll need to check what queries are running in the DB at that time.

Would you mind triggering this again, and run a ` SELECT datname, pid, state, query, age(clock_timestamp(), query_start) AS age FROM pg_stat_activity WHERE state <> 'idle'  AND state <> 'idle in transaction'   AND query NOT LIKE '% FROM pg_stat_activity %' ORDER BY age;` when you get the CPU to 100%.

**Comment by LogFlames** [comment]
I attempted to send a few messages and got this:
```
  datname   |   pid   | state  |                                                                                                            query                                                                                                             |       age
------------+---------+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------
 mattermost | 2429181 | active | SELECT p.*, (SELECT count(*) FROM Posts WHERE Posts.RootId = (CASE WHEN p.RootId = '' THEN p.Id ELSE p.RootId END) AND Posts.DeleteAt = 0) as ReplyCount FROM Posts p WHERE (p.Id = $1 OR p.RootId = $2) AND p.DeleteAt = $3 | 00:00:02.466252
 mattermost | 2429153 | active | SELECT p.*, (SELECT count(*) FROM Posts WHERE Posts.RootId = (CASE WHEN p.RootId = '' THEN p.Id ELSE p.RootId END) AND Posts.DeleteAt = 0) as ReplyCount FROM Posts p WHERE (p.Id = $1 OR p.RootId = $2) AND p.DeleteAt = $3 | 00:00:06.980723
 mattermost | 2429543 | active | SELECT p.*, (SELECT count(*) FROM Posts WHERE Posts.RootId = (CASE WHEN p.RootId = '' THEN p.Id ELSE p.RootId END) AND Posts.DeleteAt = 0) as ReplyCount FROM Posts p WHERE (p.Id = $1 OR p.RootId = $2) AND p.DeleteAt = $3 | 00:00:12.88355
```

P.S. thanks for the debugging command! I was trying to enable logging but since this is in production I didn't want to restart the postgres server and am not that used to postgres, the SELECT increased my SQL knowlegde :)

**Comment by LogFlames** [comment]
I ran these SQL queries separately and they do take a bunch of time (more than a few seconds).

I'm trying to understand the query, it seems it counts the number of repies once for every message in the thread. Which would explain why its taking so long for 5000, if it is a O(n²) operation. I have too little knowlegde about mattermost in general, does each post in the thread need to have ReplyCount set? Or only the root-message? Then maybe something like this would work

```
SELECT p.*, (SELECT count(*) FROM Posts WHERE Posts.RootId = p.Id AND Posts.DeleteAt = 0) as ReplyCount FROM Posts p WHERE (p.Id = '35phy9rpridpjk8jf8mxabb7oc' OR p.RootId = '35phy9rpridpjk8jf8mxabb7oc') AND p.DeleteAt = 0;
```
which is way quicker, although you can feel its not instant.

**Comment by agnivade** [comment]
Can you run a `vacuum analyze posts` and see if that helps?

**Comment by agnivade** [comment]
And you are right, the query indeed loops 5000 times. There doesn't seem to be a need for that. I'll look into it.

**Comment by LogFlames** [comment]
I ran `vaccum analyze posts`  and it might have helped, when running the big SELECT after that it only takes 6-7 seconds. Although I only took the time of it before once, so I don't know how certain the 17 seconds was before.

The select with changes structure was superquick, only taking around 10ms!
```
mattermost=# explain analyze with replycount as (select count(*) as num from posts where rootid='35phy9rpridpjk8jf8mxabb7oc' and deleteat=0)
select id, rootid, createat, replycount.num from posts, replycount where id='35phy9rpridpjk8jf8mxabb7oc' or rootid='35phy9rpridpjk8jf8mxabb7oc' and deleteat=0;
                                                                             QUERY PLAN                                                                             
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=260.32..5724.48 rows=4336 width=55) (actual time=2.714..11.686 rows=5002 loops=1)
   ->  Aggregate  (cost=153.95..153.96 rows=1 width=8) (actual time=2.241..2.245 rows=1 loops=1)
         ->  Index Only Scan using idx_posts_root_id_delete_at on posts posts_1  (cost=0.42..143.12 rows=4335 width=0) (actual time=0.174..1.866 rows=5001 loops=1)
               Index Cond: ((rootid = '35phy9rpridpjk8jf8mxabb7oc'::text) AND (deleteat = 0))
               Heap Fetches: 244
   ->  Bitmap Heap Scan on posts  (cost=106.36..5527.14 rows=4336 width=47) (actual time=0.465..8.515 rows=5002 loops=1)
         Recheck Cond: (((id)::text = '35phy9rpridpjk8jf8mxabb7oc'::text) OR (((rootid)::text = '35phy9rpridpjk8jf8mxabb7oc'::text) AND (deleteat = 0)))
         Heap Blocks: exact=666
         ->  BitmapOr  (cost=106.36..106.36 rows=4336 width=0) (actual time=0.350..0.352 rows=0 loops=1)
               ->  Bitmap Index Scan on posts_pkey  (cost=0.00..4.43 rows=1 width=0) (actual time=0.040..0.040 rows=1 loops=1)
                     Index Cond: ((id)::text = '35phy9rpridpjk8jf8mxabb7oc'::text)
               ->  Bitmap Index Scan on idx_posts_root_id_delete_at  (cost=0.00..99.77 rows=4335 width=0) (actual time=0.310..0.310 rows=5001 loops=1)
                     Index Cond: (((rootid)::text = '35phy9rpridpjk8jf8mxabb7oc'::text) AND (deleteat = 0))
 Planning Time: 0.550 ms
 Execution Time: 12.148 ms
```

**Comment by agnivade** [comment]
Thanks I have a PR to fix this.

**Comment by LogFlames** [comment]
Awesome! Thanks for the quick debugging :heart:
