### ISSUE TITLE
hashtags do not work when they are inside the `pretext` of the `attachments` field

### ISSUE THREAD

**Issue by Michael1248** [mattermost/mattermost#25456]
#### Summary
hashtags do not work when they are inside the `pretext` of the `attachments` field

#### Steps to reproduce
by using incoming webhook, create a message with a hashtag in the `text` field
by using incoming webhook, create a message with the same hashtag in the `pretext` field of the `attachments`
by using incoming webhook, create a message with the same hashtag in the `text` field of the `attachments`

#### Expected behavior
when clicking the hashtag, three messages are shown on the right side of the screen

#### Observed behavior
when clicking the hashtag, only the first and the last message is shown on the right side of the screen

#### notes
first message and second message screenshot. only first message is shown on the right:
![image](https://github.com/mattermost/mattermost/assets/16817496/a5b874b9-acc6-4acd-93bc-89af2a7832f2)

**Comment by amyblais** [comment]
Hi @Michael1248,
1. What OS and version are you on? What Mattermost server version are you on?
2. Is this issue related to this issue https://github.com/mattermost/mattermost/issues/25337#issuecomment-1801312305?

**Comment by Michael1248** [comment]
Hi Amy,
1. Ubuntu 20.04.6 LTS; Mattermost Version: 7.10.2 Database Schema Version: 108 Database: postgres Licensed to: Mercedes-Benz
2. I don't think so. "Normal" hashtags are working.

**Comment by amyblais** [comment]
We currently support versions v8.1 (ESR) and v9.0+ ([reference doc](https://docs.mattermost.com/upgrade/release-lifecycle.html)). Would you be open to upgrading in a near-term to see if this issue still reproduces on a supported version?

**Comment by Michael1248** [comment]
we are trying to upgrade. let me come back to you when the transition is done.

**Comment by Michael1248** [comment]
they now updated the version to 9.2.2. In the info screen it says: 
Mattermost Version: ci
Database Schema Version: 113
but I don't know what "ci" means exactly.

tested the error - still exists

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56065.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this https://github.com/mattermost/mattermost/issues/25705.
