### ISSUE TITLE
 Running Ubuntu 22.04 on 64 bit computer, Software Updater fails due to Repositories problem.

### ISSUE THREAD

**Issue by johnaaronrose** [mattermost/mattermost#25483]
#### Summary
 Running Ubuntu 22.04 on 64 bit computer, Software Updater fails due to Repositories problem.

#### Steps to reproduce
Ubuntu 22.04 with Mattermost using organise.earth server.

#### Expected behavior
Ubuntu's Software Updater should not fail and should not fail. Using CLI 'sudo apt update' should NOT give warning on Mattermost repo: N: Skipping acquisition of configured file 'main/binary-i386/Packages', as repository 'https://deb.packages.mattermost.com/ jammy InRelease' doesn't support architecture 'i386' .

#### Observed behavior (that appears unintentional) 
Ubuntu's Software Updater intermittently fails without any warning or error. Using CLI 'sudo apt update' gives warning on Mattermost repo: N: Skipping acquisition of configured file 'main/binary-i386/Packages', as repository 'https://deb.packages.mattermost.com/ jammy InRelease' doesn't support architecture 'i386'.
john@Desktop:~$ sudo apt update
[sudo] password for john:
Hit:1 https://linux.teamviewer.com/deb stable InRelease
Hit:2 https://repo.protonvpn.com/debian stable InRelease
Hit:3 https://deb.torproject.org/torproject.org jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:5 https://ppa.launchpadcontent.net/gambas-team/gambas3/ubuntu jammy InRelease
Hit:6 http://gb.archive.ubuntu.com/ubuntu jammy InRelease
Get:7 http://gb.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:8 http://dl.google.com/linux/earth/deb stable InRelease
Hit:9 https://esm.ubuntu.com/apps/ubuntu jammy-apps-security InRelease
Hit:10 https://esm.ubuntu.com/infra/ubuntu jammy-infra-security InRelease
Hit:11 https://ppa.launchpadcontent.net/m-grant-prg/utils/ubuntu jammy InRelease
Hit:12 http://gb.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:13 https://dl.google.com/linux/chrome/deb stable InRelease
Ign:14 https://repo.vivaldi.com/stable/deb stable InRelease
Hit:15 https://deb.opera.com/opera-stable stable InRelease
Hit:16 https://updates.signal.org/desktop/apt xenial InRelease
Hit:17 https://repo.vivaldi.com/stable/deb stable Release
Hit:18 https://ppa.launchpadcontent.net/xtradeb/apps/ubuntu jammy InRelease
Hit:19 https://packages.element.io/debian default InRelease
Hit:20 https://deb.packages.mattermost.com/ jammy InRelease
Get:21 http://gb.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,158 kB]
Get:22 http://gb.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [525 kB]
Get:23 http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe i386 Packages [661 kB]
Get:24 http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [995 kB]
Hit:25 https://deb.packages.mattermost.com/ stable InRelease
Fetched 3,568 kB in 7s (534 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquisition of configured file 'main/binary-i386/Packages', as repository 'https://deb.packages.mattermost.com/ jammy InRelease' doesn't support architecture 'i386'

#### Possible fixes
No idea.

**Comment by amyblais** [comment]
Hi @johnaaronrose, I'm not familiar with the Ubuntu Software Updater. What Mattermost server version are you attempting to upgrade to? Do you see errors in the Mattermost server logs?

Perhaps you can write about this issue on one of our troubleshooting channels?
 - https://community.mattermost.com/core/channels/peer-to-peer-help
 - forum.mattermost.com

**Comment by amyblais** [comment]
Closing via https://forum.mattermost.com/t/running-ubuntu-22-04-on-64-bit-computer-software-updater-fails-due-to-repositories-problem-issue-25483/17347
