### ISSUE TITLE
Draft message not visible on deleted message

### ISSUE THREAD

**Issue by ochan12** [mattermost/mattermost#25484]
#### Summary
I started a reply to a message from someone else, then that message got deleted and now I have the draft counter on 2 (because I tried it again just to be sure), but no draft messages appear when clicking on it

#### Steps to reproduce
OS: Arch Linux 6.4.16-5-MANJARO
Client Version: 5.5.1
Mattermost Version: dev-linux-arm64-v9.0.1
Database Schema Version: 111
Database: postgres

1. from User A 's account make some root Post in a channel or DM
2. from User B’s account, Add some draft messages to the Posts made my User A
3. in User B Account move to Drafts section
4. From User A’s account delete the root posts
5. On User B’s account
    - The drafts will be visible
    - when we click on draft we can see the root message is deleted
    - Reload the drafts page
    - We can see the drafts page still showing the count

#### Expected behavior
I found [this issue](https://mattermost.atlassian.net/browse/MM-52797) where it says it was fixed but for me the badge is still showing draft messages. I would expect the same thing, the badge counter to disappear. 

![image](https://github.com/mattermost/mattermost/assets/20117588/1983c509-0c43-475a-b43c-f941ee6f7e78)

**Comment by amyblais** [comment]
Hi @ochan12, I wasn't able to reproduce this just now. Are you able to reproduce this on our community server https://community.mattermost.com/, which is on the latest version?

**Comment by ochan12** [comment]
Hi, @amyblais I was able to reproduce it in the community server by doing. 
(I tested it with messages between two different accounts)

1. Start a reply to a message and then change the focus out from the reply, creating a draft. 
2. Delete the first message. (Now if I go to the deleted message it appears as `(message deleted)` and on the drafts tab it still shows)
3. If I now close the app on the account writing the draft reply and reopen it, the `(message deleted)` disappears from the channel but the badge in the Drafts tab still shows a number, but no draft

**Comment by ochan12** [comment]
![image](https://github.com/mattermost/mattermost/assets/20117588/fa18c977-e357-4dc4-bbbf-0822b0ceb1ce)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55613.

**Comment by marianunez** [comment]
> @ochan12 after the root post is deleted and does the Draft count update properly after you click away from the Draft section to somewhere else?

Nevermind @ochan12, we were able to reproduce on our side. Thanks for reporting this. Will open this issue for `Up for Grabs` for community support

**Comment by devinbinnie** [comment]
> Thanks for looking into this issue @Utsav-Ladani!
> 
> @devinbinnie any thoughts on the approach above?

Seems good to me.

**Comment by devinbinnie** [comment]
@Utsav-Ladani

So the problem with 1) is that we can't guarantee that a draft was stored on the server in the first place, and this means that we could lose locally-stored drafts from when the app was disconnected.

What would 2) involve? I know we have the `channelId` and `threadId` which should be enough to define uniqueness.

**Comment by Utsav-Ladani** [comment]
Hello @devinbinnie 

I created a [draft PR](https://github.com/mattermost/mattermost/pull/25715) and left a comment to resolve. Can you please help me resolve it?

**Comment by Utsav-Ladani** [comment]
Thank you all 🎉

**Comment by marcin-kwiatkowski** [comment]
Is it really resolved? I am experiencing right now the same issue.

- MacOS 14.2.1, M1
- Client: 5.6.0
- Server: 9.4.2
- Self-hosted MM instance.

<img width="861" alt="Screenshot 2024-02-09 at 15 51 27" src="https://github.com/mattermost/mattermost/assets/39481325/d946374c-ee31-4283-b369-726ec2fdea11">

**Steps that were done:**
1. Person A wrote a message.
2. Person A deleted a message.
3. Person B saw the deleted message as `(message deleted)` in main window.
4. Person B opened thread window and wrote any letter. Draft has been saved.
5. Person B refreshed the window (cmd+R). The result can be seen on the screen below.

**Comment by marianunez** [comment]
@marcin-kwiatkowski the fix for this one should land in v9.6 server so seems to be expected to be still an issue in your server that is 9.4.2

**Comment by MarlinMr** [comment]
I'm running `v9.11.1`, still experiencing it.

**Comment by mustymenko** [comment]
Same issue with
```
Mattermost Version: 10.0.0
Database Schema Version: 125
Build Number: 10671348655
```
<img width="774" alt="image" src="https://github.com/user-attachments/assets/d5bb70fe-178e-4476-8346-fac58ac839ad">
