### ISSUE TITLE
Attachments "jump" conversations

### ISSUE THREAD

**Issue by andreineacsu** [mattermost/mattermost#25490]
#### Summary
Attachments "jump" conversations if the user selects another window while the files are in processing state.
Note that we're using the Antivirus plugin.

#### Steps to reproduce
1. Select a channel;
2. Upload 10 large files;
3. After some files were uploading and they are currently in "processing" jump to another conversation;
Result: the files appear in the second conversation and can be sent there too.

#### Expected behavior
Files should not jump conversations.

#### Observed behavior (that appears unintentional) 
the files appear in the second conversation and can be sent there too.

**Comment by amyblais** [comment]
Hi @andreineacsu, what Mattermost server version are you on? What OS and version are you using?

**Comment by andreineacsu** [comment]
Hi @amyblais. Current version is 9.2.2.
The server is running in Amazon Linux 2023. 
Happy to provide more info if needed.

**Comment by amyblais** [comment]
@andreineacsu Would you be open to testing if you can reproduce the issue on our community server here https://community.mattermost.com/?

I wasn't able to reproduce the issue just now, though I'm not sure if the community server has the Antivirus plugin enabled, but maybe you can help double-check this there too.

**Comment by andreineacsu** [comment]
@amyblais I was able to reproduce the issue. Please find a screen recording here: https://drive.google.com/file/d/1JcCr1TyCPjUKp14bQKP7QQ1bcvWSH78G/view?usp=sharing

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55650.
