### ISSUE TITLE
LaTeX baseline incorrect on mobile app

### ISSUE THREAD

**Issue by kc9jud** [mattermost/mattermost#25506]
LaTeX formulas have a shifted baseline on mobile app but not on mobile site.

App:
![image](https://github.com/mattermost/mattermost/assets/4133644/07cee62d-aece-4138-a63c-cd5d5c65068f)

Mobile site:
![image](https://github.com/mattermost/mattermost/assets/4133644/ba0ab8ec-028b-442f-bf93-fbd92edff6f6)

Example message text:
```
Text with formula $\hbar \omega$ inline
```

Version info:

Server Version: 8.1.3 (Build 8.1.3)
App Version: 2.10.0 (Build 492)
App Platform: ios
Device Model: iPhone14,6

**Comment by kc9jud** [comment]
Desktop looks fine (like mobile site).

**Comment by kc9jud** [comment]
@amyblais This is a different issue -- formulas are rendering here, but just differently (incorrectly) from on desktop and web.

**Comment by amyblais** [comment]
Got it, opened https://mattermost.atlassian.net/browse/MM-55649.
