### ISSUE TITLE
Mattermost docker fails because of wrong permissions

### ISSUE THREAD

**Issue by Neykuratick** [mattermost/mattermost#25534]
#### Summary
I followed every step from the [documentation ](https://docs.mattermost.com/install/install-docker.html) and when I start docker containers, they fail because of wrong permissions:

```
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
```

#### Steps to reproduce
1. `git clone https://github.com/mattermost/docker && cd docker`
2. `cp env.example .env`
3. Edit DOMAIN= to your domain (in my cace `chat.safimarket.space`)
4. `mkdir -p ./volumes/app/mattermost/{config,data,logs,plugins,client/plugins,bleve-indexes}`
5. `sudo chown -R 2000:2000 ./volumes/app/mattermost`
6. sudo docker compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d

#### Expected behavior
Mattermost should start

#### Observed behavior (that appears unintentional) 
Mattermost fails with these logs:

```
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-mattermost-1  | exec /entrypoint.sh: operation not permitted
docker-mattermost-1 exited with code 1
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1    | exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
docker-postgres-1 exited with code 1
```

#### Environment
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

**Comment by Neykuratick** [comment]
Turned out, I installed the wrong docker version, not the one from the docker install guide

**Comment by agnivade** [comment]
@Neykuratick - It would be great if you are up for updating the documention to add a check for the docker version? This would prevent future contributors from stumbling into the same issue.
