### ISSUE TITLE
"View in app" does not work on IOS when a subpath is used in the webserver

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/mattermost#25558]
#### Summary

"View in app" does not work on IOS when a subpath is used in the webserver.

#### Steps to reproduce

Run a Mattermost server on a subpath, eg `https://example.org/chat`.

Sign in to that instance on iOS.

Open `https://example.org/chat` and select `View in App`

#### Expected behavior

I expect the app to show me the server I am already logged into

#### Observed behavior (that appears unintentional) 

Mattermost iOS app launches the "Add server" dialog

**Comment by amyblais** [comment]
Hi @DanielHeath,
1. What Mattermost server version are you on?
2. What Mattermost mobile app version are you on?
3. What OS and version are you using?

**Comment by DanielHeath** [comment]
Sorry, this was my error - I had the wrong url format.
