### ISSUE TITLE
Can't scroll keyboard shortcut list with keyboard

### ISSUE THREAD

**Issue by pykenny** [mattermost/mattermost#25566]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Can't scroll "keyboard shortcut" dialog with keyboard when opened.

#### Steps to reproduce
1. In Mattermost desktop or browser, enter a server.
2. Open "keyboard shortcut" dialog.
3. Try scrolling the shortcut list dialog with keyboard.

#### Expected behavior
Dialog can be scrolled through when pressing Arrow Up/Arrow Down/PageUp/PageDown keys.

#### Observed behavior (that appears unintentional) 
Doesn't scroll. Dialog view stays at the top of the list.

#### Environment
Mattermost Server version: `9.2.2`, `9.3.0` (tried this issue on two different servers)
Mattermost Desktop version: `5.5.1`
OS: `macOS Ventura 13.6.1`
Browser: `Chrome 119.0.6045.159 (x86_64)`

#### Possible fixes
Haven't checked out the code yet.

Zooming out is a possible way to view the full list with keyboard, but that will hurt your eyes pretty much.

**Comment by amyblais** [comment]
Hi @pykenny,
1. What Mattermost server version are you on?
2. What OS and version are you using?
3. What Mattermost desktop app version are you on?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55973.

**Comment by pykenny** [comment]
@amyblais
I've updated issue description with additional environment information needed. ✔️

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this https://github.com/mattermost/mattermost/issues/25679.
