### ISSUE TITLE
link from nextcloud office docx to mattermost results in empty page

### ISSUE THREAD

**Issue by wlklch** [mattermost/mattermost#25605]
#### Summary
Clicking on a link in a docx in nextcloud office leading to a mattermost channel results in empty screen

#### Steps to reproduce
1) in a browser in mattermost click a link to a file of type docx in nextcxloud
2) as expected in a new tab of the browser nextcloud office opens the file
3) in this nextcloud office click on a link to mattermost e.g. a channel
4) as expected a new tab opens

#### Expected behavior
the new tab should contain the mattermost channel as encoded in the uri of the link
or the tab should show an error message, what went wrong

#### Observed behavior (that appears unintentional) 
you see very shortly a mattermost screen, which immediatly changes in a blank screen
however, the uri is correct, if you copy paste it from the blank screen to a new tab, it works fine
in the debugger console of the blank page you find the attached info
[console.txt](https://github.com/mattermost/mattermost/files/13529683/console.txt)

We observed this on firefox and chromium on linux and chrome on windows

#### Possible fixes
???

**Comment by wlklch** [comment]
Hello Amy

Mattermost Enterprise Edition
- Mattermost-Version: 9.2.3
- Datenbankschema-Version: 113
- Build-Nummer: 6961628977
- Datenbank: mysql

I'm using the webapp on 

Client System:
*  Kernel: 5.15.0-89-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.6.8
*   tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Chromium Version 119.0.6045.159 (Official Build) for Linux Mint (64-bit)
or Firefox 120.0(64 bit)
Same Problem on  chrome on windows

Is this what you need to know?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56048.

**Comment by amyblais** [comment]
@wlklch Would you also be able to share a sample docx file for testing? Are you also able to reproduce this issue on our community server here https://community.mattermost.com/?

**Comment by wlklch** [comment]
Hi Amy
1. go to channel https://community.mattermost.com/core/channels/wlklch (I hope I invited the correct Amy ... I was not allowed to create a public channel ...)
2. click on the link under **test**
3. you should land in next cloud office, and click there (several times) to branch to mattermost - and get an empty screen

If don't see the same thing, please come back to me

**Comment by amyblais** [comment]
Thank you!
