### ISSUE TITLE
Settings to activate "channel auto-follow threads" by default

### ISSUE THREAD

**Issue by ydirson** [mattermost/mattermost#25618]
Now that we have the great "channel auto-follow threads" feature requested in #20519, we have to get it applied. It is perfect as-is when we want the feature only on a handful of channels, but for those of us with many chans, and willing to selectively opt-out of the feature on a few ones, it would be really more comfortable to have a global flag causing all new chans to auto-follow threads by default.

Also, a migration-helper feature to activate the flag on all channels would help.  Better yet, a more general feature that would provide in a single dialog a flag state for all subscribed channels would be awesome, with the ability to tune those settings in one place, and with an obvious location for a "set/clear all" control.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @ydirson,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Closing as this can be tracked on UserVoice,
