### ISSUE TITLE
Taggable @users aren't scoped per team/space

### ISSUE THREAD

**Issue by olliescase** [mattermost/mattermost#25625]
#### Summary
Taggable @users aren't scoped per team/space

#### Steps to reproduce
1. Create a team with a limited subset of users
2. Within one of the channels in this team, try `@` tagging a user in a message
3. Observe that all users appear available for tagging, even if they are not in the team.

#### Expected behavior
For security, data-protection and practical reasons, you should only be able to tag users within the currently active team.

#### Observed behavior (that appears unintentional) 
The full list of users is available, resulting in this being almost unusable to external communications with clients.

#### Possible fixes
Create a scope for the query that limits the visible users to those with access to the active team.

**Comment by amyblais** [comment]
Hi @olliescase, what Mattermost server version are you on? Are those teams public or private teams?

**Comment by amyblais** [comment]
Hi @olliescase, just following-up on the above questions.

**Comment by amyblais** [comment]
Closing for now until we receive more details on the issue,
