### ISSUE TITLE
Channel List Issue

### ISSUE THREAD

**Issue by arkacent** [mattermost/mattermost#25645]
#### Summary
The last entry in the channel list occasionally does not contain any information in the Team field.

#### Steps to reproduce
The problem is present in the Mattermost Windows client:
1. Go to "System Console" > "Channels"
2. In my case, the last entry does not contain any information about which Team it refers to. If you go to the next page of channels (scroll through the list) and then go back to the first page, the problem disappears and you can see which team the channel belongs to.

I cleared the cache completely by deleting the directory "C:\Users\User\AppData\Roaming\Mattermost", it doesn't help.

My Mattermost Windows client version is 5.5.1, Mattermost Server version is 8.1.7

![channels_bug](https://github.com/mattermost/mattermost/assets/153010764/f658bc89-0a34-4e4e-9b26-8f75b85e4f4a)

**Comment by amyblais** [comment]
Hi @arkacent, what OS and version are you on? Does this happen both on webapp and desktop app?

**Comment by arkacent** [comment]
Hi, @amyblais our server OS is Ubuntu 20.04.5. On the web version I have not been able to reproduce this issue, seems problem persist just in Windows Desktop Client.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56067.

**Comment by amyblais** [comment]
Closing per developer comment on the ticket "Fix is too large for the value to take on right now."
