### ISSUE TITLE
User status get set to away after some time and it is not set back to "online" after interacting with the OS/Mattermost

### ISSUE THREAD

**Issue by leinardi** [mattermost/mattermost#25682]
#### Summary
User status get set to away after some time and it is not set back to "online" after interacting with the OS/Mattermost.

#### Steps to reproduce
Install the official Mattermost Desktop app for Linux (Version 5.5.1 commit: db8645b) or use the Web version on Chrome Version 119.0.6045.199

#### Expected behavior
When the status is set automatically to "away", interacting to Mattermost (e.g. sending a message or changing channel) should set it back to "online". Ideally, any interaction with the OS, like typing an email or writing some code in the IDE, should keep/change the status to "online".

#### Observed behavior (that appears unintentional) 
After the status is automatically set to "away", it is not changed back automatically to "online" even after interacting with the Web app or Desktop app: sending messages or changing channel does not change the status. The only way to workaround is to manually set the status back to Online, but this only works until it is set again to "away" automatically.

System info:
```
Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Kernel: 6.5.0-10010-tuxedo
arch: x86_64 bits: 64
Desktop: GNOME v: 42.9
```

**Comment by amyblais** [comment]
Hi @leinardi, what Mattermost server version are you on?

**Comment by amyblais** [comment]
Thank you, would you be open to upgrading to a supported version to see if the issue still reproduce on a recent version? We support versions v8.1.0 and newer versions.

**Comment by leinardi** [comment]
Office IT replied that, since they started working with Mattermost this summer and the migration tools were only tested with version 7.x, this is the version it will stay until the migration is fully completed (deadline is the end of this month). After that they will focus on upgrading to a supported version.
Would it be OK to keep this issue open open until the they are able to upgrade to a stable version (hopefully already next month)?

**Comment by amyblais** [comment]
@leinardi Yes, we can keep this issue open. We also have a community server here https://community.mattermost.com/, which is on the latest version, if you are open to doing some testing there too.

**Comment by leinardi** [comment]
Oh nice, I just joined, let's see if I experience the same issue there.

**Comment by leinardi** [comment]
Hi, I'm closing this issue because, after investigating further, it seems to be caused by the `gcal` plugin: the plugin is [setting the status to away](https://github.com/mattermost/mattermost-plugin-google-calendar/issues/55) automatically if I'm on a meeting.
