### ISSUE TITLE
Mattermost Boards is acting abnormal after update to 9.4

### ISSUE THREAD

**Issue by Arie6414** [mattermost/mattermost#25712]
- I have been looking at Mattermost for similar issues, but I could not find one myself. 
- It does not involve security issues
- I pretty new to this type of stuff, so try to forgive me the stupid questions I will ask :) 

#### Summary
After updating `Mattermost/mattermost-team-edition:release-7.11` to `Mattermost/mattermost-team-edition:release-9.4` suddenly Mattermost Boards is acting weird. Team boards are dissapearing in one account and they are still available in an other account. And downgrading does not resolve the issue (Or I am not downgrading in the correct way)

#### Steps to reproduce
`Mattermost/mattermost-team-edition:release-9.4`
`postgres:15` 
1. Log:`The database was created using collation version 2.31, but the operating system provides version 2.36.`
2. I solved this message, by export and build a new database with a new version.

#### Expected behavior
Assuming it was a DB issue: after building a new database, I expected that this issues was not happening anymore
Assuming it is a Mattermost update issue: After downgrading it should be resolved.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
<img width="223" alt="Scherm­afbeelding 2023-12-12 om 22 00 38" src="https://github.com/mattermost/mattermost/assets/129661911/634a9a12-9296-4602-9b25-2291e3cf1706">
All boards started moving to the category `boards` and then they started to disappear 

<img width="218" alt="Scherm­afbeelding 2023-12-12 om 22 01 00" src="https://github.com/mattermost/mattermost/assets/129661911/f9ad7e7e-8c02-4889-b974-87306cae531f">

Suddenly Boards is not a `plugin` anymore, but a `product`

#### Possible fixes
I really don't know where to look. 
Down here is a log snippet which occurs when opening `boards`
<img width="1783" alt="Scherm­afbeelding 2023-12-12 om 22 10 51" src="https://github.com/mattermost/mattermost/assets/129661911/1748dbcc-b659-45b0-b260-9458085211cc">

```
DBG api/boards.go:83 > timestamp=2023-12-12 21:08:01.935 Z msg=GetBoards product=boards teamID=jjr8aioa57fhxyzs6ypsbzoopr boardsCount=5
DBG api/blocks.go:158 > timestamp=2023-12-12 21:08:01.935 Z msg=GetBlocks product=boards boardID=barf9s8jky7y6irqed3ffstfc4e parentID= blockType= blockID= block_count=7
DBG ws/plugin_adapter.go:371 > timestamp=2023-12-12 21:08:01.936 Z msg=Command not implemented in plugin mode product=boards command=SUBSCRIBE_TEAM webConnID=4hazupn7jf88mnic6ucdr4wdoh userID=3aqi4e9f5jgd7rdrbqbfdgbfny teamID=jjr8aioa57fhxyzs6ypsbzoopr
DBG ws/plugin_adapter.go:371 > timestamp=2023-12-12 21:08:01.938 Z msg=Command not implemented in plugin mode product=boards command=SUBSCRIBE_TEAM webConnID=4hazupn7jf88mnic6ucdr4wdoh userID=3aqi4e9f5jgd7rdrbqbfdgbfny teamID=jjr8aioa57fhxyzs6ypsbzoopr
DBG api/templates.go:88 > timestamp=2023-12-12 21:08:01.938 Z msg=GetTemplates product=boards teamID=jjr8aioa57fhxyzs6ypsbzoopr boardsCount=2
DBG app/plugin_requests.go:200 > timestamp=2023-12-12 21:08:01.938 Z msg=CSRF Check failed for request - Please migrate your plugin to either send a CSRF Header or Form Field, XMLHttpRequest is deprecated path=/plugins/boards/api/v2/teams/jjr8aioa57fhxyzs6ypsbzoopr/categories/75tx4p6thzing7j3cbznb6ikqqr/boards/barf9s8jky7y6irqed3ffstfc4e ip=172.17.0.1:56198 session_id=gm4wyd45ij8ujecehqxhpk4dgw user_id=3aqi4e9f5jgd7rdrbqbfdgbfny
DBG api/auth.go:337 > timestamp=2023-12-12 21:08:01.939 Z msg=attachSession product=boards single_user=false
ERR api/api.go:187 > timestamp=2023-12-12 21:08:01.944 Z msg=category ID specified in input does not exist for user product=boards
ERR api/api.go:204 > timestamp=2023-12-12 21:08:01.944 Z msg=API ERROR product=boards code=500 error=category ID specified in input does not exist for user api=/api/v2/teams/jjr8aioa57fhxyzs6ypsbzoopr/categories/75tx4p6thzing7j3cbznb6ikqqr/boards/barf9s8jky7y6irqed3ffstfc4e
DBG api/auth.go:337 > timestamp=2023-12-12 21:08:01.970 Z msg=attachSession product=boards single_user=false
DBG api/members.go:74 > timestamp=2023-12-12 21:08:01.975 Z msg=GetMembersForBoard product=boards boardID=barf9s8jky7y6irqed3ffstfc4e membersCount=2
DBG app/plugin_requests.go:200 > timestamp=2023-12-12 21:08:01.987 Z msg=CSRF Check failed for request - Please migrate your plugin to either send a CSRF Header or Form Field, XMLHttpRequest is deprecated path=/plugins/boards/api/v2/teams/jjr8aioa57fhxyzs6ypsbzoopr/users ip=172.17.0.1:56196 session_id=gm4wyd45ij8ujecehqxhpk4dgw user_id=3aqi4e9f5jgd7rdrbqbfdgbfny
DBG api/auth.go:337 > timestamp=2023-12-12 21:08:01.987 Z msg=attachSession product=boards single_user=false
```

**Comment by amyblais** [comment]
Hi @Arie6414, would you be open to re-opening this issue in the Boards repo https://github.com/mattermost/focalboard/issues? Thanks,
