### ISSUE TITLE
Pagination on user list totally off

### ISSUE THREAD

**Issue by sungam0** [mattermost/mattermost#25725]
#### Summary
The pagination count on the "Mattermost Users" list (under System Console -> Users Management -> Users) seems to be a bit off.

#### Steps to reproduce
Open the Mattermost Users list. Have 26 users (may work for more, but that's our count, so... I don't know), so the pagination kicks in. Notice that on first page, it says "1 - 25 users of 26 total". Click Next, and notice that it now says "51 - 25 users of 26 total". And also that the 26th user isn't displayed, but instead the text "No users found".

#### Expected behavior
a) Pagination count to work.
b) See all my 26 users.

#### Observed behavior (that appears unintentional) 
See attached screenshots from page 1 and 2. Where's the last user? Why is pagination going in the wrong direction? Should be 26 - 50, right?

![Mattermost_pagination](https://github.com/mattermost/mattermost/assets/114743587/87182e8c-bd23-40b6-a9b9-d4dd56ef3922)

#### Possible fixes
Have no idea how you handle this, so sorry, no help here.

**Comment by amyblais** [comment]
Hi @sungam0,
1. What Mattermost server version are you on?
2. What OS and version are you on?

**Comment by sungam0** [comment]
Same as previous bug report you asked about.
________________________________
Från: Amy Blais ***@***.***>
Skickat: den 14 december 2023 18:36
Till: mattermost/mattermost ***@***.***>
Kopia: Magnus Hedberg ***@***.***>; Mention ***@***.***>
Ämne: Re: [mattermost/mattermost] Pagination on user list totally off (Issue #25725)

Du får inte e-post ofta från ***@***.*** Se varför det här är viktigt.<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @sungam0<https://github.com/sungam0>,

  1.  What Mattermost server version are you on?
  2.  What OS and version are you on?

**Comment by amyblais** [comment]
Closing for now - we can re-open this if it reproduces on a supported version.
