### ISSUE TITLE
Browse Channel Modal - Channel member count is zero as member_count endpoint returns 403

### ISSUE THREAD

**Issue by sinansonmez** [mattermost/mattermost#25739]
#### Summary
Browse Channel Modal - Channel member count is zero as member_count endpoint returns 403

#### Steps to reproduce
- Open browse channel modal
- Check the member count

#### Expected behavior
Member count should not be zero

#### Observed behavior (that appears unintentional) 
Member count is always zero

![Screenshot from 2023-12-15 16-21-20](https://github.com/mattermost/mattermost/assets/37421564/36cbbd13-9e89-483a-a49b-452924ef68de)

#### Possible fixes
Review the permissions required to call /api/v4/channels/stats/member_count endpoint.

**Comment by sinansonmez** [comment]
@amyblais

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56266.
