### ISSUE TITLE
Mattermost interactive button do not call URL

### ISSUE THREAD

**Issue by MedionSF** [mattermost/mattermost#25747]
Issue https://github.com/mattermost/mattermost/issues/21765 was closed, but I have the same behavior.

I followed the documentation to post an interactive message with actions pointing to specific endpoint (url).
But when I click on the buttons, it doesn’t call my endpoint, only POST /api/v4/posts/ie5kcd67ajnsbgwuektj1go1xo/actions/unpark-TOTO

Mattermost Version: 9.0.0

Here is my Json (url hidden)

{“channel_id”:“djqsklqjdkljsqkldjqlkdjlkqsjdlkjqld”,“message”:“Test”,“props”:{“attachments”:[{“text”:“Unpark coin(s):”,“actions”:[{“id”:“unpark-TITI”,“name”:“TITI”,“integration”:{“url”:“https://----”,“context”:{“action”:“unpark”}}},{“id”:“unpark-TATA”,“name”:“TATA”,“integration”:{“url”:"https://---------,“context”:{“action”:“unpark”}}},{“id”:“unpark-TOTO”,“name”:“TOTO”,“integration”:{“url”:“https://----------”,“context”:{“action”:“unpark”}}}]}]}}

Something's wrong.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56393.

**Comment by sbishel** [comment]
@MedionSF - Can you provide duplication steps? Its hard to understand the issue across multiple issues.  Thanks.

**Comment by sbishel** [comment]
Ok. I'm not familiar with the feature. I'll have to try it locally. Anything special about your installation?

**Comment by MedionSF** [comment]
@sbishel thanks !

Nothing special, it's a standard self hosted installation. Just downloaded and set up.

**Comment by mickmister** [comment]
Hi @MedionSF, thanks for filing this issue

> But when I click on the buttons, it doesn’t call my endpoint, only POST /api/v4/posts/ie5kcd67ajnsbgwuektj1go1xo/actions/unpark-TOTO

It is the case that when you click the button, the _frontend_ will communicate to the `/api/v4/posts/ie5kcd67ajnsbgwuektj1go1xo/actions` url. The server should then communicate to your URL afterwards, though there may be some issue causing this to not work properly.

Can you please take a look at your server logs to see if there is anything going on there? If your integration's server is running on localhost, you'll need to set the server config variable `ServiceSettings.AllowedUntrustedInternalConnections` to `localhost` https://docs.mattermost.com/configure/environment-configuration-settings.html#allow-untrusted-internal-connections

> Of course a 404.

Is there another part of the response like a message stating what was "not found"? The 404 could be being returned for a number of reasons, and there may be a detailed message in that response. Thanks

**Comment by MedionSF** [comment]
HI [mickmister](https://github.com/mickmister)

Interesting! Gonna check

**Comment by MedionSF** [comment]
Still the same...

`90.25.129.60 - - [27/Jan/2024:17:26:03 +0100] "POST /api/v4/posts/jjhxx6k1zpgtjpy8hg4tjabjce/actions/test-action HTTP/1.1" 404 297 "-" "Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.0" 0.000`

**Comment by MedionSF** [comment]
Ok it was simple but still hard to find. You can't use hyphen or underscore un the "id" field... Some clear documentation would have spared me many hours of test :)
