### ISSUE TITLE
Failure to send welcome email on create user

### ISSUE THREAD

**Issue by AmyNicole8715** [mattermost/mattermost#25774]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence
Failure to send welcome email on create user

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
create a user at our instance

#### Expected behavior
Describe your issue in detail
this error:
{"timestamp":"2023-12-19 04:29:04.082 Z","level":"warn","msg":"Failed to send welcome email on create user with inviteId","caller":"app/user.go:165","path":"/api/v4/users","request_id":"ujfoz3a64pggbyoqad6fgkfjby","ip_addr":"127.0.0.1","user_id":"","method":"POST","error":"unable to connect to the SMTP server: dial tcp [::1]:10025: connect: connection refused"}
{"timestamp":"2023-12-19 04:29:59.645 Z","level":"warn","msg":"Failed to send welcome email on create user with inviteId","caller":"app/user.go:165","path":"/api/v4/users","request_id":"e3socome4t8e3jrpwbkq3qeiih","ip_addr":"127.0.0.1","user_id":"","method":"POST","error":"unable to connect to the SMTP server: dial tcp [::1]:10025: connect: connection refused"}

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
When I tried creating a user

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Hi @AmyNicole8715,

1. What Mattermost server version are you on?
2. What OS and version are you on?

**Comment by amyblais** [comment]
Closing for now until we receive additional information on this issue.
