### ISSUE TITLE
Per-channel icons

### ISSUE THREAD

**Issue by houzefa-abba** [mattermost/mattermost#25783]
I hope this is the right place to ask for such an enhancement - I skimmed through issues both here and [for the desktop app](https://github.com/mattermost/desktop/issues), couldn't find this request.

I'd love the ability to set custom icons on my channels; those icons would appear in place of (or next to?) current globe :globe_with_meridians: / lock :lock: icons displayed in the sidebar, next to each channel title.

These icons could also be shown on each channel page, at the top next to the channel title.

Channel admins would be able to define these icons, same as they currently can change title / header / etc.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @houzefa-abba,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by houzefa-abba** [comment]
O thank you for the links! Looks like this feature had already been requested on <https://mattermost.uservoice.com/forums/306457-general/suggestions/45305710-icons-for-channels>; I added my votes in there!
