### ISSUE TITLE
Add possibility to add new members to direct messages or possibility to transform direct messages to a channel

### ISSUE THREAD

**Issue by aripekkaverta** [mattermost/mattermost#25841]
When adding ad-hock direct message you have to add all the members in the beginning when creating a direct message discussion. Quite frequently you end up discussing some issue briefly and then would like to add a new member to the discussion. Currently if you add a new member to the discussion then a new ad-hock direct message is created without the content from the previous one.

Suggest having a feature where you can either
a) add new members to direct messages conversation without loosing the conversation history
b) have a possibility to convert direct messages conversation into a permanent channel that would have the discussion history intact

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @aripekkaverta,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Closing as this can be tracked on UserVoice,
