### ISSUE TITLE
SQL errors after upgrade from 9.3.0 to 9.4.0

### ISSUE THREAD

**Issue by TwizzyDizzy** [mattermost/mattermost#25849]
#### Summary
After an upgrade from 9.3.0 to 9.4.0, some channels do not load in the UI, showing only "Loading..." but not showing any channel content.

This affects SOME channels, BUT NOT ALL channels. It does not SEEM (I cannot say for sure, as I didn't clean the app's caches / storage to verify) to affect loading the same channel on the Android app.

#### Steps to reproduce
I am currently not certain, whether this is reproducable by an upgrade from `9.3.0` to `9.4.0` or whether this is due to my database structure or content.

#### Expected behavior
Channel should be loading and showing content

#### Observed behavior (that appears unintentional) 
Spinning circle with the text "Loading..." animation

#### Possible fixes
I currently have no idea yet. But here are the logs from the Mattermost process that show up, when opening such a channel in the UI..

Also, feel free to direct me to dump my database content, so you can maybe see whether my database is corrupted, possibly (but not necessarily) by historic database migrations.

```
error [2024-01-04 23:26:42.937 +01:00] Unable to get the channel member.             caller="web/context.go:115" path=/api/v4/users/14ocq7hp3by9ic95f7zqr1mjcw/channels/girsg48543bqteppqphy97xhuw/posts/unread request_id=u1g9cyuub7n9zqt1m47m8gs5ky ip_addr=127.0.0.1 user_id=14ocq7hp3by9ic95f7zqr1mjcw method=GET err_where=getChannelMemberOnly http_code=500 error="getChannelMemberOnly: Unable to get the channel member., failed to get ChannelMember with channelId=girsg48543bqteppqphy97xhuw and userId=14ocq7hp3by9ic95f7zqr1mjcw: sql: Scan error on column index 13, name "schemeguest": sql/driver: couldn't convert <nil> (<nil>) into type bool"
```

#### Additional information
OS: Debian 12
Database: PostgreSQL 15
Architecture: x86_64

**Comment by streamer45** [comment]
@TwizzyDizzy Would you be able to confirm your current schema and the data for the specific entry failing?

Using `psql` client you can run:

```
\d+ channelmembers;
```

And

```sql
SELECT * FROM ChannelMembers WHERE ChannelId = 'girsg48543bqteppqphy97xhuw' AND UserId = '14ocq7hp3by9ic95f7zqr1mjcw';

**Comment by TwizzyDizzy** [comment]
Yes, of course, here you go:

**\d+ channelmembers;**

```
                                                   Table "public.channelmembers"
       Column       |          Type          | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
--------------------+------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 channelid          | character varying(26)  |           | not null |         | extended |             |              | 
 userid             | character varying(26)  |           | not null |         | extended |             |              | 
 roles              | character varying(256) |           |          |         | extended |             |              | 
 lastviewedat       | bigint                 |           |          |         | plain    |             |              | 
 msgcount           | bigint                 |           |          |         | plain    |             |              | 
 mentioncount       | bigint                 |           |          |         | plain    |             |              | 
 notifyprops        | jsonb                  |           |          |         | extended |             |              | 
 lastupdateat       | bigint                 |           |          |         | plain    |             |              | 
 schemeuser         | boolean                |           |          |         | plain    |             |              | 
 schemeadmin        | boolean                |           |          |         | plain    |             |              | 
 schemeguest        | boolean                |           |          |         | plain    |             |              | 
 mentioncountroot   | bigint                 |           |          | 0       | plain    |             |              | 
 msgcountroot       | bigint                 |           |          | 0       | plain    |             |              | 
 urgentmentioncount | bigint                 |           |          |         | plain    |             |              | 
Indexes:
    "channelmembers_pkey" PRIMARY KEY, btree (channelid, userid)
    "idx_channelmembers_channel_id_scheme_guest_user_id" btree (channelid, schemeguest, userid)
    "idx_channelmembers_user_id_channel_id_last_viewed_at" btree (userid, channelid, lastviewedat)
Access method: heap
```

**select statement**

```
         channelid          |           userid           | roles | lastviewedat  | msgcount | mentioncount |                 notifyprops                  | lastupdateat  | schemeuser | schemeadmin | schemeguest | mentioncountroot | msgcountroot | urgentmentioncount 
----------------------------+----------------------------+-------+---------------+----------+--------------+----------------------------------------------+---------------+------------+-------------+-------------+------------------+--------------+--------------------
 girsg48543bqteppqphy97xhuw | 14ocq7hp3by9ic95f7zqr1mjcw |       | 1704458170326 |     2517 |            0 | {"desktop": "default", "mark_unread": "all"} | 1704458170326 | t          | t           |             |                0 |         1787 |                  0
(1 row)
```

Cheers
Thomas

**Comment by streamer45** [comment]
Thanks for confirming @TwizzyDizzy. This is an issue we are addressing. In the meantime you could technically fix it by updating the `NULL` `schemeguest` entries in those database rows. 

I'd check how many these are:

```sql
SELECT COUNT(*) FROM ChannelMembers WHERE SchemeGuest IS NULL;
````

And consider updating them with: 

```sql
UPDATE ChannelMembers SET SchemeGuest = false WHERE SchemeGuest IS NULL;
```

**Comment by streamer45** [comment]
Created https://mattermost.atlassian.net/browse/MM-56465 to track this issue internally.

**Comment by TwizzyDizzy** [comment]
In my case there were roughly 800 occurrences. Executing your UPDATE statement seems to have fixed the issue. A colleague of mine also noted that leaving/re-joining the channel worked for him, though that is obviously no viable solution and does not even work for default channels, which do not allow leaving.

Thanks for addressing this!

Cheers
Thomas

**Comment by haivala** [comment]
Is it safe to run that `UPDATE ChannelMembers SET SchemeGuest = false WHERE SchemeGuest IS NULL;` and it will not break anything in the future?

**Comment by streamer45** [comment]
If anything it's half broken now. Yes it should be safe, but as usual with any DB operation, a backup is always recommended.

**Comment by haavardw** [comment]
Alternatively: Downgrading to 4.3.0 works as well (at least it did for us)

**Comment by streamer45** [comment]
Yes, downgrading can be an option as well given this is an issue introduced in 9.4

**Comment by agnivade** [comment]
Going to close this as the PR is now reverted and cherry-picked.
