### ISSUE TITLE
[Bug]: Text Not Changing Color Dark Themes

### ISSUE THREAD

**Issue by ericdrgn** [mattermost/mattermost#25856]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.6.0 commit aebafea (have seen since issue at least 5.5.1)

### Operating System

macOS 14.2.1 (Intel) and Linux PopOS 22.04

### Steps to reproduce

Using any dark theme results in text that is kinda dark grey and barely readable. The screenshot below uses a custom theme but any of the default themes do the same thing and changing to any color (though I am trying to do white #ffffff) produces the same result where it won't change in the main channel but it will work as expected in the thread view.

![image](https://github.com/mattermost/desktop/assets/60805441/dd7eb261-c1dd-4434-85fa-044c85ad52f5)

### Expected behavior

Main channel text color should adjust based on theme settings.

### Observed behavior

See above.

### Log Output

```shell
N/A
```

### Additional Information

Though not only on my specific theme I have my theme pasted below

`{"awayIndicator":"#f5ab00","buttonBg":"#386fe5","buttonColor":"#ffffff","centerChannelBg":"#000000","centerChannelColor":"#ffffff","codeTheme":"monokai","dndIndicator":"#d24b4e","errorTextColor":"#da6c6e","linkColor":"#5d89ea","mentionBg":"#1c58d9","mentionBj":"#1c58d9","mentionColor":"#ffffff","mentionHighlightBg":"#0d6e6e","mentionHighlightLink":"#a4f4f4","newMessageSeparator":"#1adbdb","onlineIndicator":"#ffffff","sidebarBg":"#000000","sidebarHeaderBg":"#000000","sidebarHeaderTextColor":"#dddfe4","sidebarTeamBarBg":"#000000","sidebarText":"#ffffff","sidebarTextActiveBorder":"#1592e0","sidebarTextActiveColor":"#ffffff","sidebarTextHoverBg":"#1e1e1e","sidebarUnreadText":"#ffffff"}`

**Comment by amyblais** [comment]
Hi @ericdrgn, what Mattermost server version are you on?

**Comment by ericdrgn** [comment]
@devinbinnie It isn't a web app issue, the web app and mobile apps are fine this is an issue with desktop apps. 

@amyblais sorry since it wasn't an issue for anything except desktop apps I didn't think that was relevant. I'm on 9.3.0

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56471.

**Comment by devinbinnie** [comment]
@ericdrgn Looking at the screenshots and the theme you provided this looks like an issue with our web app. There's nothing our Desktop App currently does to affect the colours used by the web app. Though it is possible that your OS might be doing something. I'm not super familiar with PopOS, does it have a built-in Dark Mode?

FWIW, I tried your theme on the latest master branch of both the web app/desktop app and I'm not able to reproduce what you're seeing. The only other difference is that I'm on macOS, so it's starting to look like PopOS might have something to do with it.

![image](https://github.com/mattermost/mattermost/assets/52460000/6abd4453-e188-4fc4-947d-5a2edb986f80)

**Comment by ericdrgn** [comment]
Thanks for the response, the screenshot was from the desktop app. As I mentioned in the report this issue happens with MacOS as well and only with the desktop app. I have another user using my server that experiences the same thing. If you aren't seeing the issue is there some way my server settings could be pushing out something like that?

**Comment by ericdrgn** [comment]
Knowing it was an issue specific to my server now I decided to purge my server cache and reload the configuration and everything has gone back to normal.

**Comment by ImreSzebelledi** [comment]
I have the exact same issue as you after updating to Gitlab 16.8 which includes Mattermost 9.3.0 except it is the same for the browser and the client app as well. Could you tell me how did you clear the cache of the server? The button in the System console does nothing.
