### ISSUE TITLE
Mattermost team edition - problem with different versions

### ISSUE THREAD

**Issue by karoolpl** [mattermost/mattermost#25858]
Hi,

I'm using mattermost almost since start. Now i'm using it on kubernetes, and everything was working fine, until last updates. I got big problem, when i set docker image for master, messages in channels with many messages loading very slow or not loading at all, when i switch back to version latest or 9.0 everything start to works just fine with one issue, no one can set his status and in log i can see:
```
ateUser","http_code":500,"error":"UpdateUser: We encountered an error finding the account., failed to get User with userId=omwdfph5dtfdtdq5hgbpj16m3w: missing destination name lastlogin in *model.User"}
```

also regarding of which version i use, i also get a lot of websocket errors:

```
{"timestamp":"2024-01-08 08:36:57.482 Z","level":"error","msg":"websocket routing error.","caller":"platform/websocket_router.go:97","seq":7,"user_id":"rpuse3wg67bzznc641wxabdaeh","system_message":"Nieznana akcja WebSocket.","error":"ServeWebSocket: Unknown WebSocket action."}
```

can you provide mi with some info what could be wrong?

I'm using kubernetes 1.28 on rocky linux, database postgres and local storage for data etc.

**Comment by mgraff** [comment]
Same issue here (using Team Edition, docker image and postgres).
Rollback from 9.4 to 9.3 works but users still can't update their preferences, and admins can't deactivate users.

**Comment by haavardw** [comment]
Upgrading to 9.4.1 resolved the issues for us
