### ISSUE TITLE
Deactivated Users Appearing in Manage Members (of Channel) List on iOS 

### ISSUE THREAD

**Issue by kkingslek** [mattermost/mattermost#25866]
Summary
When trying to add new members to a channel on iOS, all deactivated and activated users appear in the list.

Steps to reproduce
On iOS, open a channel in which you can add members, the list of users populates which shows both active and deactivated users. (App version 2.11.0 build 497, Server version 9.2.2 build 6801073174, database postgres, database scheme version: 113)

Expected behavior
Only active users should be listed when trying to add members

Observed behavior (that appears unintentional) 
![IMG_0136](https://github.com/mattermost/mattermost/assets/156071388/45e11065-f1d1-4e97-a4ce-99ceb0f9720d)

Issue originally reported by another customer yet Closed with "won't do". 
https://mattermost.atlassian.net/browse/MM-38044

This reduces usability on iOS which should make creating Channels and managing members even easier than the desktop version. 

Thank you

**Comment by amyblais** [comment]
Hi @kkingslek,

1. Are you able to reproduce this issue on our community server https://community.mattermost.com/?
2. Does uninstalling and re-installing the app help with the issue at all?

**Comment by kkingslek** [comment]
Hi Amy,

I have tested on the community version, the issue does not exist.

I have also tested on a test server hosted on premises which is 9.3 and the issue still exists.

I have removed the app config deployed by our MDM and the issue persists on both of our on-premise versions of Mattermost.

Any ideas?

Best,
Kyle


[Logo]<https://www.medincell.com/>
Kyle KINGSLEY
IT Manager
T : +33 7 63 88 41 48
3 Rue des Frères Lumière 34830 Jacou - France
[Address-book]<https://data.sigilium.com/signatures/rc6ow4wilxguixuokx6ofphiaxyk0rc/link> [Linkedin] <https://www.linkedin.com/company/medincell/>  [Twitter] <https://twitter.com/medincell>

[https://data.sigilium.com/system/announcements/full_images/000/037/961/normal/Signature_ApprovalVD.gif]<https://data.sigilium.com/signatures/rc6ow4wilxguixuokx6ofphiaxyk0rc/redirect_link>

This electronic message contains information and/or electronic files which may be privileged and/or confidential. This information is intended to be for the use of the individual(s) or entity named above. If you are not the intended recipient be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited. If you have received this electronic message in error, please notify us by email immediately. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of MedinCell.


On 9 Jan 2024, at 18:13, Amy Blais ***@***.***> wrote:


This Message Is From an Untrusted Sender
You have not previously corresponded with this sender.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/O2ZcZSr1yQ!uQ7AW7ZEYaoCpcylgpi9wzlc2AYXGFy3aZm4lier_9OIfYW0OPzz7r9Mfp-V8_v9bmSyS1TybFp0PgudXx4WwYq8hoOxEeyHIfw27TdLTPw1IBVvpwlU$>
Report Suspicious


Hi @kkingslek<https://urldefense.com/v3/__https://github.com/kkingslek__;!!O2ZcZSr1yQ!PLD8Bv3KuEMMKTxExojRSO4i2x81guzdWQeBFY9BCCJLWTNcVFzqRaJyfLre-8LosT5OoUlRu1BOVnRQZJjAXHZ7Rwo05j8$>,

  1.  Are you able to reproduce this issue on our community server https://community.mattermost.com/<https://urldefense.com/v3/__https://community.mattermost.com/__;!!O2ZcZSr1yQ!PLD8Bv3KuEMMKTxExojRSO4i2x81guzdWQeBFY9BCCJLWTNcVFzqRaJyfLre-8LosT5OoUlRu1BOVnRQZJjAXHZ7Yu_t8eM$>?
  2.  Does uninstalling and re-installing the app help with the issue at all?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56513.
