### ISSUE TITLE
Impossible to set a custom reminder on the same day of following months

### ISSUE THREAD

**Issue by rOt779kVceSgL** [mattermost/mattermost#25867]
#### Summary
Impossible to set a custom reminder on the same day of following months.

#### Steps to reproduce
1. Hover some message and click `More` to show the menu
2. Select `Remind` → `Custom`
3. In the `Set a reminder` dialog, set `Date` to the same day of the following months (supposing today is Jan 9, set the date to either Feb 9, Mar 9, ..., or Dec 9)
4. Click `Time` entry. You can see that only the following times are selectable in the popover (supposing it's 10:00 PM, you can only see `10:30 PM`, `11:00 PM`, `11:30 PM`)
5. Choose a time from the popover. You should see `Date` changed to today automatically.
6. Repeating the operation from 3. will result in the same situation, which means you can't set a custom reminder on the same day of following months.

#### Expected behavior
- In the step 4 above, you can see and select any time from 12:00 AM to 11:30 PM
- In the step 5 above, `Date` is not changed unexpectedly and thus you can set a custom reminder on the same day of following months

#### Observed behavior (that appears unintentional)
- In the step 4 above, you can only see and select the following times
- In the step 5 above, `Date` is changed to today unexpectedly, which results you can't set a custom reminder on the same day of following months

Screencast:

https://github.com/mattermost/mattermost/assets/156086581/afd1a3b7-5e47-4ddf-9a0c-e1fe3985a17b

### Platform information
- Mattermost Version: 9.5.0 (Mattermost Community Server)
- OS: macOS Sonoma 14.2.1 (23C71)
- Client: Google Chrome 120.0.6099.199 and Mattermost Desktop App 5.6.0 (commit: 1f6924c)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56512.
