### ISSUE TITLE
Concurrent map writes. Service down.

### ISSUE THREAD

**Issue by PalachN** [mattermost/mattermost#25903]
Service down
mattermost.service: Main process exited, code=killed, status=6/ABRT

We can share the log if required. More than 36 thousand lines

Jan 12 17:17:35 xxx mattermost[610961]: fatal error: concurrent map writes
Jan 12 17:17:35 xxx  mattermost[610961]: goroutine 497528410 [running]:
...
Jan 12 17:17:42 xxx  systemd[1]: mattermost.service: Main process exited, code=killed, status=6/ABRT

Mattermost Version: 9.0.0
Database Schema Version: 111

**Comment by amyblais** [comment]
Hi @PalachN,
1. Would you be open to upgrading to a newer version to see if it helps with the issue? We currently support v9.1 and later versions.
2. You might also like to do a search on our troubleshooting forum here https://forum.mattermost.com/ to see if any other users have faced a similar issue and have posted a solution.

**Comment by agnivade** [comment]
@PalachN - Please share the full 36K lines as an attachment. Thanks.

**Comment by amyblais** [comment]
Closing for now until we hear back,

**Comment by PalachN** [comment]
The problem recurred.

Apr 17 06:50:08 *** mattermost[1922501]: fatal error: concurrent map iteration and map write
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922515 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922523 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922532 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922543 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922551 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922560 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922626 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Failed with result 'exit-code'.

Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: postgres
