### ISSUE TITLE
Notifications that should not include message contents are including message contents

### ISSUE THREAD

**Issue by tibers** [mattermost/mattermost#25958]
I confirm this issue does not relate to security. I searched for [notification message contents](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/MM-22611?jql=project%20%3D%20%22MM%22%20and%20text%20~%20%22notification%20message%20contents%22%20and%20status%20%3D%20Open%20ORDER%20BY%20created%20DESC) in JIRA and sorted by "open" and did not see anything related.

#### Summary

When going into System Console -> Notifications (under Site Configuration) I have three options: 
* Generic description with only sender name 
* Generic description with sender and channel names
* Full message content sent in the notification payload

We started out with "Full message content" and then people got nervous about the possibility of HR or PII contents being displayed on phones in notifications (email preview) so we changed it to "Generic description with sender and channel name". This was after we installed mattermost, setup channels, used the thing for a week, etc. Mattermost is not honoring this setting and uses "full message content".

**EDIT**: Also tried it with "only sender name" and it's the same thing. It's just stuck on "full message".

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

This is an open source (free) installation.

Mattermost Version: 9.4.1
Database Schema Version: 117
Build Number: 7424719315
Database: postgres

This is installed on ubuntu using snap.

1. start mattermost
2. create some users and channels
3. use the thing
4. change notification settings

There are no mattermost log entries which look related to failing to set the feature.

#### Expected behavior
Describe your issue in detail

I would like the notifications to work properly. :)

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

![image](https://github.com/mattermost/mattermost/assets/5769712/bc46c6cf-ff33-4cbc-8e5a-f333261c7b34)

Ironically discussing the notification issue...

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

I don't know what code is causing this, I'm sorry. :(

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56591.

**Comment by tibers** [comment]
Answering [Dan's comment here](https://mattermost.atlassian.net/browse/MM-56591?focusedCommentId=160758), the problem is that changing the level of detail in the mail in the settings pane is the problem. Setting the level of detail doesn't actually set the level of detail. :) 

(I can't reply in your JIRA, hopefully this comment finds him).

**Comment by amyblais** [comment]
Thank you, I will add your comment to the ticket.

**Comment by tibers** [comment]
@larkox ah thank you - I see the [email notification contents](https://docs.mattermost.com/configure/site-configuration-settings.html#email-notification-contents) setting and I see it's a paid feature. Thank you for the clarification!
