### ISSUE TITLE
Click outside the file preview area doesn't close the modal.

### ISSUE THREAD

**Issue by oOoBenoitoOo** [mattermost/mattermost#25967]
#### Summary
As a user if I open the preview on a text file, I'm not able to quit the preview by clicking outside the preview like a modal.

#### Steps to reproduce
https://github.com/mattermost/mattermost/assets/39456891/48947ba7-e2e8-41bf-b724-ebb219107969

#### Possible fixes
remove the height css property from the `.code-preview` class https://github.com/mattermost/mattermost/blob/7833dd2c1c70fb098ad6c7c9a97c8e0beb1cc8cf/webapp/channels/src/sass/components/_modal.scss#L428

for this result:

https://github.com/mattermost/mattermost/assets/39456891/6ed7186e-a57d-4c8f-80d8-d02f16846b28

**Comment by amyblais** [comment]
Hi @oOoBenoitoOo, I wasn't able to reproduce this just now.

1. Which OS and version are you on?
2. Does this only reproduce on the desktop app or does it also reproduce on webapp?
3. Can you share here a sample file that the issue reproduces with?

**Comment by oOoBenoitoOo** [comment]
Hi @amyblais,
My bad, I'm on MacOS Sonoma 14.2.1
I've this behavior on desktop and web(Chrome)
[testFile.txt](https://github.com/mattermost/mattermost/files/13991206/testFile.txt)

on web:

https://github.com/mattermost/mattermost/assets/39456891/78136e2c-6655-45ba-b2b4-ffd49727df43

**Comment by amyblais** [comment]
Thank you! Opened https://mattermost.atlassian.net/browse/MM-56602.

**Comment by marianunez** [comment]
@oOoBenoitoOo thanks for reporting this issue and the possible fix. Would you be open to submit a PR with the fix?

**Comment by oOoBenoitoOo** [comment]
Hi @marianunez , sure, I will do it today

**Comment by oOoBenoitoOo** [comment]
https://github.com/mattermost/mattermost/pull/26018

**Comment by Ons-Miladi** [comment]
Hi, could you please assign this issue to me?

**Comment by marianunez** [comment]
> Hi, could you please assign this issue to me?

@Ons-Miladi this one is already being worked on and these is a PR open for it. Feel free to find an other issues with the `Up For Grabs` label
