### ISSUE TITLE
Clicking reply to a thread results in  a white page in Mattermost Desktop on macOS

### ISSUE THREAD

**Issue by andrashatvani** [mattermost/mattermost#25999]
#### Summary
Clicking reply to a thread results in  a white page in Mattermost Desktop on macOS.

#### Steps to reproduce
It's not always reproducible.

#### Expected behavior
The thread contents will be displayed on the right side of the window.

#### Observed behavior (that appears unintentional) 
The whole window area will be replaced by a white rectangle.

<img width="1690" alt="Screenshot 2024-01-18 at 11 27 51" src="https://github.com/mattermost/mattermost/assets/695746/cb9f39ed-2fae-4233-82af-9475c94d729c">

**Comment by amyblais** [comment]
Hi @andrashatvani,
1. What Mattermost server version are you on?
2. What Mattermost desktop app version are you on?
3. What OS version are you on?
4. Do you see any errors in the Mattermost server logs or in the browser console?

**Comment by andrashatvani** [comment]
1. Mattermost Enterprise Edition
Modern communication from behind your firewall.
Mattermost Version: 9.0.0
Database Schema Version: 113
Database: mysql
2. Version 5.6.0 (71161486891)
3. macOS 14.3 (23D56)
4. I'll check next time it occurs

**Comment by amyblais** [comment]
Thank you, we have a ticket open to fix a bug which is scheduled for an upcoming v9.4.2 dot release https://mattermost.atlassian.net/browse/MM-53149. It sounds similar to the issue you described.

**Comment by andrashatvani** [comment]
That sounds about right, do you have an estimate for that release? It pretty much renders the desktop client useless.

I've attached the diagnostics and the logs from when it just has happened.
[diagnostics_24-0-2024_15-31-36-356.txt](https://github.com/mattermost/mattermost/files/14039729/diagnostics_24-0-2024_15-31-36-356.txt)
[main.log](https://github.com/mattermost/mattermost/files/14039734/main.log)

**Comment by amyblais** [comment]
My current estimate for the release is either by the end of this week or by early next week.

**Comment by amyblais** [comment]
v9.4.2 is releasing today,
