### ISSUE TITLE
[MM-49243] Use paged requests to request the list of teams

### ISSUE THREAD

**Issue by noxer** [mattermost/mattermost#25991]
#### Description
Currently we're trying to request the list of teams from a server in one big request, with a page size of 9999 or 10000. While it's unlikely that a MM server has that many teams it's possible. Also requesting such a big list will put a lot of load on the server.

- Find the instances in `mmctl` where `GetAllTeams` is called with unreasonable page sizes
- Replace the instances with a loop requesting multiple times or use the `getPages` function
- Update the tests if necessary. Bonus points for new tests covering it.

#### Jira Ticket
https://mattermost.atlassian.net/browse/MM-49243

**Comment by hanzei** [comment]
Sorry for the delay @DeanFoley. Do you still want to work on the ticket?

**Comment by EltonGohJH** [comment]
Hey @hanzei 
I am a first contributor can I give this a try?

I am trying to run test cases like `make test-mmctl-unit` but it fails locally (on clean copy). Do you have any idea on how I can run it locally?

**Comment by DeanFoley** [comment]
> Sorry for the delay @DeanFoley. Do you still want to work on the ticket?

Hi @hanzei!

I've submitted some code for this already [here](https://github.com/DeanFoley/mmctl/commit/b5c0f7b2f6ddadf88dbd616b4ca2f78a3b3498d9); I'm (un)fortunately a bit too busy to pick this back up again now, but if it proves useful for anyone else (such as @EltonGohJH) to build off of, please do feel free to do so!

I'll keep an eye on this repo for any other good issues to pick up, should I find myself itching for some extra-curricular work. Cheers!
