### ISSUE TITLE
Image preview API `/api/v4/files/file_hash/preview`  header should use local disk cache

### ISSUE THREAD

**Issue by hungpr0** [mattermost/mattermost#26020]
#### Summary
Image file API preview `/api/v4/files/file_hash/preview`  should use cache

#### Steps to reproduce
HTTP response header of `/api/v4/files/file_hash/preview`  has `Cache-Control: private, no-cache`

#### Expected behavior
`/api/v4/files/file_hash/preview` HTTP header should ask client to use local cache `Cache-Control: private, max-age=864000` for example

#### Observed behavior (that appears unintentional) 
With large image preview size or multiple big files, we need to redownload again if switching channel/team. That would make preview image slow to load.

#### Possible fixes
May add the same header with `getFileInfo` func `w.Header().Set("Cache-Control", "max-age=2592000, private")`
[If you can, link to the line of code that might be responsible for the problem](https://github.com/mattermost/mattermost/blob/master/server/channels/api4/file.go#L557)

**Comment by amyblais** [comment]
Hi @hungpr0,

1. What Mattermost server version are you on?
2. What OS version are you on?
3. Do you see any errors in the Mattermost server logs or in the browser console?

**Comment by hungpr0** [comment]
> Hi @hungpr0,
> 
>     1. What Mattermost server version are you on?
> 
>     2. What OS version are you on?
> 
>     3. Do you see any errors in the Mattermost server logs or in the browser console?

Thanks for your reply @amyblais 
1. Mattermost server `8.1.6`. Mattermost Client `5.6.0`
2. Server - Debian 11. Client: Windows 11
3. no error at all. This is just to improve the loading time for `preview` image. I can replace the header on Mattermost server side by using nginx config below but I think `Control-Cache` should have `max-age` initially instead of `no-cache`
```
location ~ "/api/v[0-9]+/files/[0-9a-z]{26}/preview$" {
               ...
                proxy_hide_header 'Cache-Control';
                add_header 'Cache-Control' "private, max-age=864000";
                ....
}
``` 

Thanks

**Comment by amyblais** [comment]
Thank you, opened https://mattermost.atlassian.net/browse/MM-56651.

**Comment by agnivade** [comment]
Sounds reasoable. @jupenur - Any concerns with changing https://github.com/mattermost/mattermost/blob/547bcff06444cc5a8cd0c0550c8fefee636b1edf/server/platform/shared/web/files.go#L38

to private with a reasonable cache duration?

**Comment by agnivade** [comment]
Gentle ping @jupenur

**Comment by jupenur** [comment]
@esarafianou do you have a good understanding of the current state of HTTP cache behaviors around different header configurations? My knowledge is outdated, I'd have to look it up.

**Comment by esarafianou** [comment]
@jupenur I'd call my understanding outdated as well.

**Comment by jupenur** [comment]
@agnivade opening a PR with this change is fine, but it should go through some quick security testing before merging

**Comment by Linkinlog** [comment]
Hi, would I be able to take a stab at this? Is the fix to just change `no-cache` here to something like `864000`?https://github.com/mattermost/mattermost/blob/547bcff06444cc5a8cd0c0550c8fefee636b1edf/server/platform/shared/web/files.go#L38

**Comment by cednore** [comment]
And also, this bug has potential of slowing down server's performance, especially when mattermost is hosted on a low-spec servers with <2GB RAM. This scenario happened to me and the whole system was down for a while, so I had to restart the server.
