### ISSUE TITLE
English (Australia) setting doesn't save

### ISSUE THREAD

**Issue by hegyok** [mattermost/mattermost#26037]
#### Summary
Changing language in localization settings doesn't stay with English (Australia). 

#### Steps to reproduce
Docker image: mattermost/mattermost-team-edition:9.4
Database(Docker): postgres:13-alpine

1. Go to System Console -> Localization -> Default Server Language/Default Client Language/Available Languages
2. Change the value to English (Australia)
3. Save

#### Expected behavior
The language setting should change, but it resets to Default Server Language: English (US), Default Client Language: English (US) instead.

#### Observed behavior 
1. I tried to change and save language settings
![image](https://github.com/mattermost/mattermost/assets/45619085/cb19795c-272a-48ac-86fe-11e168fd584f)
4. After saving the settings it stays there but it doesn't save and when I visit the language settings again it resets back to default.
![image](https://github.com/mattermost/mattermost/assets/45619085/e8d912f9-527b-48d6-bb1c-8a940e418d58)

Logs:
```
{"timestamp":"2024-01-25 07:00:46.064 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:431","path":"/api/v4/config","request_id":"8i7hdhutkjdw8cpqyis9zwb8na","ip_addr":"192.168.89.9","user_id":"pemtr1f1d7gx8rt3tc8mnjy9yc","method":"PUT","tag_value":"sysconsole_write_*_read"}
{"timestamp":"2024-01-25 07:00:46.066 Z","level":"debug","msg":"ConfigurationWillBeSaved","caller":"app/plugin_api.go:982","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).ConfigurationWillBeSaved configuration.go:466"}
{"timestamp":"2024-01-25 07:00:46.068 Z","level":"warn","msg":"DefaultServerLocale must be one of the supported locales. Setting DefaultServerLocale to en as default value.","caller":"config/utils.go:119","locale":"en-AU"}
{"timestamp":"2024-01-25 07:00:46.068 Z","level":"warn","msg":"DefaultClientLocale must be one of the supported locales. Setting DefaultClientLocale to en as default value.","caller":"config/utils.go:125","locale":"en-AU"}
{"timestamp":"2024-01-25 07:00:46.068 Z","level":"warn","msg":"AvailableLocales must include DefaultClientLocale. Setting AvailableLocales to all locales as default value.","caller":"config/utils.go:136"}
```

**Comment by hegyok** [comment]
I was also able to reproduce it in your mattermost-preview Docker image:
docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56663.
