### ISSUE TITLE
Fail to jump to old message from post permalink or post search

### ISSUE THREAD

**Issue by awermuth** [mattermost/mattermost#26049]
#### Summary
Linking to a post or linking from a search for regular accounts results in a message: Message not found. The permalink belongs to deleted messages or to a channel you do not have access to.

#### Steps to reproduce
Mattermost 9.4.1
Database: PostgreSQL
Chrome
Use the search box and find posts
Click on the jump link

#### Expected behavior
Should jump immediately to the old message.

#### Observed behavior (that appears unintentional) 
Nothing in the logs.
Navigating via permalink has the same problem.
The problem does not occur for administrative accounts.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-56575.
