### ISSUE TITLE
Download of Mattermost export fails after about 30 seconds

### ISSUE THREAD

**Issue by im-fabian** [mattermost/mattermost#26063]
#### Summary
Download of mattermost export unexpectedly fails after about 30 sec.
Also tried browserbased download (https://chat.XXXX/api/v4/exports/XXXX_export.zip)

#### Steps to reproduce

1. Create a mattermost export (mmctl export create --attachments)
2. Try to download the mattermost export (mmctl export download).
3. Failing with WARNING: failed to download export file: DownloadExport: model.client.copy.app_error, unexpected EOF. Retrying...

#### Expected behavior
Export file should be downloaded and the download shouldn't be aborted.

#### Observed behavior (that appears unintentional) 
Download fails after about 30 seconds.
![Bildschirmfoto_2024-01-28_um_18_32_09](https://github.com/mattermost/mattermost/assets/31921275/5548c28a-97b3-47ac-9ff4-cbae7e74bbad)

Nginx logs a connection closed by mattermost:
28.1.2024, 18:26:07, nginx 2024/01/28 17:26:07 [error] 88#88: *83000 upstream prematurely closed connection while sending to client, client: 83.XXX.XXX.XXX server: chat.XXX, request: "GET /api/v4/exports/XXX_export.zip HTTP/1.1", upstream: "http://172.20.0.2:8065/api/v4/exports/XXX_export.zip", host: "chat.XXX"

#### Possible fixes
I guess there must be some kind of mattermost api timeout or so.

**Comment by agnivade** [comment]
Please investigate the mattermost logs. There should be a timeout happening somewhere.

Are you using AWS S3 as a filestore? If so, please check `AmazonS3RequestTimeoutMilliseconds`.

**Comment by amyblais** [comment]
Closing for now until we hear back on this,

**Comment by jgrossophoff** [comment]
I have the some issue with the Platform Service for which we pay quite a lot. 

It's the same for calling the endpoint with CURL or using the mmctl command. I've tried using the official download from the docs and building it myself. If we resume the CURL download via the `-C -` flag the ZIP archive is corrupted.

**Comment by agnivade** [comment]
@jgrossophoff - Please raise a support ticket with all the relevant details and the error that you are seeing. We will take a look from our side.
