### ISSUE TITLE
[Bug]: The public channel to which I was added is not displayed in the left sidebar and also direct messages from users who have not messaged me before are not showing up

### ISSUE THREAD

**Issue by Thomsawyer2023** [mattermost/mattermost#26078]
#### Summary
The public channel to which I was added is not displayed in the left sidebar and also direct messages from users who have not messaged me before are not showing up

The issue often occurs when a user who has not messaged you before contacts you or when you are added to a new channel. This occurs frequently and primarily on desktop, but reproduction has been observed in the browser (more difficult to reproduce). Typically, everything is displayed correctly in the mobile application.

#### Steps to reproduce

Pre

Mattermost v9.4, Desktop v5.5.1 / Chrome
There are two channels in the team: Public-1 and Private-2.
The team consists of two members, User 1 and User 2, both with the role of system_user, who have not had previous dialogs.
User 1 is a member of both Public-1 and Private-2 channels, while User 2 is not.

Steps
User 1 sequentially adds User 2 to the Public-1 and Private-2 channels.

#### Expected behavior
User 2 is on desktop and sees messages from both the Private-2 and Public-1 channels in the sidebar. Additionally, User 2 receives a notification about an unread message on the 'Channels' tab in the top panel."

#### Observed behavior (that appears unintentional) 
User 2 is on desktop and sees a message from the Private-2 channel in the sidebar, but the Public-1 channel is not visible. Sometimes a reload (ctrl+shift+r) or a full application restart helps.
User 2 receives a notification about an unread message only on the 'Channels' tab in the top panel.

**Comment by amyblais** [comment]
Hi @Thomsawyer2023, do you see any errors in the Mattermost server logs or in your browser's console?

**Comment by Thomsawyer2023** [comment]
Tested with mattermost-docker-previe  to make sure the issue persists in the latest version 

I attach the logs of testing in debug mode
[image1.txt](https://github.com/mattermost/mattermost/files/14108017/image1.txt)

**Comment by amyblais** [comment]
Thank you, we have these related tickets open:
 - https://mattermost.atlassian.net/browse/MM-55485
 - https://mattermost.atlassian.net/browse/MM-53137

**Comment by Thomsawyer2023** [comment]
Hello! Thank you for your response.

I would like to let you know that solving this problem is probably more important than it seems. 

I see that users are still reporting this problem, but only in the desktop repository. But this is a server issue. 
https://github.com/mattermost/desktop/issues/2163
https://github.com/mattermost/desktop/issues/2163#issuecomment-1502587156

I would like you to raise the priority because users, may not see a new message for a few days. (in our workspace, it's a frequent case)

**Comment by zackyjsd** [comment]
This problem still exists in the latest version v10 cluster
@amyblais

**Comment by amyblais** [comment]
> This problem still exists in the latest version v10 cluster

Feel free to create a new Issue with details.
