### ISSUE TITLE
Unable to retrieve Private Channels in Team through API

### ISSUE THREAD

**Issue by juanmrosalesf** [mattermost/mattermost#26074]
If you've found the following limitation through the API where Private Channels in a given Team cannot be listed by a Team Admin due to access restrictions in the API

[Get Public Channels For Team](https://api.mattermost.com/#tag/channels/operation/GetPublicChannelsForTeam) currently requires permission `list_team_channels` in order to list Public Channels within a team.

[Get Private Channels For Team](https://api.mattermost.com/#tag/channels/operation/GetPrivateChannelsForTeam) currently requires permission `manage_system` in order to list Private Channels within a team. That permission is restricted to System Admins.

Per [Mattermost Permissions](https://docs.mattermost.com/onboard/advanced-permissions-backend-infrastructure.html), a `manage_system` is a permission that is only assigned to System Admins

As a Team Admin, I would like to generate a list of Private Channels within my team and retrieve their information. However, I cannot use the API point to list the Private Channels within my team. It seems that the permission is a tier higher than what it should be for this API point.

#### Summary
Private Channel list cannot be retrieved by Team Admin through API

#### Steps to reproduce
As a Team Admin (and not a System Admin), request the API point for listing Private Channels inside a given Team:
https://api.mattermost.com/#tag/channels/operation/GetPrivateChannelsForTeam

#### Expected behavior
Return the list of Private Channels

#### Observed behavior (that appears unintentional) 
API Exception with message 'You do not have the appropriate permissions.'

#### Possible fixes
Change permissions so that Team Admin can view Private Channels within the Team

**Comment by amyblais** [comment]
Hi @juanmrosalesf,
1. What Mattermost server version are you on?
2. What OS and version are you using?

**Comment by juanmrosalesf** [comment]
Mattermost Version: 9.3.0
Database Schema Version: 114
Build Number: 7014621505
Database: postgres

Running on RHEL 7.9

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @juanmrosalesf,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by juanmrosalesf** [comment]
Thank you, I've created the suggestion in uservoice

https://mattermost.uservoice.com/forums/306457-general/suggestions/47697428-retrieve-private-channels-in-team-through-api-as-t
