### ISSUE TITLE
Pricing page/Price modals (price margin issue in different devices, responsiveness)

### ISSUE THREAD

**Issue by VishwasSaini25** [mattermost/mattermost#26102]
The buttons after the price in pricing models are given some margin, but these margin vanish when you go to tablet size device resolutions and the price and the buttons get very close with 0 margin in between.
I have attached two images, one in mobile size resolution and other is in tablet size resolution.
![Screenshot (57)](https://github.com/mattermost/mattermost/assets/85990875/1839589c-ff0f-4418-8e4d-4626e1ad3481)
![Screenshot (58)](https://github.com/mattermost/mattermost/assets/85990875/86860114-5a9f-4400-87e2-29bc994874b1)

#### Summary
The buttons below price in price model should be given margin when in tablet size resolution

#### Steps to reproduce
1. Go to official website of mattermost
2. Go to inspect and select pricing section from navbar
3. Now select tablet size resolution and see the difference in the margins between price and the button below it.

#### Expected behavior
In tablet size resolution buttons below price in price modals should have margin.

#### Observed behavior (that appears unintentional) 
This is not an error, this is a ui mistake, I have checked this in google chrome and microsoft edge browser

**Comment by amyblais** [comment]
Hi there, I've opened a ticket for our Marketing team to review and take a look. Our website is currently not open-sourced, so we probably cannot assign this issue to you.

**Comment by VishwasSaini25** [comment]
sure, i got it and by the way this issue needs to be reviewed by front-end developer's team.

**Comment by emdecr** [comment]
Thanks for the flag Vishwas! This should be fixed @amyblais (margin on tablet dimensions mirrors what we see on mobile), but feel free to ping me if anything. TY!
