### ISSUE TITLE
The team unread indicator is barely visible in dark themes

### ISSUE THREAD

**Issue by lmoureaux** [mattermost/mattermost#26113]
#### Summary

In dark mode, it is hard to see that you have unread messages in a team (Indigo and Onyx themes):
![image](https://github.com/mattermost/mattermost/assets/22327575/0c298cbc-e780-4026-af8f-b76a38bea2ff)

Compare to the contrast in light mode (Denim theme):
![image](https://github.com/mattermost/mattermost/assets/22327575/870168e2-e079-4b32-8284-b93891ffa6b1)

This is similar to https://mattermost.atlassian.net/browse/MM-15031 (from 2019)

#### Steps to reproduce

1. Use version 9.2.3 as installed at CERN
2. Join multiple teams so the team sidebar is shown
3. Switch to the Indigo theme
4. Hover a channel in the sidebar and select "Mark as unread"
5. Switch to another team
6. Notice the lack of contrast in the team sidebar

#### Expected behavior

The small indicator is bright enough to be noticed immediately. Using the same white as in the Denim theme would work.

#### Observed behavior (that appears unintentional) 

Contrast is poor, resulting in missed messages.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56773.

**Comment by lmoureaux** [comment]
Thanks a lot!
