### ISSUE TITLE
Images not loading after Slack -> Mattermost migration

### ISSUE THREAD

**Issue by max1mde** [mattermost/mattermost#26160]
#### Summary
I tried to import my slack workspace to mattermost but after the export no images are loading.
I followed this guide:
https://docs.mattermost.com/onboard/migrate-from-slack.html
The export zip file included all images:
![image](https://github.com/mattermost/mattermost/assets/114857048/ab7297bb-37ab-41c1-b8d5-3262a49fe5b4)
![image](https://github.com/mattermost/mattermost/assets/114857048/09237e91-6e98-4d9f-a1ca-5f1dee3791a7)

The images do load in slack

Here is a error message from the log:
```{"timestamp":"2024-02-08 11:07:22.578 +01:00","level":"debug","msg":"Error reading image file","caller":"app/file.go:1161","path":"/api/v4/users/iuggree5ki8afgowo9tpce55gc/channels/c3zz96y8digkdx9jt4y59dqk7y/posts/unread","request_id":"4fw6f8knppft3ktq8thts8kzyc","ip_addr":"::1","user_id":"iuggree5ki8afgowo9tpce55gc","method":"GET","error":"FileReader: Unable to get a file reader., unable to open file 20240205/teams/4did8zs4uibxxem35u8hxf3cuy/channels/c3zz96y8digkdx9jt4y59dqk7y/users/1971m6sy4pyhtmtgogkwg3js4h/t3mo7yyb1fn5jr397tjashrw9e/F06HW7FJ0GY_Clipboard_-_January_5__2024_12_03_PM.png: open data/20240205/teams/4did8zs4uibxxem35u8hxf3cuy/channels/c3zz96y8digkdx9jt4y59dqk7y/users/1971m6sy4pyhtmtgogkwg3js4h/t3mo7yyb1fn5jr397tjashrw9e/F06HW7FJ0GY_Clipboard_-_January_5__2024_12_03_PM.png: no such file or directory"}```

Im not sure if thats correct but I think with `20240205/teams...`
Should be in this folder... (which does not exist)
![image](https://github.com/mattermost/mattermost/assets/114857048/7ba870ee-815c-4267-bba2-d04015e20d00)
Also all messages exist (the users got imported too) just the images are missing
![image](https://github.com/mattermost/mattermost/assets/114857048/e14111b1-5130-4922-9495-d8bca63a0f3f)

## Here in Slack:
![image](https://github.com/mattermost/mattermost/assets/114857048/2c8521cb-3a7a-448a-945f-5c3ae9cf873a)

I already:
- Restartet mattermost
- Cleared my browser cache

#### Steps to reproduce
Install mattermost community version using Tarball on Debian 12
Mattermost version 9.3.0 is installed
Export and import workspace using this guide:
https://docs.mattermost.com/onboard/migrate-from-slack.html

#### Expected behavior
The images should load

#### Observed behavior (that appears unintentional) 
The images (attachements) do not load in mattermost

**Comment by max1mde** [comment]
```
{"timestamp":"2024-02-08 12:37:56.488 +01:00","level":"info","msg":"Preparing file upload from file system","caller":"app/import_functions.go:1291","file_name":"data/bulk-export-attachments/F06HW7FJ0GY_Clipboard_-_January_5__2024_12_03_PM.png"}
{"timestamp":"2024-02-08 12:37:56.492 +01:00","level":"info","msg":"Uploading file with name","caller":"app/import_functions.go:1327","file_name":"data/bulk-export-attachments/F06HW7FJ0GY_Clipboard_-_January_5__2024_12_03_PM.png"}
{"timestamp":"2024-02-08 12:37:56.516 +01:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:172","method":"POST","url":"/api/v4/users/status/ids","request_id":"d3gtdointinttdobtky7gc3pzo","user_id":"13mm7e13ipn1bcsmrpomgoun6c","status_code":"200"}
{"timestamp":"2024-02-08 12:37:56.533 +01:00","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:1104","error":"failed to decode exif data: exif: failed to find exif intro marker"}
{"timestamp":"2024-02-08 12:37:56.550 +01:00","level":"info","msg":"Preparing file upload from file system","caller":"app/import_functions.go:1291","file_name":"data/bulk-export-attachments/F06H0QG2CTG_download__3_.jpg"}
{"timestamp":"2024-02-08 12:37:56.550 +01:00","level":"info","msg":"Uploading file with name","caller":"app/import_functions.go:1327","file_name":"data/bulk-export-attachments/F06H0QG2CTG_download__3_.jpg"}
{"timestamp":"2024-02-08 12:37:56.564 +01:00","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:1104","error":"failed to decode exif data: EOF"}
{"timestamp":"2024-02-08 12:37:56.604 +01:00","level":"info","msg":"Bulk import worker finished","caller":"app/import.go:121","bulk_import_worker_id":"3s4fkfw15prndkhysg61tqtarr","processed_lines":13}
{"timestamp":"2024-02-08 12:37:56.811 +01:00","level":"info","msg":"Preparing file upload from file system","caller":"app/import_functions.go:1291","file_name":"data/bulk-export-attachments/F06FXAGC5PV_Night-Sky-Clouds-Sunset-Scenery-4k-Wallpapers-scaled.jpg"}
{"timestamp":"2024-02-08 12:37:56.813 +01:00","level":"info","msg":"Uploading file with name","caller":"app/import_functions.go:1327","file_name":"data/bulk-export-attachments/F06FXAGC5PV_Night-Sky-Clouds-Sunset-Scenery-4k-Wallpapers-scaled.jpg"}
{"timestamp":"2024-02-08 12:37:56.901 +01:00","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:1104","error":"failed to decode exif data: EOF"}
{"timestamp":"2024-02-08 12:37:57.191 +01:00","level":"info","msg":"Preparing file upload from file system","caller":"app/import_functions.go:1291","file_name":"data/bulk-export-attachments/F06GA3260LR_Night-Sky-Clouds-Sunset-Scenery-4k-Wallpapers-scaled.jpg"}
{"timestamp":"2024-02-08 12:37:57.192 +01:00","level":"info","msg":"Uploading file with name","caller":"app/import_functions.go:1327","file_name":"data/bulk-export-attachments/F06GA3260LR_Night-Sky-Clouds-Sunset-Scenery-4k-Wallpapers-scaled.jpg"}
{"timestamp":"2024-02-08 12:37:57.258 +01:00","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:1104","error":"failed to decode exif data: EOF"}
```

**Comment by max1mde** [comment]
I found this https://github.com/mattermost/mattermost/issues/21228

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-56801.

**Comment by WerVa** [comment]
same situation when importing rocketchat files


`{"timestamp":"2024-02-12 16:26:52.115 Z","level":"info","msg":"Uploading file with name","caller":"app/import_functions.go:1325","file_name":"files/rocketchat_uploads/eur7XXS698FDx4gLv/bg_product_5900017059037.png"}
{"timestamp":"2024-02-12 16:26:52.151 Z","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:1104","error":"failed to decode exif data: exif: failed to find exif intro marker"}
{"timestamp":"2024-02-12 16:26:56.968 Z","level":"info","msg":"Preparing file upload from file system","caller":"app/import_functions.go:1289","file_name":"files/rocketchat_uploads/JacfnQbCiERzWuyCK/bannermobile.png"}
{"timestamp":"2024-02-12 16:26:56.976 Z","level":"info","msg":"Uploading file with name","caller":"app/import_functions.go:1325","file_name":"files/rocketchat_uploads/JacfnQbCiERzWuyCK/bannermobile.png"}
{"timestamp":"2024-02-12 16:26:57.004 Z","level":"debug","msg":"GetImageOrientation failed","caller":"app/file.go:1104","error":"failed to decode exif data: exif: failed to find exif intro marker"}`

**Comment by agnivade** [comment]
@max1mde - You mentioned that the export zip contains all the images. Could you check if `F06HW7FJ0GY_Clipboard_-_January_5__2024_12_03_PM.png` contains in the zip file or not? Just verifying if somehow it went into a different folder or it's not included at all.

**Comment by max1mde** [comment]
> @max1mde - You mentioned that the export zip contains all the images. Could you check if `F06HW7FJ0GY_Clipboard_-_January_5__2024_12_03_PM.png` contains in the zip file or not? Just verifying if somehow it went into a different folder or it's not included at all.

This is in the `export-with-emails-and-attachments.zip` file
![image](https://github.com/mattermost/mattermost/assets/114857048/caf879f4-85b4-46f5-bd4a-fce4bcfef51b)

After I excecuted the `mmetl transform slack --team slack-import --file export-with-emails-and-attachments.zip --output mattermost_import.jsonl
` command

This file is in the `data/bulk-export-attachments` folder:
![image](https://github.com/mattermost/mattermost/assets/114857048/4f20b3cc-3c72-4566-b795-73a2ddd700e6)

Finally I imported the data using the `mattermost import bulk ./mattermost_import.jsonl --import-path ./data --apply` command but the attachments are missing in mattermost.

**Comment by agnivade** [comment]
Hey @max1mde - The mattermost CLI has been deprecated and does not import attachments. Please use option 1 mentioned here: https://docs.mattermost.com/onboard/migrate-from-slack.html#import-data-into-mattermost. We should probably remove option 2 now. cc @cwarnermm for a doc update.

**Comment by cwarnermm** [comment]
Thanks for the flag, @agnivade! I'll ensure the docs are updated.

**Comment by max1mde** [comment]
> Hey @max1mde - The mattermost CLI has been deprecated and does not import attachments. Please use option 1 mentioned here: https://docs.mattermost.com/onboard/migrate-from-slack.html#import-data-into-mattermost. We should probably remove option 2 now. cc @cwarnermm for a doc update.

Yes this method actually worked! The images are all working now.
Thanks.
