### ISSUE TITLE
Attempting to send image crashed desktop and website chat

### ISSUE THREAD

**Issue by sophiehourihane** [mattermost/mattermost#26228]
#### Summary
Attempting to send an image crashed the desktop and website version

#### Steps to reproduce
Desktop version is 4.6.0.7303

#### Expected behavior
I should be able to drop an image and send it in the chat. 

#### Observed behavior (that appears unintentional) 
I attempted to send an image to a colleague on the desktop app and the chat went grey. I am unable to navigate away from the chat on the desktop app. I tried to send the same image on the mobile version and the same thing happened. I can navigate to other chats directly by going to the address but I cannot open the direct message or drafts (since presumably the broken message is still there). 

App: 
![image](https://github.com/mattermost/mattermost/assets/29460744/16d032f2-252b-4aa0-a739-05ebad53f0d5)

Website: 
![image](https://github.com/mattermost/mattermost/assets/29460744/7cab4014-7a5d-4847-816f-54945413349c)

**Comment by amyblais** [comment]
Hi @sophiehourihane, would you be open to updating to the latest desktop app version, which is v5.6.0 https://docs.mattermost.com/deploy/desktop-app-changelog.html#release-v5-6?

**Comment by amyblais** [comment]
Closing for now until we hear an update,
