### ISSUE TITLE
Can't mention people on the channel / user autocomplete is broken

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/mattermost#26260]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.

Done
<img width="803" alt="Screenshot 2024-02-19 at 13 50 04" src="https://github.com/mattermost/mattermost/assets/2323840/2d5dc52c-38d6-4c9e-924a-760db7ae3975">

2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).

It is not

3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Can't mention users in the channels. Since ~one week. Nor in desktop, nor in mobile app, nor in web browser in Safari.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

No ideas. But it seems like started to happen after server update to 9.4.3.
```
Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: mysql
```

#### Expected behavior
User's autocompletions and hence tagging to work like it did earlier.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

No (related) errors on the server side.
<img width="996" alt="Screenshot 2024-02-19 at 13 56 04" src="https://github.com/mattermost/mattermost/assets/2323840/41d17aea-3d36-4ba5-8019-6d5fe6dd1093">

#### Possible fixes
Don't know. It seems like API call that returns users in the room for some reason doesn't return all users. And for some reason it's only visible at autocompletion menu - everywhere else it works just fine.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-53477.

**Comment by alexander-potemkin** [comment]
I've found a work-around: remove people from the channel and add them back.

**Comment by amyblais** [comment]
Update: The ticket I linked to was closed because it was related to some internal issues we had with our servers. Our servers were pointing to the same ES indexes, causing incorrect data. We believe the issue was related to stale indexes or just incorrect indexes.

@alexander-potemkin Can you post back here if you see this issue again on your server? Can you check whether you reproduce the issue on our community server https://community.mattermost.com/?

**Comment by alexander-potemkin** [comment]
@amyblais , thank you. It feels like something got wrong on database side, certainly. I will let you know if it will re-occur, sure.

**Comment by amyblais** [comment]
I'll close this for now - we can re-open as needed,
