### ISSUE TITLE
Failed to sync plugin from file store

### ISSUE THREAD

**Issue by lucky4ever2** [mattermost/mattermost#26275]
#### Summary
If Mattermost server restart, not all plugins are installed after the restart

#### Steps to reproduce
Reboot Mattermost Server

#### Expected behavior
All plugins should be present after the reboot

#### Observed behavior (that appears unintentional) 
I upload a plugin through the system console's plugin upload feature. Upon rebooting the virtual machine, the plugin appears in the system console's left sidebar. However, it's actually missing. This issue persists across different plugins, exclusively impacting those that have been manually uploaded. Plugins obtained from the marketplace function normally. Despite being listed under "Plugins" in the left sidebar of the system console, these plugins are absent from the plugin management section, and their slash commands are unusable.

The following can be seen in the log:

`{"timestamp":"2024-02-20 22:45:23.907 +01:00","level":"info","msg":"Starting up plugins","caller":"app/plugin.go:218"}
{"timestamp":"2024-02-20 22:45:23.909 +01:00","level":"info","msg":"Syncing plugins from the file store","caller":"app/plugin.go:295"}
{"timestamp":"2024-02-20 22:45:23.921 +01:00","level":"info","msg":"Removing local installation of managed plugin before sync","caller":"app/plugin.go:322","plugin_id":"com.github.matterpoll.matterpoll"}
{"timestamp":"2024-02-20 22:45:23.921 +01:00","level":"info","msg":"Removing local installation of managed plugin before sync","caller":"app/plugin.go:322","plugin_id":"rssfeed"}
{"timestamp":"2024-02-20 22:45:23.928 +01:00","level":"info","msg":"Removing local installation of managed plugin before sync","caller":"app/plugin.go:322","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"timestamp":"2024-02-20 22:45:23.959 +01:00","level":"info","msg":"Removing local installation of managed plugin before sync","caller":"app/plugin.go:322","plugin_id":"focalboard"}
(...)
{"timestamp":"2024-02-20 22:45:54.445 +01:00","level":"error","msg":"Failed to sync plugin from file store","caller":"app/plugin.go:371","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","bundle_path":"plugins/com.github.scottleedavis.mattermost-plugin-remind.tar.gz","error":"extractPlugin: An error occurred extracting the plugin bundle., context canceled"}
{"timestamp":"2024-02-20 22:45:54.449 +01:00","level":"error","msg":"Failed to sync plugin from file store","caller":"app/plugin.go:371","plugin_id":"rssfeed","bundle_path":"plugins/rssfeed.tar.gz","error":"extractPlugin: An error occurred extracting the plugin bundle., context canceled"}
{"timestamp":"2024-02-20 22:45:54.547 +01:00","level":"error","msg":"Failed to sync plugin from file store","caller":"app/plugin.go:371","plugin_id":"com.github.matterpoll.matterpoll","bundle_path":"plugins/com.github.matterpoll.matterpoll.tar.gz","error":"extractPlugin: An error occurred extracting the plugin bundle., context canceled"}
{"timestamp":"2024-02-20 22:45:54.548 +01:00","level":"error","msg":"Failed to sync plugin from file store","caller":"app/plugin.go:371","plugin_id":"focalboard","bundle_path":"plugins/focalboard.tar.gz","error":"extractPlugin: An error occurred extracting the plugin bundle., context canceled"}
`

**Comment by amyblais** [comment]
Hi @lucky4ever2, what Mattermost server version are you on? What OS and version are you on?

**Comment by lucky4ever2** [comment]
Mattermost Serverversion: 9.5.1
OS Version: Ubuntu 20.04.6 LTS

**Comment by hanzei** [comment]
@lucky4ever2 which file store are you using? Local or S3?

**Comment by lucky4ever2** [comment]
@hanzei we use S3

**Comment by hanzei** [comment]
Can you please increase the config value of  `AmazonS3RequestTimeoutMilliseconds` and check if that resolves the issue?

**Comment by lucky4ever2** [comment]
@hanzei that is the solution! A value of 60000 solves the problem. Thank you very much

**Comment by hanzei** [comment]
Glad we found solution :+1:
