### ISSUE TITLE
Channel and team-admins can't edit or delete their own messages in read-only channels. 

### ISSUE THREAD

**Issue by william-lundgren** [mattermost/mattermost#26276]
#### Summary
Channel and team-admins can't edit or delete their own messages in read-only channels. 

#### Steps to reproduce
Make a new team. Change a channel to be read-only (uncheck "Create Posts" under channel moderation in system console). Send a message in that channel as channel or team admin. Attempt to edit message via the 3 dots. 

Using Version 5.6.0.

#### Expected behavior
I expected to see the edit message alternative. For channel admin there is no delete message alternative either as can be seen by the pictures. 

#### Observed behavior (that appears unintentional) 
I expected to see the edit message alternative. For channel admin there is no delete message alternative either. 

Screenshot of menu in a read-only channel from the view of a channel admin. Able to post message but not edit it. 
<img width="706" alt="Skärmavbild 2024-02-21 kl  13 58 34" src="https://github.com/mattermost/mattermost/assets/47833247/dd1fa982-b410-46a3-8e3a-d12c46b9bb7c">

Screenshot of the permissions tab for all users, showing they have permission to edit and delete their own messages. Channel admin also inherit these by default. 
<img width="864" alt="Skärmavbild 2024-02-21 kl  13 59 54" src="https://github.com/mattermost/mattermost/assets/47833247/92b77e84-6284-4e93-8884-047fb6ef8d09">

#### Possible fixes
Not sure but probably that read-only disables all these toggles and the channel admin only re-enables the writing without checking for permissions.

**Comment by amyblais** [comment]
Hi @william-lundgren, what Mattermost server version are you on (you can find this at Main Menu > About Mattermost)? What OS and version are you on?

**Comment by amyblais** [comment]
I tested this on the latest version (v9.5.1 Extended Support Release) and I wasn't able to reproduce it, so potentially this issue has since been fixed. Is your team planning to test or upgrade to the latest ESR version in the near-term?
