### ISSUE TITLE
js error in channel switcher after converting GM to private channel

### ISSUE THREAD

**Issue by antonbuks** [mattermost/mattermost#26277]
#### Summary
After converting a group message to a private channel the quick channel switcher (⌘ + K) breaks with a javascript error, showing the red js error banner and the channel switcher has no available options. Reproducible in web and desktop environments.

```
channel_utils.ts:281 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at L (channel_utils.ts:281:19)
    at Array.sort (<anonymous>)
    at J (channels.ts:400:28)
    at channels.ts:426:16
    at index.js:96:36
    at index.js:53:31
    at index.js:113:39
    at index.js:53:31
    at z.fetchAndFormatRecentlyViewedChannels (switch_channel_provider.tsx:717:30)
    at z.handlePretextChanged (switch_channel_provider.tsx:462:18)
 ```
 
<img width="431" alt="Screenshot 2024-02-21 at 14 17 16" src="https://github.com/mattermost/mattermost/assets/11543153/0bf0e971-def6-4d72-8b14-0c3d4b4d01ea">

#### Steps to reproduce
1) Create a group message
2) Convert group message to a private channel using the channel header action menu
3) Open channel switcher (⌘ + K)
4) After a manual refresh (⌘ + R) it works fine again and the new channel appears

#### Expected behavior
Channel switcher works after converting

**Comment by amyblais** [comment]
Hi @antonbuks, what Mattermost server version are you on? What OS and version are you on? Do you see any errors in the Mattermost server logs or in the developer console?

**Comment by amyblais** [comment]
Thank you, opened https://mattermost.atlassian.net/browse/MM-56946.
