### ISSUE TITLE
Daily Email Digest of Channel Activity

### ISSUE THREAD

**Issue by cboecking** [mattermost/mattermost#26291]
I have a stupid question. How do I get a daily email digest of activity for a given channel? 

I need to monitor all activity (not just my mentions) in many channels. It would be way easier to perform this task with a daily digest per channel.

Sorry in advance if I simply overlooked the documentation reference; however, I cannot find a way to perform this task.

**Comment by amyblais** [comment]
Here is some details on email notifications:
 - https://docs.mattermost.com/preferences/manage-your-notifications.html
 - https://docs.mattermost.com/configure/site-configuration-settings.html#notification-enableemailbatching

If you can't find what you're looking for, feel free to upvote this feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/17381215-daily-weekly-email-digests.
