### ISSUE TITLE
Login error 

### ISSUE THREAD

**Issue by YusukeMasuda36** [mattermost/mattermost#26292]
When I directly manipulated the user information in the database, the following error was logged. Please tell me the solution.

Login failed because remote users are not allow to log in.

**Comment by amyblais** [comment]
Would you be open to moving this to the troubleshooting forum here https://forum.mattermost.com/? Please also add details on your Mattermost server logs, Mattermost server version, and your authentication method.

**Comment by YusukeMasuda36** [comment]
OK!Thank you
