### ISSUE TITLE
Change CopyButton to use useTooltip instead of react bootstrap tooltip

### ISSUE THREAD

**Issue by sohzm** [mattermost/mattermost#26311]
#### Summary
Propose to refactor the CopyButton component to utilize the useTooltip hook, moving away from the current implementation that uses React-Bootstrap Tooltip.

#### Context
@M-ZubairAhmed asked if I'd be open to doing this change after a small change on the CopyButton component in a [seperate pr](https://github.com/mattermost/mattermost/pull/26285#issuecomment-1963938569).

Since the PR is greater than 20 lines of code, I've opened this issue. 

#### Request for Feedback
If there are any prerequisites or related issues I should be aware of, please let me know.

**Comment by M-ZubairAhmed** [comment]
Closing this one out in favour of https://github.com/mattermost/mattermost/issues/27414
