### ISSUE TITLE
no push notifications on mobile app

### ISSUE THREAD

**Issue by badsmoke** [mattermost/mattermost#26333]
#### Summary
no push notifications have been arriving on the mobile clients for a few weeks now.
This is also signaled in the app by the red exclamation mark
"notifications could not be ceceived from this server"

an update to mattermost 9.5.1 did not help.
Logging out/logging in/reinstalling does not help

it is a selfhosted instance that previously ran without problems, the push notification server is "http://push-test.mattermost.com"

#### Steps to reproduce
use as always

#### Expected behavior
push notifications should work as usual

### logs

```
{"timestamp":"2024-02-29 10:15:09.263 +01:00","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:443","logSource":"notifications","ackId":"1g41bet5b7fn5rwtg3caj9pn5y","type":"clear","userId":"4cbycnkiobr5fxzytbiimciefw","postId":"","status":"Prepared to send"}
{"timestamp":"2024-02-29 10:15:09.762 +01:00","level":"error","msg":"Notification error","caller":"app/notification_push.go:131","logSource":"notifications","ackId":"1g41bet5b7fn5rwtg3caj9pn5y","type":"clear","userId":"4cbycnkiobr5fxzytbiimciefw","postId":"","channelId":"5ajpyzpdrbfab8i8nryzxoda3h","deviceId":"cUntEN7YRzCzaN-s9tFDw_:APA91bFF2GMImKjKUb2mbxo0zl-mBAiI_BVdZYKbPYPt4zMhFp_DHHfTmOszLtyfU1W1hy96aCrUGP5U6c-hu5ih5b1B06kPWI6vROf8ZyXyrnAOH4SDkJwCU4My4irCX0nlxVdO4nU-","status":"failed to decode from JSON: EOF"}

```
the logs have been occurring since 15.02.2024, there were no updates or other changes on that day

**Comment by amyblais** [comment]
Hi @badsmoke,

1. Are you using TPNS or HPNS?
2. What Mattermost mobile app version are you on?
3. What OS and version are you on>

**Comment by badsmoke** [comment]
I am confused.

i tried to change the setting in the system console, but i got an error that said "failed to unmarshal config data: invalid character '{' after array element"

after searching the config only the position of the "calls" plugin came into consideration, there was a comma missing between two turn servers.

the push function has definitely not worked since 14/15.2, according to the logs nothing has been changed in the system, old snapshots also show that the setting has always been there.


was there a calls plugin update? isn't that done automatically?


after adding the command and saving the TPNS connection again, it now seems to work again



do you have an explanation for this phenomenon?

**Comment by amyblais** [comment]
> i tried to change the setting in the system console, but i got an error that said "failed to unmarshal config data: invalid character '{' after array element"

Which setting are you referring to?

> after searching the config only the position of the "calls" plugin came into consideration, there was a comma missing between two turn servers.

Can you help with more details on this?

> after adding the command and saving the TPNS connection again, it now seems to work again

Which command was added?

**Comment by badsmoke** [comment]
> Which setting are you referring to?

the push-notifications settings, which I simply wanted to deactivate as a test and then activate again.

> Can you help with more details on this?
`[{"urls":["stun:stun.global.calls.mattermost.com:3478"]},{"urls":["turns:turn.domain.com:443"]}]`

i only have snapshots back to mattermost 9.2.2, but until then the calls setting was set exactly the same with no comma.
Apparently this was not checked in the past to see if it was valid.



> Which command was added?
I just made a typing error, I meant when I added the comma

**Comment by apieceoy** [comment]
@badsmoke Try SSL URL: https://push-test.mattermost.com

**Comment by amyblais** [comment]
> @badsmoke Try SSL URL: https://push-test.mattermost.com

I asked our team and they also suggested testing whether you're able to reach the push proxy through http instead of https.

**Comment by amyblais** [comment]
A ticket was opened https://mattermost.atlassian.net/browse/MM-57489.
