### ISSUE TITLE
Bug with drafts

### ISSUE THREAD

**Issue by BdServo** [mattermost/mattermost#26373]
After post sending drafts still exists

I think that not too easy to reproduce that bug, but I'll try.

1. First we have one Mattermost window in browser with Team 1 opened.

2. We should open parallel second window with another Team (Team 2) 

3. Write post in second Window (Team 2) and send it

4. We will see sended post,  all okay (in network monitor POST query 201 ok) 
![_bug_network](https://github.com/mattermost/mattermost/assets/145204964/2b780807-352b-4b2c-ad79-d79be428ff7a)

5. After 2-3 seconds after post sended Draft counter in sidebar will increase +1 
![_bug_drafts_count](https://github.com/mattermost/mattermost/assets/145204964/4295ccb2-dd2d-4752-a5f5-a633975797e2)

6. If we refresh page we'll see our post in channel and duplicate (draft) of that post in textarea. If we open Drafts page we'll see our post here also.

---

Mattermost server 9.6.0
Mattermost client 9.6.0-rc1 / rc2 / rc3 and 9.6.0 

If we downgrade to Mattermost client 9.5.* all is okay and drafts working good. So I can say that  bug exist only on 9.6.* branch.

Browser Firefox Desktop ESR.

Also I checked console logs, and have no errors there. 
And also in first Window (Team 1) all works okay, drafts no bugged.

And one important thing, in system console "Enable server syncing of message drafts" = False.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57076.

**Comment by BdServo** [comment]
Afrer upgrade client to 9.7.0-rc1 some clients still have this issue.

**Comment by amyblais** [comment]
@devinbinnie Will this require further investigation before I cut the v9.6.1 release?

**Comment by devinbinnie** [comment]
@amyblais I think we need this fix on hub first and foremost, so we can see if it fixed our issue.
One thing I didn't notice about this issue is that server-synced drafts are off, which wasn't actually addressed by my change, so I will re-open this.
