### ISSUE TITLE
Grammar fault in french version

### ISSUE THREAD

**Issue by Pierre-PSUD** [mattermost/mattermost#26375]
#### Summary
Grammar fault on the French version of the desktop app

#### Steps to reproduce
1. Enter a chat
2. Click on your profile in the top right end corner
3. Click on "Define a status"
4. There are several suggestions : one is "En vacance"

#### Expected behavior
You should display "En vacance**s**" instead.

#### Observed behavior (that appears unintentional) 
It is currently displayed "En vacance"

#### Possible fixes
Add a "S" to "Vacance"

**Comment by amyblais** [comment]
Hi @Pierre-PSUD!

Translations can be edited through our translations server here https://translate.mattermost.com/. See more details at https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/localization#interested-in-contributing-to-product-translations.

If you don't have time to work on this fix, would you be open to sharing your feedback on our Localization channel here https://community.mattermost.com/core/channels/localization. Someone else in the translations community may be able to help fix this.

**Comment by amyblais** [comment]
Closing for now, but hopefully you're open to taking a look at the options above!
