### ISSUE TITLE
Quartz Theme - "Jump to recents" toast text isnt clearly visible

### ISSUE THREAD

**Issue by sohzm** [mattermost/mattermost#26394]
#### Summary
`Jump to recents` toast text isn't clearly visible due to background and it having less contrast

#### Steps to reproduce
1. Change theme to Quartz (Settings>Display>Theme>Quartz)
2. Go to any channel and scroll up so that `Jump to recents` toast will appear

#### Expected behavior
Background color and foreground color should have better contrast like we have in other themes, here is what default theme looks like
![default-theme](https://github.com/mattermost/mattermost/assets/68921363/01f83f54-eaa0-4807-adbc-0ffd8ab603f1)

#### Observed behavior (that appears unintentional) 
`Jump to recents` toast text isn't clearly, see the screenshot, second image is what we see when hovering.

![quartz](https://github.com/mattermost/mattermost/assets/68921363/cda08619-be12-492c-9fbe-5e5d870d4988)
![quartz-hover](https://github.com/mattermost/mattermost/assets/68921363/e86df758-200c-4cf2-b71c-96e96868448c)

#### Possible fixes
[scroll_to_bottom_toast.scss line 9](https://github.com/mattermost/mattermost/blob/09f78c240add141ca054146e6e0de590a685586e/webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.scss#L9) seems to be whats causing the issue. 

It's color should be a variable rather than a hardcoded value, although I can be wrong.

**Comment by amyblais** [comment]
Hi @sohzm,
1. What Mattermost server version are you on?
2. What OS and version are you on?

**Comment by sohzm** [comment]
Tried this on Mattermost community server https://community.mattermost.com

![Screenshot_20240305-202543.jpg](https://github.com/mattermost/mattermost/assets/68921363/a6969bec-e935-4e51-af41-2762e3c3331c)

OS: Arch Linux, Brave Browser

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-57096.
