### ISSUE TITLE
Browse Channels modal buttons are not having consistent styling

### ISSUE THREAD

**Issue by darkLord19** [mattermost/mattermost#26411]
#### Summary
Issue with css of buttons on firefox dev edition for `Browse Channels` modal

#### Steps to reproduce
open community on firefox dev edition and open `Browse Channels` modal

#### Expected behavior
Buttons to have proper styling

#### Observed behavior (that appears unintentional) 
<img width="619" alt="Screenshot 2024-03-07 at 12 13 26" src="https://github.com/mattermost/mattermost/assets/16662014/fb727166-dbbf-4b52-bbb9-1d23dbc2a84c">

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57141
