### ISSUE TITLE
Update 9.4 and after are breaking focalboard

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost#26425]
After upgrading the Mattermost server, the cards stopped working. It gives an authorisation error.
And the boards api gives error 500

<img width="1365" alt="image" src="https://github.com/mattermost/mattermost/assets/109951790/0f2ebc14-86c0-4c03-aad5-ff73f6693de3">
Clicking the login button doesn't help and the page reloads.

![Снимок экрана 2024-03-11 в 10 34 25](https://github.com/mattermost/mattermost/assets/109951790/ef87e8da-cdcb-4428-b5b6-9697d0951796)

Logs:
{
  "caller": "app/session.go:94",
  "error": "createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=95atuo4m5pgomncjajm7tzrywo",
  "level": "warn",
  "msg": "Error while creating session for user access token",
  "timestamp": "2024-03-11 08:40:30.421 +05:00"
}
{
  "caller": "plugin/client_rpc_generated.go:689",
  "error": "connection is shut down",
  "level": "error",
  "msg": "RPC call WebSocketMessageHasBeenPosted to plugin failed.",
  "plugin_id": "focalboard",
  "timestamp": "2024-03-11 08:40:30.421 +05:00"
}
{
  "caller": "plugin/client_rpc_generated.go:654",
  "error": "connection is shut down",
  "level": "error",
  "msg": "RPC call OnWebSocketDisconnect to plugin failed.",
  "plugin_id": "focalboard",
  "timestamp": "2024-03-11 08:40:30.421 +05:00"
}
{
  "caller": "plugin/client_rpc_generated.go:620",
  "error": "connection is shut down",
  "level": "error",
  "msg": "RPC call OnWebSocketConnect to plugin failed.",
  "plugin_id": "focalboard",
  "timestamp": "2024-03-11 08:40:35.432 +05:00"
}

**Comment by amyblais** [comment]
Would you be open to re-creating this issue in the focalboard repo https://github.com/mattermost/focalboard/issues?

**Comment by KakEgorka** [comment]
Thank you very much. I have duplicated the task in the board repository.
But it's a dead repository. It looks very strange from Matermost's point of view to give away a product and then abandon the users. What do we do with people who are using this product and now can't update because it's not finished in this repo?

**Comment by KakEgorka** [comment]
This has been confirmed as a problem with Golang v1.22 (golang/go#65633), which is not yet used for plugin or MM server builds. For custom builds, please use v1.21 until a fix is released.

**Comment by alerque** [comment]
I can confirm. I patched the Arch Linux Go package with the fix for this issue, then used that to rebuild mattermost. The resulting package works fine for all plugins including focalboard. If anybody needs it they can find the mattermost package in my Arch user repository (see the Wiki). I don't know if we'll be able to land this patch in Go before the next Go release so I don't know if this will hit the official repos soon or not.
