### ISSUE TITLE
ENORMOUS BUG: tab nickname completion can obliterate message / post after

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost#26422]
#### Summary
I am presently extremely upset. I have stumbled upon a very, very upsetting bug. The scenario was that I was typing a very urgent and very lengthy reply to someone with a lot of detail, but when I went back to the beginning of the message to add an @ mention the recipient, and upon pressing `<tab>` the completion obliterated the rest of the entire message after the @ mention completion. Of the several years of using Mattermost such a problem has never presented itself and I have performed  this frequently.

#### Steps to reproduce
- Using Mattermost 9.5.1, in the web interface:
- Type a message.
- Go back to the beginning and @ mention someone.
- Hope to see the remainder of the message obliterated after the @ mention.
- This seems to be an intermittent problem.

#### Expected behavior
A message's / post's contents should be preserved at whatever cost and never lost for any reason except explicit selection + deletion or outright deletion.

#### Observed behavior (that appears unintentional) 
@ mentions will intermittently obliterate message contents following tab completion of the username in an @ mention.

#### Possible fixes
Somehow back up message contents in an additional manner that will prevent loss in scenarios including tab completion or other potentially impactful edits. Double check tab completion that it is prevented from deleting much more content inadvertently.

**Comment by amyblais** [comment]
We fixed this issue in v9.5.0 https://mattermost.atlassian.net/browse/MM-33823, but it sounds like you're still experiencing this. Do the reproduction steps in the ticket match with what you're seeing?

**Comment by amyblais** [comment]
I saw this happen today. Opened https://mattermost.atlassian.net/browse/MM-57320.

**Comment by hmhealey** [comment]
@ylluminate Do you have "Allow message drafts to sync with the server" enabled in the Advanced section of your user settings? Do you also possibly have two tabs of MM open in the browser at once?

I wonder if this issue involces draft syncing, or if it's just an issue with the autocomplete code on its own
