### ISSUE TITLE
Official docker container - arm64 builds?

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/mattermost#26440]
https://hub.docker.com/r/mattermost/mattermost-team-edition provides a `linux/amd64` build, but no `linux/arm64` build. The rest of mattermost is built for arm as well, and arm CPUs are markedly cheaper to run.

**Comment by agnivade** [comment]
Hey @DanielHeath - Currently we don't support ARM architectures. However, you are welcome to build and run it yourselves.

**Comment by amyblais** [comment]
Closing as duplicate of https://github.com/mattermost/mattermost/issues/23387.
