### ISSUE TITLE
RestApi view channel endpoint doesn't work as before

### ISSUE THREAD

**Issue by BenjaminHuseinefendic** [mattermost/mattermost#26463]
On Mattermost team edition version 7.10.0 I used view channel endpoint to set when that user last viewed channel. But in newest Mattermost 9.5.2. team edition version it isn't the case. 

**last_viewed_at** property I read from get channel member endpoint (https://api.mattermost.com/#tag/channels/operation/GetChannelMember) and as I see it isn't updated after I triggered view channel (https://api.mattermost.com/#tag/channels/operation/ViewChannel).

In Mattermost version 7.10.0 team edition after I triggered view channel it sets **last_viewed_at** property to timestamp that is same as the **last_post_at** of that channel.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58031.

**Comment by larkox** [comment]
Since there is no response, I will close the ticket. Feel free to reopen if you think there is still any issue.
