### ISSUE TITLE
Custom schemes in oAuth2

### ISSUE THREAD

**Issue by dmitrijkir** [mattermost/mattermost#26497]
Hello, I wanted to try creating a native client. However, there are restrictions on creating a redirect URL in OAuth2 authorization. There is validation only for the http and https schemes. However, custom schemes like myapp:// are used for authorizing native applications. Did you intentionally implement this validation? Or can we expect that you will remove it in the future?

**Comment by amyblais** [comment]
Per Mattermost guidelines, GitHub issues are mainly used for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting questions, feel free to use https://forum.mattermost.com/. You can also post your question at https://community.mattermost.com/core/channels/peer-to-peer-help.
