### ISSUE TITLE
Dark help_text in dialog box in dark client theme

### ISSUE THREAD

**Issue by Sadisms** [mattermost/mattermost#26525]
#### Summary
In the dark client theme, in the dialog box from the bot, black text is used in help_text because of which it is not visible on the black background of the dialog box.

#### Steps to reproduce
Put a dark theme on the client and open a dialog box in the bot where there is a field with help_text.

#### Expected behavior
In description.

#### Observed behavior (that appears unintentional) 
In description.

#### Possible fixes
Didn't find it.

![image](https://github.com/mattermost/mattermost/assets/63108004/27038636-1dfc-416c-8b2c-10d89ede332c)
![image](https://github.com/mattermost/mattermost/assets/63108004/e90ad849-7738-4d9e-bd17-9aa8b1b9fa11)

**Comment by amyblais** [comment]
Hi @Sadisms, what Mattermost server version are you on? Are you able to reproduce this issue on our community server https://community.mattermost.com/?

We have this fix https://mattermost.atlassian.net/browse/MM-56528 queued for the next release (v9.7.0). Does this look like the same issue that you're seeing?

**Comment by Sadisms** [comment]
Hi, yes it sounds like this problem.
