### ISSUE TITLE
Mattermost package not being pushed to Ubuntu?

### ISSUE THREAD

**Issue by TehPeGaSuS** [mattermost/mattermost#26573]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
I've followed [this docs](https://docs.mattermost.com/install/install-ubuntu.html) to install Mattermost as a package.
While [this page](https://mattermost.com/download/#server) states `Latest Release: 9.6.0`, I still have `Mattermost Version: 9.5.2` on my instance and `apt update` doesn't show any package updates for Mattermost

#### Steps to reproduce
- Follow the steps provided [here](https://mattermost.com/download/#server) to install Mattermost as a package
- Do `apt update` and after that  `apt-cache show mattermost`
- The higher version available will be `9.5.2`

#### Expected behavior
Mattermost `9.6.0.` should be already available

#### Observed behavior (that appears unintentional) 
N/A

#### Possible fixes
N/A

**NOTE:** I don't seem to be able to create any kind of tickets on [Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/)

**Comment by amyblais** [comment]
I believe this was completed last week, but maybe something didn't get propagated yet. I'll check with our DevOps team on this.

**Comment by TehPeGaSuS** [comment]
I see that the update reached the Ubu ntu repositories.

Is this wait normal, between the release and the repository update, or was this just a glitch?

Thanks

**Comment by amyblais** [comment]
The packages are normally updated within a week or so after a release,
