### ISSUE TITLE
Accessibility: the region where the edit field for a message is placed is wrongly named

### ISSUE THREAD

**Issue by Masarczyk-Wienfluss** [mattermost/mattermost#26599]
#### Summary
Mattermost Server: Version 8.1.8
The edit field for a message in a conversation is placed inside a region with the name "Login Successful, message input". While the "Message input" part is true, the "Login successful" label is redundant.
#### Steps to reproduce
1. Load a conversation.
2. With a screen reader such as NVDA on, navigate to the message writing area by pressing F6.
#### Expected behavior
Just "Message Input, complementary region" should be announced.
#### Observed behavior (that appears unintentional)
Additionally, the message "Login successful" is spoken.
#### Possible fixes
Most likely the login successful announcement is a part of a label somewhere more parent so that it is read out in sequence when navigating to that particular spot.

**Comment by amyblais** [comment]
Ticket for reference https://mattermost.atlassian.net/browse/MM-58009.

**Comment by marianunez** [comment]
@Masarczyk-Wienfluss this was fixed in https://github.com/mattermost/mattermost/pull/24979 and should be available in version server 9.3
