### ISSUE TITLE
When uploading files larger than 30MB，An error occurred while uploading your file.

### ISSUE THREAD

**Issue by muchenlou** [mattermost/mattermost#26618]
I've changed its upload size in the backend and adjusted it to 1000MB, but uploading small files is still normal, but uploading large files is still a problem.
![1711596228309](https://github.com/mattermost/mattermost/assets/29274677/80fc0ceb-c2db-4e47-8802-492368bc7d64)

mattermost version :
![image](https://github.com/mattermost/mattermost/assets/29274677/37d10199-b12c-4e78-8d7d-ac9ab96c9a14)

configurations: 
![image](https://github.com/mattermost/mattermost/assets/29274677/46f02ae1-3d7f-4a26-9bbc-1ce29dfd2e94)

**Comment by agnivade** [comment]
Please share your server logs. Do you have an nginx proxy before your server? If so, then you might need to bump up the limits for that as well.

**Comment by muchenlou** [comment]
@agnivade  I am deploying using docker and configured nginx ssl for https communication, how should I view the logs

**Comment by muchenlou** [comment]
@agnivade  The size of the file I uploaded is 30M
