### ISSUE TITLE
not possible to simply move Plesk-extension-installed Mattermost instances between servers

### ISSUE THREAD

**Issue by 0spinboson** [mattermost/mattermost#26624]
#### Summary
You can't neatly move MM installations created using the MM plesk extension between Plesk servers.

#### Steps to reproduce
install plesk extension on two different Plesk servers, create an instance on 1 server, move it to the other server using the plesk migration tools.

#### Expected behavior
One of the main selling points of Plesk obviously is to be able to easily move websites / applications between different servers. This is also part of Plesk's advice when upgrading servers -- to move domains to a different server temporarily, then upgrade, then move them back if you desire. I would expect a MM plesk extension to allow this, but right now not even the MM instance's database is saved inside the domain you install it to, making it impossible to move the installation to another server without extensive manual intervention.

#### Observed behavior (that appears unintentional) 
After moving, the installation isn't accessible on the new server.

#### Possible fixes
the installation files should all be saved in the subscription/domain so they can be moved between servers.

**Comment by amyblais** [comment]
Hi @0spinboson, what Mattermost server version are you on?

**Comment by 0spinboson** [comment]
The one provided by the most recent version of the plesk extension, 7.1

**Comment by amyblais** [comment]
Thank you, v7.1 is currently an unsupported version. I believe the Mattermost team currently doesn't own Plesk and this might be a community-maintained project. Would you be open to taking a look if any existing issues on the Plesk forum https://talk.plesk.com/tags/mattermost/ or in the Mattermost forum https://forum.mattermost.com/search?q=plesk may be helpful?

**Comment by 0spinboson** [comment]
yeah I understand that version's not supported, but the issue isn't with the version, but with how the plesk extension is configured. If that isn't maintained by the mattermost team, I don't really know who should address it, but I don't know who maintains (or maintained) it because I can't find that information anywhere, which is why I opened this report.

As for the forums you linked, as far as I can tell none of the issues are about this except maybe tangentially (in the sense that others may run into the same root issue for different reasons).

**Comment by coltoneshaw** [comment]
Hey @0spinboson - Unfortunately, the Plesk extension for Mattermost is not maintained or developed by Mattermost. 

> I would expect a MM plesk extension to allow this, but right now not even the MM instance's database is saved inside the domain you install it to, making it impossible to move the installation to another server without extensive manual intervention.

Standard for postgres is to install the database under `/var/lib/pgsql/data`, depending on the specific OS. It looks like Plesk expects this under `/var/www/vhosts/YourDomain.com/mattermost` (or similar). So, it makes sense why moving the domain does not move the database. 

Unfortunately, this is something to bring up with the maintainers of that specific extension. It seems that the maintainer is 
Apheleia IT AG, but i cannot find any concrete info for you on how to contact them.

All that said, I would suggest attempting to install Docker on your Plesk server and then implementing Mattermost Docker, as a much more containerized approach here that would allow moving to be easier. https://docs.mattermost.com/install/install-docker.html
