### ISSUE TITLE
Add webp to MediaContentTypes in server to allow public links to show inline content

### ISSUE THREAD

**Issue by Obbi89** [mattermost/mattermost#26628]
#25784 added preview support for webp images to the webapp. It might make sense (for consistency reasons) to add [image/webp](https://caniuse.com/webp) to the list of image formats on the server, too.  
This would change forceDownload in the `files/{file_id}/public` api endpoint to *false* and display the image inline in the browser as one might expect when sharing links to webp images.

https://github.com/mattermost/mattermost/blob/acbaf4c2833603ead11050bb18bcb3921e9a5812/server/platform/shared/web/files.go#L24-L35

While at it one might consider adding [video/webm](https://caniuse.com/webm) and maybe even [image/avif](https://caniuse.com/avif). Both have similar support in browsers but would then need webapp preview support as well.

While checking the jira I got results that might need some updates :)
- https://mattermost.atlassian.net/browse/MM-29182 should be closed as webp preview in webapp is done
- https://mattermost.atlassian.net/browse/MM-11777?focusedCommentId=161335 got closed even though it was meant to track heic, avif and others

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @Obbi89,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57851.
