### ISSUE TITLE
Notification sounds stack when a mattermost tab is inactive in chrome, causing loud volume of dings when the tab is clicked again.

### ISSUE THREAD

**Issue by marican** [mattermost/mattermost#26632]
#### Summary
Notification sounds stack when a mattermost tab is inactive in chrome, causing loud volume of dings when the tab is clicked again.

#### Steps to reproduce
Open up a somewhat busy mattermost server in a tab in chrome (tested in windows).  Don't return to that tab for 6-8 hours.  Click back on tab and throw your headphones across the room while cursing.

#### Expected behavior
A single notification ding with a normal volume.

#### Observed behavior (that appears unintentional) 
All notification dings play at the same time, blowing out speakers and eardrums.

#### Possible fixes
IF ding > 1 THEN
  ding = 1
END IF

**Comment by amyblais** [comment]
Hi @marican, what Mattermost server version, Chrome version, and Windows version are you on?
Does this issue reproduce on our community server here https://community.mattermost.com/?

**Comment by marican** [comment]
Chrome version 122.0.6261.128
Windows 10 pro 19045.4170
I've joined the server for testing, but yall don't talk much so it might be a while before several dings stack up to test.  
its possible that this is some form of program or OS sleeping, and not just the tab sleeping/hibernating.  Several of my collogues have experienced the same phenomenon.  I believe they have similar systems to mine.

**Comment by amyblais** [comment]
Thank you, we currently support Mattermost server versions v9.5.0 and newer. It would be helpful if you're either able to upgrade to a more recent version to see if you are still experiencing the issue, or confirm if you are able to reproduce the issue on the community server (which is on the latest server version).

**Comment by amyblais** [comment]
Closing for now. If you're able to reproduce this issue on a supported server version, please let us know, and I can open a ticket to take a look.
