### ISSUE TITLE
stuck in search

### ISSUE THREAD

**Issue by kpgosite** [mattermost/mattermost#26648]
#### Summary
Mattermost via web browser stuck in search and cannot view any posts.

#### Steps to reproduce
logging in/out and using a different wed browser produced the same results

#### Expected behavior
Mattermost web browser stuck in search indefinitely 

#### Observed behavior (that appears unintentional) 
NA

#### Possible fixes
NA

![stuck](https://github.com/mattermost/mattermost/assets/64050562/011e127a-8067-47c8-bcfb-881eacd723e1)

**Comment by amyblais** [comment]
What Mattermost server version are you on? What OS and version are you using?

**Comment by kpgosite** [comment]
![image](https://github.com/mattermost/mattermost/assets/64050562/4e578dec-fa0b-49b9-9cd7-06dad79b2b12)

Windows 10 Pro, Two other work members do not have this issue.

**Comment by amyblais** [comment]
Thank you, we currently support the following Mattermost versions: v8.1.0, v9.5.0 and newer. Would you be open to upgrading to a support version?

**Comment by kpgosite** [comment]
ok, no thank you not at this time

**Comment by amyblais** [comment]
Thanks, I'll close this issue for now, but hopefully your team is able to upgrade to a more recent version,
