### ISSUE TITLE
Insecure private channel with playbook

### ISSUE THREAD

**Issue by lapnd** [mattermost/mattermost#26657]
Hi,
I created a private channel and add few members to join this channel only. That works fine.

After run a playbook on this channel, all other members can self-join this private channel without any invitation. Is this expected behavior? I think that is big security/privacy hole.

I'm using latest mattermost version on docker.

**Comment by amyblais** [comment]
Hi @lapnd, can you help report this issue via our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/)?

**Comment by amyblais** [comment]
I asked internally with our team, and it seems that this is intentional behaviour and is currently working as expected. Thank you for the feedback,
