### ISSUE TITLE
[Bug] V9.6.1 About mattermost dialog shows "ci" as current version

### ISSUE THREAD

**Issue by dRb1e** [mattermost/mattermost#26659]
Summary
When viewing the About mattermost dialog in Mattermost team edition 9.6.1, the version is shown as "ci". This is after upgrading from Mattermost 9.0.0.

Steps to reproduce
Open the "About mattermost" dialog

Expected behavior
The correct version info should be shown

Observed behavior (that appears unintentional)

![image](https://github.com/mattermost/mattermost/assets/140081726/5d02e029-d5ef-4f8f-89ea-75c006cfb8c1)

**Comment by dRb1e** [comment]
https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html ,I followed the steps here, and everything works except for this part

**Comment by amyblais** [comment]
We haven't been able to reproduce this internally. Following the upgrade guide, the About Mattermost shows the correct Mattermost version. 

We noticed that your About Mattermost modal includes the Webapp Build Hash which is not expected. Perhaps something went wrong with the upgrade on your end? Do you see any errors in the server logs?

**Comment by dRb1e** [comment]
![image](https://github.com/mattermost/mattermost/assets/140081726/6c769cb0-3a66-4cbd-ad7f-e380e07c5d55)
When I roll back to version 9.0.0, there doesn't seem to be any issue, but when I update to versions 9.0.5 and above, although the server and mobile app show the version correctly, the web interface shows the version as 'ci'.

**Comment by dRb1e** [comment]
In mobile application i can see like that
![image](https://github.com/mattermost/mattermost/assets/140081726/a35839cf-5860-4d9c-8851-783b50497675)

**Comment by mvitale1989** [comment]
Hello @dRb1e, could you try running the following command in your installation directory, and post back the result?
```
grep -r -l "Webapp Build Hash" mattermost/
```
I suspect the binary has been upgraded to 9.6.1 in your installation, but not the `webapp/` directory. It would explain the behaviour you're seeing, where rolling back to 9.0.0 makes this issue disappear

**Comment by dRb1e** [comment]
![image](https://github.com/mattermost/mattermost/assets/140081726/efea3714-aec2-403c-839a-d0a6b2ddcd05)

**Comment by mvitale1989** [comment]
Thank you, that confirms my theory: your `mattermost/client/` directory is not from the 9.6.1 release.

Please try the upgrade to 9.6.1 again, following the upgrade steps from start to finish. In particular, make sure you also run step 7 from [the upgrade guide](https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html#id2):
```
7. Remove all files except data and custom directories from within the current mattermost directory. We strongly recommend reading the important note below before executing the following command.

sudo find mattermost/ mattermost/client/ -mindepth 1 -maxdepth 1 \! \( -type d \( -path mattermost/client -o -path mattermost/client/plugins -o -path mattermost/config -o -path mattermost/logs -o -path mattermost/plugins -o -path mattermost/data \) -prune \) | sort | sudo xargs rm -r
```

**Comment by dRb1e** [comment]
![image](https://github.com/mattermost/mattermost/assets/140081726/1ad6248c-b9ce-4738-8774-96adbf230abb)
I wanted to express my gratitude for helping me resolve the issue. Thanks to the guidance and support provided by your help center, I was able to successfully resolve my problem. 
Best regards

**Comment by mvitale1989** [comment]
Glad you were able to resolve it! I'll close this issue
