### ISSUE TITLE
Convert ./components/latex_inline/latex_inline.tsx from Class Component to Function Component

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost#26679]
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-57711

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Please Assign this to me.

**Comment by larkox** [comment]
@Syed-Ali-Abbas-Zaidi Since you have a few PRs that need addressing, and you haven't been able to address this one yet, I will open it up for up for grabs.

**Comment by artemdev9** [comment]
Hello. Could you please assign this task to me. Thank you.

**Comment by nikhilskul7** [comment]
Can I work on this task?

**Comment by Tihomir-N** [comment]
Hi @larkox, I am also interested in working on this 🙏

**Comment by larkox** [comment]
@nikhilskul7 All yours! Sorry @Tihomir-N , but he asked first :sweat_smile:

**Comment by nikhilskul7** [comment]
Hi @larkox ,
Does mattermost have some documentation to run it locally for the first time?

**Comment by nikhilskul7** [comment]
@larkox  Do you know how I can create account in mattermost locally?
The webapp won't allow me to create one because it's not allowed in this server.

**Comment by larkox** [comment]
@nikhilskul7 When run the server for the first time, it will ask you to create the system admin user. If that did not happen, or you don't remember, you have two options:
- nuke the instance (run `make nuke`). This will delete all the data in your local instance and you can start from the beginning
- Add the test data (run `make test-data`). This will create several users, including a sysadmin that you can use. The credentials for the admin and one user will be shown at the end of the process.
