### ISSUE TITLE
webp not working if file is animated

### ISSUE THREAD

**Issue by Tragen** [mattermost/mattermost#26704]
#### Summary
webp not working if file is animated

#### Steps to reproduce
Upload one of the attached images to mattermost 9.6 or 9.6.1.
[webp.zip](https://github.com/mattermost/mattermost/files/14891153/webp.zip)

#### Expected behavior
The webp file is shown

#### Observed behavior (that appears unintentional) 
It shows just an empty message

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57742.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
