### ISSUE TITLE
Getting 403 Forbidden Error when using incoming webhook.

### ISSUE THREAD

**Issue by piabirajdar** [mattermost/mattermost#26705]
#### Summary
I am trying to use an incoming webhook for a **private  channel** to send messages through a python script. But getting **"403 Client Error: Forbidden for url"** when I run my python script.
When I curl using the same incoming webhook I am able to send that same message through my CLI. 
'curl -vvvv -i -X POST -d 'payload={"text": "Hi There", "channel":"xyz"}' https://teamchat.xyz.com/hooks/{random_hook_chars}'  This command works

** But do I need to provide authentication for incoming webhook in my python code?**

try:
      
        payload = {'text': "Hi There", 'channel': 'xyz'}
        headers = {'Content-Type': 'application/json'}
         
        response = requests.post('https://teamchat.xyz.com/hooks/{random_hook_chars}', headers=headers, data=payload)
        response.raise_for_status()

        return True
    except FileNotFoundError as e:
        print(f"not found: {e}")
        return False

**Comment by amyblais** [comment]
Hi @piabirajdar, what Mattermost server version are you on?

**Comment by piabirajdar** [comment]
> Hi @piabirajdar, what Mattermost server version are you on?
Thanks Amy, 
This can be closed. Sending "json=payload" worked in this case.
