### ISSUE TITLE
Landing page: clicking on "remember my preference" does not tick the associated checkbox

### ISSUE THREAD

**Issue by wetneb** [mattermost/mattermost#26702]
#### Summary

When going to the landing page of a Mattermost instance, I am given the options "View in Desktop App" and "View in Browser" with a checkbox "Remember my preference".

Clicking on "Remember my preference" does not tick the associated checkbox: one needs to click exactly on the checkbox. This a sign for a missing `<label>` which goes against [the guidelines from the Web Accessibility Initiative](https://www.w3.org/WAI/tutorials/forms/labels/). This can impair keyboard navigation or screen reader usage for instance.

The DOM structure there is indeed:
```html
<div class="get-app__preference">
    <button class="get-app__checkbox "></button>
    <span>Remember my preference</span>
</div>
```

#### Steps to reproduce

Observed on the landing page of a Mattermost instance (Team edition version 9.7).

#### Expected behavior

Clicking on the text "Remember my preference" should check / uncheck the associated checkbox.

#### Observed behavior (that appears unintentional) 

Only clicking on the checkbox works.
![remember_my_pref](https://github.com/mattermost/mattermost/assets/309908/fe227b82-730d-414d-92f7-eb6677c3f5d2)

#### Possible fixes

Adding the missing `<label>` element (see guidelines above).

**Comment by M-ZubairAhmed** [comment]
This needs rework to have
```
<label
-- input type=checkbox
-- text
</label
```

**Comment by amyblais** [comment]
Hi @wetneb, what Mattermost server version are you on?
