### ISSUE TITLE
Do Not Disturb

### ISSUE THREAD

**Issue by MNCamargo** [mattermost/mattermost#26706]
it's possible to set, business hours for users?

Example,

User1: 06:00 to 14:00hs

User2: 06:00 to 14:00hs

User3: 14:00 to 18:00hs

Etc to assign the DND? or change tomorrow from 09:00 to 06:00?

**Comment by amyblais** [comment]
Hi @MNCamargo, what Mattermost server version are you on?

**Comment by amyblais** [comment]
We have an existing feature request ticket here: https://mattermost.uservoice.com/forums/306457-general/suggestions/32551213-do-not-disturb-hours. Closing as this can be tracked on the feature request forum,
