### ISSUE TITLE
Invalid key signature since today April 7th 2024

### ISSUE THREAD

**Issue by haslinger** [mattermost/mattermost#26707]
Key signature for dev-ops@mattermost.com is invalid:

```
Err:14 https://deb.packages.mattermost.com focal InRelease
  The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
```
  
Yesterday it was fine.

**Comment by CryptoSiD** [comment]
They key expired 6 April 2024

**Comment by longjon929** [comment]
I tried various things, listed here and on webpages, but those didn't work for me on Ubuntu 20.04.  Piping the key into apt-key did work.  So I'm leaving this hear in case others run into the same problem:

curl -sL -o- https://deb.packages.mattermost.com/pubkey.gpg | gpg --dearmor | sudo apt-key add
