### ISSUE TITLE
Plugin Token Auth Failing

### ISSUE THREAD

**Issue by TheStu** [mattermost/mattermost#26745]
#### Summary
Token authorization is not working correctly when making plugin HTTP requests.

#### Steps to reproduce
Create a plugin that uses ServeHTTP and then make a request to that endpoint from the plugin's webapp.

#### Expected behavior
I expect the request to authenticate correctly and provide a `Mattermost-User-Id` header that I can then use to figure out who the current user is. (see discussion here: https://community.mattermost.com/core/pl/x95rjkxmobfitkbtzzox7rdxjc)

#### Observed behavior (that appears unintentional) 
The user fails to authorize because the CSRF token doesn't appear to be compared correctly.

-----------------------------

I've created a plugin that uses ServeHTTP on the server side to accept incoming API requests. Then on the webapp side I've created a button to send requests to the API endpoint I've set up. Per discussion [here](https://community.mattermost.com/core/pl/x95rjkxmobfitkbtzzox7rdxjc) it looks like my outgoing API request from the webapp should attach some kind of authentication. The server should then validate the authentication and provide a `Mattermost-User-Id` header that I can use to figure out who the user is who is making the request.

This all seems to work up to a point.

From what I can tell this comparison https://github.com/mattermost/mattermost/blob/0a496107d5ddd05fb658767fe268e2862925f7e4/server/channels/app/plugin_requests.go#L170 fails because the `sentToken` variable resolves to an empty string. However I can see in the request headers when I make the request from the webapp to the server that the request is including the correct CSRF token in the cookie (key is `MMCSRF`), the token just isn't being used in the code.

From what I can tell, the CSRF token being passed in the cookies should be accessible by calling `r.Cookie(model.SessionCookieCsrf)`. If that is compared to the `session.GetCSRF()` token then I believe the auth should succeed.

I'm happy to test this out and make a PR but I don't really know anything about the auth schema beyond 10 minutes troubleshooting this file, so I don't want to break anything.

**Comment by amyblais** [comment]
Hi @TheStu, what Mattermost server version are you on?

**Comment by TheStu** [comment]
9.7.0

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57769.

**Comment by TheStu** [comment]
@amyblais I've fixed this locally to be able to continue with my plugin development. Would I be able to submit a PR for this? It's a pretty minimal change -- https://github.com/TheStu/mattermost/commit/9957c6dbd34c10573a0de4311f265928550638d9

I see that no one has been assigned the issue in Atlassian and it would be great to get this fixed so that I can get my plugin working on a production server :)
