### ISSUE TITLE
api: wrong permissions on file uploaded to channel

### ISSUE THREAD

**Issue by haavardw** [mattermost/mattermost#26757]
#### Summary

Files uploaded with `POST /api/v4/files` are not readable for other users in the channel.

#### Steps to reproduce

```
Mattermost Version: 9.7.1
Database Schema Version: 119
Build Number: 8600638412
Database: postgres
```

Example python code that will upload the image `test_image.png` and then create a post linking to this image:
```python
MATTERMOST_SERVER_URL = os.environ['MATTERMOST_URL']
MATTERMOST_TOKEN = os.environ['MATTERMOST_TOKEN']
MATTERMOST_CHANNEL_ID = os.environ['MATTERMOST_CHANNEL_ID']

filename = "test_image.png"
filedata = open(filename, "rb").read()

# upload image
result = requests.post(
    url = MATTERMOST_SERVER_URL + "/api/v4/files",
    headers = {
        "Authorization": "Bearer " + MATTERMOST_TOKEN
    },
    files = {
        'file': (filename, filedata, "image/png"),
    },
    data = {
        'channel_id': MATTERMOST_CHANNEL_ID,
    },
)

assert result.ok, result.text

file_id = result.json()['file_infos'][0]['id']
uploaded_path = MATTERMOST_SERVER_URL + "/api/v4/files/" + file_id

# post a message with a link to the upload image

result = requests.post(
    url = MATTERMOST_SERVER_URL + "/api/v4/posts",
    headers = {
        "Authorization": "Bearer " + MATTERMOST_TOKEN
    },
    json = {
        "channel_id" : MATTERMOST_CHANNEL_ID,
        "message" : f"Here's the link: [image]({uploaded_path})"
    },
)

assert result.ok, result.text
```

#### Expected behavior
1. The code uploads an image and creates a post with a link to this image. 
2. The user should be able to 
  a. click on the link to view the image
  b. right-click on the link to view the image in a new tab

#### Observed behavior (that appears unintentional) 

In step 2a. the user is stuck in a "loading" view
In step 2b. this works for the user who uploaded the image, but other users in the channel gets an error on the form 
```
{
  "id":"api.context.permissions.app_error",
  "message":"You do not have the appropriate permissions.",
  "detailed_error":"",
  "request_id":"<redacted>",
  "status_code":403
}
```

Step 2a is reproduceable manually (without code) by creating a post with a link to a previously uploaded file, e.g. a post on the form `hi, here's a [link](https://<my_mattermost_server>/api/v4/files /<file_id>/preview) (See e.g. the post at https://community.mattermost.com/core/pl/yws4xqurs7gq5fk13oxjzyes8a)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57792.

**Comment by amyblais** [comment]
Closing as the team mentioned that this is working as expected.

**Comment by harshilsharma63** [comment]
hi @haavardw ! This is working as expected. The way file uploads work in Mattermost is that you upload the file via the mentioned `POST /api/v4/files` API, this gives you a `fileID`. This file ID is then linked to a post in a channel. Who can access a file depends on who can access the corresponding post. Only uploading the file won't work. If it did, anyone would be able to see files from channels they are not a member of.

Does that solve your concern?

**Comment by haavardw** [comment]
@harshilsharma63 Not really, I'm not sure the problem is fully understood. 
- This used to work before (I'm not sure what exact version). 
- Authorization should be checked link access time, not when the link is published. In this case the file is uploaded to a given channel and it should be available for users with read access to this channel (as per documentation).

**Comment by harshilsharma63** [comment]
Do you remember what MM version it used to work?

**Comment by harshilsharma63** [comment]
@haavardw Do you remember what MM version it used to work?

**Comment by haavardw** [comment]
@harshilsharma63 It worked in 9.6.0

**Comment by harshilsharma63** [comment]
@haavardw okay, I'll check it out.
