### ISSUE TITLE
Channel header does not render properly when using code block

### ISSUE THREAD

**Issue by Pkarle** [mattermost/mattermost#26756]
#### Summary
Channel header content does not render properly when using code block

#### Steps to reproduce
Add code block within the channel header text field such as :

```java
System.out.println("HEADER IN JAVA")
```

#### Expected behavior
See the content code block/update the UI to improve the behavior when using code block

#### Observed behavior (that appears unintentional) 
![Capture d’écran 2024-04-11 à 08 35 00](https://github.com/mattermost/mattermost/assets/32866015/a1cf0d20-3b61-4415-90c7-8cea31eaa1f7)
![Capture d’écran 2024-04-11 à 08 35 05](https://github.com/mattermost/mattermost/assets/32866015/24cf4ad1-9575-49da-b820-d2965fa4d50a)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57791.

**Comment by Aryakoste** [comment]
Hello @amyblais. I would like to work on this issue.

**Comment by Aryakoste** [comment]
I have looked into this issue. I wanted to ask that should i make code blocks size small so as to adjust it in the header or should i adjust the height of the header according to the codeblocks so it will get bigger. @amyblais

**Comment by amyblais** [comment]
As the solution is not clear, we should first triage this internally. We can open this as Help Wanted after it has been triaged.

**Comment by amyblais** [comment]
From the developers: "this is an edge case that we’ve triaged and determined that is best to not fix at this time. Ideally we wouldn’t want to show code block markdown in the channel header and are considering to limit which markdown elements are supported in the future."
