### ISSUE TITLE
root.html updated even when not needed

### ISSUE THREAD

**Issue by balki** [mattermost/mattermost#26769]
#### Summary
root.html updated even when not needed every time on server start

```
{"timestamp":"2024-04-12 01:05:57.990 -04:00","level":"debug","msg":"Rewriting static assets","caller":"utils/subpath.go:83","from_subpath":"/","to_subpath":"/"}
```
Note, both `from_subpath` and `to_subpath` are same `/`. Yet it tries to write the file

#### Steps to reproduce
Version: 9.5.3
Enable debug logging and restart server.

#### Expected behavior
No write to client directory. So should be possible to keep it readonly.

#### Possible fixes
Check if old and new values are different and only then attempt to write. The comment here is wrong.
https://github.com/mattermost/mattermost/blob/v9.5.3/server/channels/utils/subpath.go#L48

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57839.

**Comment by rowingdude** [comment]
Hi Amy, I will work on this one this week. Thank you.
