### ISSUE TITLE
BUG: compilation

### ISSUE THREAD

**Issue by ThePsina** [mattermost/mattermost#26815]
# github.com/mattermost/mattermost-server/v6/shared/mlog
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:87:11: cannot use generic function logr.Int without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:96:12: cannot use generic function logr.Uint without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:105:14: cannot use generic function logr.String without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:130:12: cannot use generic function logr.Bool without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:143:13: cannot use generic function logr.Array without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:146:11: cannot use generic function logr.Map without instantiation

**Comment by agnivade** [comment]
@ThePsina - I'd suggest to please give clear repro steps and mention clearly what you have done, what you expect, and what did you see. Thanks.

**Comment by ThePsina** [comment]
![image](https://github.com/mattermost/mattermost/assets/62567705/9a12dc06-ff67-4610-aa76-4e8cfdb634c9)

**Comment by ThePsina** [comment]
@agnivade forgot to tag you

**Comment by agnivade** [comment]
I'm sorry, I don't understand "step: try to compile app with "github.com/mattermost/mattermost-plugin-apps/apps" lib". Please mention clear steps, without any screenshots, how should one reproduce this.

**Comment by ThePsina** [comment]
@agnivade 
i use goland, because it's comfort for me. All code are written in this ide
go version: 1.22

step 1: write code with using library github.com/mattermost/mattermost-plugin-apps/apps (i write bot-app for mattermost)
step 2: install all dependencies in your go.mod - after go mod tidy you will see in go.mod something like this:
```
module <your module>

go 1.22

require (
...

	github.com/mattermost/ldap v3.0.4+incompatible // indirect
	github.com/mattermost/logr/v2 v2.0.21 // indirect
	github.com/mattermost/mattermost-plugin-api v0.1.1 // indirect
	github.com/mattermost/mattermost-server/v6 v6.7.2 // indirect
...
)

...
```
step 3: write all creds/envs/configs in your app to prepare for run
step 4: run your code by run-button in goland
step 5: receive compile error:
```
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:87:11: cannot use generic function logr.Int without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:96:12: cannot use generic function logr.Uint without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:105:14: cannot use generic function logr.String without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:130:12: cannot use generic function logr.Bool without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:143:13: cannot use generic function logr.Array without instantiation
go/pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/shared/mlog/mlog.go:146:11: cannot use generic function logr.Map without instantiation
```

i expected:
run without compile error from library github.com/mattermost/mattermost-server/v6

**Comment by ThePsina** [comment]
i found that https://github.com/mattermost/mattermost/blob/v6.7.2 on [go1.16](https://github.com/mattermost/mattermost/blob/v6.7.2/go.mod#L3) and library that is exported [here](https://github.com/mattermost/mattermost/blob/v6.7.2/shared/mlog/mlog.go#L96) is on [go1.18](https://github.com/mattermost/logr/blob/v2.0.21/go.mod#L3)

**Comment by ThePsina** [comment]
i used libraries from [example](https://developers.mattermost.com/integrate/apps/drivers/golang/)

**Comment by ThePsina** [comment]
@agnivade ping

**Comment by ThePsina** [comment]
@agnivade ping

**Comment by agnivade** [comment]
Unfortunately, I still don't understand what you are trying to do. I will leave it to someone else.

**Comment by amyblais** [comment]
I'll close this for now as our team is not sure about this issue. Would you instead be open to posting about this on one of our troubleshooting forums, either at https://community.mattermost.com/core/channels/peer-to-peer-help or at https://forum.mattermost.com/?
