### ISSUE TITLE
How to compile Enterprise?

### ISSUE THREAD

**Issue by KatiaSishost** [mattermost/mattermost#26818]
Hello, I'm doing a couple of tests, and I manage to compile everything but when I change the /bin/mattermost and /bin/mmctl files with the new ones generated...

in the admin console... it shows that I have the Team Edition version but when I put the /bin/mattermost /bin/mmctl it tells me that I have the Enterprise version with its expiration date and so on.

Could someone tell me how to compile the enterprise version so I can test directly with the version that is going to be used?

From already thank you very much.

**Comment by amyblais** [comment]
Per Mattermost guidelines, GitHub issues are mainly used for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting questions, feel free to use https://forum.mattermost.com/. You can also post your question at https://community.mattermost.com/core/channels/peer-to-peer-help.
