### ISSUE TITLE
Concurrent map iteration and map write

### ISSUE THREAD

**Issue by PalachN** [mattermost/mattermost#26810]
Service down
The problem [#25903](https://github.com/mattermost/mattermost/issues/25903) recurred. 

Apr 17 06:50:08 *** mattermost[1922501]: fatal error: concurrent map iteration and map write
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922515 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922523 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922532 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922543 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922551 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922560 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Killing process 1922626 (plugin-linux-am) with signal SIGKILL.
Apr 17 06:50:08 *** systemd[1]: mattermost.service: Failed with result 'exit-code'.

Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: postgres

**Comment by agnivade** [comment]
Please show us the output of `journalctl -r -u mattermost`.

**Comment by PalachN** [comment]
Latest events

[mattermost_2024_04_17.log](https://github.com/mattermost/mattermost/files/15005512/mattermost_2024_04_17.log)

**Comment by agnivade** [comment]
Is that the output from the command? It seems to contain systemd entries as well.

**Comment by PalachN** [comment]
This is the output of the command. We've included the last few entries that might relate problem

**Comment by agnivade** [comment]
Unfortunately this does not contain the stack trace of the crash. Can you attach the mattermost.log file?

**Comment by PalachN** [comment]
Yes. Unfortunately does not contain the stack trace of the crash. 
The attachment contains part of the mattermost.log before the crash.
[mattermost_2024_04_17_2.log](https://github.com/mattermost/mattermost/files/15062319/mattermost_2024_04_17_2.log)

**Comment by agnivade** [comment]
Yeah that's of no use unfortunately. @streamer45 - Any idea why journalctl doesn't seem to have the stack trace?

**Comment by streamer45** [comment]
Weird, I would expect to see it in there unless `GOTRACEBACK` is being used. May be worth checking the service file. @PalachN what operating system version is Mattermost running on?

**Comment by PalachN** [comment]
@streamer45 
Linux version 4.18.0-513.11.0.1.el8_9.x86_64 Red Hat 8.5.0-20.0.1

**Comment by streamer45** [comment]
@PalachN Thanks. To debug this further it would be helpful to share the following:

- The Mattermost `config.json` file (sanitized).
- Your `mattermost.service` systemd file.

**Comment by amyblais** [comment]
Closing for now as we haven't received a response. We can re-open this if the issue persists,

**Comment by amyblais** [comment]
@streamer45 Logs and other details are shared here https://github.com/mattermost/mattermost/issues/27252

**Comment by PalachN** [comment]
The problem recurred

Jun 28 23:59:35 mmst-app01.corp.skbbank.ru mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.075 +05:00","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:443","logSource":"notifications","ackId":"1tr6pp3tx3rg7j71fcs4tr3iko","type":"message","userId":"d6nbcc8eupfx9k8k9fowa595fe","postId":"63s9sp1q3prsukn3hjydwrqdyw","status":"Prepared to send"}
Jun 28 23:59:35 mmst-app01.corp.skbbank.ru mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.075 +05:00","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:443","logSource":"notifications","ackId":"d6cytuinbibsfea7kzisewtjja","type":"message","userId":"bzo7zuebn7y78euxfsa1st8mcw","postId":"63s9sp1q3prsukn3hjydwrqdyw","status":"Prepared to send"}
Jun 28 23:59:35 mmst-app01.corp.skbbank.ru mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.279 +05:00","level":"info","msg":"Notification sent","caller":"app/notification_push.go:143","logSource":"notifications","ackId":"1tr6pp3tx3rg7j71fcs4tr3iko","type":"message","userId":"d6nbcc8eupfx9k8k9fowa595fe","postId":"63s9sp1q3prsukn3hjydwrqdyw","channelId":"6z9z9edzwtgoupcm1e3tbdux8y","deviceId":"dwgMLWsQQI6IHTJ129xgp2:APA91bHGCs4hjgRLSb9Il6gEv_P7sU8MacIsXvGoq7ugpfLqh371AY5ALZGu1iNPLCm7vvOoZuf0Lg8Gam3Zv7fP5WRpGp2voAWyCtfg9rA5KDxqVYNbIhMHf6Y8n82f3gNguX96k508","status":"Successful"}
Jun 28 23:59:35 mmst-app01.corp.skbbank.ru mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.280 +05:00","level":"info","msg":"Notification sent","caller":"app/notification_push.go:143","logSource":"notifications","ackId":"d6cytuinbibsfea7kzisewtjja","type":"message","userId":"bzo7zuebn7y78euxfsa1st8mcw","postId":"63s9sp1q3prsukn3hjydwrqdyw","channelId":"6z9z9edzwtgoupcm1e3tbdux8y","deviceId":"e57vIRRhQ4KoYOzrq9N9YR:APA91bHZQOrjE4N_1ShrFOXyPAKVBRVO7Hljiswivc1cAzRyiI20LTlyDGXIrL_3w4cxnVbM0S9Dw9FfLdrNYzAt_9OQMlhLKqLsasN2EHlyGTHlQU4BeyVv1-kAoD-jXf4GY9auBiTn","status":"Successful"}
Jun 28 23:59:35 mmst-app01.corp.skbbank.ru mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.536 +05:00","level":"info","msg":"Notification received","caller":"app/notification_push.go:472","logSource":"notifications","ackId":"1tr6pp3tx3rg7j71fcs4tr3iko","type":"message","deviceType":"android","receivedAt":1719601175309,"status":"Received by device"}
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru mattermost[2941151]: {"timestamp":"2024-06-28 23:59:36.442 +05:00","level":"info","msg":"Notification received","caller":"app/notification_push.go:472","logSource":"notifications","ackId":"d6cytuinbibsfea7kzisewtjja","type":"message","deviceType":"android","receivedAt":1719601177428,"status":"Received by device"}
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru mattermost[2941151]: fatal error: concurrent map iteration and map write
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941164 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941171 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941181 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941192 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941203 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941212 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Killing process 2941256 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mmst-app01.corp.skbbank.ru systemd[1]: mattermost.service: Failed with result 'exit-code'.

Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: postgres

**Comment by PalachN** [comment]
The problem recurred

Jun 28 23:59:35 mask mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.075 +05:00","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:443","logSource":"notifications","ackId":"1tr6pp3tx3rg7j71fcs4tr3iko","type":"message","userId":"d6nbcc8eupfx9k8k9fowa595fe","postId":"63s9sp1q3prsukn3hjydwrqdyw","status":"Prepared to send"}
Jun 28 23:59:35 mask mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.075 +05:00","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:443","logSource":"notifications","ackId":"d6cytuinbibsfea7kzisewtjja","type":"message","userId":"bzo7zuebn7y78euxfsa1st8mcw","postId":"63s9sp1q3prsukn3hjydwrqdyw","status":"Prepared to send"}
Jun 28 23:59:35 mask mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.279 +05:00","level":"info","msg":"Notification sent","caller":"app/notification_push.go:143","logSource":"notifications","ackId":"1tr6pp3tx3rg7j71fcs4tr3iko","type":"message","userId":"d6nbcc8eupfx9k8k9fowa595fe","postId":"63s9sp1q3prsukn3hjydwrqdyw","channelId":"6z9z9edzwtgoupcm1e3tbdux8y","deviceId":"dwgMLWsQQI6IHTJ129xgp2:APA91bHGCs4hjgRLSb9Il6gEv_P7sU8MacIsXvGoq7ugpfLqh371AY5ALZGu1iNPLCm7vvOoZuf0Lg8Gam3Zv7fP5WRpGp2voAWyCtfg9rA5KDxqVYNbIhMHf6Y8n82f3gNguX96k508","status":"Successful"}
Jun 28 23:59:35 mask mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.280 +05:00","level":"info","msg":"Notification sent","caller":"app/notification_push.go:143","logSource":"notifications","ackId":"d6cytuinbibsfea7kzisewtjja","type":"message","userId":"bzo7zuebn7y78euxfsa1st8mcw","postId":"63s9sp1q3prsukn3hjydwrqdyw","channelId":"6z9z9edzwtgoupcm1e3tbdux8y","deviceId":"e57vIRRhQ4KoYOzrq9N9YR:APA91bHZQOrjE4N_1ShrFOXyPAKVBRVO7Hljiswivc1cAzRyiI20LTlyDGXIrL_3w4cxnVbM0S9Dw9FfLdrNYzAt_9OQMlhLKqLsasN2EHlyGTHlQU4BeyVv1-kAoD-jXf4GY9auBiTn","status":"Successful"}
Jun 28 23:59:35 mask mattermost[2941151]: {"timestamp":"2024-06-28 23:59:35.536 +05:00","level":"info","msg":"Notification received","caller":"app/notification_push.go:472","logSource":"notifications","ackId":"1tr6pp3tx3rg7j71fcs4tr3iko","type":"message","deviceType":"android","receivedAt":1719601175309,"status":"Received by device"}
Jun 28 23:59:36 mask mattermost[2941151]: {"timestamp":"2024-06-28 23:59:36.442 +05:00","level":"info","msg":"Notification received","caller":"app/notification_push.go:472","logSource":"notifications","ackId":"d6cytuinbibsfea7kzisewtjja","type":"message","deviceType":"android","receivedAt":1719601177428,"status":"Received by device"}
Jun 28 23:59:36 mask mattermost[2941151]: fatal error: concurrent map iteration and map write
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941164 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941171 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941181 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941192 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941203 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941212 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Killing process 2941256 (plugin-linux-am) with signal SIGKILL.
Jun 28 23:59:36 mask systemd[1]: mattermost.service: Failed with result 'exit-code'.

Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: postgres

**Comment by agnivade** [comment]
@PalachN - Please see the comment here: https://github.com/mattermost/mattermost/issues/26810#issuecomment-2072302235. To clarify, we need the stack trace of the crash. Without that, it's quite impossible to find the bug.

**Comment by PalachN** [comment]
@agnivade Files are attached in the header of the post
 https://github.com/mattermost/mattermost/issues/27252

**Comment by agnivade** [comment]
Thanks. It looks okay to me. It's a bit weird that the stack trace isn't appearing in your logs. I feel there's possibly something else that's suppressing the stack trace generation. `GOTRACEBACK` doesn't seem to be involved here.  @streamer45 - any ideas?

**Comment by streamer45** [comment]
@PalachN Do you have `DEBUG` level logs available from the time of the crash? If not, I suggest enabling them as they may help a bit to identify what could be triggering this.

**Comment by ThiefMaster** [comment]
I just encountered the same crash, here's my traceback:

```
fatal error: concurrent map iteration and map write

goroutine 782596154 gp=0xc0347e4380 m=29 mp=0xc02cd7d808 [running]:
runtime.fatal({0x292104c?, 0x0?})
	runtime/panic.go:1042 +0x5c fp=0xc0597a18c0 sp=0xc0597a1890 pc=0x43fc1c
runtime.mapiternext(0xc0597a1a10)
	runtime/map.go:869 +0x3b fp=0xc0597a1930 sp=0xc0597a18c0 pc=0x415dbb
github.com/mattermost/mattermost/server/public/model.(*Session).MarshalMsg(0xc01d236c80, {0x0, 0x0, 0x0})
	github.com/mattermost/mattermost/server/public/model/session_serial_gen.go:258 +0x34d fp=0xc0597a1a80 sp=0xc0597a1930 pc=0xbb74cd
github.com/mattermost/mattermost/server/v8/platform/services/cache.(*LRU).set(0xc0002de930, {0xc049ca8000, 0x1a}, {0x27b8880, 0xc01d236c80}, 0x8bb2c97000?)
	github.com/mattermost/mattermost/server/v8/platform/services/cache/lru.go:150 +0xf5 fp=0xc0597a1b28 sp=0xc0597a1a80 pc=0xc01015
github.com/mattermost/mattermost/server/v8/platform/services/cache.(*LRU).SetWithExpiry(...)
	github.com/mattermost/mattermost/server/v8/platform/services/cache/lru.go:86
github.com/mattermost/mattermost/server/v8/platform/services/cache.LRUStriped.SetWithExpiry({{0xc0024b4880, 0xf, 0xf}, {0x0, 0x0}, {0x0, 0x0}}, {0xc049ca8000, 0x1a}, {0x27b8880, ...}, ...)
	github.com/mattermost/mattermost/server/v8/platform/services/cache/lru_striped.go:77 +0x8f fp=0xc0597a1b80 sp=0xc0597a1b28 pc=0xc022af
github.com/mattermost/mattermost/server/v8/platform/services/cache.(*LRUStriped).SetWithExpiry(0xc04f674720?, {0xc049ca8000?, 0x671bcf3ad9bf?}, {0x27b8880?, 0xc01d236c80?}, 0x4877e80?)
	<autogenerated>:1 +0xc7 fp=0xc0597a1c28 sp=0xc0597a1b80 pc=0xc03807
github.com/mattermost/mattermost/server/v8/channels/app/platform.(*PlatformService).AddSessionToCache(0xc000a56b08, 0xc01d236c80)
	github.com/mattermost/mattermost/server/v8/channels/app/platform/session.go:49 +0x6a fp=0xc0597a1c68 sp=0xc0597a1c28 pc=0x18adcaa
github.com/mattermost/mattermost/server/v8/channels/app/platform.(*PlatformService).UpdateLastActivityAtIfNeeded(0xc000a56b08, {{0xc030341ca0, 0x1a}, {0xc049ca8000, 0x1a}, 0x1916f41eb06, 0x1950e3a9b05, 0x191992fefc7, {0xc049ca8020, 0x1a}, ...})
	github.com/mattermost/mattermost/server/v8/channels/app/platform/status.go:244 +0x50d fp=0xc0597a1ef0 sp=0xc0597a1c68 pc=0x18b302d
github.com/mattermost/mattermost/server/v8/channels/app/platform.(*PlatformService).NewWebConn.func1()
	github.com/mattermost/mattermost/server/v8/channels/app/platform/web_conn.go:195 +0x85 fp=0xc0597a1fb0 sp=0xc0597a1ef0 pc=0x18b5705
github.com/mattermost/mattermost/server/v8/channels/app/platform.(*PlatformService).Go.func1()
	github.com/mattermost/mattermost/server/v8/channels/app/platform/goroutines.go:14 +0x22 fp=0xc0597a1fe0 sp=0xc0597a1fb0 pc=0x18a2242
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0597a1fe8 sp=0xc0597a1fe0 pc=0x47a861
created by github.com/mattermost/mattermost/server/v8/channels/app/platform.(*PlatformService).Go in goroutine 782596152
	github.com/mattermost/mattermost/server/v8/channels/app/platform/goroutines.go:13 +0x73

goroutine 1 gp=0xc0000061c0 m=nil [chan receive, 1888 minutes]:
runtime.gopark(0xa9e505?, 0x25b4680?, 0x1?, 0x1b?, 0xc004613b68?)
	runtime/proc.go:402 +0xce fp=0xc00a183ad8 sp=0xc00a183ab8 pc=0x442aee
runtime.chanrecv(0xc0000b6e40, 0x0, 0x1)
	runtime/chan.go:583 +0x3bf fp=0xc00a183b50 sp=0xc00a183ad8 pc=0x40c57f
runtime.chanrecv1(0xc0000b6e40?, 0xc004613c18?)
	runtime/chan.go:442 +0x12 fp=0xc00a183b78 sp=0xc00a183b50 pc=0x40c192
github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands.runServer(0xc0005b2070, 0xc0000b6e40)
	github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands/server.go:120 +0x1fd fp=0xc00a183c58 sp=0xc00a183b78 pc=0x23272bd
github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands.serverCmdF(0x4848b80, {0x28764a1?, 0x4?, 0x2876475?})
	github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands/server.go:58 +0x10a fp=0xc00a183cd0 sp=0xc00a183c58 pc=0x2326fca
github.com/spf13/cobra.(*Command).execute(0x4848b80, {0xc000126040, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca fp=0xc00a183e58 sp=0xc00a183cd0 pc=0x22ebdaa
github.com/spf13/cobra.(*Command).ExecuteC(0x4848b80)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff fp=0xc00a183f30 sp=0xc00a183e58 pc=0x22ec67f
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands.Run(...)
	github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands/root.go:17
main.main()
	github.com/mattermost/mattermost/server/v8/cmd/mattermost/main.go:23 +0x88 fp=0xc00a183f50 sp=0xc00a183f30 pc=0x232aa68
runtime.main()
	runtime/proc.go:271 +0x29d fp=0xc00a183fe0 sp=0xc00a183f50 pc=0x44269d
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00a183fe8 sp=0xc00a183fe0 pc=0x47a861
```

**Comment by streamer45** [comment]
Thanks @ThiefMaster, that looks exactly like what we were missing.

**Comment by streamer45** [comment]
Filed https://mattermost.atlassian.net/browse/MM-60307

**Comment by ThiefMaster** [comment]
This was on v9.9.1 btw (custom build but none of my changes are likely to be related to that crash).

**Comment by agnivade** [comment]
Ahh thank you @ThiefMaster !

**Comment by ThiefMaster** [comment]
I'm afraid that won't help since we jumped from 9.2.x to 9.9.x

**Comment by agnivade** [comment]
Ok, that still helps! So you didn't see this crash in 9.2.x?

**Comment by ThiefMaster** [comment]
Not sure if I still have logs for that. Since my container infra automatically restarts the pod in case of a crash (or lack of response from the server), I don't necessarily notice it. But if I still have such old logs I can check.

**Comment by hanzei** [comment]
Closing, as the issue has been fixed with https://github.com/mattermost/mattermost/pull/28195.
