### ISSUE TITLE
Fix dropdown-position of select element in Interactive Dialogs

### ISSUE THREAD

**Issue by annaos** [mattermost/mattermost#26831]
#### Summary
In the case of scrollable interactive dialogs with a select field, the select dropdown is not scrolled.

#### Steps to reproduce

1. Make your window smaller
2. Open a long interactive dialogue with a select box
3. Click on the select box to show the drop down menu
4. Scroll down

#### Expected behavior
Dropdown scrolls with dialogue content

#### Observed behavior (that appears unintentional) 
Dropdown has a fixed position in the window
![Bildschirmfoto vom 2024-04-21 12-57-36](https://github.com/mattermost/mattermost/assets/5798989/26ad0e6f-6756-4c97-9809-2edb5829159f)
![Bildschirmfoto vom 2024-04-21 12-57-56](https://github.com/mattermost/mattermost/assets/5798989/9218332a-12f4-4481-b12e-20d7edb888b3)

#### Possible fixes
Will provided in PR

**Comment by sCmEcOLJUcL** [comment]
Hi! please tell me what releases consiste the fix?

**Comment by annaos** [comment]
I think it should be in v9.9.0
