### ISSUE TITLE
GetEmojiList caps page size to 200 even if the request specifies a larger per_page value

### ISSUE THREAD

**Issue by connorkuehl** [mattermost/mattermost#26830]
#### Summary

The "Get a list of custom emoji" endpoint seems to limit the page size for listing emojis to 200 even when a larger page size is specified in the request.

#### Steps to reproduce

Mattermost 9.7.1

1. Have more than 200 custom emojis

```
mattermost=# SELECT COUNT(*) FROM emoji WHERE deleteat=0;
 count
-------
   230
(1 row)
```

2. Request more than 200 emojis

```console
$ curl -s -H 'Authorization: Bearer REDACTED' 'https://REDACTED/api/v4/emoji?per_page=300&page=0' | jq '. | length'
200
```

#### Expected behavior

Since the request's `per_page` parameter is larger than the total number of custom emojis on the server, I would have expected all 230 entries in the response.

#### Observed behavior (that appears unintentional) 

Only 200 entries are returned in the response, despite the per_page parameter being larger.

**Comment by connorkuehl** [comment]
Ah, I see it is not a bug

https://github.com/mattermost/mattermost/blob/62064e3bf7e0d66101968eca672e704f5b26b54f/server/channels/web/params.go#L259

**Comment by connorkuehl** [comment]
@amyblais Do you know if this limit is mentioned in the API docs? It is possible I have just missed it.

**Comment by amyblais** [comment]
Opened to fix API docs https://mattermost.atlassian.net/browse/MM-57966.

**Comment by agnivade** [comment]
@connorkuehl - Thanks for raising this? This is a global limit that is applied to all endpoints. Would you be open to send a PR to fix this? The directory which contains the files are `/api/v4/source/`. Just something like "The maximum number of elements per page is capped to 200. Setting a higher number will be automatically capped to 200." should do.

**Comment by kaoski** [comment]
Hi @agnivade , @amyblais , @connorkuehl, I've created a PR to update the documentation as suggested by @agnivade. Could you please review it?
