### ISSUE TITLE
Firefox tab crashes right after login for Firefox browser version 115.9.1esr

### ISSUE THREAD

**Issue by christianhueserhzdr** [mattermost/mattermost#26838]
#### Summary

Browser tab crashes after upgrading from package _**firefox-115.8.0-1.el8_9.x86_64**_ to _**firefox-115.9.1-1.el8_9.x86_64**_

#### Steps to reproduce

1. Login via GitLab Single Sign-On
2. Page will be redirected and Mattemost ist visible for about a second until the browser tab finally crashes.

#### Expected behavior

Mattermost should stay visible without letting the browser tab crash.

#### Observed behavior (that appears unintentional) 

Mattermost tab crashes.

#### Possible fixes

n.a.

**The Mattermost server version:**

* Mattermost Team Edition
* Mattermost Version: 9.4.3

Is this browser issue known and is there a solution or workaround for that?

Do you need any additional information?

Thank you very much for your support!

**Comment by hmhealey** [comment]
Hi @christianhueserhzdr. Thanks for the report!

If you have the JS console open when that happens, do you see any error messages printed to the console when that happens? And when you say that it crashed, do you mean the page goes completely blank or that you get the "Your tab just crashed" error from Firefox itself?

I'm not aware of anything that would cause different versions of Firefox to behave differently there, so anything that could give us a better idea of what's happening here would be helpful

**Comment by hmhealey** [comment]
Thanks for the screenshot! Unfortunately, that doesn't point to anything in Mattermost that might be the cause. From some googling, it sounds like it might be an issue with Firefox itself, but it's possible that MM is doing something to trigger that. If they go to `about:crashes`, there's crash logs that might contain more info about it whatever happened to cause it to crash

https://support.mozilla.org/en-US/kb/troubleshoot-firefox-crashes-closing-or-quitting

**Comment by hmhealey** [comment]
No worries. I'm not sure how much else we can do to help then, but I'll keep an eye out for anything else that might help.

My only other idea would be to try disabling any browser extensions that the user has to see if those might be related to the issue. Perhaps MM is causing one of them to break or vice versa. That could explain what is happening if not everyone is affected by the issue

**Comment by christianhueserhzdr** [comment]
Dear Harrison @hmhealey, the issue has now been fixed in Firefox version: firefox-115.10.0-1.el8_9.x86_64. For this reason I think we can close this issue. Thank you very much again for your support and quick responses. :+1:
