### ISSUE TITLE
Remove Desktop app contributor Event from upcoming event section

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/mattermost#26842]
![Screenshot_2024_0422_223634](https://github.com/mattermost/mattermost/assets/71702982/4c5871b2-42b4-43bf-be34-bd3210c97796)
https://mattermost.com/events/

**Comment by fasal26** [comment]
@varghesejose2020 I would like to take this one

**Comment by drashtiv03** [comment]
@varghesejose2020  I would love to work on this issue.

**Comment by varghesejose2020** [comment]
Issue already sorted. @drashtiv03
