### ISSUE TITLE
Attempting to create a team with the URL of an existing team shows the wrong error message

### ISSUE THREAD

**Issue by hmhealey** [mattermost/mattermost#26841]
Repro steps:

1. Click on the header of the channel list in the sidebar of the web app
2. Click on Create Team
3. On the Team Name scree, enter anything and click Next
4. On the Team URL screen, change the URL to be the URL of an existing team
5. Click Finish

Observed: The error message reads “Must call update for existing team.”
![image-20240416-175228](https://github.com/mattermost/mattermost/assets/3277310/f395c0bb-57c6-4be8-a899-4f20a7759e7f)
Expected: The error message reads “A team with that URL already exists.”

---

To do this, we should have the web app intercept the existing error message by its ID and show the more friendly error message instead.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-57877

**Comment by MeHow25** [comment]
Can you assign me?

**Comment by MeHow25** [comment]
@hmhealey I was trying to reproduce this bug accordingly to your description and for me it shows a different error message. I added a screenshot of the message at the bottom. Honestly, for me it looks quite friendly. What do you think?

Can you also tell me what version of Mattermost are you using here? I'm using Mattermost Team Edition with the latest master branch.

![image](https://github.com/mattermost/mattermost/assets/61119231/83305130-9f51-4830-8405-f24ae218917c)

**Comment by hmhealey** [comment]
I also saw the "This URL is taken" error message when I just tested on my admin account, but I see the incorrect error message on my other account, so there's something else going on here. It seems like either there's something here caused by incorrect permissions or perhaps it has to do with being on that other team.

Hopefully that gives you something to work off of, but let me know if neither of those end up being the issue, and I can take another look.

Also, if it still matters, I'm on the latest master branch as well

**Comment by MeHow25** [comment]
@hmhealey thanks for a hint about permissions. I found a way to recreate this behavior.

Here are the steps to reproduce the bug:
1. Create User No. 1.
2. Create a team with the URL “/lorem” using that user, but do not invite anyone.
3. Create User No. 2.
4. As User No. 2, attempt to create a new team with the same URL “/lorem.”
5. An error message stating “Must call update for existing team” will be displayed.

Now I'm trying to fix the issue.

**Comment by MeHow25** [comment]
@hmhealey I believe I've identified the code responsible for this issue. The `team.go` file contains a `teamExists` function that checks if the name of a new team is available or already taken, but I'm puzzled by its logic. Not only does it verify the team name, but it also checks if the current user has access to that team if it exists. If the user lacks access, the function returns false, implying the team doesn't exist. Shouldn't it return true instead?

I'm curious about this because the `teamExists` function is invoked during team creation and it's causing this issue.

Here is the link to this function:
https://github.com/mattermost/mattermost/blob/8348acac49198422d4762abf6d8dab29ffa21a4a/server/channels/api4/team.go#L1237

**Comment by hmhealey** [comment]
Looking back further, that permission check goes back to https://github.com/mattermost/mattermost/pull/12130 which is to fix a minor security issue where guest users could figure out if a team exists using that endpoint when they shouldn't have been able to. Unfortunately, that makes it so that the `teamExists` API is kind of useless for what it's supposed to do.

Since I don't think we can change the API to make that more helpful, I guess the next best thing would be to detect the "must call update" error in the frontend and show a nicer error message to the end user. There's an error ID that you could use for that.

How does that sound?

---

Also, CC @jespino in case he has any ideas for how to make that API more useful again for non-admin, non-guest users

**Comment by MeHow25** [comment]
@hmhealey Sure. The error on the frontend side comes from this line of code where we are calling the endpoint to create a team: 
https://github.com/mattermost/mattermost/blob/978f335925b91a3e92c87766caf4f4a638d0760b/webapp/channels/src/components/create_team/components/team_url/team_url.tsx#L169

I'm just not sure what should be the error message here. Wouldn't `A team with that URL already exists` also cause the same security issue? Maybe it should be something more general like `You cannot use this URL`?

**Comment by hmhealey** [comment]
That's a good point. I guess the difference here is that the `createTeam` endpoint requires stricter permissions than `teamExists`, and guests shouldn't have that permission so they'd get a "permission denied" before they could find if a team with that URL exists.

Because of that, I think it's fine to still use "A team with this URL already exists" in this case
