### ISSUE TITLE
Closed direct messsages are reopened

### ISSUE THREAD

**Issue by rokka** [mattermost/mattermost#26845]
#### Summary
Has anyone else noticed that conversations that have already been closed (for example with the /leave command) are reopened /shown again in the section “Direct Messages”. This also happens on conversations  with user who have already been archived?

We get this behaviour with the desktop client on windows as well as with the web client.

#### Steps to reproduce
Described in the summary

Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: postgres

#### Expected behavior
Direct message, that are read and closed, should stay closed as long a no new message is coming in.

#### Observed behavior (that appears unintentional) 
Direct message, that are read and closed, are shown again in the desktop and webclient.

**Comment by amyblais** [comment]
@rokka What OS and version are you on? Do you see any errors related to this in the Mattermost server logs or in the developer console?

**Comment by rokka** [comment]
Hi Amy,

we have updated Mattermost Server to the latest version which seems to solve the problem :-)
