### ISSUE TITLE
update image with updated GitLab logo 

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/mattermost#26897]
![Screenshot from 2024-04-26 20-03-55](https://github.com/mattermost/mattermost/assets/71702982/f7e4edeb-24b8-4d70-9f68-2ac5d3d33953)
https://mattermost.com/solutions/mattermost-gitlab/

**Comment by amyblais** [comment]
Opened a Marketing ticket,

**Comment by amyblais** [comment]
This is fixed,
