### ISSUE TITLE
Update broken Links in GitLab Integration page

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/mattermost#26898]
![Screenshot from 2024-04-26 20-09-08](https://github.com/mattermost/mattermost/assets/71702982/27091ec4-ef07-437c-9fd2-424365db4af5)
https://mattermost.com/solutions/mattermost-gitlab/

**Comment by amyblais** [comment]
Opened a Marketing ticket,

**Comment by emdecr** [comment]
Thanks for all the recent flags @varghesejose2020 - took care of all the link ones (including this one) and will forward the gitlab image flag to the creative team.
