### ISSUE TITLE
Lack of MariaDB support

### ISSUE THREAD

**Issue by svaroqui** [mattermost/mattermost#26946]
I get the feeling having no documentation and pointers to MariaDB MDEV for what is incompatible with  the support of MariaDB backend is not open source friendly what is now documented is the drop of performance when upgrading to MySQL. Please refer to MDB Foundation blog recent posts for performance over Major upgrade.

**Comment by agnivade** [comment]
Unfortunately, we don't have the engineering bandwidth to support MariaDB. We used to have unofficial support in the past, but that led to a lot of problems. Therefore we decided to officially stop supporting it. We are also dropping support for MySQL in the future. Please consider using Postgres only.
