### ISSUE TITLE
Remove one of `@all` and `@channel`

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost#26945]
Until 9.7.3, there is still `@all` and `@channel` in special mention feature. As such two things are same, I suggest to remove one of it.

This proposal has been there since 2018: [https://forum.mattermost.com/t/at-all-vs-at-channel/6298](https://forum.mattermost.com/t/at-all-vs-at-channel/6298).

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @eli-yip,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
