### ISSUE TITLE
Emoji hover panel obscures user status on RHS

### ISSUE THREAD

**Issue by chenilim** [mattermost/mattermost#26981]
#### Summary
If a user has a custom status, I can't hover to see it on the thread RHS because the Emoji panel pops over it.

#### Steps to reproduce
1. Try to hover over the user custom status on the RHS
2. Emoji bar blocks you

#### Expected behavior
0/5, but perhaps also show the custom status on the emoji bar? 

#### Observed behavior (that appears unintentional) 
Video:

https://github.com/mattermost/mattermost/assets/46905241/a03b4588-6a3a-496e-920d-c2a2ce68f97a

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-58188.
