### ISSUE TITLE
Uploaded plugins fail to load on OpenBSD

### ISSUE THREAD

**Issue by athompso** [mattermost/mattermost#26989]
#### Summary
Uploaded plugins fail to load on OpenBSD

#### Steps to reproduce
Install mattermost 8.1.2 from OpenBSD pre-built port (`pkg_add mattermost`), upload community plugins.

#### Expected behavior
Community plugins should load.

#### Observed behavior (that appears unintentional) 
```
info  [2024-05-09 21:05:37.804 -05:00] Starting up plugins                           caller="app/plugin.go:213"
info  [2024-05-09 21:05:37.804 -05:00] Syncing plugins from the file store           caller="app/plugin.go:293"
warn  [2024-05-09 21:05:37.805 -05:00] Skipping sync for unmanaged plugin            caller="app/plugin.go:313" plugin_id=zoom
info  [2024-05-09 21:05:37.828 -05:00] Syncing plugin from file store                caller="app/plugin.go:353" bundle=plugins/com.mattermost.calls.tar.gz
info  [2024-05-09 21:05:37.828 -05:00] Syncing plugin from file store                caller="app/plugin.go:353" bundle=plugins/zoom.tar.gz
info  [2024-05-09 21:05:37.828 -05:00] Syncing plugin from file store                caller="app/plugin.go:353" bundle=plugins/jitsi.tar.gz
error [2024-05-09 21:05:39.410 -05:00] Failed to sync plugin from file store         caller="app/plugin.go:355" bundle=plugins/jitsi.tar.gz error="installExtractedPlugin: Unable to restart plugin on upgrade., unable to start plugin: jitsi: unable to generate plugin checksum: read /var/mattermost/plugins/jitsi: is a directory"
error [2024-05-09 21:05:39.569 -05:00] Failed to sync plugin from file store         caller="app/plugin.go:355" bundle=plugins/zoom.tar.gz error="installExtractedPlugin: Unable to restart plugin on upgrade., unable to start plugin: zoom: unable to generate plugin checksum: read /var/mattermost/plugins/zoom: is a directory"
```

#### Possible fixes
The proximate problem is obviously at https://github.com/mattermost/mattermost/blob/f0121d4f23e065a05e63fd452486570271c6a28f/server/public/plugin/supervisor.go#L239
but I suspect there might be an earlier problem somewhere closer to
https://github.com/mattermost/mattermost/blob/f0121d4f23e065a05e63fd452486570271c6a28f/server/public/model/manifest.go#L240
I don't currently have the ability to either rebuild from source or debug the binary... working on that, and I'll report back if/when I have a better idea of the root cause

I've opened the ticket in mattermost/mattermost instead of mattermost-community/* because non-manually-uploaded plugins work fine, and multiple community-maintained plugins are broken.  Given the niche OS, I'm expecting it'll be something OpenBSD-specific.

**Comment by amyblais** [comment]
@athompso Given that v8.1 is going out of support on May 15th, would you be open to upgrading to v9.5 or a newer version to see if the issue still reproduces?

**Comment by amyblais** [comment]
Closing for now as we haven't heard back. This issue can be re-opened if the issue persists on a supported version,
