### ISSUE TITLE
Unclear message text when message property is too long

### ISSUE THREAD

**Issue by pmokeev** [mattermost/mattermost#27059]
#### Summary
When I'm trying to post a message which contains [mattermost.PostMessageMaxRunesV2](https://github.com/mattermost/mattermost/blob/cef7826fa865ee18d5082c4f8209bd7e8d54d7c4/server/public/model/post.go#L60) + 1 of symbols, I receive `"invalid message"` error, which is definitely unclear what is exactly invalid in my message. I see that the code [contains a check](https://github.com/mattermost/mattermost/blob/b9f7d38cb1609733eb1e5c16a2be85b1c34a5543/server/public/model/post.go#L413) for the length of the message which is being sent, but then it maps to `"Invalid message"` message using i18 json files, the text of which seems too general. Moreover, searching for more codebase I found that there is another [message error](https://github.com/mattermost/mattermost/blob/b9f7d38cb1609733eb1e5c16a2be85b1c34a5543/server/channels/app/imports/import_validators.go#L431), which specifies information about message length. 

So my proposal is to rename `model.post.is_valid.msg.app_error` error to something like `model.post.is_valid.message_length.app_error` and the mapping message to `Post Message property is longer than the maximum permitted length.`

#### Steps to reproduce
```golang
import (
	"context"
	"strings"

	mattermost "github.com/mattermost/mattermost/server/public/model"
)

func main() {
	mattermostClient := mattermost.NewAPIv4Client("http://localhost:8065")
	mattermostClient.SetToken("SOME_TOKEN")

	msg := mattermost.Post{
		ChannelId: "SOME_CHANNEL_ID",
		Message:   strings.Repeat("!", mattermost.PostMessageMaxRunesV2+1),
	}

	_, _, err := mattermostClient.CreatePost(context.TODO(), &msg)
	if err != nil {
		panic(err)
	}
}
```

#### Expected behavior
```shell
panic: Post Message property is longer than the maximum permitted length.
```

#### Observed behavior (that appears unintentional) 
```shell
panic: Invalid message.
```

#### Possible fixes
- Rename `model.post.is_valid.msg.app_error` to `model.post.is_valid.message_length.app_error`
- Rename `Invalid message` mapping error text to `Post Message property is longer than the maximum permitted length.`

WDYT? I can create a PR by my own to solve this issue.

**Comment by pmokeev** [comment]
It seems that `model.draft.is_valid.msg.app_error` has similar behaviour - [Link](https://github.com/search?q=repo%3Amattermost%2Fmattermost%20%22model.draft.is_valid.msg.app_error%22&type=code)

**Comment by amyblais** [comment]
Feel free to open a PR for this!

**Comment by pmokeev** [comment]
@amyblais hi! After a little extra time, I finally solved this issue — [PR](https://github.com/mattermost/mattermost/pull/29252) :)
