### ISSUE TITLE
User status (active/inactive) mismatch between users and teams/members API responses

### ISSUE THREAD

**Issue by petriaarnio** [mattermost/mattermost#27063]
#### Summary
User status (active/inactive) mismatch between users and teams/members API responses

Version: team edition 9.7.1

#### Steps to reproduce
Deactivate a user who is a member of a team.

#### Expected behavior
Either:
1) Both users and teams/members API response has the user's status inactive -> delete_at is nonzero
2) teams/members API does not have deactivated user in the response

#### Observed behavior (that appears unintentional) 
Deactivated user status still looks active (delete_at = 0) in teams/members API response, but users API has correctly a number in delete_at property.

Example responses:

users API:
{
	"id": "1a8r8zkq7prruyxis7imwbed8e",
	"create_at": 1640158315104,
	"update_at": 1715940346409,
	"delete_at": 1715937655584,
	"username": "pzsdaapcgeqtzmsutuuqao",
	"auth_data": "",
	"auth_service": "",
	"email": "9cb715d7-14bd-4d32-8b1e-21ca24b2a362@deleteduser.invalid",
	"nickname": "",
	"first_name": "Deleted",
	"last_name": "User",
	"position": "",
	"roles": "system_user",
	"locale": "",
	"timezone": {},
	"disable_welcome_email": false
}

teams/members:
	{
		"team_id": "oxe7f7wzyfy97jrqqoa5qoi7gy",
		"user_id": "1a8r8zkq7prruyxis7imwbed8e",
		"roles": "team_user",
		"delete_at": 0,
		"scheme_guest": false,
		"scheme_user": true,
		"scheme_admin": false,
		"explicit_roles": ""
	},

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58348.
