### ISSUE TITLE
Impossible to use multiple domains

### ISSUE THREAD

**Issue by MrFrogoz** [mattermost/mattermost#27169]
#### Summary
Impossible to use multiple domains
```
{
  "ServiceSettings": {
    "SiteURL": "",
......
}
```

#### Steps to reproduce
https://docs.mattermost.com/configure/web-server-configuration-settings.html

#### Expected behavior
Can you make it possible to configure multiple domains?

#### Observed behavior (that appears unintentional) 
Empty

#### Possible fixes
Transform SiteURL from string to array

**Comment by amyblais** [comment]
Hi @MrFrogoz, is this troubleshooting thread helpful https://forum.mattermost.com/t/multiple-instances-on-one-server/7968?

**Comment by amyblais** [comment]
Also, what Mattermost server version are you on, and do you see any errors in the Mattermost logs?

**Comment by MrFrogoz** [comment]
I don't have to create more instances, the server is the same, I just wish there was the possibility of configuring more domains. 
I'm using the latest version of mattermost.
I don't think logs are needed, I just made this change request so that a single mattermost instance hosts multiple domains

**Comment by amyblais** [comment]
Thanks, appreciate your feedback,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
