### ISSUE TITLE
Post messages look like they've been crushed

### ISSUE THREAD

**Issue by picnoir** [mattermost/mattermost#27181]
#### Summary
The font used for displaying messages in a regular chat (and threads) look crushed on my system.

#### Steps to reproduce

Open a chat window on the webui with your system font set to Open Sans.

Issue experienced on firefox 125.0.2 on a Linux system.

#### Expected behavior

The font size should be set to a round number to prevent from such fractal scaling issues. Either 13px or 14px. The text input is already set to 14px, I guess it makes sense to choose this value for.

#### Observed behavior (that appears unintentional) 

![09:52:10](https://github.com/mattermost/mattermost/assets/1219785/f5d93f59-8543-4d06-ab11-138f268402c7)

As you can see in the above screenshot, the first message and the 3rd look "crushed". The font aspect is distorted and overall harder to read. 

The second message has been manually modified from a size of 13.5 -> 14. With this round number, the font shape is kept untouched, it is still perfectly readable.

This fractal 13.5 value is set here: https://github.com/mattermost/mattermost/blob/beb8d5e8e07a1eb7f0d807875b4f4e644fc7254a/webapp/channels/src/sass/components/_post.scss#L1052

The message text input is currently set to 14 and looks fine.

#### Possible fixes
Set the font size to 14px there:  https://github.com/mattermost/mattermost/blob/beb8d5e8e07a1eb7f0d807875b4f4e644fc7254a/webapp/channels/src/sass/components/_post.scss#L1052

**Comment by amyblais** [comment]
Hi @picnoir, what Mattermost server version are you on?

**Comment by picnoir** [comment]
Hey! 

9.8.0

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58496.

**Comment by 7H3XXX** [comment]
Hello, @amyblais If this is still unsolved, I can make the adjustment.

**Comment by 7H3XXX** [comment]
This should fix it as the solution of @picnoir suggests.
