### ISSUE TITLE
Add support markdown for Attachment.Footer

### ISSUE THREAD

**Issue by kolsys** [mattermost/mattermost#27207]
Currently [Attachment.footer](https://developers.mattermost.com/integrate/reference/message-attachments/#footer) does not support markdown processing. It's not allowed to add URL to footer, like Slack.

Would be cool to fix this. For example, Grafana alert uses this.

Slack
![image](https://github.com/mattermost/mattermost/assets/6312063/1db3d27d-9be5-45e7-9d45-1233e83a7296)

Same post in Mattermost
![image](https://github.com/mattermost/mattermost/assets/6312063/832e8fb0-5f21-4717-9e91-cda02b9d01c8)

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @kolsys,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
