### ISSUE TITLE
Channel expand fail in Group channels

### ISSUE THREAD

**Issue by sblaisot** [mattermost/mattermost#27218]
#### Summary

Having `channel: summary` in the `expand` section of an app (using app framework) make it unusable in the context of a group channel with the error message

```
failed to expand context: failed post-expand consistency check: expanded channel's team ID  is different from user agent context 1ntjrqrqdjy8mffhoc44g1e9zr
```

#### Steps to reproduce

Having an app (using mattermost app framework) with the following binding:

```
            {
                "location": "/post_menu",
                "bindings": [
                    {
                        "location": "make-a-thing-menu",
                        "icon": "thing.png",
                        "label": "Make a thing",
                        "description": "Use this post to make a thing.",
                        "submit": {
                            "path": "/make-a-thing-form",
                            "expand": {
                                "team": "summary",
                                "channel": "summary",
                                "post": "summary",
                                "acting_user": "summary",
                                "acting_user_access_token": "all",
                                "locale": "all",
                            },
                        },
                    },
                ],
            },
```

add a button on the "app" buttons for each post to "make a thing" with the post.
This works great for posts in regular (public) channels, private channels or 2-users direct message channels.

However, if the post is in a group channel, the `channel: summary` expand fails with the following error message printed in the interface to the user and also in the server logs:

```
failed to expand context: failed post-expand consistency check: expanded channel's team ID  is different from user agent context 1ntjrqrqdjy8mffhoc44g1e9zr
```

Please note the double spaces between "channel's team ID` and `is different` meaning that mattermost server didn't manage to get team ID for this type of channel.

Subsequently, the app call is not fired and the app malfunction.

This comes from [this piece of code](https://github.com/mattermost/mattermost-plugin-apps/blob/master/server/proxy/expand.go#L491-L494)

#### Expected behavior

App call is fired, no error message

#### Observed behavior (that appears unintentional) 

The `channel: summary` expand fails with the an error message visible on the interface. The app call is not fired.

#### Possible fixes

It seems that Group Channel don't have a teamID. Probably you should add `e.ExpandedContext.Channel.Type != ChannelTypeGroup` on [this line](https://github.com/mattermost/mattermost-plugin-apps/blob/master/server/proxy/expand.go#L491)

**Comment by amyblais** [comment]
Hi @sblaisot, what Mattermost server version are you on? What OS and version are you on?

**Comment by sblaisot** [comment]
@amyblais I reproduced with mattermost 9.7.1 on Ubuntu 22.04 and also with mattermost/mattermost-enterprise-edition:9.8.1 docker image

I pointed to code in master branch so latest version should be affected

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58505.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
