### ISSUE TITLE
Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING, caused by sql.LevelSerializable

### ISSUE THREAD

**Issue by LukasMojzis** [mattermost/mattermost#27239]
#### Summary
Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING, caused by sql.LevelSerializable

#### Steps to reproduce
Run Mattermost on Percona XtraDB Cluster

#### Expected behavior
Mattermost should attempt to use SERIALIZABLE but if it fails, it should fall back on lesser isolation.

#### Observed behavior (that appears unintentional) 
The server doesn't start.

#### Possible fixes
Try to use sql.LevelSerializable, then resort to using lesser locks.
Also provide isolation level as config via MM_DB_ISOLATIONLEVEL or such.

**Comment by amyblais** [comment]
Hi @LukasMojzis, what Mattermost server version are you on? Do you see errors in the Mattermost server logs?
