### ISSUE TITLE
Concurrent map iteration and map write

### ISSUE THREAD

**Issue by PalachN** [mattermost/mattermost#27252]
Service down
The problem https://github.com/mattermost/mattermost/issues/26810 recurred.

[config.json](https://github.com/user-attachments/files/15533316/config.json)
[mattermost.service.txt](https://github.com/user-attachments/files/15533324/mattermost.service.txt)

Jun 03 16:01:00 *mask* mattermost[1381131]: {"timestamp":"2024-06-03 16:01:00.800 +05:00","level":"info","msg":"Notification sent","caller":"app/notification_push.go:143","logSource":"notifications","ackId":"5ubrx5rhhfg8fpu9bxzqw5n1ka","type":"clear","userId":"8k7ie9pinprt8mck11nnb4y5tc","postId":"","channelId":"7bxzrbktptdb7ka4de8hzqqwkr","deviceId":"fh-O9cBTSPS_EJFRxPf8gR:APA91bFDe0k7JMgWOfimv18EQYBOYxtosNHBbrHF6kz2kL5GFSFJD2ASAKUuark-GOwAKNHZBtBqELircfHYlf2v9M7Rp6OoEZQU7w2BFvkmLMW_F-kxZTKTVC9yBBb4-zHxQcnNDQ4h","status":"Successful"}
Jun 03 16:01:00 *mask* mattermost[1381131]: {"timestamp":"2024-06-03 16:01:00.826 +05:00","level":"info","msg":"Notification sent","caller":"app/notification_push.go:143","logSource":"notifications","ackId":"wf17jbm3abrd8g8z34zcuihfby","type":"clear","userId":"eq9imaxib7rkpn1agprj6rgaby","postId":"","channelId":"bkst3r5mspywixi37stfwtj5wh","deviceId":"47cfb05710e851bdb8f406792c949564ae60843b9aabd720766c661c80226796","status":"Successful"}
Jun 03 16:01:01 *mask* mattermost[1381131]: {"timestamp":"2024-06-03 16:01:01.786 +05:00","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:443","logSource":"notifications","ackId":"93tsith95pg5bd4bez9556y18a","type":"clear","userId":"aaxnzdbpatddzjg9s54cp5droo","postId":"","status":"Prepared to send"}
Jun 03 16:01:01 *mask* mattermost[1381131]: fatal error: concurrent map iteration and map write
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381144 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381152 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381163 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381172 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381182 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381190 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Killing process 1381209 (plugin-linux-am) with signal SIGKILL.
Jun 03 16:01:01 *mask* systemd[1]: mattermost.service: Failed with result 'exit-code'.
Jun 03 16:05:15 *mask* systemd[1]: Starting Mattermost...

Mattermost Version: 9.5.1
Database Schema Version: 119
Build Number: 7877635852
Database: postgres

**Comment by amyblais** [comment]
Re-opened https://github.com/mattermost/mattermost/issues/26810 so we can continue the discussion there.
