### ISSUE TITLE
Incorrect or missing config in request body

### ISSUE THREAD

**Issue by Sadisms** [mattermost/mattermost#27250]
#### Summary
When saving settings the error ‘Incorrect or missing config in request body’ appears.

#### Steps to reproduce
Save settings. MM version 9.7.3. Tried both Desktop client and web version.

#### Expected behavior
When saving settings in system console, error ‘Incorrect or missing config in request body’ pops up.

#### Observed behavior (that appears unintentional) 
```json
{
    "id": "api.context.invalid_body_param.app_error",
    "message": "Incorrect or missing config in request body.",
    "detailed_error": "",
    "request_id": "7ffyxmzybpy1uj58wc6hniwx6y",
    "status_code": 400
}
```
![image](https://github.com/mattermost/mattermost/assets/63108004/a3b4b957-fc7d-41b7-9d04-942b5d1024f3)

#### Possible fixes
https://github.com/mattermost/mattermost/blob/58b7032a8ce617be1d313e42fd9a002cceaa90a5/server/channels/api4/config.go#L279

**Comment by amyblais** [comment]
Hi @Sadisms, would you be able to share more details on what settings you're attempting to change?

**Comment by Sadisms** [comment]
When changing any settings it comes out, but for the first time I noticed it when changing plugin settings.

**Comment by Sadisms** [comment]
In logs I found this entry

```json
{"timestamp":"2024-06-04 04:59:26.266 Z","level":"debug","msg":"Invalid or missing config in request body.","caller":"web/context.go:111","path":"/api/v4/config/patch","request_id":"1gbz95o7n7nrpfmjyxsyb6fkrw","ip_addr":"127.0.0.1","user_id":"phzna4nq6j8tud9qw6i6e6ky9h","method":"PUT","err_where":"Context","http_code":400,"error":"Context: Invalid or missing config in request body., http: request body too large"}
```

It was ‘http: request body too large’ that was confusing.

**Comment by Sadisms** [comment]
Problem was fixed, increasing the ‘MaximumPayloadSizeBytes’ value helped.
