### ISSUE TITLE
View Member search matches entire string for the Position field instead of each word.

### ISSUE THREAD

**Issue by baermb** [mattermost/mattermost#27283]
1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
I could not find a similar issue.

2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
It is not a security issue.

3. 
#### Summary
In a channel's 'View Member' search, when it searches in the position field, it does a match from beginning of the string and not the beginning of each word. E.g. For 'Systems Engineer at Some Company', 'Systems' or 'Systems Engineer' matches, but 'Engineer' or 'Company' would not. I'd expect it to do word matches.

#### Steps to reproduce
Mattermost Server v9.8.1
Mattermost Ubuntu 22 Desktop v5.7.0 and Browser app with Firefox 115.12.0esr
Search in a channel's 'View Members' search box. When it searches the Position field, it does an  match from beginning of the string search. E.g. For 'Systems Engineer at Some Company', 'Systems' or 'Systems Engineer' matches, but 'Engineer' or 'Company' would not. I'd expect it to do word matches.

#### Expected behavior
I'd expect it to do matches on words as it does withe the other fields. Re the example above, 'Company' and 'Engineer' should match.

#### Observed behavior (that appears unintentional) 
Search only matches from the beginning of the Position field's string.

#### Possible fixes
Not sure where the in code the code this is , but change the type of search for the position field so that word matches work.

Edit: Added that I was testing on a linux desktop and a browser version of the app.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58562.

**Comment by Ari1009** [comment]
Having trouble searching for messages based on a user's positon in any channel. Search only lets me look by username. How do I search with respect to the position?

**Comment by baermb** [comment]
Sorry, I may not have been clear enough. I was talking about the 'Position' field within a user's profile, not the position of a user's comment in a channel. There's a different when searching via 'Direct Message +" or searching via a channel's 'View Member'. 'Direct Message +' will do a word search for a user in the different profile fields of all users. But 'View Members' does a word search in most of the user profile fields (I didn't test nickname), but for some reason does a full string match for the Position field. e.g.:
Position: Software Engineer at Example.com
A search in the 'View Members' search box would match for 'Software' or 'Software Engineer' but not for 'Engineer' or 'Example.com. Those would match if you search in the 'Direct Message +' search box.
It's small inconsistency, but for the site I'm seeing this on, looking for a company name is not uncommon. And since the search methods don't behave the same way, my assumption is it is not working this way on purpose.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this,
