### ISSUE TITLE
Wasabi S3 Backend File Upload Problem

### ISSUE THREAD

**Issue by myaspm** [mattermost/mattermost#27293]
Hi everyone,

Recently some regions on Wasabi started to give an error when uploading files on Mattermost. The error is this:

Value for x-amz-checksum-crc32c header is invalid.

I contacted the Wasabi support back in May and they said that they were rolling an update on some regions and the issue was with a library version in Mattermost. Their response is below:

![image](https://github.com/mattermost/mattermost/assets/8374770/d1e454c1-c5e1-41c4-9af8-53dd3f384505)

I've since then tried to compile the Mattermost binary with the correct minio-go version but couldn't get it to work properly, so i changed regions and so far it was fine but today i think they completed their updates and now none of the regions will accept uploads from Mattermost. The funny thing is, profile picture uploads are working but i dont know if they are uploaded to S3 or they are in a local data folder in the server.

You can verify this issue by simply connection any Wasabi bucket as S3 backend storage to a Mattermost installation and trying to upload a file.

Thanks in advance and i will be happy to provide more info if needed.

**Comment by amyblais** [comment]
Hi @myaspm, what Mattermost server version are you on? Do you see errors in the Mattermost server logs?

**Comment by myaspm** [comment]
Hi, i'm on 9.8.1 now but the problem is also on 9.2 and 9.0. I even downgraded one instance to 8.X but can't remember now what the specific version vas.

The full error message i'm getting is below:

```
{"timestamp":"2024-06-06 14:34:13.180 Z","level":"error","msg":"Unable to write the file.","caller":"web/context.go:115","path":"/api/v4/files","request_id":"p4gdbqhbntdyibnzdiw5czt5jr","ip_addr":"X.X.X.X","user_id":"1grwc17gdt8b8fimz7c47su4fy","method":"POST","err_where":"WriteFile","http_code":500,"error":"WriteFile: Unable to write the file., unable write the data in the file 20240606/teams/noteam/channels/oyee43whatgj7m4qmdoni7yyhh/users/1grwc17gdt8b8fimz7c47su4fy/xgr9jct9ipbqtem3icwsxtwo9y/XXX: Value for x-amz-checksum-crc32c header is invalid."}
```

**Comment by RiffleHatch** [comment]
Hi,
I am also using Wasabi and facing the same issue.
The problem started on version 9.8.0 and continues in 9.8.1.
It began on June 5th.
The OS is Ubuntu 22.04.4.
Mattermost is the Enterprise Edition.

**Comment by hibobmaster** [comment]
Same here.

error [2024-06-11 12:24:22.993 +08:00] Unable to write the file.                     caller="web/context.go:115" path=/api/v4/files request_id=6o71wtgtf3g6pxrshfdgfp7pco ip_addr=(redacted) user_id=5ojjqyzc8p8u8n1wow53oh8eia method=POST err_where=WriteFile http_code=500 error="WriteFile: Unable to write the file., unable write the data in the file 20240611/teams/noteam/channels/toez5ibyopri5d7twtc5sm5axh/users/5ojjqyzc8p8u8n1wow53oh8eia/qmeczk8fp3b1mkewj46mkgn6xc/Snipaste_2024-06-11_00-16-08.jpg: Value for x-amz-checksum-crc32c header is invalid."
debug [2024-06-11 12:24:22.993 +08:00] Received HTTP request                         caller="web/handlers.go:187" method=POST url=/api/v4/files request_id=6o71wtgtf3g6pxrshfdgfp7pco user_id=5ojjqyzc8p8u8n1wow53oh8eia status_code=500

**Comment by agnivade** [comment]
Hey all, we do not support Wasabi or any other custom backends other than Amazon S3 or Minio. I'd suggest everyone on this thread to switch to Amazon S3 for an officially supported and tested backend.

**Comment by hibobmaster** [comment]
@myaspm @RiffleHatch Tested with minio-go v7.0.71 still has the same problem.
![image](https://github.com/mattermost/mattermost/assets/32976627/dc5ee639-e1b7-4f77-958c-a3947d6b4d10)

v7.0.59 the same problem:
![image](https://github.com/mattermost/mattermost/assets/32976627/506629e5-8a74-41f6-99bd-e32c591213f3)

Do you guy have any idea?

**Comment by alekseyp** [comment]
@agnivade worst response ever. Especially for an enterprise client.

Well... I suggest switch to another chat solution.

**Comment by hibobmaster** [comment]
@alekseyp @myaspm @RiffleHatch @agnivade @amyblais 

After add an option for `options.SendContentMd5 = true` in `s3PutOptions()`, it works now. Tested with v7.0.59 and v7.0.67, both works on well.
reference: https://github.com/mattermost/mattermost/issues/22221
![image](https://github.com/mattermost/mattermost/assets/32976627/efbc74cc-dc55-40aa-85ef-a6b170ef1391)
v7.0.59
![image](https://github.com/mattermost/mattermost/assets/32976627/86081d4a-630f-4c7a-80bb-7442bae596da)
v7.0.67
![image](https://github.com/mattermost/mattermost/assets/32976627/6e0babff-8585-469e-9ad8-f9e05da1d352)

**Comment by hibobmaster** [comment]
@alekseyp @myaspm @RiffleHatch
I fork the mattermost repository and add a build step, you can use it as reference to modify mattermost as you need.
https://github.com/hibobmaster/mattermost/commit/96feb745c6b23a80284c824eeb596ee8aad0f849
https://github.com/hibobmaster/mattermost/actions/runs/9610233989/job/26506294919

**Comment by Kurisama91** [comment]
I too would love a fix for this. As an indie game dev studio, having us stick to Amazon is quite expensive which is why many would use something as Wasabi. It's like a 10x price difference. I understand the complexities of supporting multiple, but if the community finds a fix for it, it would be nice to implement it. It would be a very kind thing for the Mattermost team to do. Regardless, we absolutely love your product and live on it here at Nami Tentou. Keep up the amazing work. :)

**Comment by agnivade** [comment]
Thank you @Kurisama91. Wondering if you have taken a look at [Minio](https://github.com/minio/minio)? We also support that along with AWS S3.

**Comment by Kurisama91** [comment]
> Thank you @Kurisama91. Wondering if you have taken a look at [Minio](https://github.com/minio/minio)? We also support that along with AWS S3.

Took a look, doesn't make sense for us to migrate when there was a simple fix provided by a user and it'll cost us more. 

I recommend anyone reading this thread to do what @hibobmaster did, until Mattermost incorporates something similar to support Wasabi.

**Comment by alekseyp** [comment]
For anyone searching: looks like it's working again with wasabi s3
