### ISSUE TITLE
Can't post messages containing SQL "select *" in text

### ISSUE THREAD

**Issue by cwatzl** [mattermost/mattermost#27320]
#### Summary

Messages containing the sequence "select *" are not delivered. The user will only see the "Retry" and "Cancel" buttons, but no error message. 

It does not matter whether it is unformatted text, enclosed in single backticks (monospace) or triple backtick code blocks.

We are using Mattermost within an IT company and regularly send code snippets around within our organization; sending text containing SQL snippets seems an entirely legitimate use case.

#### Steps to reproduce

- Enter text containing "select * from foo" into a chat 
- Observe that the message it isn't delivered; instead, the "Retry" and "Cancel" buttons are shown
- Desktop client version: 5.8.0
- Server version 9.0.0 and 9.9.0

How can we reproduce the issue (what version are you using?)

#### Expected behavior

Mattermost should sending of SQL snippets containing "select *"; or if this is not possible due for security reasons, provide a useful error message.

#### Observed behavior (that appears unintentional) 

![image](https://github.com/mattermost/mattermost/assets/49339714/cb26ad47-1e17-45e4-a947-9cdfe317348d)

**Comment by amyblais** [comment]
Hi @cwatzl, I wasn't able to reproduce it.

1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see errors in Mattermost logs?
4. Are you able to reproduce this at https://community.mattermost.com?

**Comment by cwatzl** [comment]
> Hi @cwatzl, I wasn't able to reproduce it.
> 
>     1. What Mattermost server version are you on?
> 
>     2. What OS and version are you on?
> 
>     3. Do you see errors in Mattermost logs?
> 
>     4. Are you able to reproduce this at https://community.mattermost.com?

@amyblais Thanks for the incredibly fast response :)

Desktop client version is 5.8.0, running on the latest version of Windows 11. Not sure about the server, Seems to be unrelated to the desktop client though. I could also reproduce it with the web client.

 I'll try to get server version & OS info from our admin, along with logs. Might take some time though. 

Can't reproduce it on community.mattermost.com

**Comment by amyblais** [comment]
Thank you, you can find the server version from the Main Menu > About Mattermost. 

<img width="286" alt="Screenshot at Jun 11 12-02-34" src="https://github.com/mattermost/mattermost/assets/29708087/fac5b50e-98c9-4cc0-933f-321c086a3013">

**Comment by cwatzl** [comment]
Ah found it.

It's version 9.0.0, 
Build hash 987e843629fe3f11861fda23ceb66884f5973ef1
EE Build Hash d5fcba6ba62b19cd029e6c913b1b65d81d2c89f3,
Build Date: Fri Sep 8 19:04:35 UTC 2023

Still trying to get a hold of server logs.

![image](https://github.com/mattermost/mattermost/assets/49339714/58a55987-ed90-4dfa-bab1-3fccc3ba83bc)

**Comment by cwatzl** [comment]
Our admin checked the Mattermost server logs but could not find any error messages.

There are error messages that correspond to the failing messages in the NGINX reverse proxy we have in front of Mattermost server (used e.g. for TLS offloading). I redacted IPs / host names for privacy reasons.

```
2024/06/12 12:19:54 [error] 1601539#1601539: *341511 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: <<my-client-ip>>>, server:  http://<<my-mattermost-host-name>>  , request: "POST /api/v4/posts HTTP/2.0", upstream: "http://<<my-mattermost-server-ip>>>:8065/api/v4/posts", host: " http://<<my-mattermost-host-name>>  "
2024/06/12 12:19:59 [error] 1601539#1601539: *341511 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: <<my-client-ip>>>, server:  http://<<my-mattermost-host-name>>  , request: "POST /api/v4/posts HTTP/2.0", upstream: "http://<<my-mattermost-server-ip>>>:8065/api/v4/posts", host: " http://<<my-mattermost-host-name>>  "
2024/06/12 12:20:14 [error] 1601539#1601539: *341511 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: <<my-client-ip>>>, server:  http://<<my-mattermost-host-name>>  , request: "POST /api/v4/posts HTTP/2.0", upstream: "http://<<my-mattermost-server-ip>>>:8065/api/v4/posts", host: " http://<<my-mattermost-host-name>>  "
```

**Comment by amyblais** [comment]
Thank you, v9.0 is an unsupported version. Would your team be open to upgrading to v9.5 or a newer version?

**Comment by cwatzl** [comment]
> Thank you, v9.0 is an unsupported version. Would your team be open to upgrading to v9.5 or a newer version?

I see. I will ask the admin team to upgrade. I'm sure they are open to that, just don't know when they find the time.
I guess we can close this issue for now, I'd reopen it if it happens again with a supported version.

Thanks again for your incredibly fast support!

**Comment by cwatzl** [comment]
@amyblais The Mattermost server has now been updated to version 9.9.0.

![image](https://github.com/mattermost/mattermost/assets/49339714/80cb2d17-ec08-4238-9f02-f518a4743a29)

Unfortunately, the problem still persists. Can you please reopen the issue?

Message containing the following text works:

> select foo from bar;

Message containing the following fails:

> select * from bar;

The only difference is the "*" character in the text. 

The server just seems to return HTTP status code 104 when trying to post the message. There still isn't any error message in the server log.

**Comment by amyblais** [comment]
@mattermost/server-platform I wasn't able to reproduce this (neither on a PostgreSQL nor on a MySQL test server). Should I open a ticket for further investigating this?

**Comment by agnivade** [comment]
@cwatzl - Are you sure there is no application firewall like WAF or something similar between nginx and Mattermost? It sounds like either the firewall is closing the connection or somehow Mattermost is crashing.

**Comment by cwatzl** [comment]
@agnivade Yes, pretty sure. Also the connection is otherwise stable, we only have problems with this very specific message payload pattern. For a WAF to interfere, it would have to do deep packet inspection, and we definitely don't have that in our network.

@amyblais Well, to be perfectly frank, it's just a minor inconvenience, so I wouldn't presume to take up more of anyone's time with this if it's not even reproducible outside of our specific environment. Thank you a lot anyway for all the effort you already put in.

**Comment by agnivade** [comment]
Ok, then most likely Mattermost is crashing and that's why you are not able to see any logs. What sort of deployment you are using? If you are using a systemd service, you can get the console logs via `journalctl -u mattermost -e`.

**Comment by amyblais** [comment]
Closing for now until we hear back,
