### ISSUE TITLE
bulk import of accounts with auth_service openid

### ISSUE THREAD

**Issue by small1** [mattermost/mattermost#27337]
#### Summary
After exporting accounts where custom openid has been used as auth service. All accounts has "auth_service":"openid"   This file is not possible to import again because it says that openid is an invalid auth service. 

#### Steps to reproduce
Export users form a server with users using openid as authentication. Try to import that file again.

look at the job list and you will have this error:
Data: map[error:Error during job execution. — BulkImport: Invalid auth service: openid extract_content:true import_file:anwqak1sstfwix84wuiso1n6so_name5.zip line_number:36 local_mode:false]

#### Expected behavior
Be able to import the same file as i have exported. And ability to bulk import new users with openid as auth_service

#### Observed behavior (that appears unintentional) 
Data: map[error:Error during job execution. — BulkImport: Invalid auth service: openid extract_content:true import_file:anwqak1sstfwix84wuiso1n6so_name5.zip line_number:36 local_mode:false]

#### Possible fixes
Import needs to be changes so that it can handle openid as valid auth service

**Comment by amyblais** [comment]
Please let us know if you're able to share more details about your environment, and we can re-open this issue,

**Comment by small1** [comment]
Sorry for the late reply.  Im using latest mattermost on docker.   This is a limitation in the code. It can handle openid as auth. But as soon as a user uses that for authentication it is possible to export but not import without manually changing the import file.  It would also be good if one could convert users to openid and not just ldap and saml.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59359.
