### ISSUE TITLE
`registerCallButtonAction` method should accept an icon parameter

### ISSUE THREAD

**Issue by ckaznable** [mattermost/mattermost#27359]
#### Summary
The `registerCallButtonAction` method dispatches both `CallButton` and `MobileChannelHeaderButton`. Without an icon parameter, the header button on mobile web shows as an empty icon.

#### Steps to reproduce
1. Install the [mattermost-plugin-calls](https://github.com/mattermost/mattermost-plugin-calls).
2. Switch to mobile web view.

#### Expected behavior
The plugin's icon should be displayed correctly on the mobile web header button.

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/18453951/cfe99306-62a6-4377-bd3f-55934291d598)

#### Possible fixes
Accept an icon parameter or provide an alternative method to customize the `MobileChannelHeaderButton`.

**Comment by amyblais** [comment]
Hi @ckaznable, what Mattermost server version are you on? What OS and version are you on?

**Comment by amyblais** [comment]
Closing as a duplicate,
