### ISSUE TITLE
Custom branding in signup/signin overlap with back button

### ISSUE THREAD

**Issue by zenocode-org** [mattermost/mattermost#27372]
#### Summary
Back button overlap the custom branding name

#### Steps to reproduce
Add a custom branding name and go to the signin/signup page

#### Expected behavior
Show the back button bellow the custom branding

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/86880242/8d40b8e4-d4b9-44de-b94e-3fd3a575f116)
![image](https://github.com/mattermost/mattermost/assets/86880242/0c1954dd-dada-4551-a9ef-fddb2503dde5)

#### Possible fixes
https://github.com/mattermost/mattermost/blob/master/webapp/channels/src/components/header_footer_route/header.tsx#L43

**Comment by zenocode-org** [comment]
Separated but unsure where to ask this, how can I get the permissions to edit strings for the French translation language on Mattermost weblate ? I have seen several important missing string ("Create an account" as the most important)

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-58802

**Comment by Ari1009** [comment]
Can i work on this?

**Comment by zenocode-org** [comment]
@Ari1009 https://github.com/mattermost/mattermost/pull/27394

**Comment by Ari1009** [comment]
Thanks for the clarification! Without a linked PR, I assumed the issue was still open. Appreciate the heads up.

**Comment by zenocode-org** [comment]
I will close the issue once the PR https://github.com/mattermost/mattermost/pull/27394 is merged. Thanks for proposing your help here.
