### ISSUE TITLE
Minio S3 Backend File Upload Problem

### ISSUE THREAD

**Issue by alekseyp** [mattermost/mattermost#27373]
Follow up from https://github.com/mattermost/mattermost/issues/27293 after it was closed without checking anything.

Internal was closed as well, stating inly minio and aws are supported: https://mattermost.atlassian.net/browse/MM-58677

Minio uploads are failing with the same error as in original issue.

https://github.com/mattermost/mattermost/issues/27293#issuecomment-2171743191

**Comment by agnivade** [comment]
Thanks @alekseyp - could you please let us know the version of Minio that you are using? Thanks.

**Comment by agnivade** [comment]
For reference, I updated our CI system to run the latest Minio image and observed no issues. I tested manually as well. Please let us know the Minio version and Mattermost version you are using.

**Comment by amyblais** [comment]
Closing for now until we hear back on more details,

**Comment by alekseyp** [comment]
Based on the answers given in other tickets and lost trust due to those answers - we've moved on to other solutions.
