### ISSUE TITLE
`Uncaught TypeError: navigator.sendBeacon is not a function` in MM 9.9.0 with Firefox Nighly 129.0a1

### ISSUE THREAD

**Issue by svenseeberg** [mattermost/mattermost#27423]
#### Summary
After upgrading to MM 9.9.0 and reloading the web application and waiting for about 20 seconds, Mattermost shows the following message:

> A JavaScript error has occurred. Please use the JavaScript console to capture and report the error

The JS console reports `Uncaught TypeError: navigator.sendBeacon is not a function`:

![image](https://github.com/mattermost/mattermost/assets/15197000/3139099b-414a-4676-99cd-72a20f2d3160)

Everything else in the console looks good.

I have tested this on Firefox Nightly 129.0a1 and Chromium 125.0.6422.141. The problem does not occur on Chromium.

#### Steps to reproduce
AFAICT logging in on Mattermost 9.9.0 with Firefox Nightly is sufficient to reproduce the issue.

#### Expected behavior
N/A

#### Observed behavior (that appears unintentional) 
Mattermost shows the following message:

> A JavaScript error has occurred. Please use the JavaScript console to capture and report the error

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Hi @svenseeberg, are you able to reproduce the issue at https://community.mattermost.com/?

**Comment by svenseeberg** [comment]
Yes:

![image](https://github.com/mattermost/mattermost/assets/15197000/101e0455-d4cc-4aa2-bc14-c6080e976de6)

**Comment by fab-kaz** [comment]
hello,

same here with MM9.9.0 and ff 115.12.0esr (64 bits)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59052.
