### ISSUE TITLE
Threads not visible on Chrome mobile

### ISSUE THREAD

**Issue by dfolias** [mattermost/mattermost#27424]
#### Summary
When using Mattermost on Chrome mobile, the Threads view is empty after upgrade to self-hosted Mattermost Version: 9.9.0

#### Steps to reproduce
With Collapsed Reply Threads enabled, click on Threads on Chrome mobile

#### Expected behavior
Threads view is visible on Chrome mobile devices

#### Observed behavior (that appears unintentional) 
The issue appears when dimensions are <= 768 pixels
![image](https://github.com/mattermost/mattermost/assets/6143582/7d8bbb3b-e91d-4c23-85af-98386a3c9d87)

**Comment by amyblais** [comment]
Hi @dfolias, what Chrome version are you on? Are you able to reproduce the issue at https://community.mattermost.com/?

**Comment by dfolias** [comment]
Chrome 126.0.6478.110 is the version on Mobile

I was able to reproduce at https://community.mattermost.com/

Also able to reproduce from Chromium Version 126.0.6478.114 by using Device Mode with:
Ctrl+Shift+I  (DevTools)
Ctrl+Shift+M (Toggle [Device Mode](https://developer.chrome.com/docs/devtools/device-mode))

From Device Mode you can change dimensions and reproduce the issue when setting to < =768 pixels.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59040.
