### ISSUE TITLE
Improving the Overview Section

### ISSUE THREAD

**Issue by Parth20GitHub** [mattermost/mattermost#27434]
![image](https://github.com/mattermost/mattermost/assets/142086512/8c0da824-70db-4c0f-9d0f-1b1fd2d9da20)

It's an error and should be resolved,
ASSIGN me , I would really like to contribute !

**Comment by amyblais** [comment]
Hi @Parth20GitHub, the website is not open sourced, so this would need to be fixed internally by the Marketing team. What issue are you seeing on this page?

**Comment by amyblais** [comment]
Closing for now. Please let us know what issue you're experiencing and we can re-open this,
