### ISSUE TITLE
Text: DND and custom status have datetime in different manners

### ISSUE THREAD

**Issue by tnir** [mattermost/mattermost#27492]
#### Summary

DND (https://mattermost.atlassian.net/browse/MM-38745 and #26334 (#19134)) and custom status show datetime in different manners.

#### Steps to reproduce

1. Sets DND with "Clear after:" in 30 mins.
2. Sets custom status with "Clear after: " in 30 mins.
3. Click my avatar image on the top right to open the status menu to see the difference in both.

#### Expected behavior

Style in the one should be as same as style in the other.

#### Observed behavior (that appears unintentional) 

With only time (Clear after: 30 mins)

![mm-time-only](https://github.com/mattermost/mattermost/assets/10229505/f19d92b7-25e2-404e-bc13-010378c9824f)

With date time (Clear after: 26 hours)

![mm-date-time](https://github.com/mattermost/mattermost/assets/10229505/e9a6e3da-dca5-4616-afc9-e4de62280e58)

#### Possible fixes

- `ExpiryTime` component defined in `webapp/channels/src/components/custom_status/expiry_time.tsx` looks too complicated unlike `renderDndExtraText` in `StatusDropdown` (`webapp/channels/src/components/status_dropdown/status_dropdown.tsx`).

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59268.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this,
