### ISSUE TITLE
Can't open web client on iOS Safari

### ISSUE THREAD

**Issue by MJegorovas** [mattermost/mattermost#27503]
#### Summary
Mattermost web client page is not loading when using iOS Safari browser

#### Steps to reproduce
Try to open any mattermost client page on iOS Safari

#### Expected behavior
Correctly display client page or login page if unathorized

#### Observed behavior (that appears unintentional) 
First, I wanted to open my company's mattermost client (which is on 9.10 version) and after it loads the mobile app page and I select "view in browser" option the page is not loading anymore. `community.mattermost.com` is also not loading. Worth noting that I could login into my company's client using this flow previously (don't remember how long ago and what version it was based on but should be 1-2 weeks before). Tested on iOS 15.8 and iOS 17.4 real devices, also on same version simulators. Could not reproduce this on mac Safari changing user agent though. On Android everything works correctly. Can provide further info if needed.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Fixed in v9.10.1,
