### ISSUE TITLE
Threads: Proposal for additional usability and readability Option

### ISSUE THREAD

**Issue by githubkoma** [mattermost/mattermost#27567]
Dear Team,
thanks for the awesome Mattermost App!

I love threads, and i would like to suggest an additional usability and readability option:

Background (or "what drives me mad"):
Everybody knows the flow of conversations, they have the tendency to get unstructurized and important threads of messages get "buried" below new incoming messages in the parent channel.
Also People sometimes dont answer in threads, either they dont want to use threads, or they accidently answer in the parent channel.
This makes things more than often confusing to follow..

My Proposal to implement just some options:

How it works Now:
- Open Channel
- Write either "normally" into the channel, or reply to a thread

Proposal:
- Open Channel
- DONT ALLOW to write normally ! input field is disabled.
- Just allow to reply to threads, that are already open.
- AND have the ability to create a new thread

This would be awesome to have that settings per Channel. 
Like in Channel A this is activated, and in Channel B,C,D its just like it was before.

Thanks for considering and wishing you the best,
githubkoma

P.S.: I made a mockup of what a thread enabled channel perhaps could look like to (1.) achieve or even (2.) enforce a structure thats different from other messengers Thread views:

![mattermost threads mockup](https://github.com/mattermost/mattermost/assets/5107805/8d5ed4aa-c298-4803-a353-6efdbf0e79ef)

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @githubkoma,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by michalgor** [comment]
Hello.

Why this issue has been closed as completed? This would be very useful feature. Especially per channel settings. 

Discussion on some channels are better suited for threads mode. This feature would allow to act some channels as some kind of forum.
