### ISSUE TITLE
Sending image from android app via share option fails and then crashes Mattermost on rety

### ISSUE THREAD

**Issue by rivendellstuff** [mattermost/mattermost#27579]
#### Summary
Sending image from android app via share option fails and then crashes Mattermost.

#### Steps to reproduce
(tested on Motorola Razr Flip (Aves) and Samsung Galaxy 10S)
1. Open your photos app on Android
2. Open an image
3. Share image
4. Choose Mattermost
5. Choose a person
6. Message optional
7. Click send
8. You'll end up back at the image you tried to share
9. Image will not have been sent
10. Immediately repeat steps 3-7
11. Mattermost crashes
12. Image DOES send

#### Operating System
Android App

#### Mattermost Server Version
Mattermost Team Edition ( Docker )
Mattermost Version: 9.9.1
Database Schema Version: 121
Build Number: 9683539226
Database: postgres

#### Expected behavior
Image sends and Mattermost no crash

#### Observed behavior
Image no send and Mattermost crashes on retry

**Comment by amyblais** [comment]
A fix for this is queued for the next mobile app release v2.18.0,
