### ISSUE TITLE
UI issue : bad behavior on window resizing

### ISSUE THREAD

**Issue by rex-banner** [mattermost/mattermost#27585]
#### Summary
On a specific windows resizing method (double click when having double vertical arrow cursor on window border), Mattermost client do not fill in the extended window

#### Steps to reproduce
When double clicking on the top or bottom border of Mattermost window (when having double vertical arrow cursor), the extended window is not properly filled
![resize before](https://github.com/mattermost/mattermost/assets/18286828/845370bd-7137-44e6-a9e0-8b4ce465793c)
![resize after](https://github.com/mattermost/mattermost/assets/18286828/e06c0b66-face-455c-8808-bf89948733dd)

#### Operating System
Windows 10 x64 Enterprise

#### Mattermost Server Version
Server version 9.8.1
Client version 5.8.1

#### Expected behavior
UI should use the full extended window

#### Observed behavior
Blank space on the extended window part

**Comment by amyblais** [comment]
@rex-banner v5.8.1 might be your desktop app version. You can find the server version from Main Menu > About Mattermost.

Also, are you able to reproduce this issue at https://community.mattermost.com/?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59409.
