### ISSUE TITLE
Setup complexity is over engineered, add go.work, remove github.com/mattermost/mattermost/v8 import

### ISSUE THREAD

**Issue by lil5** [mattermost/mattermost#27633]
1. Unignore `go.work` and `go.work.sum, I'm assuming you have an enterprise go.work file that I understand would like to keep hidden, but then use a different version for the open source mattermost version and save it elsewhere like (`go.work-oss`,`go.work.sum-oss`) so that we can symlink it.
2. Remove the `github.com/mattermost/mattermost/server/v8` currently a lot of code is broken if you git clone atm.
3. Simplify getting started as a developer, A simple docker-compose file should be enough, with the following services: database + volume, golang, node, caddy to temporarily combine the frontend & backend with reverse proxies. This allows for hot-reloading for frontend, the ability to restart the backend separately & to contain everything in docker

#### Operating System
What Operating System do you use? (Apple Silicon 14.5, LinuxMint 21.3)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59545.

**Comment by agnivade** [comment]
1. There is only one go.work file. There is an enterprise module. And the go.work file is dynamically generated depending on if you have the directory or not. There is no need to symlink anything.
2. Can you please mention the steps and what do you see? Perhaps there are some documentation changes needed. This is what you should be following: https://developers.mattermost.com/contribute/developer-setup/
3. We do have a docker-compose file. That is also dynamically generated depending on how many services you want to be created. There are additional components needed like - Elasticsearch, LDAP, Minio, Prometheus, Grafana etc. https://github.com/mattermost/mattermost/blob/master/server/build/docker-compose.common.yml. If you find anything that could be simplified, a PR would be most appreciated.

**Comment by amyblais** [comment]
Closing for now as we haven't received more details, can be re-opened as needed.
