### ISSUE TITLE
UI issue : blank area on extended thread

### ISSUE THREAD

**Issue by vadzhiltsov** [mattermost/mattermost#27709]
**Summary:**
The bug report describes an issue where extending a thread in Mattermost leaves a blank vertical stripe on the right side of the screen on Windows 10.

**Steps to reproduce:**
- Set zoom level in your browser to at least 110%.
- Click the bidirectional diagonal arrow in the top right corner of the UI to extend a thread.
- Observe the blank vertical stripe on the right side of the screen.

**Expected behavior:**
The extended thread should fill the entire dedicated area without any blank spaces.

**Observed behavior:**
The extended thread leaves a blank space on the right side of the screen.

**Additional information:**
- Operating System: Windows 10 x64 Pro
- Mattermost Server Version: 9.9.1
- Client Version: 5.8.1 and web-client

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59855.

**Comment by adityasoni2019** [comment]
Hey @vadzhiltsov could you provide screenshots?

**Comment by vadzhiltsov** [comment]
Hi Aditya,

Please find the screenshot attached to this message.
