### ISSUE TITLE
Slow Loading of User Nicknames and Interface Elements after Upgrading to 9.10.1

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost#27713]
#### Summary

Slow Loading of User Nicknames and Interface Elements after Upgrading to 9.10.1

#### Steps to reproduce

1. Access the web interface or refresh the web interface.
2. Observe that the user's nickname initially displays as "someone".
3. Wait for several seconds, during which the user's nickname updates to the correct one, and other interface elements like replies appear.

#### Operating System

MacOS 14.5

#### Mattermost Server Version

9.10.1

#### Expected behavior

Same with 9.9.1, load quickly.

#### Observed behavior

Load slowly.

#### Additional Information

In version 9.9.1, although a similar process occurs, it is very fast and requires 0.25x speed to notice it.
In version 9.10.1, this process takes several seconds, significantly impacting user experience.

**Comment by eli-yip** [comment]
> Hi @eli-yip, I wasn't able to reproduce this just now. Do you see errors in the server logs? Can you reproduce this issue at [community.mattermost.com](https://community.mattermost.com/)?

Sorry I have downgraded to 9.9.1, so no error logs.

But I can reproduce it on the server you provided, I recorded a gif:

![2024-07-22-VvOCtyd5000853](https://github.com/user-attachments/assets/82003549-c32d-43fa-bb03-9f91cc3f8ba2)

I have disable all the chrome extensions.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59832.

**Comment by agnivade** [comment]
Hey @eli-yip - this is expected and controlled by the `ExperimentalSettings.UsersStatusAndProfileFetchingPollIntervalMilliseconds` flag. Release notes here: https://docs.mattermost.com/about/mattermost-v9-changelog.html#changes-to-all-plans.

If you want to fetch the user profile earlier, please reduce the interval. But do note that the shorter you make the interval the more load you generate on your server and the browser. It's a tradeoff between performance and usability.

**Comment by eli-yip** [comment]
> Hey @eli-yip - this is expected and controlled by the `ExperimentalSettings.UsersStatusAndProfileFetchingPollIntervalMilliseconds` flag. Release notes here: [docs.mattermost.com/about/mattermost-v9-changelog.html#changes-to-all-plans](https://docs.mattermost.com/about/mattermost-v9-changelog.html#changes-to-all-plans).
> 
> If you want to fetch the user profile earlier, please reduce the interval. But do note that the shorter you make the interval the more load you generate on your server and the browser. It's a tradeoff between performance and usability.

@agnivade Thank you, after changing it to 1000 solved the problem. More questions come out...

I wonder what's client behavior when server is under 9.10.x like 9.9.2. I set this interval to 1000 in 9.10.2, but not fast as before.

I think if I decrease this interval, server will have more pressure, but 9.9.2 server returns user status faster then 1000 interval at init(?). So what is difference between 9.9.x and 9.10.x in user status fetch? Can I set it to a much lower status to get better user experience?

Last, if I can change the configure to achieve this effect:

- At init(after refreshing), client get user status as faster as it can.
- After initing, client get user status as config's interval settings.

**Comment by agnivade** [comment]
Will defer @M-ZubairAhmed for more comments.

**Comment by M-ZubairAhmed** [comment]
@eli-yip 
Thank you for detailed suggestion. For your first suggestion currently both user profiles and statuses are tied to a single configurable interval value. It does seems like separate configuration is valuable as well.
You can even turn off the feature i.e fetch without any interval if you set it to 0. We will add this in the docs.

**Comment by eli-yip** [comment]
> @eli-yip Thank you for detailed suggestion. For your first suggestion currently both user profiles and statuses are tied to a single configurable interval value. It does seems like separate configuration is valuable as well. You can even turn off the feature i.e fetch without any interval if you set it to 0. We added this note in the docs as well [docs.mattermost.com/configure/experimental-configuration-settings.html#user-s-status-and-profile-fetching-poll-interval](https://docs.mattermost.com/configure/experimental-configuration-settings.html#user-s-status-and-profile-fetching-poll-interval)

@M-ZubairAhmed Thank you for your suggestions! Finally I change this settings to 0, though I truly want to get team members' latest status. Hope separate configuration will be in roadmap soon.

Should I close this issue or keep it as a reminder for mattermost team?

**Comment by M-ZubairAhmed** [comment]
> Thank you for your suggestions! Finally I change this settings to 0

Changint to 0 doesnt turn off the app ability to get the status. It just turns off the batching we had done to improve performance. You would still get the latest user statuses and profiles without any problem. Hope that answers the question.

Feel free to close it. We have more upgrade on this feature in pipline.

**Comment by eli-yip** [comment]
> > Thank you for your suggestions! Finally I change this settings to 0
> 
> Changint to 0 doesnt turn off the app ability to get the status. It just turns off the batching we had done to improve performance. You would still get the latest user statuses and profiles without any problem. Hope that answers the question.
> 
> Feel free to close it. We have more upgrade on this feature in pipline.

@M-ZubairAhmed Sorry, I have one last question: If I set this to 0, will the client only fetch the latest user status when I first open the client and refresh it?

**Comment by M-ZubairAhmed** [comment]
> If I set this to 0, will the client only fetch the latest user status when I first open the client and refresh it?

The client fetches statuses upon initial load and subsequently as needed. Setting the value to zero disables the batching mechanism, which was initially implemented to manage the high volume of requests sent in a short duration, particularly in scenarios with high user engagement. Therefore, setting the value to zero means statuses are fetched immediately as required, whereas any non-zero value introduces a slight delay before fetching the statuses. Regardless of the setting, statuses are always fetched; this behavior remains unchanged.

**Comment by eli-yip** [comment]
> > If I set this to 0, will the client only fetch the latest user status when I first open the client and refresh it?
> 
> The client fetches statuses upon initial load and subsequently as needed. Setting the value to zero disables the batching mechanism, which was initially implemented to manage the high volume of requests sent in a short duration, particularly in scenarios with high user engagement. Therefore, setting the value to zero means statuses are fetched immediately as required, whereas any non-zero value introduces a slight delay before fetching the statuses. Regardless of the setting, statuses are always fetched; this behavior remains unchanged.

Thank you, I fully understand this.
