### ISSUE TITLE
Session has expired with multiple instances on same IP

### ISSUE THREAD

**Issue by olodar** [mattermost/mattermost#27718]
#### Summary
I have installed multiple different mattermost instances which accessing through one IP using port forwarding, so scheme looks like this:
mattermost1 -> 192.168.1.100:100 -> 10.10.10.1:8065
mattermost2 -> 192.168.1.100:101 -> 10.10.10.2:8065
mattermost3 -> 192.168.1.100:102 -> 10.10.10.3:8065
so, when I logging in to one of them, it's okay, but when I accessing to any another instance (i.e. opening it in another tab), previous tab has logging out with message "Your session has expired. Please log in again.".

#### Steps to reproduce
I think need to access from one IP to multiple MM instances with different ports on "forwarder".

#### Operating System
Ubuntu Linux 22.04 LTS x64

#### Mattermost Server Version
Mattermost Version: 9.10.0

#### Expected behavior
All instances should be logged in and working in parallel

#### Observed behavior
It simply drops the session

#### Log Output
Idk what exactly logs are need...

![2024-07-21_20-32](https://github.com/user-attachments/assets/0de2630c-8440-48e8-8e29-ece7a6650649)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59848.

**Comment by amyblais** [comment]
Closing older issues as our team hasn't been able to prioritize this,
