### ISSUE TITLE
Keybase Missing PGP Public Key

### ISSUE THREAD

**Issue by jenic** [mattermost/mattermost#27711]
#### Summary
Keybase key for verifying the tar archive's signature is missing. Looks like a repeat of closed issue #20008 

#### Steps to reproduce
```sh
$ curl https://keybase.io/mattermost/pgp_keys.asc
SELF-SIGNED PUBLIC KEY NOT FOUND
```

#### Operating System
Linux

#### Mattermost Server Version
N/A

#### Expected behavior
Receive GPG public key block.

#### Observed behavior
Received a "not found" error

#### Log Output
N/A

#### Additional Information
Looks like this issue occurred in #20008 as well.

**Comment by amyblais** [comment]
@jenic Can you help confirm that it is not related to this issue https://github.com/mattermost/desktop/issues/3000#issuecomment-2042139381?

**Comment by jenic** [comment]
> @jenic Can you help confirm that it is not related to this issue [mattermost/desktop#3000 (comment)](https://github.com/mattermost/desktop/issues/3000#issuecomment-2042139381)?

Hey Amy, it's definitely related. The key returned by deb.packages.mattermost.com is the same key id but with an updated expiration so I am assuming fetching the key from Keybase is no longer an accepted method and I will instead fetch from that URL. Thanks for the help!
