### ISSUE TITLE
Application crashes when using the Voice feature on Linux

### ISSUE THREAD

**Issue by MiMmohammdi** [mattermost/mattermost#27723]
Hello,

When using the Voice feature in the Mattermost application, the program unexpectedly crashes and stops working. This issue only occurs on the Linux operating system and is not observed on other platforms.

Operating System: Manjaro KDE 24.0.3
App Version: 5.7.0-2

Steps to Reproduce:

Open the Mattermost application on Linux.
Navigate to the section where you can send Voice messages.
Attempt to send a voice message.
Expected Result:
The application should send the voice message correctly without crashing.

Observed Result:
The application crashes and stops working.

I would appreciate it if you could look into this issue and resolve it.

**Comment by ksinaa** [comment]
i have this issue too

**Comment by amyblais** [comment]
Hi @MiMmohammdi,
1. Does this reproduce on the latest app version, v5.8.1?
2. Are there errors in the Mattermost server logs or in the developer console?
3. What Mattermost Server Version are you on?
4. Are you able to reproduce the issue on https://community.mattermost.com/?

**Comment by amyblais** [comment]
Closing for now until we hear back,
