### ISSUE TITLE
Upgrading from 5.19 to latest

### ISSUE THREAD

**Issue by amirad1** [mattermost/mattermost#27735]
How Can I upgrade from 5.19 version to 9.10 version? I cannot understand the documents 
I have directly migrated with a backingup and restoring postgres db in new version but I had some issues ?
can anybody help ?

**Comment by agnivade** [comment]
This should help you: https://docs.mattermost.com/upgrade/prepare-to-upgrade-mattermost.html#upgrade-best-practices

**Comment by amyblais** [comment]
Closing as this was opened in the troubleshooting forum site https://forum.mattermost.com/t/how-to-upgrade-from-5-19-to-latest-version/19077/1.
