### ISSUE TITLE
Close direct messages doesn't work

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/mattermost#27753]
#### Summary
Closed direct messages get back - probably, after server restart on a server migrated from MySQL version.

#### Steps to reproduce
- Close direct message

#### Operating System
Ubuntu Linux 24.04, MacOS 14.5

#### Mattermost Server Version
Mattermost Version: 9.9.2
Database Schema Version: 124
Build Number: 9962179521
Database: postgres

#### Expected behavior
Closed messages / channels remain closed.

#### Observed behavior
They re-appears.

#### Log Output
Not sure what are the log files required.

#### Additional Information
No errors.. =/

#### Possible fixes
N/A

**Comment by eli-yip** [comment]
Yes, I often encounter this problem. It seems to be with bad category syncing between mobile app and web.

**Comment by amyblais** [comment]
I wasn't able to reproduce it - I spun up a test server, restarted it, but closed DMs remained closed. You can either get troubleshooting assistance in the forum here https://forum.mattermost.com/, or we may need additional details to reproduce the bug.

**Comment by alexander-potemkin** [comment]
Apologies for the delay: yes, resetting cache everywhere and removing from web desktop helped - thanks for the hint!
