### ISSUE TITLE
Interactive messages - Home Assistant Node Red

### ISSUE THREAD

**Issue by iptvcld** [mattermost/mattermost#27762]
Hello; I have a self hosted setup and i am sending the email json to my chat with 2 buttons but I can never get a response back when i click the button. I have been reading for hours now

**Comment by amyblais** [comment]
You can get troubleshooting assistance in the forum here https://forum.mattermost.com/.

If you believe that this is a bug, please fill in the details as requested in the issue creation screen: https://github.com/mattermost/mattermost/issues/new.
