### ISSUE TITLE
Markdown issues with gender-neutral German

### ISSUE THREAD

**Issue by Haliax** [mattermost/mattermost#27814]
#### Summary
The gender-neutral or -inclusive German language appends `*in`, `*innen` to words.
The Markdown formatting is interpreting this (correctly) as italic when using it multiple times within a paragraph without escaping the asterisk.

A workaround in the German language can be, to append `:in` and `:innen` instead. However, it doesn't work on mobile platforms as well.
If a paragraph is starting with a word like that, it is mistakenly interpreted as a link.
The same is true, if a German special character like `ä` is used in the word.

#### Steps to reproduce
**Asterisk annotation**:
- Type: `Liebe Freund*innen und Kolleg*innen` (dear friends and colleagues).
  - Non-tech-savvy users are expecting to see exactly what is printed above. They do not understand how to escape those characters.
  - Additionally, some users on Apple devices and German keyboard layout are reporting, that they cannot use the escaping symbol `/`. Because a shortcut (i think the help page) is bound to the key-combination. 
- The real output is: Liebe Freund*innen und Kolleg*innen.
  - This effect is even more noticeable, if both words are further apart from each other.

**Colon annotation**:
- This is only observed using the mobile applications.
  - I reproduced it on the Android App on a Google Pixel device.
- Type: `Freun:in` at the start of a paragraph.
  - Result: It is mistakenly interpreted as a link.
- Type: `Träger:innen` somewhere in a sentence.
  - Result: `Trä` is a text. `ger:innen` is interpreted as a link.

#### Operating System
Independent of the operating system.

#### Mattermost Server Version
All versions.

#### Expected behavior
What happens is the expected with Markdown.
However, it is not user-friendly.

#### Observed behavior
What issue did you see happen?

See the description in the above section.

#### Log Output
Output from the log files if applicable.

Not applicable.

#### Additional Information
Other applications, that are based on Markdown, are facing the same issues.
For example, Obsidian discussed it here: https://forum.obsidian.md/t/better-handle-mid-word-asterisks-for-gender-neutral-german/27567

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

There are two options:
- 1. We can create a plugin. This plugin scans every submitted message for `[word]*in `. Or `[word]*innen `. And manually adding the escape symbol on those two cases. German-speaking servers could add that community-plugin.
- 2. Add that behavior to the Mattermost engine.

I would be willing to implement the option of your choosing.

**Comment by amyblais** [comment]
Feel free to join our [contributors](https://community.mattermost.com/core/channels/tickets) and [localization](https://community.mattermost.com/core/channels/localization) channels on our community server to share the proposed solutions. One of our devs and other community members likely have thoughts on which option might work the best.

**Comment by Haliax** [comment]
There has not been any reaction in the general i18n channel and only one answer in the German i18n channel.

Therefore, I assume the problem does not bother to many instances. We will build a plugin to solve it for our instance.

**Comment by Haliax** [comment]
The plugin has been created: https://github.com/Haliax/mattermost-plugin-german-gender-neutral-language
