### ISSUE TITLE
Personal Status Not Updating Correctly on Mattermost Web Client

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost#27832]
#### Description

When the Mattermost web client is set to auto-update status, if no tabs are open for the Mattermost web client, opening a new web client tab often fails to switch the personal status to "Online", regardless of how many times the page is refreshed.

#### Steps to Reproduce

1. Open a new web client tab; the personal status remains "Offline" regardless of how many times the page is refreshed.
2. Open another web client tab; both tabs update the personal status to "Online," and refreshing either tab keeps the status as "Online".
3. Check `status` table in postgresql database, found status is online, but not correctly showed on web client. Other users can see my correct status, which is online.

FYI, when only one tab is open, clicking on the channel member list switches the status to "Online", but refreshing the page reverts the status to "Offline."

#### Testing Environment

1. Self-hosted Mattermost 9.10.1 and community.mattermost.com.
2. Browsers: Edge 127.0.2651.74 and iPadOS Safari.
4. Operating Systems: macOS 14.6 and iPadOS 17.6.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-59952.

**Comment by eli-yip** [comment]
@amyblais I saw the ticket you created in Jira, but it seems that my reproduction steps are missing: When there are no clients online, the frontend interface always shows as offline unless certain buttons are clicked (even though my status appears normal in the database and to other users). However, when multiple clients are online, the status is normal.

**Comment by amyblais** [comment]
Updated the ticket.

**Comment by eli-yip** [comment]
I just found a temp solution: Open a direct message with the account you are using. Keep the direct message "channel" on side bar will make status shown properly.
