### ISSUE TITLE
Fix unable to upload image/attachment on edit - missing

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost#27847]
Before filing a bug report, please check the following:

#### Summary
Currently when editing a message it functionality is missing that should be present: uploading an attachment. Currently a message has to be deleted and reposted or replied to. This is unexpected behavior and disruptive to the user experience in many instances.

#### Steps to reproduce
Edit a post/message and see pasting or attempting to upload an attachment is missing.

#### Operating System
What Operating System do you use? (examples: Windows 10 x64, macOS Ventura 13.2 Apple Silicon, Ubuntu Linux 22.04 LTS x64)

#### Mattermost Server Version
9.10.0

#### Expected behavior
Editing should allow uploading of documents/images/attachments.

#### Observed behavior
Currently pasting does not work and does not give an option to upload an attachment when editing a post.

#### Possible fixes
Implementing the upload function for editing would be the best way to handle this behavior. It's simply not reasonable to eliminate the ability to attach something after having posted something, especially when - in a thread - the original post might need such for attention/priority/effect/etc.

**Comment by amyblais** [comment]
Existing ticket: https://mattermost.atlassian.net/browse/MM-20143.
