### ISSUE TITLE
A JavaScript error has occurred. Please use the JavaScript console to capture and report the error

### ISSUE THREAD

**Issue by uglyeoin** [mattermost/mattermost#27877]
#### Summary
I see this error message: A JavaScript error has occurred. Please use the JavaScript console to capture and report the error

I have tried in both the Joomla Mattermost and also https://community.mattermost.com/

#### Steps to reproduce
Login, send a message.

#### Operating System
Windows 10 pro 64x

#### Mattermost Server Version
Joomla: Mattermost Version: 9.10.1
Community: Mattermost Version: 9.11.0

#### Expected behavior
Actually I don't notice any bad behaviour, but the message asks me to report it.

#### Observed behavior
Joomla Version
Console:
unable to open cloud modal  - general.ts:398 
com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312 [Util] handleError::  ResizeObserver loop completed with undelivered notifications.  - com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312 
Failed to load resource: the server responded with a status of 403 () (various)
/api/v4/groups?q=&filter_allow_reference=true&page=0&per_page=60&include_member_count=true&include_channel_member_count=h9m117uxdifwiduwejrhrc93kr:1 

Community version:
       GET https://community.mattermost.com/plugins/playbooks/api/v0/runs/channel/ui6wy4q7rpyb5mp7dhzn4w3jir 404 (Not Found) - client.ts:721 

[Util] handleError::  ResizeObserver loop completed with undelivered notifications. (various)
channel-notes_39c7f71e3c9f89f3_bundle.js:16 [Util] handleError::  ResizeObserver loop completed with undelivered notifications.
y @ channel-notes_39c7f71e3c9f89f3_bundle.js:16
k @ channel-notes_39c7f71e3c9f89f3_bundle.js:16
(anonymous) @ channel-notes_39c7f71e3c9f89f3_bundle.js:16
error
n @ channel-notes_39c7f71e3c9f89f3_bundle.js:1
(anonymous) @ channel-notes_39c7f71e3c9f89f3_bundle.js:24
com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312 [Util] handleError::  ResizeObserver loop completed with undelivered notifications.
b @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
N @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
(anonymous) @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
error
n @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:1
(anonymous) @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:18
(anonymous) @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
(anonymous) @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:288
(anonymous) @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:317
com.mattermost.nps_e0f4f7088d82c850_bundle.js:273 [Util] handleError::  ResizeObserver loop completed with undelivered notifications.
g @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
N @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
error
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
n @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:3
n @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
n @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:3
n @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:278
n @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
n @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:1
com.mattermost.agenda_6c1e12eaf003c4e3_bundle.js:16 [Util] handleError::  ResizeObserver loop completed with undelivered notifications.

#### Log Output
I don't know how to find this.

#### Additional Information
I think the text above is more useful than the screenshots.

#### Possible fixes
See above

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60058.

**Comment by amyblais** [comment]
Please re-open this issue in the matterpoll plugin repo here https://github.com/matterpoll/matterpoll/issues.

**Comment by uglyeoin** [comment]
Do I need to take action here or is it already done @amyblais ?

**Comment by amyblais** [comment]
@uglyeoin It would be helpful if you are open to creating this issue in the matterpoll repo. This bug seems to be related to the plugin.
