### ISSUE TITLE
Convert ./reducers/views/modals.test.tsx from Class Component to Function Component

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost#27901]
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-60079

**Comment by kyoichishido** [comment]
Hi, I'd like to work on this, issue please assign this to me.

**Comment by larkox** [comment]
@kyoichishido All yours! :smile:

**Comment by iutkarsh077** [comment]
interested

**Comment by Sandy712** [comment]
@larkox can this be assigned to me?

**Comment by larkox** [comment]
@kyoichishido Are you still working on this? Let me know to decide whether we assign this issue to @Sandy712 or we keep it yours :smile:

**Comment by Rishiii7** [comment]
Hi @larkox, I'm interested in contributing to this issue.

**Comment by larkox** [comment]
@kyoichishido is taking some time to answer, so this ticket will go to the next in line. @Sandy712 Are you still open to work on this?

**Comment by Tihomir-N** [comment]
Hi, I'm also available to work on the task immediately ;)

**Comment by larkox** [comment]
No answer from @kyoichishido nor @Sandy712 , so next one in line is @Rishiii7 . Are you willing to take the issue?

**Comment by Rishiii7** [comment]
Hi @larkox , yes I'll work on this issue

**Comment by Sandy712** [comment]
Apologies for the delayed response. If the task is still available, I'm ready to take it on. Please let me know how I can assist.

**Comment by larkox** [comment]
@Sandy712 right now @Rishiii7 has the issue assigned. If we is not able to do it, we can get back to you :smile:
