### ISSUE TITLE
Slow Response on /api/v4/limits/server Due to postCount Field

### ISSUE THREAD

**Issue by EndikaRamos** [mattermost/mattermost#27945]
#### Summary
The API endpoint `https://ownserver.company.com/api/v4/limits/server` is experiencing slow response times (5-8 seconds) specifically due to the `postCount` field.

#### Steps to reproduce
1. Access the endpoint `https://ownserver.company.com/api/v4/limits/server`.
2. Observe the response time.
3. Note that the query takes about 5-8 seconds to return data, including the `postCount` field.

#### Operating System
Debian 12

#### Mattermost Server Version
Mattermost 9.8

#### Expected behavior
The API should respond quickly, ideally within a few seconds, and the `postCount` field should not impact performance significantly.

#### Observed behavior
The API response time is considerably slow, taking 5-8 seconds. The slow performance seems to be related to the inclusion of the `postCount` field in the response.

#### Server Hardware
- **Cores**: 16
- **RAM**: 32 GB
- **Storage**: SSD

#### Additional Information
The API response includes the following JSON:
```json
{
  "maxUsersLimit": 10000,
  "maxUsersHardLimit": 11000,
  "activeUserCount": 1208,
  "maxPostLimit": 5000000,
  "postCount": 2473836
}

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60181

**Comment by harshilsharma63** [comment]
Hi @EndikaRamos 👋 

The post limit was added in v9.8.0, but was removed in v9.8.1. I request you to please upgrade to the latest v9.8.3 release.

LMK how it goes!

**Comment by amyblais** [comment]
Closing for now as an upgrade will resolve this,
