### ISSUE TITLE
Not prompted to keep status as offline

### ISSUE THREAD

**Issue by njnatale-lm** [mattermost/mattermost#28014]
#### Summary
I used to receive the "would you like to switch your status to online?" prompt when I opened the MM desktop app on my PC each day; I don't receive the prompt anymore and my status is already set to "online" each day.

#### Steps to reproduce
1. Boot up laptop
2. Launch MM desktop client
3. Status is set to online, no prompt (status was previously set to "offline" the night before)

#### Operating System
* Windows 11 23H2

#### Mattermost Server Version
* `9.9.0`

#### Expected behavior
* Receive the prompt described in this [Jira issue](https://mattermost.atlassian.net/browse/MM-4815)

#### Observed behavior
* I don't get the prompt

#### Log Output
* N/A

#### Additional Information
* N/A

#### Possible fixes
* N/A

**Comment by amyblais** [comment]
@njnatale-lm I wasn't able to reproduce it just now. Are you able to reproduce this on our community server https://community.mattermost.com/?

**Comment by njnatale-lm** [comment]
I've understood the cause, but I think a better solution is needed; it appears I may have accidentally clicked on the "Do not show again" checkbox on this prompt at some point in the past.

**There appears to be no method of resetting/clearing this from an end-user perspective.**

I was able to fix this by deleting a row in the `preferences` table; there was an entry for my user ID with the category of `auto_reset_manual_status`.

Can this issue be used to drive a better method of clearing this for users? Perhaps a "Reset previously hid dialogs" button within the user preference modal?

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @njnatale-lm,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by njnatale-lm** [comment]
Feature idea forum [post created](https://mattermost.uservoice.com/forums/306457-general/suggestions/48766835-allow-users-to-reset-do-not-ask-me-again-prompts). Unfortunately I do not have the bandwidth to look into implementing this.
