### ISSUE TITLE
Missing space in german translation 'Du bistauf dem aktuellen Stand'

### ISSUE THREAD

**Issue by JonnxW** [mattermost/mattermost#28010]
#### Summary
A small typo (missing space) in a german translation (`de.json`) in the conversations overview. When you have no unread conversations, the header reads 'Du bistauf dem aktuellen Stand', but it should say 'Du bist auf dem aktuellen Stand'

#### Steps to reproduce
Open the conversations overview of a channel

#### Operating System
Windows 10 x64

#### Mattermost Server Version
5.9.0

#### Possible fixes
In the file `webapp\channels\src\i18n\de.json` change line 3813 from

`"globalThreads.threadPane.unselectedTitle": "{numUnread, plural, =0 {Du bistauf dem aktuellen Stand} other {Lese deine Unterhaltungen}}",` 

to 

`"globalThreads.threadPane.unselectedTitle": "{numUnread, plural, =0 {Du bist auf dem aktuellen Stand} other {Lese deine Unterhaltungen}}",`

**Comment by amyblais** [comment]
@JonnxW Translations are done by volunteers via the translations server https://translate.mattermost.com/languages/. Would you be open to signing up and suggesting a translation edit via the server?

**Comment by JonnxW** [comment]
@amyblais Yes, I would be happy to sign up. Sorry for taking the wrong path here, I found the missing space while at work and had not to much time reporting it 🙈
