### ISSUE TITLE
The « Integrations » web view is broken in Firefox 115.14.0esr (64 bits) under Rocky Linux 8.10

### ISSUE THREAD

**Issue by glouton** [mattermost/mattermost#28030]
Hello there,

Thanks a lot for the very good job to everyone involved in this project.

#### Summary
The « Integrations » web view is broken in Firefox 115.14.0esr (64 bits) under Rocky Linux 8.10.

#### Steps to reproduce
Open the « Integrations » panel via the top left menu.

#### Operating System
Rocky Linux 8.10
Firefox 115.14.0esr (64 bits)

#### Mattermost Server Version
Mattermost Version: 9.11.0
Database Schema Version: 124
Build Number: 10163357270
Database: postgres

With Mattermost Docker

#### Expected behavior
The « Integrations » view should open full page from top left corner.

#### Observed behavior
The « Integrations » view displays shifted to the bottom right.

#### Log Output
Not applicable.

#### Additional Information
It was displaying ok before I recently updated to 9.11.0.
It's ok under Chromium.
Under Firefox 115.14.0esr (64 bits):
![image](https://github.com/user-attachments/assets/f03039e2-eec0-4666-af32-8120f406eaf3)

#### Possible fixes
No idea

Best regards,

**Comment by amyblais** [comment]
Hi @glouton, are you able to reproduce this on https://community.mattermost.com/?

**Comment by glouton** [comment]
Hi @amyblais ,

Thank you for your quick answer.

Sadly I can't reproduce this on community.mattermost.com because I don't have access to he « Integrations » section.
I guess one has to be admin, which would make sense.
![Capture d’écran de 2024-08-23 11-18-08](https://github.com/user-attachments/assets/1d1a9a9a-0c72-4860-9638-ecefbafa48cd)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60267.

**Comment by glouton** [comment]
Thanks! :)

**Comment by marianunez** [comment]
@glouton can you try and see if it's still an issue for you in https://community.mattermost.com/core/emoji ?

**Comment by marianunez** [comment]
@glouton we haven't been able to reproduce this in our end. Could you try updating your Firefox and try again?

**Comment by glouton** [comment]
@marianunez thanks for looking into it.
Today I've updated Mattermost (docker) to 10.0.0 but the issue was persisting under Firefox 115.14.0esr (64 bits) for Rocky Linux 8.
Then there was an automatic update of Firefox to 128.2.0esr (64-bit) and problem's gone, the Integration is back to its place.
![image](https://github.com/user-attachments/assets/8819661b-5746-4742-8943-7514041f71a7)

No idea what was causing this but as far as I'm concern, problem "solved". XD

**Comment by marianunez** [comment]
Glad to hear it's no longer an issue 🎉 Thanks @glouton!
