### ISSUE TITLE
Gitlab SSO requires full api scope

### ISSUE THREAD

**Issue by maritz** [mattermost/mattermost#28047]
#### Summary
GitLab SSO requires full api scope instead of only read_user as the docs state.

#### Steps to reproduce
- Set up GitLab SSO and don't check the "api" scope when creating the application in GitLab
- Try to switch a user (or make a new one) to GitLab SSO

#### Mattermost Server Version
Mattermost Version: 9.11.0

#### Expected behavior
SSO should work (as it does when selecting the api scope)

#### Observed behavior
GitLab page with error message: "The requested scope is invalid, unknown, or malformed."

#### Log Output
Can provide some later, if needed.

#### Possible fixes
Reduce the requested scope to read_user as suggested here: https://gitlab.com/gitlab-org/gitlab/-/issues/287946#note_453774032
(also in that issue thread is another mattermost user experiencing the same issue)

The full api scope provides too much access and thus poses a security problem.

**Comment by micolous** [comment]
I saw the same issue trying to set up GitLab auth on a fresh team edition install.

I was missing a `GitLabSettings.Scope` configuration (noted in ["Step 2: Configure Mattermost for GitLab SSO"](https://docs.mattermost.com/onboard/sso-gitlab.html#step-2-configure-mattermost-for-gitlab-sso), 7th item) – and the default is to set this to `""` (empty string).

Setting this to `read_user` was enough to get it working in team edition.

It doesn't look like there's any way to set this parameter from within the Mattermost web UI, or with environment variables (at least [not documented here](https://docs.mattermost.com/configure/authentication-configuration-settings.html#gitlab-oauth-2-0-settings)).

The only way to set it is by editing `config.json` manually, and restarting the server.

Exposing this parameter to the web UI ([suggested in another report for this issue](https://github.com/mattermost/mattermost/issues/17499#issuecomment-978814072)) seems like an easy way to address this class of issue 😉

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60770.
