### ISSUE TITLE
Incorrect API Return type in documentation

### ISSUE THREAD

**Issue by Jorricks** [mattermost/mattermost#28058]
#### Summary
The mentioned return type in the API docs is not correct for the following two operations:
- [Adds members to a custom group](https://api.mattermost.com/#tag/groups/operation/AddGroupMembers)
- [Removes members from a custom group](https://api.mattermost.com/#tag/groups/operation/DeleteGroupMembers).

I noticed this when building an API client based on auto-generated [Pydantic types](https://docs.pydantic.dev/latest/). These were auto-generated using the OpenAPI specification.

#### Steps to reproduce
Call the API endpoint successfully and observe you do not get back the [StatusOK type](https://github.com/mattermost/mattermost/blob/master/api/v4/source/groups.yaml#L857) as mentioned in the docs but [a list of GroupMembers](https://github.com/mattermost/mattermost/blob/081aa8f6dc305dbcc7857344a9d23c216121c1c9/server/channels/app/group.go#L832).

#### Operating System
MacOS

#### Mattermost Server Version
Mattermost Version: 9.5.7

#### Expected behavior
To return what the API docs mention (or update the API docs)

#### Observed behavior
I observed when building an API client that I got other data back then expected, namely;
```
[{'group_id': '......', 'user_id': '......', 'create_at': 1724702088521, 'delete_at': 1724702296238}]
```

#### Log Output
No logs required

#### Additional Information
No need. Links are provided in Steps to Reproduce.

#### Possible fixes
Update the documentation with the correct return type.

**Comment by Rupeshprajapati2123** [comment]
hii @Jorricks I am interested in this issue , Can I work on it?

**Comment by Jorricks** [comment]
> hii @Jorricks I am interested in this issue , Can I work on it?

Go for it :)

**Comment by Rupeshprajapati2123** [comment]
![image](https://github.com/user-attachments/assets/1ea44262-ff68-49db-a563-153a4bf0d14d)

Hi @Jorricks , I followed the developer docs given here https://developers.mattermost.com/contribute/developer-setup/
but unfortunately when at the final step when I try to run server which I clones locally after forking the main branch . It is giving me this error . Can you please provide some information on how to run the server and remove this error.

**Comment by Jorricks** [comment]
> ![image](https://github.com/user-attachments/assets/1ea44262-ff68-49db-a563-153a4bf0d14d)
> 
> Hi @Jorricks , I followed the developer docs given here https://developers.mattermost.com/contribute/developer-setup/
> but unfortunately when at the final step when I try to run server which I clones locally after forking the main branch . It is giving me this error . Can you please provide some information on how to run the server and remove this error.
> 

Sorry I'm not the right person to ask. I have no experience with the development of Mattermost.

**Comment by Aryakoste** [comment]
Hello @amyblais I would like to work on this issue if it's available.

**Comment by Aryakoste** [comment]
Working on this.
