### ISSUE TITLE
Messages not showing until quit+reopen app

### ISSUE THREAD

**Issue by brynwhyman** [mattermost/mattermost#28073]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] (Maybe - hard to recreate) This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Almost every 1-2 days, I and other users in my organisation do not receive sent direct messages (maybe tags in channels too). Quitting the desktop application and re-opening it will then show unread messages that were previously not visible.

**Environment**
- Operating System: Reported MacOS Monterey; Windows 10; Linux
- Mattermost Desktop App version: 5.1.0
- Mattermost Server version: 6.7.0

**Steps to reproduce**
1. Have someone send you a direct message (possibly it only occurs with 3+ people in the DM)

**Expected behavior**
1. The recipient sees a new unread message 

**Observed behavior**
1. (Often but not always) The recipient does not see the new message in the MM app. Quitting and re-opening the app will then show the new messages.

**Other notes**
Of course I'm not sure how this is happening but to state the obvious, it's incredibly frustrating!

**Comment by devinbinnie** [comment]
Closing as no responses, assuming the cluster fix was enough.

**Comment by lifeofguenter** [comment]
We have this issue on non-clusters as well.

**Comment by setpill** [comment]
Have you done any attempts to reproduce? I trivially just reproduced it again on community.mattermost.com. It's not that hard. :/

**Comment by setpill** [comment]
1. Connect to home wifi
2. Open 2 tabs with community.mattermost.com
3. Open DM to self
4. Send "test pre-network change" in tab 1
5. See it appear in tab 2
6. Connect to mobile hotspot instead of wifi
7. Send "test post-network change" in tab 2
8. It doesn't appear in tab 2.

**Comment by setpill** [comment]
Tab 1:
![image](https://github.com/user-attachments/assets/9e3934ff-3cb2-4865-a0aa-32dd84d9511c)

Tab 2:
![image](https://github.com/user-attachments/assets/0a5b6eec-08f2-4a1b-91fa-b8afe1b5e5c0)

Tab 3 (aka "new tab"):
![image](https://github.com/user-attachments/assets/37cc3bd4-09be-4493-81b4-425bd7cb0393)

**Comment by devinbinnie** [comment]
@lifeofguenter Do you have reproduction steps for your issue?

@setpill This is not something that's been easy to reproduce for us, so it sounds like there might be connectivity issues on your team. Can you confirm that the websocket is reconnecting? Can you send us a HAR file perhaps so we can see what the network traffic is doing? Are there any logs reported?

**Comment by setpill** [comment]
> @setpill This is not something that's been easy to reproduce for us, so it sounds like there might be connectivity issues on your team. Can you confirm that the websocket is reconnecting? Can you send us a HAR file perhaps so we can see what the network traffic is doing? Are there any logs reported?

I'm not sure what my team has to do with it; as stated I have reproduced this on `community.mattermost.com`.

As for the websocket; as I've responded before I never see a `websocket closed` in the console.

**Comment by setpill** [comment]
I'm not sure what kind of logs you are looking for, do you mean server logs? Perhaps the admin of `community.mattermost.com` might be of help there. I'm not sure what a HAR file is.

**Comment by setpill** [comment]
Hm, okay, so it turns out the issue actually *is* fixed on community.mattermost.com... It just takes around 15 minutes for the websocket timeout to hit and the connection to be reconnected. I only noticed because I went on with my day after the latest test and noticed both tabs had recovered. Set up a timer in the console, triggered it again and checked how long it took to recover.

15 minutes seems a strangely long time for mattermost to notice it got disconnected. Maybe that could be lowered to something closer to what people would expect from an instant messaging platform? I'm not sure what the load on big instances would be, but I would expect to receive a message at most within a minute of it being sent, preferably much less. Is there some way to configure a mattermost server to lower this timeout?

**Comment by devinbinnie** [comment]
@setpill What you're likely seeing is the `reconnect()` wake up handler being disabled. Are you not interacting with the app at all after you bring it back online? That should usually reconnect the websocket.

**Comment by setpill** [comment]
I am, I'm sending messages in the DM channel. Those messages also get delivered to the server (as confirmed by opening a new tab - tab 3 - where they are visible). But messages are not propagated to tab 1 and 2 (the ones opened pre-network change).

Furthermore, I think a commonly expected usage pattern is also that you have mattermost passively running in the background and it notifies you if anyone pings you for attention. If this potentially breaks for 15 minutes at a time that's... A suboptimal experience.

**Comment by devinbinnie** [comment]
> Connect to home wifi
Open 2 tabs with community.mattermost.com
Open DM to self
Send "test pre-network change" in tab 1
See it appear in tab 2
Connect to mobile hotspot instead of wifi
Send "test post-network change" in tab 2
It doesn't appear in tab 2.

@setpill Do you do anything else to get this to happen? I can't reproduce with these exact steps on community. If you expect a mention to pop up in a DM with yourself, that won't because you've already read it on the other tab.

**Comment by setpill** [comment]
> @setpill Do you do anything else to get this to happen? I can't reproduce with these exact steps on community. If you expect a mention to pop up in a DM with yourself, that won't because you've already read it on the other tab.

Not talking about mentions, literally talking about the messages not showing up. The tabs are "out of sync". See [the screenshots here](https://github.com/mattermost/mattermost/issues/28073#issuecomment-2353557468); they were all taken at the same time.

**Comment by setpill** [comment]
If relevant, I'm using `chromium` version `128.0.6613.119`

**Comment by zackyjsd** [comment]
I can also confirm this happens - particularly on the "new dm"
I'm using desktopApp  5.10.0 , Mattermost Server version:v10 cluster
@devinbinnie

**Comment by zackyjsd** [comment]
In the cluster
1. Create a new user (or someone who has never sent you a message)
2. The new user sends you a DM message

I guess that after the new DM channel was created, the other person was not notified, or there was a problem in the middle. Many people reported that they didn’t see the new DM until they reopened the app or waited for several hours.

**Comment by devinbinnie** [comment]
@zackyjsd Is this easily reproducible for you? If so, can you try something for me?
1) Open Dev Tools, then refresh your app
2) Reproduce the problem (receive a new DM)
3) Go to the Network tab, then filter by WS. Open the websocket connection entry
4) Under messages, check if there's a `user_added` message.

**Comment by ZarenOFF** [comment]
We are also currently facing this issue on a large scale. Mattermost Server 9.11.0, Desktop App 5.9.0.

**Comment by devinbinnie** [comment]
> We are also currently facing this issue on a large scale. Mattermost Server 9.11.0 non cluster, Desktop App 5.9.0. Perhaps it is worth reopening this issue?

@ZarenOFF Can you try the above as well?

**Comment by feeblelight** [comment]
@devinbinnie Of course, I'll provide feedback as soon as I can reproduce the issue.

**Comment by setpill** [comment]
![image](https://github.com/user-attachments/assets/30439be0-ffb6-42de-bbc6-7f69350714fc)

Still trivially reproducable on commmunity.mattermost.com...

**Comment by setpill** [comment]
Can this be reopened?

**Comment by foinf** [comment]
I am having the same issue with Mattermost 10.3.1 flatpak version on Nobara (Fedora Linux)

I don't need to restart the app itself to make the new messages appear. If I just switch the channel and then come back to the channel I was on, the new messages appear. It doesn't happen all the time, either.

Mattermost app on my phone (Android) is not having this problem while connected to the same server.

Seems to start happening at random.

**Comment by setpill** [comment]
Created a new issue #30164 because it seems this one is not being reopened. Not sure why.
