### ISSUE TITLE
Problem uploading files

### ISSUE THREAD

**Issue by BdServo** [mattermost/mattermost#28103]
When uploading any file (any size from zero kb to mb, any format) frequency got error. May success on the 3-5 try, in bad scenario always failed. 

Mattermost v10.0.0-rc3

![2024-08-30_16-15](https://github.com/user-attachments/assets/4881f913-4ab1-4518-9eea-28da1c8004dd)
![2024-08-30_16-16](https://github.com/user-attachments/assets/6a58e039-5c37-4714-99f5-e3e2ffd89824)

Browser Console:
On every failed upload got console message:
`The connection was refused when attempting to contact wss://mm.domain.com/api/v4/websocket?connection_id=x75rqbbuafbudmbmhbnk5tnuka&sequence_number=18&posted_ack=true.`

Network:
![2024-08-30_16-26](https://github.com/user-attachments/assets/ef22769c-a631-4465-815c-8e3fca84cf87)
No status/ no response headers 

Mattermost Server logs / nginx logs: no new records

#### Additional Information
Maybe regression on latest Mattermost releases. Because 1-2 month ago our users dont report about that problem. Also can say that users have slow/bad internet connection.

**Comment by amyblais** [comment]
@BdServo Are you able to reproduce this on our community server here https://community.mattermost.com/?

**Comment by BdServo** [comment]
@amyblais Working good to me on https://community.mattermost.com/

**Comment by amyblais** [comment]
We haven't reproduced this internally, but I'll merge this together with an existing ticket https://mattermost.atlassian.net/browse/MM-54241 / https://github.com/mattermost/mattermost/issues/24363.
