### ISSUE TITLE
Migration from S3 to Local Storage

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost#28107]
Given the very disturbing and highly upsetting word here:
https://github.com/mattermost/mattermost/issues/27293#issuecomment-2165664293

It is clear that many of us who have been using perfectly amazing and wonderful services such as Wasabi (that are [far more cost effective than even Minio](https://github.com/mattermost/mattermost/issues/27293#issuecomment-2323237985)) will have to reconsider some things with Mattermost.

Please provide us with a guide that will help us to understand how we should migrate our data from S3 to Local Storage properly.

**Comment by agnivade** [comment]
Hello @ylluminate - To migrate from S3 to local storage, you would need to copy over your entire S3 bucket to a local directory, and then change FileSettings.DriverName to `local` and set FileSettings.Directory to that local directory. And then restart Mattermost with those new settings.

Is there anything specific you were looking for?
