### ISSUE TITLE
Failed to construct 'URL' when trying to access "product-switcher-menu"

### ISSUE THREAD

**Issue by SzymonRysztof** [mattermost/mattermost#28117]
#### Summary
Failed to construct 'URL' when trying to access "product-switcher-menu", only white page is being rendered, and console is outputting error. 

#### Steps to reproduce
On our deployment bug is consistent and happens all the time when clicking on "product-switcher-menu" button. 

#### Operating System
Official docker image / Debian 12 host

#### Mattermost Server Version
9.10.0 and 9.11.1

#### Expected behavior
Being able to access "product-switcher-menu"

#### Observed behavior
Error is happening silently. After clicking said button, only white page is being rendered and nothing else. At the same time error log is being sent to Js console 

#### Log Output
```
react-dom.production.min.js:216 TypeError: Failed to construct 'URL': Invalid URL
    at index.tsx:39:41
    at ao (react-dom.production.min.js:157:137)
    at Uo (react-dom.production.min.js:176:260)
    at $u (react-dom.production.min.js:271:400)
    at Ni (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at Ci (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at n.unstable_runWithPriority (scheduler.production.min.js:18:343)
iu @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
pa @ react-dom.production.min.js:131
mu @ react-dom.production.min.js:220
Li @ react-dom.production.min.js:259
n.unstable_runWithPriority @ scheduler.production.min.js:18
Hl @ react-dom.production.min.js:122
zi @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
n.unstable_runWithPriority @ scheduler.production.min.js:18
Hl @ react-dom.production.min.js:122
Kl @ react-dom.production.min.js:123
ql @ react-dom.production.min.js:122
Me @ react-dom.production.min.js:292
Xn @ react-dom.production.min.js:73
Show 16 more frames
Show less
index.js:3404 [Util] handleError::  Uncaught TypeError: Failed to construct 'URL': Invalid URL
com.mattermost.nps_e0f4f7088d82c850_bundle.js:273 [Util] handleError::  Uncaught TypeError: Failed to construct 'URL': Invalid URL
g @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
N @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
(anonymous) @ com.mattermost.nps_e0f4f7088d82c850_bundle.js:273
react-dom.production.min.js:123 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at index.tsx:39:41
    at ao (react-dom.production.min.js:157:137)
    at Uo (react-dom.production.min.js:176:260)
    at $u (react-dom.production.min.js:271:400)
    at Ni (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at Ci (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at n.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

#### Additional Information
It's probably configuration related, because this bug was not happening after initial deployment, only after configuring server, but after checking config.json I can tell, that `SiteURL` is correct (protocol://domain, and I don't know what else may it be. 
Error log points to index.tsx:39, but to my understanding, IF condition from line 38 should never be true, since our domain does not contain `mattermost.com` but I'm not a programmer, and maybe i understand this condition wrong. 

#### Possible fixes
According to logs its index.tsx:39

**Comment by amyblais** [comment]
Hi @SzymonRysztof, are you able to reproduce this on our community server here https://community.mattermost.com/?

**Comment by SzymonRysztof** [comment]
@amyblais 
I cannot reproduce the issue on community mattermost server. 
But i can say, that the issue is browser agnostic. 

I'll try to create a fresh instance of mattermost and reproduce the issue using our specific config.json file.

**Comment by SzymonRysztof** [comment]
@amyblais 
I were able to reproduce this bug using fresh install of mattermost and stripped down config.json file. 
I can grant you access to this instance or I can share `config.json` with you. There are some config values that i'm not comfortable sharing in public (but not sensitive), so we would have to establish another communication channel for me to send it. 
Please, tell me which option works for you.

**Comment by amyblais** [comment]
Feel free to send the instance / config.json via a DM for ``amy.blais`` at https://community.mattermost.com/.

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-60423

**Comment by hmhealey** [comment]
@SzymonRysztof Looking through the code quickly, it seems like this might happen depending on the value of the `NativeAppSettings.AppDownloadLink` in the `config.json`. I haven't managed to make the app crash or show a blank white page when that happens, but the "Download Apps" link in that menu seems like the most likely place in the menu that this could be happening ([code link](https://github.com/mattermost/mattermost/blob/master/webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx#L211))

**Comment by SzymonRysztof** [comment]
@hmhealey 
That's a great catch. 
Indeed, it was excatly this key. 
My client have set this key to `://mattermost.com/pl/download-apps` so they stripped down the protocol part, probably a typo.  

Anyways, I think, that for UX, there should be some validation and exception should be handled properly for this case. 
Especially, that it looks like doing the same for eg. `AndroidAppDownloadLink` does not produce the same output, so i believe its being handled properly

@amyblais

**Comment by amyblais** [comment]
Closing as the issue was resolved,
