### ISSUE TITLE
"Town Square" archived prevents login

### ISSUE THREAD

**Issue by grosjo** [mattermost/mattermost#28179]
#### Summary

When closing/archiving the TownSquare, users can not login anymore ("no teams available") 

#### Steps to reproduce
1 - Archive/Close TownSquare
2 - Create another channel
3 - Try to login -> " No teams available" 

#### Operating System
Archlinux

#### Mattermost Server Version
10.0.0

#### Expected behavior
Users to login as usual

#### Observed behavior
Users have to go the URL of a specific channel to be able to connect, instead of the "/" usual

#### Log Output
N/A

#### Possible fixes
I think it would be helpful to have a flag on any channel to decide to be the "default" channel (the label "TownSquare" being awkward to start with and may not fit many teams), allowing people to login properly as well

Thank you for the good work

**Comment by grosjo** [comment]
@amyblais there is no "new issue". template on the link provided, onle one about security 

Maybe can you verfy ?

**Comment by grosjo** [comment]
I used some other issue topics. Hope this is ok @amyblais

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60573.

**Comment by sbishel** [comment]
@grosjo How were you able to archive "Town Square". That should not be allowed.

**Comment by amyblais** [comment]
@sbishel I was able to reproduce via System Console > Channels (under User Management) > Town Square > Edit > Archive Channel.

**Comment by sbishel** [comment]
> @sbishel I was able to reproduce via System Console > Channels (under User Management) > Town Square > Edit > Archive Channel.

Even after pressing save. After I press "Save" I get an error it isn't archived.  I'll take a closer look at the code.

![Screenshot 2024-09-17 at 5 04 44 PM](https://github.com/user-attachments/assets/ca943e6f-3916-4dee-a231-771d2c16ac8d)

**Comment by amyblais** [comment]
I don't remember if I saw the error but maybe I didn't notice it. After doing the steps above, I got the "No teams available" page when logging in with a test user account.

**Comment by amyblais** [comment]
@sbishel I tested it again and I wasn't able to reproduce it now. I will close the Jira ticket.
