### ISSUE TITLE
Make profile-popover-modal wider

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost#28188]
#### Summary
When you click on a username, a description profile popover modal is displayed. But its not really wide enough to usefully display anything interesting using custom profile badges.

#### Steps to reproduce
+ Click on a Username.
+ Watch as text gets truncated.

#### Operating System
N/A

#### Mattermost Server Version
Mattermost Version: 9.11.1

#### Expected behavior
The modal should be like at least by 100px bigger in width.

#### Observed behavior
The modal is small. See screenshot.
![screen_20240913_182211](https://github.com/user-attachments/assets/9f2cf6c0-8aec-4b94-8686-c5ab8e17f641)

#### Log Output
N/A

#### Additional Information
N/A

#### Possible fixes
Increase the modal width via CSS.

**Comment by amyblais** [comment]
Hi @someone-somenet-org, I wasn't able to reproduce this now. 

<img width="249" alt="Screenshot at Sep 13 13-28-48" src="https://github.com/user-attachments/assets/9aa0d8eb-a8b5-460f-b107-68c7be3794c7">



Do you have more details for reproducing? Are you able to reproduce this on https://community.mattermost.com/?
