### ISSUE TITLE
[API] error 400 when adding multiple user_ids to channel

### ISSUE THREAD

**Issue by mrvnklm** [mattermost/mattermost#28210]
#### Summary
`channels/channel_id/members` results in 400 when setting `user_ids` instead of `user_id`

#### Steps to reproduce
call api and add multiple users to a channel

#### Operating System
microk8s amd64, mattermost helm chart

#### Mattermost Server Version
chart: mattermost-team-edition-6.6.62
mattermost: 9.9.1

#### Expected behavior
add multiple users at once

#### Observed behavior
api error missing `user_id` param

#### Log Output
```
Mattermost API Error: {"id":"api.context.invalid_body_param.app_error","message":"Invalid or missing user_id in request body.","detailed_error":"","request_id":"etc9mib7zjrp7xxkxcgnr5morr","status_code":400}
```

**Comment by neehhaa06** [comment]
Hello @mrvnklm 

fix: #28210

``
To fix this bug, modify your code to add users one at a time, as the Mattermost API does not support adding multiple `user_ids` in a single request. Loop through the `user_ids` array and send individual API requests for each user. For example, using Axios in JavaScript, iterate through each `user_id` and make separate `POST` requests to add them to the channel. This will prevent the `400` error by complying with the API's requirements.
``

**Comment by mrvnklm** [comment]
@neehhaa06 Thank you for your response, this is indeed what I am currently doing.
Though this is still a workaround and the bug which is reflected in the official API reference still exists and should be fixed at some point.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60734.
