### ISSUE TITLE
Support for S3 storage classes (Pull Request)

### ISSUE THREAD

**Issue by NadavTasher** [mattermost/mattermost#28318]
#### Summary
Passing the storage class parameter to S3 is not supported.

#### Mattermost Server Version
Mattermost Free 10.0.0

#### Expected behavior
Be able to pass the storage class parameter (header is `X-Amz-Storage-Class`)

#### Possible fixes
I have created a PR that adds support for this feature, which basically just passes this parameter from the configuration to `minio-go`'s API.

**Comment by NadavTasher** [comment]
Created a PR: https://github.com/mattermost/mattermost/pull/28319

**Comment by NadavTasher** [comment]
I have opened a pull-request that introduces this feature: https://github.com/mattermost/mattermost/pull/28319

**Comment by NadavTasher** [comment]
@amyblais When will a version containing this feature be released?

**Comment by amyblais** [comment]
> When will a version containing this feature be released?

v10.4 is scheduled for January 16th.

**Comment by NadavTasher** [comment]
Why can't make it in time for v10.3?

**Comment by agnivade** [comment]
Because our release cadence is defined that way: 
- https://handbook.mattermost.com/operations/research-and-development/product/release-process/feature-release
- https://handbook.mattermost.com/operations/research-and-development/product/release-process/release-overview
