### ISSUE TITLE
ERROR: missing destination name mfausedtimestamps in *[]*model.UserReportQuery"

### ISSUE THREAD

**Issue by noone-silent** [mattermost/mattermost#28344]
#### Summary
After upgrade from v9.6.1 (mysql) to v10.0.0 (postgre) we are unable to list users.

`error [2024-09-28 09:49:04.747 +02:00] Failed to fetch user report. caller="web/context.go:124" path=/api/v4/reports/users request_id=XXX ip_addr=XXX user_id=XXX method=GET err_where=GetUsersForReporting http_code=500 error="GetUsersForReporting: Failed to fetch user report., failed to get users for reporting: missing destination name mfausedtimestamps in *[]*model.UserReportQuery"`

#### Steps to reproduce
System Console > Users

#### Operating System
Debian Bookworm

#### Mattermost Server Version
v10.0.0

#### Expected behavior
List users.

#### Observed behavior
Doesn't list users.

#### Log Output
`error [2024-09-28 09:49:04.747 +02:00] Failed to fetch user report. caller="web/context.go:124" path=/api/v4/reports/users request_id=XXX ip_addr=XXX user_id=XXX method=GET err_where=GetUsersForReporting http_code=500 error="GetUsersForReporting: Failed to fetch user report., failed to get users for reporting: missing destination name mfausedtimestamps in *[]*model.UserReportQuery"`

#### Additional Information
`users.mfausedtimestamps` column exists in postgre and is null for all.

#### Possible fixes
NA

**Comment by amyblais** [comment]
@noone-silent For troubleshooting assistance, I'd recommend posting this issue either at https://community.mattermost.com/core/channels/peer-to-peer-help or at https://forum.mattermost.com/.

**Comment by ChristianSchindler** [comment]
I have the same problem after the update from v9.6.1 (postgres) to v10.0.0 (postgres) did you found a solution

**Comment by seoch-web** [comment]
I'm having the same issue since the v10 upgrade. When will the resolved version come out in the future?

**Comment by lidoma** [comment]
I can confirm the error was resolved by upgrading to the v10.1.1 version.

**Comment by seoch-web** [comment]
Thanks you. So much.

2024년 10월 7일 (월) 오후 5:13, M. Davaee ***@***.***>님이 작성:
