### ISSUE TITLE
Upgrade to 10.1.0 cause user show unknown status

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost#28432]
Mattermost Server 10.1.0 Team Edition Web App

After upgrading, some users listed in my direct message sidebar shows some status like `shared with trusted organizations`. Checked database `status` table, I found nothing related to it.

![2024-10-03-Rzpmpm5p001034](https://github.com/user-attachments/assets/e599d31d-2eae-4097-8530-23fd35135bd5)

If I downgrade to 10.0.0, the icon and text disappeared.

My questions:

- Where does this come from, it seems not in the 10.1 changelog.
- How to disable it?

**Comment by amyblais** [comment]
To be scheduled for v10.1.1 dot release.
