### ISSUE TITLE
Bug when you press page up or page down

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost#28436]
#### Summary
Bug when you press page up or page down

#### Steps to reproduce
If you write a long message in the message entry, as a result of which a scroll appears in the message entry window.
And at the same time the right panel of the track is open. If you press page up or page down, the mattermost will move to the left

#### Operating System
Windows 10 x64, Ubuntu Linux 22.04 LTS x64

#### Mattermost Server Version
Mattermost Version: 9.11.1
Database Schema Version: 124
Build Number: 10419911144

#### Additional Information
![image (1)](https://github.com/user-attachments/assets/599bfa96-49e0-4458-8197-ec18292eef67)

#### Possible fixes
Press the keyboard shortcut ctrl + r

**Comment by amyblais** [comment]
@KakEgorka Are you able to reproduce this on our community server here https://community.mattermost.com/?

I wasn't able to reproduce this just now on macOS.

**Comment by KakEgorka** [comment]
> @KakEgorka Are you able to reproduce this on our community server here https://community.mattermost.com/?
> 
> 
> 
> I wasn't able to reproduce this just now on macOS.

Uh, I'm sorry. Didn't write that it's only on Windows. Tested on Windows 11.

The main thing is that a large text should be written in the message input field and the thread should be open. Then it will have this effect when you press the buttons. 

Everything is fine on macOS. Linux has not been tested.

**Comment by amyblais** [comment]
Thank you, did you also reproduce it at https://community.mattermost.com/?

**Comment by KakEgorka** [comment]
> https://community.mattermost.com/

Yes [on your site](https://community.mattermost.com/) this problem is recurring too. 
![image (9)](https://github.com/user-attachments/assets/e70f1868-1bb1-465f-921a-4c60a32c85a4)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60878.

**Comment by Ravijhabit** [comment]
Hi @amyblais, Can you assign me this issue ?

**Comment by lorumic** [comment]
Hi there :wave: 
I just sent a PR to fix this: #29272
