### ISSUE TITLE
Add Hover Effect to Icons in Organizations Section

### ISSUE THREAD

**Issue by jenyyy4** [mattermost/mattermost#28605]
### Issue: Add Hover Effect to Icons in Organizations Section

**Description:**
The icons in the "Organizations" section need a hover effect to improve the interactivity and visual appeal of the section. Adding this effect will make the section more engaging and align it with the overall design style of the site.

**Comment by jenyyy4** [comment]
@lieut-data i would like to work on this issue, please assign it to me.

**Comment by keerthi5465** [comment]
I want to work on this issue plz assign me

**Comment by lieut-data** [comment]
Hi @jenyyy4! Thanks for filing this suggested improvement. At this time, we are not looking to adopt the styling you propose, but feel free to join our https://community.mattermost.com/ and promote your ideas with the team :)
