### ISSUE TITLE
Files filter dropdown menu is not internationalized

### ISSUE THREAD

**Issue by 2017Yasu** [mattermost/mattermost#28648]
#### Summary
Files filter dropdown menu is not internationalized.

#### Steps to reproduce
1. Change display language other than English.
2. View channel information.
3. Open "Files" in the right hand side bar.
4. Click filter button.

#### Operating System
Windows 11 x64
With Microsoft Edge (version: 129.0.2792.79)

#### Mattermost Server Version
10.2.0

#### Expected behavior
Dropdown menu items are translated into selected language.

#### Observed behavior
Items are in English.

#### Log Output
N/A

#### Additional Information
![スクリーンショット 2024-10-09 102408](https://github.com/user-attachments/assets/d1718464-daff-4ff0-bd42-423a30e400b2)

#### Possible fixes
In `webapp/channels/src/components/search_results/files_filter_menu.tsx`, the menu item texts are hard coded, so they should be defined with `formatMessage` method of `Intl` instance just like below:

```typescript
export default function FilesFilterMenu(props: Props): JSX.Element {
    const {formatMessage} = useIntl();
    const words = useMemo<{[k in SearchFilterType]: string}>(() => ({
        all: formatMessage({
            id: 'some.key.all',
            defaultMessage: 'All file types',
        }),
        ...
    }), [formatMessage]);

    return (
        <div className='FilesFilterMenu'>
            <MenuWrapper>
                ...

                <Menu
                    ariaLabel={'file menu'}
                    openLeft={true}
                >
                    <Menu.ItemAction
                        ariaLabel={words.all}
                        text={words.all}
                        onClick={() => props.onFilter('all')}
                        icon={props.selectedFilter === 'all' ? <i className='icon icon-check'/> : null}
                    />
                    ...
```

**Comment by sahariardev** [comment]
hi @amyblais
I would like to work on this issue
