### ISSUE TITLE
Users lost in system console after upgrading to Mattermost 10.0.0

### ISSUE THREAD

**Issue by igmarketing** [mattermost/mattermost#28666]
#### Summary
The system console is not showing my users anymore after upgrading from 9.11 to 10.0

#### Steps to reproduce
Upgrading Mattermost from 9.11 to 10.0

#### Operating System
Ubuntu Linux 22.04 LTS x64, Cloudron

#### Mattermost Server Version
Team Edition, Version 10.0.0

#### Expected behavior
Keeping my users

#### Observed behavior
I can invite new users and everything seem to work fine... but my users aren't able to update their profile anymore, it returns the message "We encountered an error finding the account". I checked in the System console and the user's tab is empty. It shows no users.

#### Log Output
{
  "caller": "web/context.go:124",
  "err_where": "UpdateUser",
  "error": "UpdateUser: We encountered an error finding the account., failed to get User with userId=a7uip8ymrjdn3edynpg68wmaee: missing destination name mfausedtimestamps in *model.User",
  "http_code": 500,
  "ip_addr": "**********",
  "level": "error",
  "method": "PUT",
  "msg": "We encountered an error finding the account.",
  "path": "/api/v4/users/me/patch",
  "request_id": "hfc7nzz6ffnadk8bz8xb8z3nsr",
  "timestamp": "2024-10-09 13:07:42.635 Z",
  "user_id": "a7uip8ymrjdn3edynpg68wmaee"
}
{
  "caller": "web/context.go:124",
  "err_where": "GetUsersForReporting",
  "error": "GetUsersForReporting: Failed to fetch user report., failed to get users for reporting: missing destination name mfausedtimestamps in *[]*model.UserReportQuery",
  "http_code": 500,
  "ip_addr": "********",
  "level": "error",
  "method": "GET",
  "msg": "Failed to fetch user report.",
  "path": "/api/v4/reports/users",
  "request_id": "h9tjdth7jbdbxemi4o66gdqa8a",
  "timestamp": "2024-10-09 14:26:17.922 Z",
  "user_id": "gsut3z5izjgctp1bhy5kuj84gr"
}
{
  "caller": "app/plugin_api.go:1011",
  "level": "error",
  "msg": "failed to get all active calls: failed to get calls: sql: database is closed",
  "origin": "main.(*Plugin).OnDeactivate activate.go:232",
  "plugin_id": "com.mattermost.calls",
  "timestamp": "2024-10-09 14:27:18.497 Z"
}
{
  "caller": "app/plugin_api.go:1011",
  "level": "error",
  "msg": "Not activating plugin because diagnostics are disabled",
  "plugin_id": "com.mattermost.nps",
  "timestamp": "2024-10-09 14:27:34.809 Z"
}
{
  "bundle_path": "/app/code/team/prepackaged_plugins/mattermost-plugin-nps-v1.3.3-linux-amd64.tar.gz",
  "caller": "app/plugin.go:939",
  "error": "Failed to install extracted prepackaged plugin /app/code/team/prepackaged_plugins/mattermost-plugin-nps-v1.3.3-linux-amd64.tar.gz: installExtractedPlugin: Unable to restart plugin on upgrade., Not activating plugin because diagnostics are disabled",
  "level": "error",
  "msg": "Failed to install prepackaged plugin",
  "timestamp": "2024-10-09 14:27:34.928 Z"
}

#### Additional Information
![mattermost_logs1](https://github.com/user-attachments/assets/6fe48a8a-c31c-4b25-92bd-4aa356fa68e0)
![mattermost_users](https://github.com/user-attachments/assets/18b41a73-d2d1-4388-934c-87d13ca753a4)
![mattermost_logs2](https://github.com/user-attachments/assets/fbec149e-9414-44b3-a672-90d46c9db6a2)

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-60966.

**Comment by Neptoos** [comment]
Having the same issue. Upgraded from 9.11.3 to 10.0.1.

**Comment by Grienauer** [comment]
we have the same issue.

**Comment by Grienauer** [comment]
updating to 10.1.1. fixed the issue for us!
