### ISSUE TITLE
Giphy API start being chargeable

### ISSUE THREAD

**Issue by L3o-pold** [mattermost/mattermost#28837]
Giphy was bought by Shutterstock and start calling their "customer" to charge their API (12k a year).

Is there any plan to move to an other provider?

**Comment by RS-labhub** [comment]
What about Tenor?

**Comment by RS-labhub** [comment]
It's good and free. Tenor has more options than Giphy 😉

**Comment by amyblais** [comment]
Mattermost customers will continue to have Giphy support as before.
Also, we're not planning to move to another provider at this time.

**Comment by L3o-pold** [comment]
That is not what Giphy told me over phone and email.
