### ISSUE TITLE
Uploads over 1mb? no longer work after upgrading to latest version 10.1.1

### ISSUE THREAD

**Issue by rivendellstuff** [mattermost/mattermost#28845]
#### Summary
Uploads over 1mb? no longer work after upgrading to latest version 10.1.1

#### Steps to reproduce
Drag a file over. I tried a 1.6mb file... and same error. Prior I could upload up to my limit which is 10gb. but generally are under 1gb. Point being there was no issue before.

#### Operating System
Windows 10 x64 Mattermost client 5.9.0

#### Mattermost Server Version
**DOCKER**
Mattermost Version: 10.1.1
Database Schema Version: 127
Build Number: 11162711545
Database: postgres

#### Expected behavior
File uploads fine. I've uploaded 6gb files before

#### Observed behavior
File does not upload. If its under 1MB it seems to work. Anything higher doesnt.

#### Log Output
In the client I just get: There was a problem uploading your files.

I have an automated script that uploads files to specific channels based on where they're saved. This worked forever and is now broken (which is how I discovered the issue). My python script is outputting this error:

```
Processing file: /mnt/sulling/scratch/tmp/vids/test/testVid.mp4
Uploading:  40%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                     | 786k/1.99M [00:00<00:00, 7.48Mbytes/s]
Failed to upload testVid.mp4. Status code: 413
Response content: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.27.2</center>
</body>
</html>

```

![image](https://github.com/user-attachments/assets/541bf3e4-17e5-4390-9bb7-72be17bc1498)

**Comment by amyblais** [comment]
@rivendellstuff I wasn't able to reproduce this just now. Are you able to reproduce this on our community server https://community.mattermost.com/?

**Comment by rivendellstuff** [comment]
> @rivendellstuff I wasn't able to reproduce this just now. Are you able to reproduce this on our community server https://community.mattermost.com/?

Hey, I tested it there and it seems to work.

This is 100% from the upgrade tho. Everything worked fine for 2 years and immediately hit this right after the upgrade. 
Is it possible to roll back to the latest 9.x version are there breaking changes?

I did notice the community server is 
Mattermost Version: 10.2.0

while mine is
Mattermost Version: 10.1.1

**Comment by rivendellstuff** [comment]
also seeing this for ppl that dont have profile pictures set:

![image](https://github.com/user-attachments/assets/2c7079b9-7140-436e-a706-99362ecbd4f9)

**Comment by rivendellstuff** [comment]
an update. 

It appears to be any mp4 files and any image files. But I can upload a 2gig .iso file. 

Not sure why yet.

**Comment by rivendellstuff** [comment]
Update 2: 

Looks like I was wrong. It wasnt Mattermost update specific, I'm seeing a new CORS error in my reverse proxy. I copied everything to a different docker server and the issue is NOT present there on version 10.1.1.

Hopefully you didnt waste much time, but I really appreciate you checking it out. 
Thank you!
