### ISSUE TITLE
The scroll function for messages in the Drafts section has stopped working after upgrading from 9.10.0 to 9.11.3

### ISSUE THREAD

**Issue by ixpict** [mattermost/mattermost#28875]
#### Summary
The scroll function for messages in the Drafts section has stopped working.

#### Steps to reproduce
1. Create several different drafts; 5-6 should be enough.
2. Adjust the vertical size of your browser or Mattermost client window so that the drafts don't fully display in the window.
3. Done. Accessing older drafts is impossible because the scroll function doesn't work.

#### Operating System
Windows 11 x64, macOS Ventura 15.0.1 Apple Silicon

#### Mattermost Server Version
9.11.3

#### Expected behavior
It was expected that if the list of drafts doesn't fit in the window, a scroll bar would appear.

#### Additional Information
We noticed this issue after upgrading from 9.10.0 to 9.11.3.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-60539.
