### ISSUE TITLE
API GetChannels: what is total_msg_count_root?

### ISSUE THREAD

**Issue by iva-5-middleware** [mattermost/mattermost#28889]
Hey there,

I was looking for a way to get the total message count of a channel. In the API docs I found GetChannel ( https://api.mattermost.com/#tag/channels/operation/GetChannel ) with the parameter `total_msg_count`. But the api endpoint returns `total_msg_count` *and* `total_msg_count_root`. What is the difference? I couldn't find any explanation at all, could this please be better documented?

In this repo I only found the following explanation:

- `total_msg_count`: the total number of posts in this channel, not including join/leave messages
- `total_msg_count_root`: the number of root posts in this channel, not including join/leave messages

What are root posts?

**Comment by amyblais** [comment]
@iva-5-middleware Root post is the first post in a thread.

**Comment by iva-5-middleware** [comment]
Thanks for the clarification, I'll close this issue
