### ISSUE TITLE
FCC Amateur Radio Call Signs in Uppercase allowed in Usernames, as well as unicode u00d8 Ø symbol. 

### ISSUE THREAD

**Issue by gnuamua** [mattermost/mattermost#29014]
#### Summary
Uppercase Letters and Unicode u00d8 Ø symbol in usermames for FCC Amatuer Radio Call Signs.
Make a check for 5 letters long, and not allow uppercase usernames longer than 5 letters & numbers.

#### Steps to reproduce
Create username in Mattermost

#### Operating System
All Operating Systems

#### Mattermost Server Version
All current Versions of Mattermost

#### Expected behavior
Use of Uppercase letters in Username including unicode u00d8 Ø Symbol

#### Observed behavior
Forced lowercase username

#### Log Output
Not Applicable

#### Additional Information
N/A

#### Possible fixes
I expect changes to code where the function is used to force input  to lowercase, as well as possible changes to database behavior.

Create a mechanism to check for uppercase username 5 letters or numbers long, and not allow more than 5 characters.

Only allow FCC Call Signs Uppercase in Usernames for instance: KFØUFO , check for 5 Uppercase letters & numbers,  and not allow Uppercase Usernames any longer than 5 letters. Include the capability for the unicode symbol u00d8 Ø in usernames.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @gnuamua,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by gnuamua** [comment]
Thank you, and Done.
[uservoice](https://mattermost.uservoice.com/forums/306457-general/suggestions/40706974-add-option-to-show-nickname-or-username-never-rea)

[Mattermost Discussion](https://community.mattermost.com/core/pl/ts1dqxa48tbybrjopmk9w7nsxo)

**Comment by gnuamua** [comment]
Why is uservoice used by Mattermost if it's not actually monitored or moderated or really "used" at all? It seems everything posted on uservoice is worthless...  ??!
