### ISSUE TITLE
Setting a custom status to clear after "Today" doesnt actually clear the status until tomorrow at 8am.

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/mattermost#29041]
#### Summary
Since v9.11, setting a custom status with an expiration set to "Clear After [Today]", the status doesnt actually clear until _tomorrrow_ at 8am (which, isn't semantically accurate).

#### Steps to reproduce
1. Create a custom status
2. Set the expiration to clear after "Today"
3. Visibly confirm that the status will not clear until 8am on the following day (tomorrow).

#### Operating System
N/A

#### Mattermost Server Version
Currently on v10.1.1; however it appears that [PR-XXXX](https://github.com/mattermost/mattermost/pull/27353) introduced this issue starting in version 9.11.

#### Expected behavior
When selecting to clear a custom status after today, I would expect the status to clear at midnight.

#### Observed behavior
Users login the following morning and arent aware that they still have a custom status showing. Other users may read the status from the previous day and get confused.

**Comment by Gesare5** [comment]
LOL! @shieldsjared that was my PR, my bad, I can fix that.
