### ISSUE TITLE
Scrollbar not clickable when there is a toaster

### ISSUE THREAD

**Issue by Aryakoste** [mattermost/mattermost#29069]
#### Summary
Scrollbar not clickable. Not big of an issue as we can scroll through other means or close the toaster but still kind of a bug.

#### Steps to reproduce
Scroll up in a channel until toaster arrives specifically of jump recents and try ctrl + shift + F to search the channel. 

#### Operating System
Windows 11

#### Mattermost Server Version
10.3.0

#### Expected behavior
Scrollbar should be clikable at all times. 

#### Observed behavior
Scrollbar not clickable

#### Possible fixes
The toaster is overlapping the scrollbar which is causing this behaviour. If we can adjust the width of the toaster to avoid scrollbar i think we can fix this. 

#### Video
https://github.com/user-attachments/assets/c93dcad4-6f5a-47d1-8728-170a8288866e

**Comment by lorumic** [comment]
Hello :wave: 
I created a PR to fix this: #29251
