### ISSUE TITLE
Emoji too small in Emoji picker in Firefox 133

### ISSUE THREAD

**Issue by lucaswerkmeister** [mattermost/mattermost#29114]
#### Summary
In Firefox 133 (currently Firefox Developer Edition, but I suspect the issue will also happen in the main Firefox version one release later), emoji in the emoji picker are far too small.

#### Steps to reproduce
* Install Firefox Developer Edition (Nightly might also work)
* Open Mattermost in the browser
* Open the emoji selector

#### Operating System
Arch Linux

#### Mattermost Server Version
9.11.1 (Build Number: 10419911144)

#### Expected behavior
The emoji should have a reasonable size, as they do on Firefox 132 (current main version):
![image](https://github.com/user-attachments/assets/ae8bec7d-0727-4880-9e8f-1903bcf86304)

#### Observed behavior
They are tiny.
![image](https://github.com/user-attachments/assets/c0295d05-d0fe-4aeb-aa3c-8beb33ac1b42)

#### Log Output
N/A

#### Additional Information
This seems to be due to some different interpretation of CSS. In Firefox 132, the CSS is shown like this:
![image](https://github.com/user-attachments/assets/54f5a838-4494-4962-bc58-799bb25fd7b6)
The `-moz-transform: scale(0.35)` is apparently ignored, so only the `zoom` has an effect. By contrast, in Firefox 133 it looks like this:
![image](https://github.com/user-attachments/assets/178914aa-748d-463b-980b-058ef2205f82)
Presumably, the `-moz-transform: scale(0.35)` now stacks with the `zoom: .35`, so the emoji are scaled down twice.

(These styles are for non-selected emoji; selected ones have slightly different styles, but I think the issue is similar.)

#### Possible fixes
Remove the `-moz-transform` from [_emojisprite.scss](https://github.com/mattermost/mattermost/blob/bfffc2383f315a38ea6adcd51f3c90b1ce0b486a/webapp/channels/src/sass/components/_emojisprite.scss#L23)? But probably use `git blame` to [find out why it’s there](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence) first :)

Arguably, this could be considered a Firefox issue, but I think it’s more likely Mattermost’s responsibility to use the `-moz-*` property correctly.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-61527.

**Comment by lorumic** [comment]
Hello :wave: 
Here is a PR which should fix this: #29276

**Comment by stmichaelis** [comment]
Firefox 133 is live now in the stable channel. Can confirm this bug on Windows.

**Comment by madrisan** [comment]
Same issue on Linux Fedora 41 and Mattermost 9.11.0 (Build Number: 10163357270)

**Comment by ThiefMaster** [comment]
Yeah, unfortunately 9.11.6 also does not contain this fix - but luckily it's a single commit so at least when building mattermost yourself it's trivial to cherry-pick :)

**Comment by AlexHaan-i** [comment]
For anyone that can't wait. This userscript (fill in your domain!) will also resolve this:
```js
// ==UserScript==
// @name         Mattermost: fix emoticon size
// @version      0.1
// @match        https://[domain]/*
// @grant        none
// ==/UserScript==

(function() {
	'use strict';
	const style = document.createElement('style');
	style.textContent = `
		.emojisprite {
			-moz-transform: none !important;
		}
	`;
	document.body.append(style);
})();
```

**Comment by VincentSC** [comment]
> Yeah, unfortunately 9.11.6 also does not contain this fix - but luckily it's a single commit so at least when building mattermost yourself it's trivial to cherry-pick :)

As this is a hotfix for a bug, I'm not following why this has not been included yet. Could it be that it's being forgotten? Just as they are forgetting to test on Firefox?

**Comment by Pyroluk** [comment]
Mattermost 10.3.1, Firefox 134.0. And this is still broken.
Please remeber to include the fix in the next release.

**Comment by stmichaelis** [comment]
Mattermost 9.11.7, still same effect.

**Comment by fleaz** [comment]
Can confirm it's fixed in the current ESR (9.11.8) :)

**Comment by Ralfeins** [comment]
With Mattermost 10.1.1 on Firefox for Linux 137.0 (64-bit) the problem still exists.

**Comment by ThiefMaster** [comment]
That's an outdated and non-LTS version.... so no surprise IMHO, considering that support for 10.1 ended on 2025-01-15.
