### ISSUE TITLE
Group names' Default background colour is lost after refresh

### ISSUE THREAD

**Issue by aberenyi** [mattermost/mattermost#29162]
#### Summary
Group names' Default background colour is lost after refresh - causes issues when using dark (Indigo, Onyx) themes.

#### Steps to reproduce
1. Select a dark theme (Indigo, Onyx).
2. Navigate to Boards - everything looks okay, the Default color is a darker grey.
3. Refresh (⌘+R) Mattermost
4. Groups (except for the `No Status` Group) now have a white-_ish_ Default background

#### Operating System
macOS Sequoia 15.1 (24B83)

#### Mattermost Server Version
`10.1.1`

#### Expected behavior
The Default colour should stay the same after refresh/reload/etc.

#### Observed behavior
Group names' Default background colour is resetted to a white-_ish_ colour.

#### Log Output
N/A

#### Additional Information
Step 2
![Step 2](https://github.com/user-attachments/assets/6781d5c0-f47d-444f-8784-e62ec6fcde2a)
Step 4
![Step 4](https://github.com/user-attachments/assets/ba658b8b-88e5-4e0d-bb80-d2fcbdd01df1)

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Hi @aberenyi, would you be open to recreating this issue in the Boards repo here https://github.com/mattermost/mattermost-plugin-boards/issues?

**Comment by aberenyi** [comment]
sure thing
https://github.com/mattermost/mattermost-plugin-boards/issues/31
