### ISSUE TITLE
Session hijacking using mmauthtoken

### ISSUE THREAD

**Issue by tjdalsry** [mattermost/mattermost#29244]
#### Summary
Developer tools → Application → Cookies → Copy the mmauthtoken and change the token in another account developer tool to log in.

#### Steps to reproduce
For example

AAA account Cookies Session mmauthtoken abcdef21221feeee

attacker

Server Developer tools → Application → Cookies → mmauthtoken

change abcdef21221feeee

login success

#### Operating System

Windows 10

#### Mattermost Server Version
Mattermost Server 9.5.1

Session hijacking becomes very easy if you only know the session token. Is there a way to fix it?

**Comment by amyblais** [comment]
Hi @tjdalsry, please report this via the process here https://mattermost.com/security-vulnerability-report/.
