### ISSUE TITLE
Do not change case of input strings in the input field (form)

### ISSUE THREAD

**Issue by tnir** [mattermost/mattermost#29362]
#### Summary

Do not change case of input strings in the input field (form).

#### Steps to reproduce

1. Create a message in a channel.
2. Click the [emoji reaction](https://docs.mattermost.com/collaborate/react-with-emojis-gifs.html) icon to open the input field with selected emojis.
3. Input `ZZZ` (in upper case) in the input field to filter emojis and will find "zzz" in the input field (in lower case).

![zzz](https://github.com/user-attachments/assets/66c28369-d433-4045-b31e-07b89c5f195b)

(Check out the case of `zzz` in the input box while they input `ZZZ` from the keyboard.)

#### Operating System

macOS 15 and 15.1.

#### Mattermost Server Version

Mattermost 10.1 (Team)

#### Expected behavior

The user should see "ZZZ" in the field (i.e., without any case conversion) and find the emoji `:zzz:` (lowercase).

#### Observed behavior

The user see "zzz" in the field with case conversion but still find the emoji `:zzz:` (lowercase).

#### Log Output

n/a

#### Additional Information

Unusual behavior like this can cause the error in non-western input such as [Japanese input](https://www.google.co.jp/ime/) etc.

#### Possible fixes

The frontend code should not change "zzz" (as value) in the `input` form field.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-61946.

**Comment by Kuruyia** [comment]
Hi, I'd like to try fixing this issue if it's available for the community :)
@amyblais
