### ISSUE TITLE
attach a draw has no effect

### ISSUE THREAD

**Issue by kaddkaka** [mattermost/mattermost#29430]
#### Summary
The draw button under the attach button ahs no effect.

#### Steps to reproduce
Click the attach button, then click "Draw"

#### Operating System
Ubuntu 24.04

#### Mattermost Server Version
9.8.0

#### Expected behavior
Something to happen, draw tool opening or a message explaining why nothing happens

#### Observed behavior
Nothing happens

#### Log Output
Where can I find those?

#### Possible fixes
What is the intention of draw feature?  Should It launch a drawing program on my computer or a builtin drawtool?

**Comment by amyblais** [comment]
Hi @kaddkaka, would you be open to re-creating this issue in the Draw plugin repository here https://github.com/jespino/mattermost-plugin-draw/issues?

**Comment by kaddkaka** [comment]
> Hi @kaddkaka, would you be open to re-creating this issue in the Draw plugin repository here https://github.com/jespino/mattermost-plugin-draw/issues?

Sure, created it here https://github.com/jespino/mattermost-plugin-draw 

Do you have knowledge to answer my questions and why this issue should go under that plugin rather than here?

**Comment by amyblais** [comment]
> Sure, created it here https://github.com/jespino/mattermost-plugin-draw
> 
> Do you have knowledge to answer my questions and why this issue should go under that plugin rather than here?

Thank you! You can find details on the Draw plugin in the repository where you opened the issue: https://github.com/jespino/mattermost-plugin-draw/blob/master/README.md.

**Comment by kaddkaka** [comment]
Thank you, is this completely related to draw plugin? 

What I mean is: is it the draw plugin that causes that draw button to appear?
