### ISSUE TITLE
PageUp button causes interface shift with open discussions

### ISSUE THREAD

**Issue by Reydan46** [mattermost/mattermost#29493]
#### Summary
While in an open channel/direct message, if the discussion block is open and text is present in the input field, pressing the PageUp button shifts the interface to the left.

#### Steps to Reproduce
1. Open a channel.
2. Open a discussion by clicking on any message.
3. Enter text in the message input field.
4. Press the PageUp button (the interface shifts to the left), then press the PageDown button (the interface shifts to the right).

#### Operating System
Windows 10 x64

#### Mattermost Server Version
10.2.0

#### Expected Behavior
The cursor moves to the beginning (the interface remains in place).

#### Observed Behavior
The interface shifts.

#### Log Output
\-

#### Additional Information
The issue occurs both in the web version and the desktop client.

Before press PageUp
![1](https://github.com/user-attachments/assets/cc80ac8a-deb4-4845-be97-14eaba258d22)
After press PageUp
![2](https://github.com/user-attachments/assets/386e537c-54b1-4662-af3d-bb9496a723c4)

#### Possible Fixes
\-

**Comment by amyblais** [comment]
Hi @Reydan46, are you able to reproduce this on our community server here https://community.mattermost.com/?

**Comment by Reydan46** [comment]
@amyblais Reproduced, but not so globally. On community.mattermost.com, there is a shift of a couple of pixels to the left.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-62080

**Comment by hmhealey** [comment]
Thanks for the report! This is likely the same issue as https://github.com/mattermost/mattermost/issues/28436 which should be resolved in 10.4.0 when that comes out in January. Feel free to reopen this if it comes up again after that
