### ISSUE TITLE
Error encountered while configuring self-hosted Apple Push Notification server on Ubuntu 22.04

### ISSUE THREAD

**Issue by ducconit** [mattermost/mattermost#29511]
#### Summary
Error encountered while configuring self-hosted Apple Push Notification server on Ubuntu 22.04. I would appreciate any guidance or suggestions on resolving this issue. Thank you in advance for your help, and I look forward to your response.

#### Steps to reproduce
1. Exported `Certificates.p12` from Apple Developer account.
2. Ran the following command to extract the private key:
   ```bash
   openssl pkcs12 -in Certificates.p12 -out aps_production_priv.pem -nodes -clcerts -passin pass:password -legacy -rc2
   ```
3. Attempted to test the connection with Apple Push Notification gateway:
   ```bash
   openssl s_client -connect gateway.push.apple.com:2195 -cert aps_production.pem -key aps_production_priv.pem
   ```
4. Received the following error:
   ```
   Could not read client certificate private key from aps_production_priv.pem
   4007000B567F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
   4007000B567F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-CBC : 4), Properties ()
   ```

#### Operating System
Ubuntu 22.04 LTS x64 (AMD64 architecture).

#### Expected behavior
Successfully establish a connection to `gateway.push.apple.com:2195` using the generated PEM files.

#### Observed behavior
The connection fails with errors indicating an unsupported algorithm (`RC2-CBC`) or issue with the private key extraction.

#### Log Output
```
4007000B567F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
4007000B567F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-CBC : 4), Properties ()
```

#### Additional Information
- Commands were executed on a fresh Ubuntu 22.04 installation.
- OpenSSL version:
  ```bash
  openssl version
  ```
  Output: `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)`

#### Possible fixes
- Ensure compatibility of the private key extraction command with OpenSSL 3.0.x.
- Check if RC2 algorithm is required or if there is a workaround for generating certificates without RC2 encryption.
- Verify if a different OpenSSL configuration or legacy version resolves the issue.

**Comment by amyblais** [comment]
@ducconit, for troubleshooting assistance, feel free to post this issue at https://forum.mattermost.com/.

**Comment by ducconit** [comment]
I did it on mac and it no longer reported the error when removing the -rc2 option
