### ISSUE TITLE
use WARN log level when ws can't report hostname

### ISSUE THREAD

**Issue by davidkrauser** [mattermost/mattermost#29522]
#### Summary
As reported by @agnivade in pull #29413, we should log a warning (not an error) when we can't report the hostname in the websocket HELLO message:

https://github.com/mattermost/mattermost/pull/29413#discussion_r1875421503

Additionally, we should include the `user_id` and `connection_id` in the log event.

**Comment by amyblais** [comment]
Re-reated this as a Jira ticket: https://mattermost.atlassian.net/browse/MM-62105.
