### ISSUE TITLE
[Help Wanted] [MM-11279] Migrate components/access_history_modal/access_history_modal.jsx to Redux and PureComponent

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost#9089]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11279)

If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`/access_history_modal/access_history_modal.jsx`](https://github.com/mattermost/mattermost-webapp/tree/master/components/access_history_modal/access_history_modal.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://docs.mattermost.com/developer/webapp-component.html#testing-your-component). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by R-Wang97** [comment]
I can take a look at this.
