### ISSUE TITLE
[Help Wanted] [MM-12465] [Bulk Export] Include reactions to posts in the Bulk Export

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost#9545]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12465)

This ticket forms part of the Bulk Export campaign. The bulk export feature (implementation in `app/export.go` and `app/export_converters.go` is intended to provide a CLI-based means to export the data in a Mattermost instance to a JSONL file. It is the inverse of the much more well developed Bulk Import feature, so a data file exported from the Bulk Export feature should be importable with the Bulk Import feature.

Currently the bulk export feature does not export the reactions on posts. This ticket is to include them there. See `app/import_functions.go` and the function `ImportReaction` for how the import-side of the process works, and the struct `ReactionImportData` in `app/import_types.go` for the struct that will be used for the export/import.

**Comment by waseem18** [comment]
I would like to take up this issue.

**Comment by esethna** [comment]
Thanks @waseem18!

**Comment by jespino** [comment]
@waseem18 good question, I would expect to have the same `reactions` field inside each entry of `replies` (when it has replies).

**Comment by waseem18** [comment]
I see that the method `GetRepliesForExport` from `post_store` returns replies of a given `Post Id` without reactions. 

To be able to export reactions of replies, I think we would need to write a new method or make some changes to the existing one. I'm on it.

**Comment by waseem18** [comment]
Update - Here's how the JSON is going to be 

```
{
  "type": "post",
  "post": {
    "team": "ad-1",
    "channel": "sequi-7",
    "user": "sysadmin",
    "message": "BAZINGAA",
    "create_at": 1539071841548,
    "reactions": [
      {
        "user": "qwxc51mcci8gmbkdynpkjkc7dr",
        "create_at": 1539071845432,
        "emoji_name": "grinning"
      },
      {
        "user": "qwxc51mcci8gmbkdynpkjkc7dr",
        "create_at": 1539078944889,
        "emoji_name": "clown_face"
      }
    ],
    "replies": [
      {
        "user": "sysadmin",
        "message": "REPLY TO BAZINGA",
        "create_at": 1539075550033,
        "reactions": [
          {
            "user": "qwxc51mcci8gmbkdynpkjkc7dr",
            "create_at": 1539079394197,
            "emoji_name": "sleeping"
          },
          {
            "user": "6yupkpfxdfgg9xq699fr4hkmyc",
            "create_at": 1539113584029,
            "emoji_name": "mattermost"
          }
        ]
      }
    ]
  }
}
```
