### ISSUE TITLE
Searches for users don't work when @ symbol is included

### ISSUE THREAD

**Issue by zeroimpl** [mattermost/mattermost#9755]
#### Summary
Typing an "@" symbol in the dialog for starting a new direct message conversation always returns no results.

#### Steps to reproduce
Try to start a new direct message, and type the account name starting with an @ symbol, such as "@user", or type in a full email address such as "username@domain.com". 

#### Expected behavior
Typing "@user" behaves identically to typing "user" (this is how things work in Slack, and the search results always display the @ symbol so it's weird that typing it in doesn't work)
Typing "username@domain.com" finds the user with that email address.

#### Observed behavior (that appears unintentional) 
Search results always become empty once @ symbol is entered. For email searches, you can type in only the username portion or the domain portion and it works, but entering the full address with the @ will not work.

#### Possible fixes
The fix likely involves two components:
- Change the /api/v4/users/search endpoint to ignore leading @ symbols
- Change the function filterProfilesMatchingTerm in mattermost-redux user_utils.js to deal with both cases properly.

Note I have a fix for this issue mostly ready to submit already.

**Comment by amyblais** [comment]
Hi @zeroimpl!

Not 100% sure if there's any specific reason why we don't support this yet - thank you for helping with a fix for this and let me know any questions.

**Comment by lindalumitchell** [comment]
Testing note: I ran through a QA review on https://github.com/mattermost/mattermost-webapp/pull/2012, and approved. 👍
