### ISSUE TITLE
Improve email headers.

### ISSUE THREAD

**Issue by MrSorcus** [mattermost/mattermost#9822]
#### Summary
Rspamd assign some spam points based on few email headers.

#### Steps to reproduce
Version 5.4.0.
Just get notification and look at source of email.

#### Expected behavior
`MIME-version` and `Message-ID` must be correct.

#### Observed behavior (that appears unintentional)
![screen shot 2018-11-12 at 09 00 41](https://user-images.githubusercontent.com/23472035/48337114-f57eb600-e659-11e8-8b3f-6cbef8714964.png)
Screenshot from Rspamd. Here 2.90 / 15. If it be 5.90 / 15, soft reject will be applied.
If 15 / 15 - hard reject.
`Mime-Version: 1.0` - here MIME must be capitalized (see https://tools.ietf.org/html/rfc4021#section-2.2.1)
`Message-ID` - must be received from Mattermost server (see https://tools.ietf.org/html/rfc4021#section-2.1.8)

**Comment by amyblais** [comment]
Hi @MrSorcus,

Giving you an update that I'm working on investigating this,

**Comment by amyblais** [comment]
I created a ticket for this here: https://mattermost.atlassian.net/browse/MM-13012.

**Comment by amyblais** [comment]
Hi @MrSorcus it looks like a PR was already opened in the gomail library for the MIME issue: https://github.com/go-gomail/gomail/pull/127.

For any further issues, it seems it would make sense to open an Issue in the gomail repo: https://github.com/go-gomail/gomail/issues. Would you be able to help with that?

**Comment by MrSorcus** [comment]
> Would you be able to help with that?

Looks that here issue exists - https://github.com/go-gomail/gomail/issues/36
But it closed.

**Comment by MrSorcus** [comment]
If i understand correctly, there is only one way to implement it. In mattermost-server.

**Comment by jamiew0w** [comment]
Is there any movement on this? Looked at the jira but appears dead. Having issues with everything arriving in spam despite _everything_ being setup correctly.

**Comment by compilenix** [comment]
Here is an updated state:
![Screenshot from 2022-02-19 14-56-28](https://user-images.githubusercontent.com/6356150/154803871-cb556641-686f-4cbc-9b44-2ae1c15163b1.png)

**Comment by amyblais** [comment]
Closing as this is an old issue and can be tracked via https://github.com/go-gomail/gomail/pull/127.
