### ISSUE TITLE
Plugin API method to get posts for a specific date range

### ISSUE THREAD

**Issue by chetanyakan** [mattermost/mattermost#9979]
#### Summary
I am trying to get posts of a channel for a specific time interval. Currently, there is no Plugin API method for the same. The most similar would be:

```
(API) GetPostsSince 
GetPostsSince(channelId string, time int64) (*model.PostList, *model.AppError)
GetPostsSince gets posts created after a specified time as Unix time in milliseconds.
```

But this will only get posts after a specified time. There is no option to specify an end date.

#### Possible Fixes
Add another API `GetPostsBetween` to get posts in a channel lying in a specific date range.

**Comment by amyblais** [comment]
Hi @chetanyakan,

The API documentation also has options for "Before" and "After", would these help: https://api.mattermost.com/#tag/posts%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1posts%2Fget?

Also, here are some Forum threads that might help:
 - https://forum.mattermost.org/t/shouldnt-i-use-since-parameter-for-recursive-fetch/6150
 - https://forum.mattermost.org/t/getting-posts-for-a-channel-on-a-specific-date/3560

**Comment by chetanyakan** [comment]
@amyblais Sorry for the delayed response.


- The API I mentioned, [`GetPostsSince`](https://developers.mattermost.com/extend/plugins/server/reference/#API.GetPostsSince) is a Plugin API. But it only offers specifying start time and no pagination, nor an ability to specify the end time.

- The API you mentioned in the [API documentation](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1posts%2Fget) is not a Plugin API. So, I would not be able to use it.

**Comment by amyblais** [comment]
Hi @chetanyakan,

Sounds good, would this be something you are interested in adding?

Let me know if you don't currently have time and I will add your suggestion to our current Help Wanted ticket for plugin APIs: https://github.com/mattermost/mattermost-server/issues/9458.

**Comment by amyblais** [comment]
Hi @chetanyakan, following up on this ^

**Comment by chetanyakan** [comment]
@amyblais It will be helpful to add it in the Help Wanted APIs for now. I might look into it if I have time to spare.
